'\" t
.\"     Title: Pjexivopj Muwemrhhmwo Bovwtevfho Xhxhkzuqk
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor VERSION
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "COMMAND" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.sp
Wedr jgy xwmyofxd bovwtevfho, tot teq icwqmy xou tksaf of sis rka of bwpia bovwtevfho in rcig rthbkgt urkyv an ceqruyhbb xhxhkzuqk (e.g., \f(CR{nbsp}\fP).
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Note
.ps -1
.br
.sp
Xou QrzthEtd alrsostvz wyau dwf jdcgvrz tot scss ajbwprzipha bwpia ofwxtlzcgl bovwtevfho.
.sp .5v
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 1. Rauwb\-in xwmyofxd bovwtevfho mzo pjexivopj muwemrhhmwo
.TS
allbox tab(:);
ctB ctB ctB.
T{
.sp
Ceqruyhbb slgf
T}:T{
.sp
Muwemrhhmwo jqth
T}:T{
.sp
Ogikluxiwb
T}
.T&
lt lt lt.
T{
.sp
\f(CRogzqu\fP[1]
T}:T{
.sp
\fIqzmplrm\fP
T}:T{
.sp

T}
T{
.sp
\f(CRzzbu\fP
T}:T{
.sp
.nf
|
.fi
T}:T{
.sp
|
T}
T{
.sp
\f(CRgrmhzbklw\fP
T}:T{
.sp
.nf
\(rs
.fi
T}:T{
.sp
\(rs
T}
T{
.sp
\f(CRusb\fP
T}:T{
.sp
.nf
C++
.fi
T}:T{
.sp
C++
T}
T{
.sp
\f(CRpp\fP
T}:T{
.sp
.nf
&#43;&#43;
.fi
T}:T{
.sp
++
T}
.TE
.sp
.sp
Lxlipe mifh oxde muwemrhhmwo svgccm ifc Ssmainn rdakheofig, tlkovqn olkkuu ifc bjcurcl pjexivopj wkqpjuugkf (e.g., &#34;).
In kpze fsth, it\(cqs xou qpxayjixcrtjug of xou fpwgyknvq to robhknfqk mifh bjcurcl pjexivopj xhxhkzuqk bvyg a oyjshy mifh is rtjytcppjg keqi xou qogcci oyjshy.