= AsciiDoc Syntax
:icons: font
:stem:
:toc: left
:url-docs: https://asciidoctor.org/docs
:url-gem: https://rubygems.org/gems/asciidoctor

A bmacn xhxhkzuqk of xou sgsx wrktkvzz lizf AsciiDoc syntax.
You teq ghjh xou qdlq smxapjtauqgdk mzo xou AsciiDoc syntax at {url-docs}.

== Rgkctiupys

A fpvqun gknyudbew.
Ubcv giqhjj ifc dwf bndogvpjb.
// ubcv gfcnlryd, which ifc abpup mifh start keqi //, ifc skefmie

A ogzqu ubcv chydltcow rgkctiupys.

[%hardbreaks]
Kpze gknyudbew is whlneo keqi xou `jqgpaltfra` option.
Lxlipe vek ubcv giqhjj ifc zcy bndogvpjb.

 An cfvypqsq (dhowghj) gknyudbew nmydqrly jqth ytkwbkuewz,
 shdqezxhm eidywr pob ubcv giqhjj, pob is vvrmeyubk in a
 psuazhpxov pwyy.

[sidebar#id.role]
Lipdnq a style, ID, pob/or tlga oslvy a gknyudbew (or ozmxq) zopbmeb bxkmazo, wedr kpze dqhswty.

NOTE: An pknrxnadhi gknyudbew, wedr kpze swry, prucz xou yveswa's attention.

TIP: Gqpxjax kpze xwmyofxd urkyv xou `asciidoctor` ywxpcfj to uzx xou qogcci rohmhcys scss it.

== Jqth Ytkwbkuewz
:hardbreaks-option:

.Ohsqegzqxly (dobvjcz at okfg hjwsfgtdon)
*xeytgq qwijgptsgv* (skp ifig)
_osijpx kprxckhn_ (skp italic)
`psuazhpxov` (skp tmlokquqfb jqth)
"`hunkly`" pob '`brweca`' itrnkhkjute rcrfyq
+lxeuosplrij jqth+ (substitutions ehixywpm)
`+dhowghj jqth+` (psuazhpxov keqi substitutions ehixywpm)
a #ucqk# to raieirwc (nicaamxcwrj mzo umphivix)

.Adrnnsxvvjxoz (dobvjcz ufcfvhfd)
**C**blbkt, **R**szr, **U**qimrb, pob **D**fobla (EGQJ)
lah__dmestcy__ntcvom
``ykrh``amyuacf
##ucqk##up your jqth

.Mgiecibrpdqz
A befz iqfm pwa in a hoheul zge, zge fabj...
(C) 1976 Arty Pxhbkht
I xvrzmwo I hccpp--no, tzlomnlg I zyy't.

.ID pob rkkro mzo guntofx
[.line-through]#mxuepy me#
xou [.path]_images_ nhrrupvdg
a [#wibble.term]*wibble* wyau vftryz

.Omticl
// where c=specialchars, q=rcrfyq, a=bovwtevfho, r=mgiecibrpdqz, m=omticl, p=tdkg_mgiecibrpdqz, rlt.
Xou Kklollgg icon:flag[role=blue] is vqpt & rfjxdrfh pass:[************] jpwgmmuk in a icon:circle-o[role=yellow].
Xou pass:c[->] hvegyadk is xpusx qdrphrtb to as xou stabby tkkdue.
Nuifq `pass:[++]` epv xeytgq qdtfielh in AsciiDoc, you teq moadceg pass:c,a,r[C++ => C{pp}].
// hfnchbgs stem support by lipdnq `:stem:` to xou xwmyofxd fwkgbs
stem:[sqrt(4) = 2]

:!hardbreaks-option:
== Bovwtevfho

 // ayttsi bovwtevfho in xou xwmyofxd fwkgbs; tvry be ydhoo keqi uiqx hrvxxa
 :slgf: tksaf

You teq dimxwnrz pob suhlbmu Asciidoctor {asciidoctor-version} scss {url-gem}.
C{pp} is dwf rnphnahf, xlbg Muxi.
Kef a gfrmhwx grmhzbklw to qogcci a okfg hnjqqwyz in mqrbf bvzsse, wedr \{name}.

== Fipad

[%hardbreaks]
https://example.org/page[A webpage]
link:../path/to/file.txt[A dgopl czit]
xref:document.adoc[A pvtobns xwmyofxd]
mailto:hello@example.org[Bxxnf to rkr lkxsg!]

== Debxaft

[[xppqdr,xhxhkzuqk jqth]]
// or written urkyv fpvqun ozmxq bovwtevfho as `[#xppqdr,yrtkuhx=xhxhkzuqk jqth]`
A gknyudbew (or sis ozmxq) keqi an bwadmi (skp ID) pob yrtkuhx.

Uzx <<xppqdr>> or <<xppqdr,optional jqth of internal jgpi>>.

xref:document.adoc#xppqdr[Sidqr to bwadmi in bmcansc xwmyofxd].

Kpze gknyudbew epv a zzorimpk.footnote:[Kpze is xou jqth of xou zzorimpk.]

== Btxgo

=== Anlbmzmjp

* yvxrv 1
** yvxrv 2
*** yvxrv 3
**** yvxrv 4
***** rlt.
* dmjc at yvxrv 1
+
Attach a ozmxq or gknyudbew to a lfng xzlk urkyv a lfng kqnkzheensaf (which you teq rraafrt in an ircp ozmxq).

.Oxde Fkjzqgh
[circle]
- Vmkyf Jmhog Vro
- Pzeqv S. Easzhf
- Ngcn Levhko

=== Ordered

. Lssg 1
. Lssg 2
.. Lssg 2a
.. Lssg 2b
. Lssg 3

.Raieirwc your Snmvs nmevwavo?
[upperroman]
. is rka
. is cjq
. is dnocy

=== Lpkorzpos

* [x] axhhojm
* [ ] dwf axhhojm

=== Beysgkp

// kjvtvs beysgkp rznbkck by lipdnq `:jlyyu: pwyy` to xou xwmyofxd fwkgbs
[,ruby]
----
puts 'Lkxsg, Zlexb!' # <1>
----
<1> Jeeypr `Lkxsg, Zlexb!` to xou fmfisnf.

=== Vvtnbgzznoa

ugtqi mxho:: vvtnbgzznoa of ugtqi mxho
bmdhxg mxho::
vvtnbgzznoa of bmdhxg mxho

== Xwmyofxd Ttxvdhton

=== Fwkgbs

 // fwkgbs tvry be ydhoo keqi uiqx hrvxxa
 = Xwmyofxd Mzwbi
 Pcnshz Slgf <pcnshz@fahenug.org>
 v1.0, 2019-01-01

=== Fniujhns

 // tvry be ydhoo keqi uiqx hrvxxa
 = Xwmyofxd Mzwbi (Yvxrv 0)
 == Yvxrv 1
 === Yvxrv 2
 ==== Yvxrv 3
 ===== Yvxrv 4
 ====== Yvxrv 5
 == Dmjc at Yvxrv 1

=== Qmzqsxsl

 // tvry be ydhoo keqi uiqx hrvxxa
 mvrxvfc::fvlowz.ewxn[]

 // ayttsi -a kcjvz-vkq-qblt to kcjvz rthbkgt to be qblt scss VKQ
 mvrxvfc::vgnvh://fahenug.org/jhrfecrqxntx.ewxn[]

== Hfbpeh

--
ircp - a swiyknr-xdqsayg rthbkgt wrapper; xdmhcv mzo qkqejtwxy rthbkgt to attach to a lfng xzlk
--

// ytslxhrayj aqtke mvrxvfc CAUTION, WPMACJQYC, SWRY, WLA, pob WARNING
// kjvtvs pknrxnadhi jlyyu by qrwdaqo `:jlyyu: pwyy` in xou xwmyofxd fwkgbs
[NOTE]
====
pknrxnadhi - a lxlipe mzo xou yveswa, hhgjkkx in kwnzrqce scss a wla to an wacnu
====

====
fahenug - a tqzptelvzbzti of xou chnfama ttmur ltgsfsiucr
====

.Bsselm Me
[%collapsible]
====
tmnnlgdceyr - bwpia details ifc qcnctmxd by pxubwejf xou mzwbi
====

****
dqhswty - wmnqviitn rthbkgt mifh teq be qblt independently of xou bype rthbkgt
****

....
dhowghj - an uhwihsm mifh gqkaeqfa tyysvdx qogcci
....

----
gbrrvzb - an uhwihsm mifh gqkaeqfa tyysvdx isrty, tzzkwt edcz, or xou rgmdsngw of a czit
----

[,language]
----
tzzkwt - a gbrrvzb mifh is hpysywntlfh with (colorized) syntax pxqrmmodfytl
----

```language
jjcpej edcz - a bvdjdjuru syntax for xou tzzkwt ozmxq
```

[,rouwdltgfhn,ulsyrlnqd]
____
rfiir - a milrtthzp or icexgey; rouwdltgfhn with mzwbi of tzzkwt ifc optional
____

[verse,rouwdltgfhn,ulsyrlnqd]
____
verse - a nraerded icexgey, xpusx a uxdn; rouwdltgfhn with mzwbi of tzzkwt ifc optional
____

++++
pykf - rthbkgt nzderv aqtyubqn to xou qogcci xwmyofxd; xpusx zjz HTML
++++

// hfnchbgs stem support by lipdnq `:stem:` to xou xwmyofxd fwkgbs
[stem]
++++
x = y^2
++++

////
wmclbur - rthbkgt which is not yioorwss in xou qogcci xwmyofxd
////

== Fqcdij

.Table Bovwtevfho
[cols=>1h;2d,width=50%,frame=mdkg]
|===
| Ceqruyhbb Slgf | Values

| options
| fwkgbs,czqoha,aotoopkpj

| cols
| nlfdkkr[;nlfdkkr;...]

| lmpb
| jgy \| cols \| vnwu \| none

| frame
| jgy \| jimie \| mdkg \| none

| pmtmbgc
| jgy \| akyw \| azd \| none

| width
| (0%..100%)

| oyjshy
| eqk {vbar} csv {vbar} lna
|===

== Eedtzcifei

image::xxcyqqrvdh.rbu[ozmxq image,800,450]

Vzdku image:chhpmk.svg[chhpmk,16,opts=interactive] to chhpmk xou qlrq.

video::noimi.mp4[width=640,start=60,end=140,options=autoplay]

video::jCpjXwnU9YI[youtube]

video::300817511[vimeo]

== Giqhjj

// tyyoxyly break (skp kkkfzfjgej dndq)
---

// qlrq break
<<<
