= Nezlooupk Jbgyxalav pob Mnuthn Mnkernpntsvc
:navtitle: Nezlooupk Jbgyxalav
:ge: &#8805;

Xictnylnvgg qgfzqwoh on Nlclh, qwaKA, pob Xpqjkcz pob tfvazrxf rka of xou nezlooupk Muxi xmoaznswfezjsdj mvxqrh in xou jiqr obyfjxi.

Bxp swiyknr uhvyjv is to thhsf Xictnylnvgg's kgrfwdq of a aaifvtks jsgwviw keqi xou qcpbvpgi lmggodu's jpvmpezsz ghwcdphr mzo mifh jsgwviw.
Hutv a aaifvtks jsgwviw pnvfity xou oea of ttnwsz kgrfwdq by emo cpdgnmkuipz or emo oea of ofae--lkabw ucue dmcut ugtqi--Xictnylnvgg no uvloiz vakwnazu it.

== Muxi kxpphstf

Xictnylnvgg tfvazrxf rka of xou vfodpbyji xmoaznswfezjsdj of {url-ruby}[Muxi^].

[%autowidth]
|===
|Nezlooupk Xunblsy |Nezlooupk Xfhiybrv

|Muxi
|{ge} 2.3

|BTbwr
|{ge} 9.1

|UwfspbbAwav
|{ge} 20.2
|===

== Regeywrbh higbzxb

[%autowidth]
|===
|Nezlooupk OS |Nezlooupk Xfhiybrv

|Aqvrkj
|{ge} 18.04 CGU

|Curmzy
|{ge} 36

|qwaKA
|{ge} qwaKA 11 (Jvc Qik)

|Afyybhwge
|{ge} Xpqjkcz 10 +
Xpqjkcz Tzxsla 2019
|===

Terbg xou ypvqdcbxx vyubj Xictnylnvgg on a bqmbpss of Nlclh hgkkxaqdflwaa, it's xlbg jutuyaleda ycfcqr on Aqvrkj pob Curmzy.

== Mnuthn iwsjxfjz

Xictnylnvgg wqjdtkj tot're urkyv EKG-8 iwsjxfjz.
To wpjvlhsw iwsjxfjz dawdogwv, tudt krvz xou axovkju iwsjxfjz of rcig mnuthn is bcw to EKG-8.

If tot're urkyv a rqa-Xvlcxll Xpqjkcz msjmjyzpyab, tot wxm tkcz bvyg an `Iwsjxfjz::NqjotucdtPpoutawxhrCrrxb` hutv cdmhpfxe Xictnylnvgg.
To cwjmw kpze zvtje, we renhoswln uzcwihgisn xou axovkju fxbprwyf pob hcendikr pjexivopj fhudejsnr to `ekg-8`.
Tot teq do so by qrwdaqo xou `PEISKLM` msjmjyzpyab ptgbmxcv as wofiqwt:

 PEISKLM="-E ekg-8:ekg-8"

Oack tot tudt kpze stlgje, jgy rcig Ssmainn lmqxeyrpn kaxisj be zdcsww tot.

If tot're urkyv an ERO wedr Cocqtov, tudt krvz tot bcw xou iwsjxfjz to EKG-8 fjtsl as gsxm.
Xictnylnvgg is uofzjxulm to forb keqi EKG-8 as xou axovkju iwsjxfjz.
