description = "Anchor: a pool document cut down and sanitized."
source = "pool:capture-asciidoctor-main/links_test.rb:1144.1"
formats = ["manpage"]

[options]
input = "./input.adoc"
standalone = false

[attributes]
"docname" = "test"
