description = "Anchor: a pool document cut down and sanitized."
source = "pool:quarkus/docs/src/main/asciidoc/security-authentication-mechanisms.adoc"
formats = ["xhtml5"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
