description = "Anchor: a pool document cut down and sanitized."
source = "pool:progit2/book/04-git-server/sections/generating-ssh-key.asc"
formats = ["pdf"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
