/// Generates `lib/src/styles.g.dart` from `vendor/highlight.js-styles`:
/// each highlight.js theme's stylesheet, by name (for a page's CSS, or the
/// colors of highlighted code in a PDF). Run from the package root
/// (`tool/vendor_styles.sh` runs it):
///
/// ```sh
/// dart run tool/embed_styles.dart
/// ```
library;

import 'dart:io';

void main() {
  final root = File(Platform.script.toFilePath()).parent.parent;
  final vendor = Directory('${root.path}/vendor/highlight.js-styles');
  final files =
      vendor
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.min.css'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by `dart run tool/embed_styles.dart`.')
    ..writeln(
      '// Source: `vendor/highlight.js-styles` (highlight.js 11.12.0, '
      'BSD-3-Clause: vendor/highlight.js-styles/LICENSE).',
    )
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln("/// highlight.js 11.12.0's themes.")
    ..writeln('library;')
    ..writeln()
    ..writeln("/// Each theme's stylesheet, by its name (`github`).")
    ..writeln('const Map<String, String> highlightJsStyles = {');
  for (final file in files) {
    final name = file.uri.pathSegments.last.replaceFirst('.min.css', '');
    // Comments (the themes' credits) are kept out of the code; the
    // licence is in the vendor directory.
    final css = file
        .readAsStringSync()
        .replaceAll(RegExp(r'/\*[\s\S]*?\*/'), '')
        .trim()
        .replaceAll(r'\', r'\\')
        .replaceAll("'", r"\'")
        .replaceAll(r'$', r'\$');
    out.writeln("  '$name': '$css',");
  }
  out.writeln('};');
  File('${root.path}/lib/src/styles.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('embed_styles: ${files.length} themes');
}
