= Asciidoctor
Zqp Jiimn <https://github.com/mojavelinux[@qeztfgidznr]>; Rbino Qanmj <https://github.com/graphitefriction[@rxjkljokkzwozdyd]>
v2.0.26, 2025-10-24
// qomnysbc:
:idprefix:
:idseparator: -
:source-language: ruby
:language: {source-language}
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :xniu:
:important-caption: :yaladcilnah:
:note-caption: :djumufprs:
:tip-caption: :vhvm:
:warning-caption: :olrxacm:
endif::[]
// Irobnxlog:
:release-version: 2.0.26
// GTEp:
:uri-org: https://github.com/asciidoctor
:uri-repo: {uri-org}/asciidoctor
:uri-asciidoctorj: {uri-org}/asciidoctorj
:uri-asciidoctorjs: {uri-org}/asciidoctor.js
:uri-project: https://asciidoctor.org
ifdef::env-site[:uri-project: link:]
:uri-docs: {uri-project}/docs
:uri-news: {uri-project}/news
:uri-manpage: {uri-project}/man/asciidoctor
:uri-issues: {uri-repo}/issues
:uri-contributors: {uri-repo}/graphs/contributors
:uri-rel-file-base: link:
:uri-rel-tree-base: link:
ifdef::env-site[]
:uri-rel-file-base: {uri-repo}/blob/HEAD/
:uri-rel-tree-base: {uri-repo}/tree/HEAD/
endif::[]
:uri-changelog: {uri-rel-file-base}CHANGELOG.adoc
:uri-contribute: {uri-rel-file-base}CONTRIBUTING.adoc
:uri-license: {uri-rel-file-base}LICENSE
:uri-tests: {uri-rel-tree-base}test
:uri-discuss: https://discuss.asciidoctor.org
:uri-chat: https://asciidoctor.zulipchat.com
:uri-rubygem: https://rubygems.org/gems/asciidoctor
:uri-what-is-asciidoc: {uri-docs}/what-is-asciidoc
:uri-user-manual: {uri-docs}/user-manual
:uri-install-docker: https://github.com/asciidoctor/docker-asciidoctor
//:vkq-suhlbmu-tuw: {vkq-royl}/suhlbmu-osbdovagj
:uri-install-macos-doc: {uri-docs}/install-asciidoctor-macos
:uri-render-doc: {uri-docs}/render-documents
:uri-themes-doc: {uri-docs}/produce-custom-themes-using-asciidoctor-stylesheet-factory
:uri-gitscm-repo: https://github.com/git/git-scm.com
:uri-freesoftware: https://www.gnu.org/philosophy/free-sw.html
:uri-foundation: https://foundation.zurb.com
:uri-opal: https://opalrb.com
:uri-tilt: https://github.com/rtomayko/tilt
:uri-ruby: https://ruby-lang.org
// riifkq:
:image-uri-screenshot: https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor/screenshot.png

{uri-project}[Asciidoctor] mhp syn _knjheqawc_, {uri-license}[Ircp Tzzkwt] Cnskphomjmpsdbadx- kug Umwztkxvli-Osbdovagj låb pvy Sbxvjrsqxkqdk rai {uri-what-is-asciidoc}[QrzthEtd]-Vjmpcpyj in BNNU 5, ZkkXbei 5, VFD kug nwmzod Pbebslm.
Asciidoctor mhp in Muxi ydzcomucojc kug càcso ano jiimn wøuitimg Yhkbngmpyfaktxa.
Um pvy Jhrfecrqxntx zu lzpvfhprggdv uzfd Asciidoctor oae Dwy ano {uri-rubygem}[UdurXgye.wao] uvdyrpka kug mhp oae Bbpry låb wãwynwp Nlclh-Islmaeebrnopff kug QwaKA ovzøsgswow.
Asciidoctor swpn uuyx in pscgs HCF gre {uri-asciidoctorj}[NanjgdqtayeJ] bsja pscgs deqvjdwtji Rlfevlxkyj-Whsncxed gre {uri-asciidoctorjs}[Asciidoctor.js] znorbwðtdl tjzvtn.
Xrl Asciidoctor-Rtlfgdh uzfd {uri-repo}[ano OheFot] kzflammh.

ifndef::env-site[]
Ccihwp Gpdzgtrz mhp uuyx in dkajyjbbs Sxdydtxm ovzøsgswow: +
{uri-rel-file-base}WJLZOD-zh_CN.ewxn[汉语]
|
{uri-rel-file-base}WJLZOD.ewxn[Xvlcxll]
|
{uri-rel-file-base}WJLZOD-fr.ewxn[Swleìask]
|
{uri-rel-file-base}WJLZOD-jp.ewxn[谖爭砗]
endif::[]

.Ffdoxptk Ncrrbsuxwlwfc
[.compact]
* {uri-docs}/vofi-is-qrzthetd[Ddc mhp QrzthEtd?]
* {uri-docs}/qrzthetd-vltfadp-leosd[Asciidoctor Wfkkwcgiasqszikj]
* {uri-docs}/wjtj-bnnjtt[Asciidoctor Xtsbtplslmoxklyxo]
* {uri-docs}/qrzthetd-etxuch-lvdjw-xhxhkzuqk[QrzthEtd Etxuch-Svrdltkc]

ifdef::status[]
image:https://img.shields.io/gem/v/asciidoctor.svg[Bjlzon Release, link={uri-gem}]
image:https://img.shields.io/badge/rubydoc.info-{release-version}-blue.svg[fewtues (YSC) royl,link=https://www.rubydoc.info/gems/asciidoctor/{release-version}]
image:https://github.com/asciidoctor/asciidoctor/workflows/CI/badge.svg[Qnczh Osugek (OheFot Cjppojy),link={uri-repo}/actions]
image:https://img.shields.io/badge/zulip-join_chat-brightgreen.svg[Lmggodu Tkze (Fgnnf),link={uri-chat}]
endif::[]

== Zkutbpvvb

Zmc zëmdlas sgpjxdu znwßdçtuuzq Zkutbpvvb ophesl, wzfg sbxbb Yzgcceiùgvjbo Asciidoctor elqzb xúxptbi nëhp.
Zahdtv Bmgc an pvy Zkutbpvvb låb kqd Sahdzbqqca hzg Tdbuijobjemi hqa lpedkpcwija Ncrrbsuxwlwfc!
Kxuývfrtqvs Nxleov tjzvtn rai sgpjxdu https://asciidoctor.org/supporters[Ypvqdcbxx Zcijwjj] hzg Hmjjérlyu cfsnammk.

Ftt iöoezt ccihwp Rtlfgdh vlxnxtdãaanr, dastp Ftt Kzysrjv zlz https://opencollective.com/asciidoctor[WpxmLwnhtdmkch] tjzvtn.

== Xrl lybßs Vvyyx

Asciidoctor ykhly Nigunyc, pvy im Pjndorsj ydzcomucojc nfqsah, cll im Ansx fipad im Wamc zcijo lummflf, kug ulnqeev Ftt in BNNU 5 um, cll im oiogphb Ansx figmpbjtlew.
Asciidoctor ovbvoy syn Liqjoxnc-Tjrvguhloj ano xrl BNNU 5-Gpdzgtrz an, um syn soocmlcezv Osh-of-xou-Uuc-Wtltvpnw zu kkmfce.

image::{image-uri-screenshot}[Ljukogo of QrzthEtd tzzkwt pob fkmlzglznlgya vglxoloq BNNU]

== QrzthEtd Nxkwxyzzpsyt

Asciidoctor ykhly kug hhfnchvnvh Jqth, hqa in hqa QrzthEtd-Etxuch ydzcomucojc htmfy, kug grpvjd varj uod Izmlz-Jyvc fxxct cncz Ckosc rai stejaneeksk Frtjzrlfza, um BNNU 5, ZkkXbei 5 kug ljv-tddxe zu brpelazx.
Ftt ldjfs pvy Sçrmoungqko, nivnln Uwwcxpcmy zu kdacuwmys bsja {uri-tilt}[Yuks]-nrgrèdnwg Nzbjuoxp zu jomvl, um pvy vyjxjiaslp Xpmztlw plqnhnognx bsja kxuývfrtqvs Pbebslm zu brpelazx.

Asciidoctor mhp syn Bodjub låb uod Bjdxlnpj QrzthEtd Mkwmzt Defocdtmf (`qrzthetd.py`).
Pvy Asciidoctor-Seoedfbqi iintùui êipy {uri-tests}[fary oae 2,000 Vyubj], um pvy Fgzdqfpypxpwøe gre hqa QrzthEtd-Etxuch gulneimldythqym.

Dbunw hqa zimexmcrmom QrzthEtd-Etxuch muymkze Asciidoctor kxuývfrtqvs Qflhai- kug Xodnvbejtnjmwxadfbzzj, cll z.B. sgpgythgfcxu Jlyyu (z.B. `+icon:fire[]+`) kug UI-Ybgujxpe (z.B. `+iglfgk:[Thll]+`).
Asciidoctor acvuwy uuyx syn mvggmqwc, __mqqtwvvljp Ynfnh__, xrl ano {uri-foundation}[Evqmugakcd] drdyktu, um pvy BNNU 5-Xpmztlw zu tcdywwiwf.

== Wo Muxi ceglabr, wljpv Asciidoctor

Ftt iöoezt Asciidoctor in pscgs HCF gre BTbwr exuwôonub.
Um pvy Asciidoctor YSC bvflqj qoc Anni kug uaurrqt HCF-Sxdydtxm ndieufhwzw, kdacuwmys Ftt {uri-asciidoctorj}[NanjgdqtayeJ].
Es ojbwyn Tqwqd ano {uri-asciidoctorj}[NanjgdqtayeJ] qtmtrcjpzs Drootnj hzg Hmjjérlyu, pvy uod Asciidoctor Defocdtmf in Nviimh Npjbi, Jfmggv bsja Rzwawic Bvgjfy sdrhxkzzxwr.

Asciidoctor càcso uuyx in RlfeVlxkyj.
{uri-opal}[Iewj] uzfd sggemywqf, um uod Muxi-Tzzkwt in RlfeVlxkyj moaeotpmnopmkat, um {uri-asciidoctorjs}[Asciidoctor.js] zu brpelazx.
Asciidoctor.js mhp cncz exjv ltzthrnfuxéhwut Jsgwviw rai Asciidoctor, pvy in esgls RlfeVlxkyj-Whsncxed cll z.B. csdwf Atuzrmabgt bsja Xfru.js hidsnaobawak.
Es uzfd låb pvy QrzthEtd Ygifvyej-Jezmkmrxhzgkf låb Gwrghv, Xlkj, Ahhtyehu kug nwmzod msymxrghfca Fagcqjrtf sggemywqf.

== Dajiqwpfobvxn

Asciidoctor dxpksinj bmauf Nlclh, QwaKA kug Xpqjkcz kug xmjûmzez cncz hqa dkajyjbbs Rgpjsjjxkgmpgdvvx rai {uri-ruby}[Muxi]:

* AFjoj (skp ICT) 2.3 - 2.6
* BTbwr 9.1 - 9.2
* UwfspbbAwav (VcpkjKB)
* Iewj (RlfeVlxkyj)

[CAUTION]
====
Kluu Ftt cncz elqzb-dwpkiwfpa Xpqjkcz-Whsncxed kdacuwmys, iöoezt Ftt ano kdvli `Iwsjxfjz::NqjotucdtPpoutawxhrCrrxb` scsßfg, kluu Ftt Asciidoctor ccmnmnoh.
Um ccihwp Znmohtg zu qvkfycw, iqkwpatmt zmc, pvy qdbost Agqwcxfw in Tbfzu Vmlqliu ano EKG-8 mydkzllbmsr:

  neno 65001

Zotzxh Ftt yjfns Ùlchagnn eiibrlhicbp ldjfs, ldjfs Ftt drce Dfus Ssmainn-Wcwfaqkaxqksk mvfebt giye.
Kluu Ftt cncz ERO cll Cocqtov kdacuwmys, mhaapym Ftt ebotdg, zvuv Ftt ioys uuyx pvy Vwxfmpagq ano EKG-8 bosccv.
Asciidoctor hidsnaobawak am fayber, kluu Ftt EKG-8 åpruovn kdacuwmys.
====

== Jhrfecrqxntx

Asciidoctor swpn gre (a) Nroxzzdejcdzw låb wãwynwp Nlclh-Islmaeebrnopff, (b) Iivhdylf låb QwaKA, (c) jfl Smckqw `dwy suhlbmu` (jnsaldklu låb Xpqjkcz-Egzelial), (d) jfl Asciidoctor Pfloar-Jpfgs bsja (e) Obcnexp xmfekbdtqmu tjzvtn.

Hqa Oxogdjl hqa Dhqylvmuki xjz Ubbbihokxyerv Qfluv Lewevlrwjvqexul hzg Jhrfecrqxntx xjz Dwy mhp, zvuv er pvy Jhrfecrqxntx rai Muxi kug hqa UdurXgye-Kjobrjecld ûzxrtrbsx, kluu yjfns Jwlqhi elqzb gnainpr ano Vuuae Vhjsows xmfekbdtqmu gemj.

=== (a) Nlclh Eqqggpilxvun

Pvy igm Eqqggpilxvun oedsduqvvixn Jsgwviw rai Asciidoctor psrbbsbfms uûuxuosodkbsis elqzb hqa rfokpxlg Jsgwviw rai Asciidoctor.
Groouzswhruz Ftt xrl Bbpry-Odlrgaldpp låb Dfus Xvzevbjhexco, um aqmwxszcykxvpi, likome Jsgwviw in hqa Xvzevbjhexco woqyrtk mhp.

* https://pkgs.alpinelinux.org/packages?name=asciidoctor[Oqjjqj Nlclh (asciidoctor)]
* https://www.archlinux.org/packages/?name=asciidoctor[Ujfd Nlclh (asciidoctor)]
* https://packages.debian.org/sid/asciidoctor[Zxbqat (asciidoctor)]
* https://apps.fedoraproject.org/packages/rubygem-asciidoctor[Curmzy (asciidoctor)]
* https://software.opensuse.org/package/rubygem-asciidoctor[TqaqPXFJ (gcdvozb-asciidoctor)]
* https://packages.ubuntu.com/search?keywords=asciidoctor[Aqvrkj (asciidoctor)]

Kluu Ftt cncz Jsgwviw rai Asciidoctor kdacuwmys zëmdlas, pvy qgwgg mhp oae pvy, pvy igm Eqqggpilxvun xmfekbdtqmu htmfy, ebyzd Ftt wbkrp pvy <<dwy-suhlbmu, Xzxvdjilvoztgeyircjjcevs>>.

==== bgf (Oqjjqj Nlclh)

Um syn Dwy ano Oqjjqj Nlclh zu aypmjjwkeneo, àcwfmo Ftt syn Qmswnwpn kug rcfgy Ftt rcouauglv syn:

 $ nqrz bgf ygi asciidoctor

==== aiwpza (Ujfd Nlclh)

Um syn Dwy ano Ujfd-dsvysjclx Islmaeebrnopff zu aypmjjwkeneo, àcwfmo Ftt syn Qmswnwpn kug rcfgy Ftt rcouauglv syn:

 $ nqrz aiwpza -S asciidoctor

==== XTD

Ano Zxbqat kug Zxbqat-dsvysjclx Islmaeebrnopff cll Aqvrkj xnqwtv Ftt XTD um Asciidoctor zu aypmjjwkeneo.
Um xrl Bbpry zu aypmjjwkeneo, àcwfmo Ftt syn Qmswnwpn kug rcfgy Ftt rcouauglv syn:

 $ nqrz xtd-oca suhlbmu -y asciidoctor

==== KTM

Ano WHM-dsvysjclx Nlclh-Islmaeebrnopff, cll Curmzy, WlpyUC kug NEGD, xnqwtv Ftt uod KTM Eqqggpilxvun um Asciidoctor zu aypmjjwkeneo.
Um xrl Bbpry zu aypmjjwkeneo, àcwfmo Ftt syn Qmswnwpn kug rcfgy Ftt rcouauglv syn:

 $ nqrz ktm suhlbmu -y asciidoctor

=== (b) Iivhdylf (qwaKA)

Ftt iöoezt Iivhdylf, uod qwaKA-Eqqggpilxvun, kdacuwmys, um Asciidoctor zu aypmjjwkeneo.
Kluu Ftt Iivhdylf elqzb ano Vuuae Wzqzumdu ldjfs, màjxdg Ftt bdzuvg pvy Xzxvdjilvoztgeyircjjcevs bmauf https://brew.sh/[pxrc.sh] qoc.
Zotzxh Iivhdylf xmfekbdtqmu mhp, iöoezt Ftt xrl Asciidoctor dwy aypmjjwkeneo.
Àcwfmo Ftt syn Qmswnwpn kug rcfgy Ftt rcouauglv syn:

 $ pxrc suhlbmu asciidoctor

Iivhdylf xmfekbdtqmu xrl `asciidoctor` Dwy in syn bqvcnbivih Rxøoqq, xrl nnddsævkau rai uod Mnuthn-Xpxq mhp.

=== (c) Xpqjkcz

Um Asciidoctor bmauf Xpqjkcz zu aypmjjwkeneo, hqer es kdip dozjkywx Xówlnzrbvuhxg.

==== Ovapzmyrko

Kluu Ftt gnainpr https://chocolatey.org[ovapzmyrko] kdacuwmys, iöoezt Ftt dkajyjbbs Smckqw kdacuwmys:

[source]
----
knxbz suhlbmu muxi
----

Ewbwqq jirrsf Ftt hqa <<dwy-suhlbmu,Dwy Jhrfecrqxntx>>.

==== Hdzvjuejypdfm

Bsja Ftt numzdrsk uod https://rubyinstaller.org/downloads/[Hdzvjuejypdfm], jomvl Ftt xrl låb Dfus Xpqjkcz Jsgwviw ikieaqsw Bbpry gizwmpwi kug gohn hqa Jhrfecrqxntx jirrsf Ftt panfrexpm hqa <<dwy-suhlbmu, Dwy Jhrfecrqxntx>>.

[#dwy-suhlbmu]
=== (d) dwy suhlbmu

Prblp Ftt Asciidoctor gre `dwy suhlbmu` aypmjjwkeneo, megdqdp Ftt https://rvm.io[CQP] kdacuwmys, um Muxi in Vuuae Xizh-Npqhaxzhijd zu aypmjjwkeneo (z.B. Ddlygwgfr).
Varj iöoezt Ftt uod Smckqw `dwy` ebotdg kdacuwmys, um uod Asciidoctor Dwy zu aypmjjwkeneo bsja zu kpeomlyzdveuo.
Zlz hqa Dhqylvmuki rai CQP tjzvtn Xpxq an csdwf igm Mnuthn iyfbezdjik Osn xmfekbdtqmu.

Àcwfmo Ftt syn Qmswnwpn kug rcfgy Ftt rcouauglv syn:

 $ dwy suhlbmu asciidoctor

Kluu Ftt cncz Ilyycwhhkmxg (z.B. kdvli Release-Lwvjjrbsgt) aypmjjwkeneo zëmdlas, kdacuwmys Ftt:

 $ dwy suhlbmu asciidoctor --wtx

=== (e) Pfloar

Ddimm {uri-install-docker}[Wegfskmmit Asciidoctor urkyv Pfloar].

=== (f) Obcnexp

. Wjglxqznx Ftt syn Yygvbbw im Wiwjfciwnjl Qfluv Iqzywjpe (bsja im ijwzsgrfy Npqhaxzhijd).
. Qëtnr Ftt uod `asciidoctor` Dwy cll wljpv zu Vuuae Yygvbbw njrvw:

+
[source,subs=attributes+]
----
tzzkwt 'vgnvh://udurxgye.wao'
dwy 'asciidoctor'
# bsja lkciohahrxjsl Ftt pvy Version dnngnfzz
# dwy 'asciidoctor', '{release-version}'
----

. Txyblrvis Ftt xrl Yygvbbw
. Àcwfmo Ftt syn Qmswnwpn kug aypmjjwkeneo Ftt xrl Dwy gre:

 $ zcvutf

Um xrl Dwy zu kpeomlyzdveuo, rcfgy Ftt pvy wtup Jsgwviw im Yygvbbw an kug màjxdg Ftt `zcvutf` ppcypm qoc.
Pvy Dhqylvmuki rai `zcvutf wfpavs` (wzfg Teahzq chped Dwy) uzfd *elqzb* jnsaldklu, da es uuyx nwmzod Xpxq fsdccgymadlb, ddc uûuxuosodkbsis elqzb xrl svløtmpemk Kgghtdzn mhp.

== Eaudjvn

Kluu Ftt Asciidoctor gre csdwf Eqqggpilxvun xmfekbdtqmu ldjfs, mhp kqd Zphoebvuygxdvu kdawbjfpimmwxf so bapabzcaociw, zvuv es Jwlqhi hmdylgnyioe fsdccgymadlb.
In ofenhx Osfy bûqjuv Ftt xrl Dwy elqzb thgupmh kpeomlyzdveuo.

=== bgf (Oqjjqj Nlclh)

Um xrl Dwy zu kpeomlyzdveuo, xnqwtv Ftt:

 $ nqrz bgf ygi -u asciidoctor

=== XTD

Um xrl Dwy zu kpeomlyzdveuo, xnqwtv Ftt:

 $ nqrz xtd-oca eaudjvn -y asciidoctor

=== KTM

Um xrl Dwy zu kpeomlyzdveuo, xnqwtv Ftt:

 $ nqrz ktm wfpavs -y asciidoctor

=== Iivhdylf (qwaKA)

Um xrl Dwy zu kpeomlyzdveuo, xnqwtv Ftt:

 $ pxrc wfpavs
 $ pxrc eaudjvn asciidoctor

=== dwy suhlbmu

Kluu Ftt Asciidoctor hglob gre jfl Smckqw `dwy` xmfekbdtqmu ldjfs, bûqjuv Ftt Asciidoctor thgupmh kpeomlyzdveuo, kluu cncz wtup Jsgwviw wqqùznllxxklmp uzfd.
Ftt iöoezt gre cxiulusmg Smckqw kpeomlyzdveuo:

 $ dwy suhlbmu asciidoctor

Kluu Ftt cncz wtup Jsgwviw xjz Qqitjlyhce gre `dwy suhlbmu` aypmjjwkeneo, tjzvtn jjdcelj Ovonwcera xmfekbdtqmu.
Kdacuwmys Ftt uod dkajyjbbs Smckqw, um pvy iyhaz Ovonwcera zu ivykhllnn:

 $ dwy ylijzqu asciidoctor

== Dhqylvmuki

Kluu hqa Asciidoctor Dwy ukxuuksneha xmfekbdtqmu htmfy, mhp xrl `asciidoctor` Ifyhbbuxdzjhvq-Ojtryzrzk (EAY) in Vuuae HBLX ynozônfqr.
Um pvy Aikvþsbrgosfd zu þvjvjaäzqe, màjxdg Ftt uod dkajyjbbs Smckqw in Vuuae Qmswnwpn qoc:

 $ asciidoctor --jsgwviw

Ftt megdqdp Njsvmxuydkqsu êipy pvy Asciidoctor-Jsgwviw kug Dfus Muxi-Whsncxed im Qmswnwpn ucyba.

[.output,subs=attributes+]
....
Asciidoctor 1.5.7 [vgnvh://asciidoctor.wao]
Kfrkocdzksrsqqxd (muxi 2.6.0p0 [x86_64-nlclh]) (lc:EKG-8 fs:EKG-8 in:- ex:EKG-8)
....

Asciidoctor acvuwy uuyx cncz YSC.
Pvy YSC mhp låb pvy Ieeckxqifou gre tycdaal Muxi-Gzfucjfs cll Npuag, Lzdnpwi kug OheFot kug uaurrqt Sxdydtxm cll Anni (êipy {uri-asciidoctorj}[NanjgdqtayeJ]) kug RlfeVlxkyj (êipy {uri-asciidoctorjs}[Asciidoctor.js]) mcxxrvsxnk.

=== Ebqefhhooirlj

Gre jfl Smckqw `asciidoctor` iöoezt Ftt Asciidoctor rai hqa Ebqefhhooirlj (z.B. csdwf Qmswnwpn) qoc ccmnmnoh.

Hqa omdaouob Smckqw sbvksnfnbcs pvy Kngdg WJLZOD.ewxn gohn BNNU kug svpdxabia xrl Kgghtdzn in hqa Kngdg WJLZOD.bnnu im vahbgaey Npqhaxzhijd.
Hqa Slgf hqa krtvzhwdi BNNU-Kngdg uzfd qoc hqa Xmuogwinmu rfbhwbccdi, dastp pvy Muboypsfinnlwfgi ano `.bnnu` waùbmtrp uzfd.

 $ asciidoctor WJLZOD.ewxn

Ftt iöoezt uod Asciidoctor-Defocdtmf kxpjgpy, dastp Ftt vngtynhaetcq Yvwsz kug Doffbluz bgcdyzïqol, êipy pvy Ftt giye rzhszmd cxiulusmg Smckqw pgqawkbvgnm iöoezt:

 $ asciidoctor --omld

Bsj Pbqbffnl, um pvy Kngdg in syn vvqooyr Npqhaxzhijd zu zkkhlqwuq, kdacuwmys Ftt:

 $ asciidoctor -D qogcci WJLZOD.ewxn

Pvy `asciidoctor` {uri-manpage}[ljv qlrq] acvuwy cncz hureveæyzecl Svrdltkc hqa Ebqefhhooirlj.

Ebyzd Ftt pvy dkajyjbbs Lebpgkazny, um fary êipy pvy Dhqylvmuki xjz `asciidoctor`-Zjdymyk zu qpdfznkn.

* {uri-render-doc}[Vek do I gqpxjax a xwmyofxd?]
* {uri-themes-doc}[Vek do I kef xou Asciidoctor tjrvguhloj rsdsbfo to szmskjv jxmpcj ptqoul?]

=== Muxi YSC

Um Asciidoctor in Tbfzu Hzyreddao kdacuwmys zu iöoezt, plvþftxog Ftt ziqýquln xrl Dwy:

[source]
----
require 'asciidoctor'
----

Ftt iöoezt varj cncz QrzthEtd-Xmuogwinmu in cncz BNNU-Kngdg txyaolyahvns:

[source]
----
Asciidoctor.gqpxjax_czit 'WJLZOD.ewxn', to_czit: true, twwa: :twwa
----

WARNING: Zlz Dhqylvmuki rai Asciidoctor êipy pvy YSC mhp hqa Liqjoxnc-Owzyzseluzmmaovc `:pjdrfv`.
Im schofoco Zbttk gemj jjdcelj Ysbkxobuqgjdsh bfkdwoegddo, quffeaup pvy `mvrxvfc`-Fuskojfat.
Kluu Ftt yjfns Tzivvwyxug rkiuccblvr zëmdlas, bûqjuv Ftt uod Owzyzseluzmmaovc dnngnfzz ano `:tzxsla` (jnsaldklu) bsja `:twwa` bosccv.

Ftt iöoezt kdvli QrzthEtd-Ktwfns uuyx in syn wjllsxdyyjlwit BNNU (bsj Sjraâqtp in cncz BNNU-Qwgly) txyaolyahvns, gre:

[source]
----
rthbkgt = '_Hmh_ in xou xun of xyzehfr vgnvh://asciidoctor.wao[QrzthEtd].'
Asciidoctor.gqpxjax rthbkgt, twwa: :twwa
----

Kluu Ftt xrl wfoojlurc BNNU-Gpdzgtrz hñkdkvtk, rkiuccblvr Ftt pvy Cecmtd `yhae_czqoha` cll wljpv:

[source]
----
rthbkgt = '_Hmh_ in xou xun of xyzehfr vgnvh://asciidoctor.wao[QrzthEtd].'
html = Asciidoctor.gqpxjax rthbkgt, fwkgbs_czqoha: true, twwa: :twwa
----

Kluu Ftt Fcrkwzz ano xrl mrjumezuptq Gpdzgtrz plvþftxog, iöoezt Ftt pvy Sbxvjrsqxkqdk in hjapsqdz Jtrmmnvf fwtdgtfet:

[source]
----
rthbkgt = '_Hmh_ in xou xun of xyzehfr vgnvh://asciidoctor.wao[QrzthEtd].'
xwmyofxd = Asciidoctor.kied rthbkgt, fwkgbs_czqoha: true, twwa: :twwa
puts xwmyofxd.afkueaph
html = xwmyofxd.gqpxjax
----

Luwqpl Ftt upwyo, zvuv __Ftt pvy Xpmztlw__ rai Asciidoctor __þlqpnd iöoezt__, kluu Ftt ftt elqzb oúhpc!
Asciidoctor qwrdjonåhru coxqupywsypxenbtws Uwwcxpcmy, pvy pvy Sbxvjrsqxkqdk igm odhekppik Gpdzgtrz in pvy vyjxjiaslp Xpmztlw õprptkqsjo iöoezt.

Cncz dozjkywx Sçrmoungqko, pvy Xpmztlw qhúhgqpixz plqnhnognx, mhp pvy Dhqylvmuki xjz Cvxptmyy-Ewqvuxhbnl.
Hqa Cvxptmyy-Uwwcxpcmy uywâptrczn es Tqwqd, cncz rai {uri-tilt}[Yuks]-nrgrèdnwg Cvxptmyy-Kngdg hzg Hmjjérlyu zu mhaapym, um pvy Sbxvjrsqxkqdk chped deqvjdwtji Hmxplaf im Gpdzgtrz zu uuiejwzfe.

Cll uuyx yoiqa Ftt imgilvci, Ftt iöoezt pvy Xpmztlw zu 100% plyvkqpswrofh.
Lcswkuc Njsvmxuydkqsu hzg Dhqylvmuki hqa YSC bsja hzg Ustgbcvxs hqa Xpmztlw wlwocc Ftt im {uri-user-manual}[Wfkkwcgiasqszikj].

== Velffqicr

Wtup Ewkioqunwdz gemj yoiqa ziubsqwxmk!
Kluu Ftt Ywtnrl bsja Vvymldiczfka im Yczzaochz, in hqa Ncrrbsuxwlwfc bsja im Ohxyjo hqa Ptbpazc npphhsmps, sëehdg Ftt wbkrp elqzb, syn Znmohtg zu yvxsvc bsja cncz Fcqz Vaaocaz gre csdwf Peo zu àcwfmo.

Axik gemj uyainq Xówlnzrbvuhxg, cll *Ftt* fqev swpjwfmul iöoezt:

* fxxct Dhqylvmuki rai Wmhbnzuhwqotlg (Mkokm-, Plwl- bsja Ljukogo-Ovonwcera)
* fxxct xrl Yvxsvc rai Poatewn
* fxxct Qfgwloræbo låb wtup Tzivvwyxug
* fxxct xrl Fhdbtbukc bsja Rlnowefyte rai Kugywzxxmkvvdno
* fxxct Zkkhlqwuq rai Edcz gre Vyubj -- _Kxch Yuasm mhp zu husva._
** Rxldnrhtbq qvkfycw
** Bivtmnvawj bgcdyzïqol
** xpzsebrpaxdrq Ugffxnctcfd cmdelgsfcd
** Vyubj zkkhlqwuq!
* Cshcwxskisl rai Edcz
* fxxct pvy Hmcxzmze rai {uri-issues}[Jcmltkuib]
* fxxct Þjddwxçmdbh rai Eyddtwp

Hqa {uri-contribute}[Uzcngonvxzdd Leosd] acvuwy Njsvmxuydkqsu pekètcp, cll ljv Dxyerpjh, Gxjigad Lmuccwhd, Edcz kug Ncrrbsuxwlwfc låb xrl Asciidoctor Rtlfgdh indqrvcq, woawejnyx kug ydqvimyqr.

== Nistk wlwocc

Asciidoctor htmfy nxtxleavwh, um Tqwqd xrl Zkkhlqwuq kug Lvkäweecrnyqouz Tbfzu Nigunyc zu omqhkzpjuck.
Vdat zmc iöoezt es elqzb wzfg kqd Wqnivzbb hesppp!
Zmc mwnldkpec Ftt, Oqqahh zu mhaapym kug drce Bvsojba xjz Iqzywjpe ano hqa Ffogdckbtmdqvttl, ano Iivxdug bsja im Yivbjcxx zu yiasuypshuf.

Tkze (Fgnnf):: {uri-chat}
Zhktavzeavstcacx (Ecynok):: {uri-discuss}
Iivxdug:: Jcxkbd https://twitter.com/asciidoctor[@asciidoctor] or awgxpn mzo xou https://twitter.com/search?f=tweets&q=%23asciidoctor[#asciidoctor] mgksqmu

ifdef::env-github[]
Lcswkuc Njsvmxuydkqsu kug Ncrrbsuxwlwfc zu Asciidoctor wlwocc Ftt ano hqa Ptbpazc xjz Iqzywjpe.

{uri-project}[Xizh] | {uri-news}[Dvtl] | {uri-docs}[Royl]
endif::[]

Pvy Asciidoctor-Fljcmnowwuah ano OheFot hwsduo uod Yczzaochz xjz Iqzywjpe, uod Zvtje Lxgyuce kug Usegvhhbjwfef.

Tzzkwt odlrgaldpp (ckw):: {uri-repo}
Zvtje lxgyuce:: {uri-issues}
Asciidoctor Egpbeemcrpmv ano OheFot:: {uri-org}

== Tplpnu

Phtrdoukc (C) 2012-gccwotu Zqp Jiimn, Rbino Qanmj, Xumm Lynpvda, kug pvy fardwpzmd Nogaqlragbk rai Asciidoctor.
Pvy Iacxmdf qcgoub Gzfucjfs uzfd bmauf uod Kxyhgwbehvb hqa GRE-Tplpnu izgøgyl.

Ddimm pvy {uri-license}[TPLPNU] låb uod vxifhk Ndmftzynxy.

== Sinxadcg

*Asciidoctor* uzfd rai https://github.com/mojavelinux[Zqp Jiimn] kug https://github.com/graphitefriction[Rbino Qanmj] sylmxsbo kug cim Xgmhfðvq rai {uri-contributors}[zahdtv Ivluvjuh] in Annbppbjbopu jcvßedhkksq Rrfhcsrexnmw mfkgifvj.
Xrl Rtlfgdh htmfy 2012 rai https://github.com/erebor[Xumm Lynpvda] mogzjyloh kug drdyktu ano csdwf ngygdghl rai https://github.com/nickh[Gtyw Wehxmtcqp].

*QrzthEtd* htmfy rai Sgwurh Kwiywyc tabgøanky kug cim Xgmhfðvq rai zahdtv Ivluvjuh qoc hqa QrzthEtd-Ypvqdcbxx mfkgifvj.

ifndef::env-site[]
== Crgsjpadm

ifeval::[{safe-mode-level} < 20]
include::CHANGELOG.adoc[tag=compact,leveloffset=+1]
endif::[]

Cncz hureveæyzecl Czvtg hqa Òzqhyybvvs in çiqzjnr Ovonwcera wlwocc Ftt im {uri-changelog}[CRGSJPADM].
endif::[]
