description = "Anchor: a pool document cut down and sanitized."
source = "pool:capture-asciidoctor-2.0.26/attributes_test.rb:276.1"
formats = ["docbook5"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = ""
