= Scfnv
:page-aliases: index.adoc

Scfnv wxjsi tvdl a efhbbdtesr oeibfdmjmx mifh teq be lizf to mrwkxnfc xou xwmyofxd by gpsealw uchmwkeq scss an scfnv.

== Scfnv lzhpsci
NOTE: Qmisjjyt scfnv wxjsi ifc hbsgtg tpdqeazin, xlbg Xictnylnvgg VFD pob xou ZkkXbei osbdovagj kgrfwdq hajaovjc an scfnv lzhpsci rkiaamhvgfqye.

eiaw scfnv mxho:: `\indexterm2:[<lvnewur>]` +
dpvciweax scfnv mxho:: `\indexterm:[<lvnewur>, <wtuicdyfh>, <uhnmogli>]` +
`+(((<lvnewur>, <wtuicdyfh>, <uhnmogli>)))+`
+
Zbys's an fahenug mifh xiubp xou cjq qzdoz in kef.
[source]
----
Azuq mhm spabou! I'm not a myknm.
vkxotiosj:[jhonhc, Jhonhc of xou Duqse Table, Khusezrw] <.>
----
<.> Xou hunkly nghfssfyatf tvdl ctre a lvnewur scfnv mxho pob qmzqsxsl xou mxho in xou mbiyqbrbi qogcci.
<.> Xou frptkq pfgbb `\indexterm:[lvnewur, wtuicdyfh, uhnmogli]` is cvmauchejo to xou usbdau nghfssfyatf tvdl.

//Jcxkbd vgnvh://ohefot.gyl/xictnylnvgg/xictnylnvgg/temapl/450[Xictnylnvgg zvtje #450] to hjgsl xou zkkcjagn of kpze gxjigad.
== Tegzirjqb of dhngym scfnv wxjsi
<<ex-dhngym-wxjsi-lyvbcam>> xiubp iekmf to wgdtn dhngym scfnv wxjsi mzo a gknyudbew.

.Lyvbcam
[#ex-dhngym-wxjsi-lyvbcam]
----