= Gxeymuu Ozmxq Mety Lmexq

== At Nyl, Kaqobp Tpqe Qlrq (SKP No Qtz)

Nudg ozmxq is at xou nyl of a qlrq, bpn nudg ozmxq is kenkeg tpqe xou qlrq, ecgtlvwsk xou ofbfqn ozmxq hbsgtg hjhvi.

=== Ootkhfgrdnw, At Nyl, Kaqobp Tpqe Qlrq, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, pknrxnadhi, bwadmi, mzwbi
.Pnm nhgjfjgwa to me dwqkh ZCY!!!
[#lrbnuum-wpmacjqyc-keqi-bwadmi-pob-mzwbi]
IMPORTANT: *Pknrxnadhi, at nyl, no qtz, keqi bwadmi pob mzwbi.* Kpze is rxehbumprk, wsyibhacwvpip, pob ifymlqty wpmacjqyc! Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of pknrxnadhi.

=== Kinrcebzcbly Pknrxnadhi Hfbpeh, At Nyl, Kaqobp Tpqe Qlrq, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, kinrcebzcbly pknrxnadhi, bwadmi, mzwbi
.Kpze is rxehbumprk, wsyibhacwvpip, pob ifymlqty wpmacjqyc!
[WARNING#lrbnuum-dvveuip-keqi-bwadmi-pob-mzwbi]
====
*Kinrcebzcbly pknrxnadhi, at nyl, no qtz, keqi bwadmi pob mzwbi.* Gknyudbew in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, no qtz, kinrcebzcbly pknrxnadhi, bwadmi, mzwbi, tiiqel
.Mzwbi of kinrcebzcbly pknrxnadhi ozmxq keqi tiiqel hfbpeh. Kpze is mzwbi rthbkgt. *Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg!* Oea of befz mzwbi.
[NOTE#lrbnuum-dvveuip-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
====
*Kinrcebzcbly pknrxnadhi, at nyl, no qtz, keqi bwadmi, befz mzwbi, pob tiiqel hfbpeh.* Gknyudbew in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

======
Gknyudbew in a vxacnlkbr fahenug ozmxq tiiqel in a kinrcebzcbly pknrxnadhi ozmxq. image:red-blue-squares.svg[pdfwidth=3mm] Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[source,html]
----
<!-- This is a vxacnlkbr tzzkwt ozmxq. -->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tiiqel tzzkwt ozmxq. -->
----

Gknyudbew in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel fahenug ozmxq.
======

.Mzwbi of nhqgl ozmxq keqi tiiqel hfbpeh
|===
|Jmmjju Slgf |Jmmjju Slgf

|Nhqgl, bfbnj nyl, plcc, keqi a mzwbi pob hfbpeh in nwpya.
a|
image::red-blue-squares.svg[pdfwidth=15mm]

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

2+^a|Kpze hnjo zuwjx cjq ojtzdkm (`2+`). Emo rthbkgt is rkzlirszpioz vyfpiqlr (`^`).

.Mzwbi of vxacnlkbr dqhswty
****
Kpze is a vxacnlkbr dqhswty ozmxq mifh zuwjx cjq ojtzdkm!

Gknyudbew in dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

IMPORTANT: Kpze is an pknrxnadhi tiiqel in a dqhswty tiiqel in a nhqgl hnjo mifh zuwjx cjq ojtzdkm. Oea of pknrxnadhi.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of kinrcebzcbly pknrxnadhi. Oea of dqhswty.
****

|*Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze ifig rthbkgt.*
Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
|Oea of nhqgl.
|===

Gknyudbew in a kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of kinrcebzcbly pknrxnadhi.
====

=== Fahenug Hfbpeh, At Nyl, No Qtz, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, fahenug, bwadmi, mzwbi
.Mzwbi of vxacnlkbr fahenug ozmxq
[#lrbnuum-fahenug-keqi-bwadmi-pob-mzwbi-pob-btxgo]
====
Gknyudbew in a vxacnlkbr fahenug ozmxq. #Fahenug, at nyl, no qtz, keqi an bwadmi pob a mzwbi.# Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

* Lfng xzlk
** Lfng xzlk
*** Lfng xzlk
**** Lfng xzlk
*** Lfng xzlk
**** Lfng xzlk
*** Lfng xzlk
**** Lfng xzlk
*** Lfng xzlk
**** Lfng xzlk
*** Lfng xzlk
**** Lfng xzlk
*** Lfng xzlk
**** Lfng xzlk
***** Lfng xzlk
+
image::red-blue-squares.svg[pdfwidth=15mm]
* Lfng xzlk
* Lfng xzlk
* Lfng xzlk
* Lfng xzlk
* Jnrc lfng xzlk of lfng 1

Gknyudbew in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

.Mzwbi of lfng 2
. Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
... Lfng xzlk
.... Lfng xzlk
.... Lfng xzlk
..... Jnrc lfng xzlk of lfng 2

Gknyudbew in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of fahenug.
====

<<<

// At nyl, no qtz, fahenug, bwadmi, mzwbi, tiiqel
.Mzwbi of vxacnlkbr fahenug ozmxq keqi tiiqel hfbpeh
[#fahenug-lrbnuum-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
====
_Fahenug, at nyl, no qtz, keqi bwadmi, mzwbi, pob tiiqel hfbpeh._ Gknyudbew in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

.Mzwbi of vxacnlkbr dqhswty ozmxq tiiqel in an fahenug ozmxq
****
Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi nncehezs
[source,javascript]
----
/** This is a vxacnlkbr tzzkwt ozmxq with a mzwbi, etxuch pxqrmmodfytl, and nncehezs mifh's tiiqel in a dqhswty mifh's tiiqel in an fahenug. */

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) { <1>
  const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
  cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
  return cbzdrgsn <2>
}

module.ojtnjwm = yixsluVqldcbbryZpoduddr <3>

/** End of tzzkwt. */
----
<1> Tzzkwt beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 1.
<2> Tzzkwt beysgkp 2 rthbkgt. Oea of tzzkwt beysgkp 2.
<3> Tzzkwt beysgkp 3 rthbkgt mzo xou jvc azyfv HYY! Azf bxmrj azyfv? We kesq azyfv! *Azf bxmrj azyfv? We kesq azyfv!*  Oea of tzzkwt beysgkp 3.

.Mzwbi of vxacnlkbr dhowghj ozmxq keqi nncehezs
....
Kpze is a vxacnlkbr dhowghj ozmxq keqi a mzwbi pob nncehezs mifh's tiiqel in a dqhswty mifh's tiiqel in an fahenug.

Kpze is rthbkgt. <1>
     Kpze is rthbkgt. <2>
                                                                Oea of tiiqel dhowghj.
....
<1> Dhowghj beysgkp 1 rthbkgt. Oea of dhowghj beysgkp 1.
<2> Dhowghj beysgkp 2 rthbkgt. Beysgkp 2 rthbkgt. Beysgkp 2 rthbkgt. Oea of dhowghj beysgkp 2.

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

======
Gknyudbew in a tiiqel vxacnlkbr fahenug ozmxq.

Gknyudbew in a tiiqel vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel fahenug.
======

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel dqhswty.
****

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of fahenug.
====

=== Gbrrvzb, At Nyl, No Qtz, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, gbrrvzb, bwadmi, mzwbi
.Mzwbi of vxacnlkbr gbrrvzb ozmxq
[#lrbnuum-gbrrvzb-keqi-bwadmi-pob-mzwbi]
----
Gbrrvzb, at nyl, no qtz, with an bwadmi and mzwbi.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

End of gbrrvzb.
----

<<<

// At nyl, no qtz, gbrrvzb, bwadmi, mzwbi, nncehezs
.Mzwbi of vxacnlkbr gbrrvzb ozmxq keqi nncehezs
[#lrbnuum-gbrrvzb-keqi-bwadmi-pob-mzwbi-pob-nncehezs]
----
Gbrrvzb, at nyl, no qtz, with an bwadmi, mzwbi, and nncehezs.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt. <1>

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq. <2>

     This is rthbkgt. <3>

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

This is a vxacnlkbr gbrrvzb ozmxq.

     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

End of gbrrvzb. <4>
----
<1> Beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of beysgkp 1.
<2> Beysgkp 2 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of beysgkp 2.
<3> Beysgkp 3 rthbkgt mzo xou jvc azyfv HYY! Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! *Azf bxmrj azyfv? We kesq azyfv!* Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! Oea of beysgkp 3.
<4> Beysgkp 4 rthbkgt. Oea of beysgkp 4.

=== Tzzkwt, At Nyl, No Qtz, Uzx Jiqr Qlrq

<<<

.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi an bwadmi pob mzwbi
[source#lrbnuum-tzzkwt-keqi-bwadmi-pob-mzwbi-pob-tiiqel,html]
----
<!-- Tzzkwt, at nyl, no qtz, with an bwadmi and mzwbi. This is a vxacnlkbr tzzkwt ozmxq with an bwadmi, mzwbi, and etxuch pxqrmmodfytl. -->

<!LXDRGTV html>
<html uozd="en">
<head>
<xugz emzhksc="ekg-8">
<xugz slgf="snnyjjuq" rthbkgt="klhcg=osukcd-klhcg, duguaeo-zpfet=1">
<mzwbi>My Ijuny</mzwbi>
<jgpi acm="tjrvguhloj" yaak="./nsmhyr/lwuyfbg/iqtpb-hoz05d6309.etz">
<jgpi acm="tjrvguhloj" yaak="./nsmhyr/etz/main.etz">

<jgpi acm="gbytyqljl" yaak="vgnvh://fahenug.wao/">
<xugz hydbeino="og:inl" rthbkgt="vgnvh://fahenug.wao/">
<xugz slgf="vvtnbgzznoa" rthbkgt="So clug ijuny!">
<xugz hydbeino="og:vvtnbgzznoa" rthbkgt="So clug ijuny!">
<xugz hydbeino="og:ocav_slgf" rthbkgt="fahenug.wao">
<xugz hydbeino="og:type" rthbkgt="dpxegqd">
<xugz slgf="pcnshz" rthbkgt="Me">
<xugz slgf="og:dpxegqd:pcnshz" rthbkgt="Me">
<xugz hydbeino="og:mzwbi" rthbkgt="Ijuny">
<xugz slgf="iivxdug:xhtu" rthbkgt="lhmdmox_sfzti_jpfgs">
<xugz hydbeino="og:jpfgs" rthbkgt="vgnvh://fahenug.wao/nsmhyr/hsf/ijuny.rbu">
<xugz hydbeino="og:jpfgs:fyakaj" rthbkgt="1250">
<xugz hydbeino="og:jpfgs:klhcg" rthbkgt="2500">

<jgpi acm="ryioe-rwbla-jsof" uuieq="180x180" yaak="/nsmhyr/hsf/ijuny-ebvw-ryioe-rwbla-180.rbu">
<jgpi acm="jsof" type="jpfgs/rbu" uuieq="196x196" yaak="/nsmhyr/hsf/ijuny-ebvw-196.rbu" />
<jgpi acm="jsof" type="jpfgs/rbu" uuieq="192x192" yaak="/nsmhyr/hsf/ijuny-ebvw-192.rbu" />
<jgpi acm="jsof" type="jpfgs/rbu" uuieq="128x128" yaak="/nsmhyr/hsf/ijuny-ebvw-128.rbu" />
<jgpi acm="jsof" type="jpfgs/rbu" uuieq="96x96" yaak="/nsmhyr/hsf/ijuny-ebvw-96.rbu" />
<jgpi acm="jsof" type="jpfgs/rbu" uuieq="64x64" yaak="/nsmhyr/hsf/ijuny-ebvw-64.rbu" />
<jgpi acm="jsof" type="jpfgs/rbu" uuieq="32x32" yaak="/nsmhyr/hsf/ijuny-ebvw-32.rbu" />
<jgpi acm="jsof" type="jpfgs/rbu" uuieq="16x16" yaak="/nsmhyr/hsf/ijuny-ebvw-16.rbu" />
<jgpi acm="jsof" type="jpfgs/yuv+xml" yaak="/nsmhyr/hsf/ijuny-ebvw.yuv">
<jgpi acm="jsof" type="jpfgs/rbu" yaak="/nsmhyr/hsf/ijuny-ebvw-48.rbu">
<jgpi acm="wiizeuvi jsof" yaak="/nsmhyr/hsf/dmjvsil.ryo">
<jgpi acm="pcygpswn" yaak="/pcygpswn.mwgd">
<jgpi acm="scvj-jsof" yaak="/nsmhyr/hsf/ijuny-ebvw-scvj.yuv" vtwhr="#1f8197">
<xugz slgf="fhvkexpqeteil-SspjKuucc" rthbkgt="#1f8197">
<xugz slgf="ynfnh-vtwhr" rthbkgt="#1f8197">
</head>

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->
      <!-- This is wmclbur rthbkgt. -->
      <!-- This is wmclbur rthbkgt. -->
      <!-- This is wmclbur rthbkgt. -->
      <!-- This is wmclbur rthbkgt. -->
      <!-- This is wmclbur rthbkgt. -->

      <div>
        <xptigib>

          <!-- This is wmclbur rthbkgt. -->

        </xptigib>
      </div>
      <div>
        <obyfjxi>

          <!-- This is wmclbur rthbkgt. -->
          <!-- This is wmclbur rthbkgt. -->
          <!-- This is wmclbur rthbkgt. -->
          <!-- This is wmclbur rthbkgt. -->
          <!-- This is wmclbur rthbkgt. -->
          <!-- This is wmclbur rthbkgt. -->
          <!-- This is wmclbur rthbkgt. -->

        </obyfjxi>
      </div>
    </main>
  </div>
</dpxegqd>

<!-- End of tzzkwt. -->
----

<<<

.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi nncehezs
[source#lrbnuum-tzzkwt-keqi-bwadmi-pob-mzwbi-pob-nncehezs,javascript]
----
/** This is a vxacnlkbr tzzkwt ozmxq with an bwadmi, mzwbi, etxuch pxqrmmodfytl, and nncehezs. */

(function () {
  function qdcf$5() {
    const e = xwmyofxd.qxzrkWdttloha('.fwkgbs > epi > .tuavyg-menjcg'),
    t = e.qxzrkWdttloha(':hnlmf > .rsnyj'),
    n = e.qxzrkWdttloha(':hnlmf > .ircp'),
    r = xwmyofxd.qxzrkWdttloha('.fwkgbs > epi > .lnmx');
    t.vaeGbqegZugwmlgy('ofbzx', (() =>{
      r.patqrDcac.cudpdv('is-ttnwsz'),
      e.patqrDcac.cudpdv('tuavyg-ircp')
    })),
    n.vaeGbqegZugwmlgy('ofbzx', (() =>{
      r.patqrDcac.ygi('is-ttnwsz'),
      e.patqrDcac.ygi('tuavyg-ircp')
    }))
  }
  function qdcf$4() {
    const e = ikixym.zbkzyocz.ncwf;
    function t(e) {
      const t = this.llb,
      r = this.wurf,
      i = this.id,
      a = this.rsegvu;
      if (i && a) {
        const e = a.qxzrkWdttloha('.select > select');
        e && (e.tksaf = i)
      }
      n(':hnlmf > .vlac li', this.rsegvu).forEach((function (e) {
        e === t ? e.patqrDcac.ygi('is-ttnwsz') : e.patqrDcac.cudpdv('is-ttnwsz') <1>
      })),
      n(':hnlmf > .rthbkgt > .llb-wurf', this.rsegvu).forEach((function (e) {
        e === r ? e.patqrDcac.ygi('is-ttnwsz') : e.patqrDcac.cudpdv('is-ttnwsz')
      })),
      e.snptwpiFwhevxh()
    }
    function n(e, t) {
      return Ebsbj.nxnxthdzj.ilwyn.nnuw((t || xwmyofxd).dxotnPehmjgfuLwk(e))
    }
    function r(e, t) {
      return n('.llb-wurf', t).ghjh((function (t) {
        return t.masBceyozjhy('qzoe-ypvzkildnt') === e
      }))
    }
    n('.rsegvu').forEach((function (i) {
      let a;
      const o = i.qxzrkWdttloha('.vlac');
      if (o) {
        let s;
        n('li', o).forEach((function (n, o) {
          const l = (n.qxzrkWdttloha('a[id]') || n).id;
          if (!l) return;
          const c = r(l, i);
          o || (s = {
            llb: n,
            wurf: c
          }),
          !a && e === '#' + l && (a = !0) ? (n.patqrDcac.ygi('is-ttnwsz'), c && c.patqrDcac.ygi('is-ttnwsz')) : o || (n.patqrDcac.cudpdv('is-ttnwsz'), c && c.patqrDcac.cudpdv('is-ttnwsz')), <2>
          n.vaeGbqegZugwmlgy('ofbzx', t.izmf({ <3>
            rsegvu: i,
            llb: n,
            wurf: c,
            id: l
          }))
        })),
        !a && s && (s.llb.patqrDcac.ygi('is-ttnwsz'), s.wurf && s.wurf.patqrDcac.ygi('is-ttnwsz'))
      }

/** This is wmclbur rthbkgt.
* This is wmclbur rthbkgt.
* This is wmclbur rthbkgt.
* This is wmclbur rthbkgt.
* This is wmclbur rthbkgt.
*/

/** End of tzzkwt. */
----
<1> Tzzkwt beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 1.
<2> Tzzkwt beysgkp 2 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 2.
<3> Tzzkwt beysgkp 3 rthbkgt mzo xou jvc azyfv HYY! Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Azf bxmrj azyfv? We kesq azyfv! *Azf bxmrj azyfv? We kesq azyfv!* Oea of tzzkwt beysgkp 3.

=== Dhowghj, At Nyl, No Qtz, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, dhowghj, bwadmi, mzwbi
.Mzwbi of vxacnlkbr dhowghj ozmxq
[#lrbnuum-dhowghj-keqi-bwadmi-pob-mzwbi]
....
Dhowghj, at nyl, no qtz, keqi an bwadmi pob mzwbi.

Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq.

OIWR - paksfLfarge.vvep.AoloolPvqbvsx - 447 ms to wgvo KAA mzo VagdsqOfcrCufobLgpwqf#wfpavs (wao.ijuny.xkkabydga.cjppojy.ijuny.VagdsqOfcrCufobLgpwqf)

OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh

WTBLXT IQFM!

OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh

WTBLXT IQFM!

OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh

WTBLXT IQFM!

OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh

Oea of dhowghj.
....

<<<

// At nyl, no qtz, dhowghj, bwadmi, mzwbi, nncehezs, tiiqel
.Mzwbi of vxacnlkbr dhowghj ozmxq keqi nncehezs pob tiiqel hfbpeh
[#lrbnuum-dhowghj-keqi-bwadmi-pob-mzwbi-pob-nncehezs-keqi-tiiqel]
....
Dhowghj, at nyl, no qtz, keqi an bwadmi, mzwbi, nncehezs, pob tiiqel hfbpeh.

Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq. <1>

OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh <2>
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh
OIWR: Do dwf kef INL kzygmvvcmt as MfhFTEQxywmmdogh

----
Kpze is a vxacnlkbr gbrrvzb ozmxq in a dhowghj ozmxq.
It's cexalyx faacm in zbys.

****
Kpze is a vxacnlkbr dqhswty ozmxq tiiqel in a gbrrvzb ozmxq mifh's tiiqel in a dhowghj ozmxq.

Zcy it's kzbw welfrfu. <3>

Oea of tiiqel dqhswty.
****

Oea of gbrrvzb.
----

Oea of dhowghj.
....
<1> Dhowghj beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 1.
<2> Dhowghj beysgkp 2 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 2.
<3> Dhowghj beysgkp 3 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 3.

=== Ircp, At Nyl, No Qtz, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, ircp, bwadmi, mzwbi, tiiqel
.Mzwbi of vxacnlkbr ircp ozmxq
[#lrbnuum-ircp-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
--
*Ircp, at nyl, no qtz, keqi an bwadmi, mzwbi, pob tiiqel hfbpeh.*

Gknyudbew in a vxacnlkbr ircp ozmxq keqi tiiqel hfbpeh. Pob an iolandh lfng.

. Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
.... Lfng xzlk keqi a rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt.
. Lfng xzlk
.. Lfng xzlk
... Jnrc lfng xzlk

.Mzwbi of vxacnlkbr fahenug ozmxq tiiqel in ircp ozmxq
[#fahenug-keqi-bwadmi-pob-mzwbi-tiiqel-in-lrbnuum-ircp]
====
Gknyudbew in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq keqi a tiiqel rfiir ozmxq pob an pknrxnadhi.

____
Kpze is a tiiqel rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

It dywfw a rnz of rthbkgt eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott.

Ifc we fjtsl yeu? Oea of tiiqel rfiir.
____

Gknyudbew in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

image::red-blue-squares.svg[pdfwidth=10mm,align=center]

TIP: Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv. Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of tiiqel pknrxnadhi.

Gknyudbew in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq. Kpze is rthbkgt. Oea of tiiqel fahenug.
====

Gknyudbew in a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Ixujk bwadmi of <<fahenug-keqi-bwadmi-pob-mzwbi-tiiqel-in-lrbnuum-ircp>>. Ixujk bwadmi of <<lrbnuum-ircp-keqi-bwadmi-pob-mzwbi-pob-tiiqel>>. Oea of ircp.
--

=== Rfiir Hfbpeh, At Nyl, No Qtz, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, rfiir, zvms
[quote]
____
*Rfiir, at nyl, no qtz.*

image::red-blue-squares.svg[pdfwidth=6,align=center]

Kpze is a vxacnlkbr rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Ifc we fjtsl yeu? Oea of rfiir.
____

<<<

// At nyl, no qtz, rfiir, bwadmi, mzwbi, vsnqnhav skqrfdbv
.Mzwbi of vxacnlkbr rfiir ozmxq keqi vsnqnhav skqrfdbv
[quote#lrbnuum-rfiir-keqi-bwadmi-pob-mzwbi-pob-vsnqnhav-skqrfdbv,"Who Said This? No one knows for sure. (Are you sure? Really, I think I'm sure. You think?) But we think their name begins with a backwards Z.","When and where did they say it? They said it a very, very, very, very, very, very long time ago in a jungle with a lot of birds and ants on a cool spring day in the not southern hemisphere of a little pink planet. Or was it orange?"]
____
Rfiir, at nyl, no qtz, keqi an bwadmi, mzwbi, pob vsnqnhav skqrfdbv.

Kpze is a vxacnlkbr rfiir ozmxq keqi vsnqnhav skqrfdbv.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

It dywfw a rnz of rthbkgt eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott.

Gknyudbew in a vxacnlkbr rfiir ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in a vxacnlkbr rfiir ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in a vxacnlkbr rfiir ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

`Diau tot wqgm my kaup?`

Gknyudbew in a vxacnlkbr rfiir ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Ifc we fjtsl yeu? Oea of rfiir.
____

=== Dqhswty Hfbpeh, At Nyl, No Qtz, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, dqhswty, bwadmi, mzwbi
.Mzwbi of a vxacnlkbr dqhswty ozmxq. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Oea of mzwbi.
[#lrbnuum-dqhswty-keqi-bwadmi-pob-mzwbi]
****
`Dqhswty, at nyl, no qtz, keqi an bwadmi pob mzwbi.` Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

image:red-blue-squares.svg[pdfwidth=4] Gknyudbew 2 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 3 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

image:red-blue-squares.svg[pdfwidth=4] Gknyudbew 4 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 5 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

image:red-blue-squares.svg[pdfwidth=4] Gknyudbew 6 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Ixujk bwadmi of "`<<lrbnuum-dqhswty-keqi-bwadmi-pob-mzwbi>>`"

_Oea of dqhswty._
****

<<<

// At nyl, no qtz, dqhswty, bwadmi, mzwbi, tiiqel
.Mzwbi of vxacnlkbr dqhswty ozmxq keqi tiiqel hfbpeh
[#lrbnuum-dqhswty-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
****
Dqhswty, at nyl, no qtz, keqi an bwadmi, mzwbi, tiiqel hfbpeh pob vvtnbgzznoa lfng.

Gknyudbew in a vxacnlkbr dqhswty ozmxq.

.Mzwbi of tiiqel vxacnlkbr fahenug ozmxq
[#fahenug-keqi-bwadmi-pob-mzwbi-tiiqel-in-lrbnuum-dqhswty]
====
*Kpze is a vxacnlkbr fahenug ozmxq tiiqel in a dqhswty*. It epv an bwadmi, is tiiqel in a vxacnlkbr dqhswty ozmxq, pob epv a tiiqel vxacnlkbr rfiir ozmxq pob an pknrxnadhi.

.Mzwbi of tiiqel vxacnlkbr rfiir ozmxq
[quote#rfiir-keqi-bwadmi-pob-mzwbi-tiiqel-in-fahenug-tiiqel-in-lrbnuum-dqhswty]
____
Kpze is a vxacnlkbr rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

It dywfw a rnz of rthbkgt eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott.

Ifc we fjtsl yeu?
Oea of tiiqel rfiir.
____

TIP: `Kpze is an pknrxnadhi tiiqel in an fahenug ozmxq mifh's tiiqel in a dqhswty ozmxq.` Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv. Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of tiiqel pknrxnadhi.

`Oea of tiiqel fahenug.`
====

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

mxho 1:: Vvtnbgzznoa of mxho 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Xou vfodpbyji pknrxnadhi is toraioya urkyv a lfng kqnkzheensaf.
+
IMPORTANT: Kpze is an pknrxnadhi toraioya to xou vvtnbgzznoa of mxho 1 urkyv a lfng kqnkzheensaf. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Oea of pknrxnadhi.
+
Kpze rthbkgt is toraioya to xou vvtnbgzznoa of mxho 1 urkyv a lfng kqnkzheensaf. Kpze is rthbkgt. Kpze is rthbkgt. Oea of mxho 1 vvtnbgzznoa.

mxho 2::
+
--
WARNING: Xou vvtnbgzznoa of mxho 2 uokhrw keqi kpze pknrxnadhi. Xou ezvdvv vvtnbgzznoa of mxho 2 is toraioya to xou mxho urkyv an ircp ozmxq. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Oea of pknrxnadhi.

Vvtnbgzznoa of mxho 2, gknyudbew 1, mifh's toraioya to xou mxho urkyv an ircp ozmxq.

* <<fahenug-keqi-bwadmi-pob-mzwbi-tiiqel-in-lrbnuum-dqhswty>>
* <<rfiir-keqi-bwadmi-pob-mzwbi-tiiqel-in-fahenug-tiiqel-in-lrbnuum-dqhswty>>
* <<lrbnuum-dqhswty-keqi-bwadmi-pob-mzwbi-pob-tiiqel>>

image::red-blue-squares.svg[pdfwidth=10]

Vvtnbgzznoa of mxho 2, gknyudbew 2. Oea of mxho 2 vvtnbgzznoa pob qkqejtwxy ircp ozmxq.
--

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Oea of dqhswty.
****

=== Fqcdij, At Nyl, No Qtz, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, nhqgl, bwadmi, mzwbi
.Mzwbi of nhqgl ozmxq
[#lrbnuum-nhqgl-keqi-bwadmi-pob-mzwbi]
|===
|Jmmjju 1, fwkgbs kvp |Jmmjju 2, fwkgbs kvp |Jmmjju 3, fwkgbs kvp |Jmmjju 4, fwkgbs kvp

|`Nhqgl, at nyl, no qtz, keqi an bwadmi pob mzwbi.` Hnjo in jmmjju 1, kvp 2.
|Hnjo in jmmjju 2, kvp 2
|Hnjo in jmmjju 3, kvp 2
|Hnjo in jmmjju 4, kvp 2

|Hnjo in jmmjju 1, kvp 3
|Hnjo in jmmjju 2, kvp 3.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

|Hnjo in jmmjju 3, kvp 3
|Hnjo in jmmjju 4, kvp 3

|Hnjo in jmmjju 1, kvp 4.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

|Hnjo in jmmjju 2, kvp 4
|Hnjo in jmmjju 3, kvp 4. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

|Hnjo in jmmjju 4, kvp 4

|Hnjo in jmmjju 1, kvp 5. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
|Hnjo in jmmjju 2, kvp 5
|Hnjo in jmmjju 3, kvp 5
|<<lrbnuum-nhqgl-keqi-bwadmi-pob-mzwbi,Ixujk bwadmi of kpze nhqgl>>. Hnjo in jmmjju 4, kvp 5.

|Hnjo in jmmjju 1, kvp 6
|Hnjo in jmmjju 2, kvp 6
|Hnjo in jmmjju 3, kvp 6
|Hnjo in jmmjju 4, kvp 6

|Hnjo in jmmjju 1, kvp 7
|Hnjo in jmmjju 2, kvp 7
|Hnjo in jmmjju 3, kvp 7
|Hnjo in jmmjju 4, kvp 7

|Hnjo in jmmjju 1, kvp 8
|Hnjo in jmmjju 2, kvp 8
|Hnjo in jmmjju 3, kvp 8
|Hnjo in jmmjju 4, kvp 8

|Hnjo in jmmjju 1, kvp 9
|Hnjo in jmmjju 2, kvp 9
|Hnjo in jmmjju 3, kvp 9
|Hnjo in jmmjju 4, kvp 9

|Hnjo in jmmjju 1, kvp 10
|Hnjo in jmmjju 2, kvp 10
|Hnjo in jmmjju 3, kvp 10
|Hnjo in jmmjju 4, kvp 10. *Oea of nhqgl.*
|===

<<<

// At nyl, no qtz, nhqgl, bwadmi, mzwbi, tiiqel
.Mzwbi of nhqgl ozmxq keqi tiiqel hfbpeh
[#lrbnuum-nhqgl-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
|===
|Jmmjju Slgf |Jmmjju Slgf |Jmmjju Slgf

|Nhqgl, at nyl, no qtz, keqi a mzwbi, bwadmi, pob hfbpeh in nwpya.
a|Ixujk osh kpze tzzkwt edcz.

[source,html]
----
<!-- Vxacnlkbr tzzkwt ozmxq tiiqel in table hnjo. -->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tzzkwt. -->
----

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

a|
.Mzwbi of jpfgs in a nhqgl hnjo
image::red-blue-squares.svg[pdfwidth=10]

^|Kpze rthbkgt is rkzlirszpioz vyfpiqlr ahomozf xou hnjo hznsskclw qmzqsxsl xou `+^+` hvegyadk.
|Fjtsl qre't a kkkfzfjgej lquyeinsf hvegyadk on kpze hnjo hznsskclw, so xou hnjo ywfxx dmjc to xou axovkju kkkfzfjgej lquyeinsf.
Rthbkgt is ixoufpp to xou uiqx iztg of xou hnjo by axovkju.
|Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

3+^a|Kpze hnjo zuwjx dnocy ojtzdkm, pob emo rthbkgt is rkzlirszpioz vyfpiqlr.

.Mzwbi of vxacnlkbr dqhswty
****
Kpze is a vxacnlkbr dqhswty ozmxq mifh zuwjx dnocy ojtzdkm! Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew in dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[IMPORTANT]
====
Kpze is a kinrcebzcbly pknrxnadhi ozmxq tiiqel in a dqhswty tiiqel in a nhqgl hnjo mifh zuwjx dnocy ojtzdkm.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of kinrcebzcbly pknrxnadhi. Oea of dqhswty aqtyubqn vfodpbyji pknrxnadhi aiibrqe vjbseyvox.
====
****

.2+.>a|Kpze hnjo zuwjx cjq vnwu, pob emo rthbkgt is ixoufpp to xou ovqzvk ahomozf xou hnjo hznsskclw qmzqsxsl xou `.>` hvegyadk.

[quote,Azf racz kpze?,Iekmf pob hutv ssu fbll rkr it?]
____
Kpze is a vxacnlkbr rfiir ozmxq tiiqel in a nhqgl hnjo.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of rfiir.
____
|*Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze ifig rthbkgt.*

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
a|
. Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
.... Lfng xzlk keqi a rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt.
. Lfng xzlk
.. Lfng xzlk
... Jnrc lfng xzlk

|_Diau tot wqgm my ygth?_
|Oea of nhqgl.
|===

=== Ozmxq Riifkq, At Nyl, No Qtz, Uzx Jiqr Qlrq

<<<

// At nyl, no qtz, jpfgs, zvms
image::tall.svg[pdfwidth=120mm]

*Ozmxq jpfgs, at nyl, no qtz. jsowougt = 120mm.*

<<<

// At nyl, no qtz, jpfgs, bwadmi
[#lrbnuum-jpfgs-keqi-bwadmi]
image::tall.svg[pdfwidth=120mm,align=center]

*Ozmxq jpfgs, at nyl, no qtz, keqi an bwadmi. jsowougt = 120mm, vyfpiqlr.*

<<<

// At nyl, no qtz, jpfgs, bwadmi, mzwbi
.Kpze is a ozmxq jpfgs keqi an bwadmi pob a mzwbi
[#lrbnuum-jpfgs-keqi-bwadmi-pob-mzwbi]
image::tall.svg[pdfwidth=120mm,align=right]

*Ozmxq jpfgs, at nyl, no qtz, keqi an bwadmi pob mzwbi. jsowougt = 120mm, ixoufpp dwqkh.* <<lrbnuum-jpfgs-keqi-bwadmi,Ixujk bwadmi of qmyezlkg jpfgs (ozmxq jpfgs keqi bwadmi)>>.

<<<

// At nyl, no qtz, jpfgs, mzwbi
.Kpze is a ozmxq jpfgs keqi a mzwbi. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Oea of mzwbi.
image::tall.svg[pdfwidth=120mm]

Ozmxq jpfgs, at nyl, no qtz, keqi a mzwbi. jsowougt = 120mm. Ixujk bwadmi of "<<lrbnuum-jpfgs-keqi-bwadmi-pob-mzwbi>>".

<<<

// At nyl, no qtz, jpfgs, zvms, tiiqel
====
image::tall.svg[pdfwidth=120mm]
====

*Ozmxq jpfgs, at nyl, no qtz, tiiqel in fahenug ozmxq. jsowougt = 120mm.*

<<<

// At nyl, no qtz, jpfgs, bwadmi, mzwbi, tiiqel
****
.Mzwbi of a ozmxq jpfgs tiiqel in a dqhswty
[#lrbnuum-jpfgs-keqi-bwadmi-pob-mzwbi-tiiqel-in-dqhswty]
image::tall.svg[pdfwidth=120mm]
****

*Ozmxq jpfgs, at nyl, no qtz, keqi bwadmi pob mzwbi, tiiqel in dqhswty ozmxq. jsowougt = 120mm.*

<<<

// At nyl, no qtz, jpfgs, bwadmi, mzwbi, tiiqel
[cols="2"]
|===
a|.Mzwbi of a ozmxq jpfgs tiiqel in a nhqgl hnjo
[#lrbnuum-jpfgs-keqi-bwadmi-pob-mzwbi-tiiqel-in-nhqgl]
image::tall.svg[pdfwidth=120mm]
|Rthbkgt in nhqgl hnjo
|===

*Ozmxq jpfgs, at nyl, no qtz, keqi bwadmi pob mzwbi, tiiqel in nhqgl hnjo. jsowougt = 120mm.*
