// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated from `man/asciidoctor.1` and
// `data/reference/syntax.adoc` (see `tool/embed_data.dart` for the
// escaping rules; concatenation reproduces each file exactly).
library;

/// Compile-time embedded copies of the `-h` topic files.
///
/// Used as a fallback when the checkout files cannot be found
/// (e.g. a standalone executable run outside the repository);
/// see `test/cli/help_topics_test.dart`.
abstract final class HelpTopics {
  /// The `man/asciidoctor.1` troff source, byte-identical.
  static const String manpage =
      '\'\\" t\n'
      '.\\"     Title: asciidoctor\n'
      '.\\"    Author: Dan Allen, Sarah White\n'
      '.\\" Generator: Asciidoctor 2.0.26\n'
      '.\\"      Date: 2026-10-04\n'
      '.\\"    Manual: Asciidoctor Manual\n'
      '.\\"    Source: Asciidoctor 2.0.26\n'
      '.\\"  Language: English\n'
      '.\\"\n'
      '.TH "ASCIIDOCTOR" "1" "2026-10-04" "Asciidoctor 2.0.26" "Asciidoctor Manual"\n'
      '.ie \\n(.g .ds Aq \\(aq\n'
      '.el       .ds Aq \'\n'
      '.ss \\n[.ss] 0\n'
      '.nh\n'
      '.ad l\n'
      '.de URL\n'
      '\\fI\\\\\$2\\fP <\\\\\$1>\\\\\$3\n'
      '..\n'
      '.als MTO URL\n'
      '.if \\n[.g] \\{\\\n'
      '.  mso www.tmac\n'
      '.  am URL\n'
      '.    ad l\n'
      '.  .\n'
      '.  am MTO\n'
      '.    ad l\n'
      '.  .\n'
      '.  LINKSTYLE blue R < >\n'
      '.\\}\n'
      '.SH "NAME"\n'
      'asciidoctor \\- converts AsciiDoc source files to HTML, DocBook, and other formats\n'
      '.SH "SYNOPSIS"\n'
      '.sp\n'
      '\\fBasciidoctor\\fP [\\fIOPTION\\fP].\\|.\\|. \\fIFILE\\fP.\\|.\\|.\n'
      '.SH "DESCRIPTION"\n'
      '.sp\n'
      'The asciidoctor(1) command converts the AsciiDoc source file(s) \\fIFILE\\fP to HTML5, DocBook 5, man(ual) page, and other custom output formats.\n'
      '.sp\n'
      'If \\fIFILE\\fP is \\fI\\-\\fP then the AsciiDoc source is read from standard input.\n'
      '.SH "OPTIONS"\n'
      '.SS "Security Settings"\n'
      '.sp\n'
      '\\fB\\-B, \\-\\-base\\-dir\\fP=\\fIDIR\\fP\n'
      '.RS 4\n'
      'Base directory containing the document and resources.\n'
      'Defaults to the directory containing the source file or, if the source is read from a stream, the working directory.\n'
      'When combined with the safe mode setting, can be used to chroot the execution of the program.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-S, \\-\\-safe\\-mode\\fP=\\fISAFE_MODE\\fP\n'
      '.RS 4\n'
      'Set safe mode level: \\fIunsafe\\fP, \\fIsafe\\fP, \\fIserver\\fP, or \\fIsecure\\fP.\n'
      'Disables potentially dangerous macros in source files, such as \\f(CRinclude::[]\\fP.\n'
      'If not set, the safe mode level defaults to \\fIunsafe\\fP when Asciidoctor is invoked using this script.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-\\-safe\\fP\n'
      '.RS 4\n'
      'Set safe mode level to \\fIsafe\\fP.\n'
      'Enables include directives, but prevents access to ancestor paths of source file.\n'
      'Provided for compatibility with the asciidoc command.\n'
      'If not set, the safe mode level defaults to \\fIunsafe\\fP when Asciidoctor is invoked using this script.\n'
      '.RE\n'
      '.SS "Document Settings"\n'
      '.sp\n'
      '\\fB\\-a, \\-\\-attribute\\fP=\\fIATTRIBUTE\\fP\n'
      '.RS 4\n'
      'Define, override, or unset a document attribute.\n'
      'Command\\-line attributes take precedence over attributes defined in the source file unless either the name or value ends in \\fI@\\fP.\n'
      'No substitutions are applied to the value.\n'
      '.sp\n'
      '\\fIATTRIBUTE\\fP is normally formatted as a key\\-value pair, in the form \\fINAME=VALUE\\fP.\n'
      'Alternate forms are \\fINAME\\fP (where the \\fIVALUE\\fP defaults to an empty string), \\fINAME!\\fP (unsets the \\fINAME\\fP attribute), and \\fINAME=VALUE@\\fP (or \\fINAME@=VALUE\\fP) (where \\fIVALUE\\fP does not override the \\fINAME\\fP attribute if it\\(cqs already defined in the source document).\n'
      'A value containing spaces must be enclosed in quotes, in the form \\fINAME="VALUE WITH SPACES"\\fP.\n'
      '.sp\n'
      'This option may be specified more than once.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-b, \\-\\-backend\\fP=\\fIBACKEND\\fP\n'
      '.RS 4\n'
      'Backend output file format: \\fIhtml5\\fP, \\fIdocbook5\\fP, and \\fImanpage\\fP are supported out of the box.\n'
      'You can also use the backend alias names \\fIhtml\\fP (aliased to \\fIhtml5\\fP) or \\fIdocbook\\fP (aliased to \\fIdocbook5\\fP).\n'
      'Other values can be passed, but if Asciidoctor cannot resolve the backend to a converter, it will fail.\n'
      'Defaults to \\fIhtml5\\fP.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-d, \\-\\-doctype\\fP=\\fIDOCTYPE\\fP\n'
      '.RS 4\n'
      'Document type: \\fIarticle\\fP, \\fIbook\\fP, \\fImanpage\\fP, or \\fIinline\\fP.\n'
      'Sets the root element when using the \\fIdocbook\\fP backend and the style class on the HTML body element when using the \\fIhtml\\fP backend.\n'
      'The \\fIbook\\fP document type allows multiple level\\-0 section titles in a single document.\n'
      'The \\fImanpage\\fP document type enables parsing of metadata necessary to produce a man page.\n'
      'The \\fIinline\\fP document type allows the content of a single paragraph to be formatted and returned without wrapping it in a containing element.\n'
      'Defaults to \\fIarticle\\fP.\n'
      '.RE\n'
      '.SS "Document Conversion"\n'
      '.sp\n'
      '\\fB\\-D, \\-\\-destination\\-dir\\fP=\\fIDIR\\fP\n'
      '.RS 4\n'
      'Destination output directory.\n'
      'Defaults to the directory containing the source file or, if the source is read from a stream, the working directory.\n'
      'If specified, the directory is resolved relative to the working directory.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-E, \\-\\-template\\-engine\\fP=\\fINAME\\fP\n'
      '.RS 4\n'
      'Template engine to use for the custom converter templates: \\fImustache\\fP (templates loaded from the template directory) or \\fIdart\\fP (transforms registered in code only).\n'
      'This name is also used to build the full path to the custom converter templates.\n'
      'If a template engine is not specified, it will be auto\\-detected based on the file extension of the custom converter templates found.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-e, \\-\\-embedded\\fP\n'
      '.RS 4\n'
      'Output an embeddable document, which excludes the header, the footer, and everything outside the body of the document.\n'
      'This option is useful for producing documents that can be inserted into an external template.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-I, \\-\\-load\\-path\\fP=\\fIDIRECTORY\\fP\n'
      '.RS 4\n'
      'Accepted for compatibility; has no effect, because this build cannot load libraries at runtime.\n'
      'This option may be specified more than once.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-n, \\-\\-section\\-numbers\\fP\n'
      '.RS 4\n'
      'Auto\\-number section titles.\n'
      'Synonym for \\fB\\-\\-attribute sectnums\\fP.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-o, \\-\\-out\\-file\\fP=\\fIOUT_FILE\\fP\n'
      '.RS 4\n'
      'Write output to file \\fIOUT_FILE\\fP.\n'
      'Defaults to the base name of the input file suffixed with \\fIbackend\\fP extension.\n'
      'The file is resolved relative to the working directory.\n'
      'If the input is read from standard input or a named pipe (fifo), then the output file defaults to stdout.\n'
      'If \\fIOUT_FILE\\fP is \\fI\\-\\fP, then the output file is written to standard output.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-R, \\-\\-source\\-dir\\fP=\\fIDIR\\fP\n'
      '.RS 4\n'
      'Source directory.\n'
      'Currently only used if the destination directory is also specified.\n'
      'Used to preserve the directory structure of files converted within this directory in the destination directory.\n'
      'If specified, the directory is resolved relative to the working directory.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-r, \\-\\-require\\fP=\\fILIBRARY\\fP\n'
      '.RS 4\n'
      'Accepted for compatibility; because this build cannot load libraries at runtime, any library fails to load and processing stops.\n'
      'Compile extensions into a custom binary instead (see \\fBasciidoctor init\\-config\\fP).\n'
      'This option may be specified more than once.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-s, \\-\\-no\\-header\\-footer\\fP\n'
      '.RS 4\n'
      'Output an embeddable document, which excludes the header, the footer, and everything outside the body of the document.\n'
      'This option is useful for producing documents that can be inserted into an external template.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-T, \\-\\-template\\-dir\\fP=\\fIDIR\\fP\n'
      '.RS 4\n'
      'A directory containing custom converter templates that override one or more templates from the built\\-in set.\n'
      'Templates are Mustache files named after the node, such as \\fIparagraph.mustache\\fP.\n'
      '.sp\n'
      'If there is a subfolder that matches the engine name (if specified), that folder is appended to the template directory path.\n'
      'Similarly, if there is a subfolder in the resulting template directory that matches the name of the backend, that folder is appended to the template directory path.\n'
      '.sp\n'
      'This option may be specified more than once.\n'
      'Matching templates found in subsequent directories override ones previously discovered.\n'
      '.RE\n'
      '.SS "Processing Information"\n'
      '.sp\n'
      '\\fB\\-\\-failure\\-level\\fP=\\fILEVEL\\fP\n'
      '.RS 4\n'
      'Set the minimum logging level (default: FATAL) that yields a non\\-zero exit code (i.e., failure).\n'
      'If this option is not set, the program exits with a zero exit code even if warnings or errors have been logged.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-q, \\-\\-quiet\\fP\n'
      '.RS 4\n'
      'Silence application log messages and script warnings.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-\\-trace\\fP\n'
      '.RS 4\n'
      'Include backtrace information when reporting errors.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-v, \\-\\-verbose\\fP\n'
      '.RS 4\n'
      'Sets log level to DEBUG so application messages logged at INFO or DEBUG level are printed to stderr.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-w, \\-\\-warnings\\fP\n'
      '.RS 4\n'
      'Turn on script warnings (applies to executed code).\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-t, \\-\\-timings\\fP\n'
      '.RS 4\n'
      'Print timings report to stderr (time to read, parse, and convert).\n'
      '.RE\n'
      '.SS "Program Information"\n'
      '.sp\n'
      '\\fB\\-h, \\-\\-help\\fP [\\fITOPIC\\fP]\n'
      '.RS 4\n'
      'Print a help message.\n'
      'Show the command usage if \\fITOPIC\\fP is not specified or recognized.\n'
      'Dump the Asciidoctor man page (in troff/groff format) if \\fITOPIC\\fP is \\fImanpage\\fP.\n'
      'Print an AsciiDoc syntax crib sheet (in AsciiDoc) if \\fITOPIC\\fP is \\fIsyntax\\fP.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-V, \\-\\-version\\fP\n'
      '.RS 4\n'
      'Print program version number.\n'
      '.sp\n'
      '\\fB\\-v\\fP can also be used if no source files are specified.\n'
      '.RE\n'
      '.SH "ENVIRONMENT"\n'
      '.sp\n'
      '\\fBAsciidoctor\\fP honors the \\fBSOURCE_DATE_EPOCH\\fP environment variable.\n'
      'If this variable is assigned an integer value, that value is used as the epoch of all input documents and as the local date and time.\n'
      'See \\c\n'
      '.URL "https://reproducible\\-builds.org/specs/source\\-date\\-epoch/" "" ""\n'
      'for more information about this environment variable.\n'
      '.SH "EXIT STATUS"\n'
      '.sp\n'
      '\\fB0\\fP\n'
      '.RS 4\n'
      'Success.\n'
      '.RE\n'
      '.sp\n'
      '\\fB1\\fP\n'
      '.RS 4\n'
      'Failure (syntax or usage error; configuration error; document processing failure; unexpected error).\n'
      '.RE\n'
      '.SH "BUGS"\n'
      '.sp\n'
      'Refer to the \\fBAsciidoctor\\fP issue tracker at \\c\n'
      '.URL "https://github.com/asciidoctor/asciidoctor/issues?q=is%3Aopen" "" "."\n'
      '.SH "AUTHORS"\n'
      '.sp\n'
      '\\fBAsciidoctor\\fP is led and maintained by Dan Allen and Sarah White and has received contributions from many individuals in the Asciidoctor community.\n'
      'The project was started in 2012 by Ryan Waldron based on a prototype written by Nick Hengeveld for the Git website.\n'
      'Jason Porter wrote the first implementation of the CLI interface provided by this command.\n'
      '.sp\n'
      '\\fBAsciiDoc.py\\fP was created by Stuart Rackham and has received contributions from many individuals in the AsciiDoc.py community.\n'
      '.SH "RESOURCES"\n'
      '.sp\n'
      '\\fBProject website:\\fP \\c\n'
      '.URL "https://asciidoctor.org" "" ""\n'
      '.sp\n'
      '\\fBProject documentation:\\fP \\c\n'
      '.URL "https://docs.asciidoctor.org" "" ""\n'
      '.sp\n'
      '\\fBCommunity chat:\\fP \\c\n'
      '.URL "https://chat.asciidoctor.org" "" ""\n'
      '.sp\n'
      '\\fBSource repository:\\fP \\c\n'
      '.URL "https://github.com/asciidoctor/asciidoctor" "" ""\n'
      '.sp\n'
      '\\fBMailing list archive:\\fP \\c\n'
      '.URL "https://discuss.asciidoctor.org" "" ""\n'
      '.SH "COPYING"\n'
      '.sp\n'
      'Copyright (C) 2012\\-present Dan Allen, Sarah White, Ryan Waldron, and the individual contributors to Asciidoctor.\n'
      'Use of this software is granted under the terms of the MIT License.';

  /// The `data/reference/syntax.adoc` source, byte-identical.
  static const String syntax =
      '= AsciiDoc Syntax\n'
      ':icons: font\n'
      ':stem:\n'
      ':toc: left\n'
      ':url-docs: https://asciidoctor.org/docs\n'
      ':url-gem: https://rubygems.org/gems/asciidoctor\n'
      '\n'
      'A brief reference of the most commonly used AsciiDoc syntax.\n'
      'You can find the full documentation for the AsciiDoc syntax at {url-docs}.\n'
      '\n'
      '== Paragraphs\n'
      '\n'
      'A normal paragraph.\n'
      'Line breaks are not preserved.\n'
      '// line comments, which are lines that start with //, are skipped\n'
      '\n'
      'A blank line separates paragraphs.\n'
      '\n'
      '[%hardbreaks]\n'
      'This paragraph is marked with the `hardbreaks` option.\n'
      'Notice how line breaks are now preserved.\n'
      '\n'
      ' An indented (literal) paragraph disables text formatting,\n'
      ' preserves spaces and line breaks, and is displayed in a\n'
      ' monospaced font.\n'
      '\n'
      '[sidebar#id.role]\n'
      'Adding a style, ID, and/or role gives a paragraph (or block) special meaning, like this sidebar.\n'
      '\n'
      'NOTE: An admonition paragraph, like this note, grabs the reader\'s attention.\n'
      '\n'
      'TIP: Convert this document using the `asciidoctor` command to see the output produced from it.\n'
      '\n'
      '== Text Formatting\n'
      ':hardbreaks-option:\n'
      '\n'
      '.Constrained (applied at word boundaries)\n'
      '*strong importance* (aka bold)\n'
      '_stress emphasis_ (aka italic)\n'
      '`monospaced` (aka typewriter text)\n'
      '"`double`" and \'`single`\' typographic quotes\n'
      '+passthrough text+ (substitutions disabled)\n'
      '`+literal text+` (monospaced with substitutions disabled)\n'
      'a #mark# to remember (highlighted for notation)\n'
      '\n'
      '.Unconstrained (applied anywhere)\n'
      '**C**reate, **R**ead, **U**pdate, and **D**elete (CRUD)\n'
      'fan__freakin__tastic\n'
      '``mono``culture\n'
      '##mark##up your text\n'
      '\n'
      '.Replacements\n'
      'A long time ago in a galaxy far, far away...\n'
      '(C) 1976 Arty Artisan\n'
      'I believe I shall--no, actually I won\'t.\n'
      '\n'
      '.ID and roles for phrases\n'
      '[.line-through]#delete me#\n'
      'the [.path]_images_ directory\n'
      'a [#wibble.term]*wibble* does wobble\n'
      '\n'
      '.Macros\n'
      '// where c=specialchars, q=quotes, a=attributes, r=replacements, m=macros, p=post_replacements, etc.\n'
      'The European icon:flag[role=blue] is blue & contains pass:[************] arranged in a icon:circle-o[role=yellow].\n'
      'The pass:c[->] operator is often referred to as the stabby lambda.\n'
      'Since `pass:[++]` has strong priority in AsciiDoc, you can rewrite pass:c,a,r[C++ => C{pp}].\n'
      '// activate stem support by adding `:stem:` to the document header\n'
      'stem:[sqrt(4) = 2]\n'
      '\n'
      ':!hardbreaks-option:\n'
      '== Attributes\n'
      '\n'
      ' // define attributes in the document header; must be flush with left margin\n'
      ' :name: value\n'
      '\n'
      'You can download and install Asciidoctor {asciidoctor-version} from {url-gem}.\n'
      'C{pp} is not required, only Ruby.\n'
      'Use a leading backslash to output a word enclosed in curly braces, like \\{name}.\n'
      '\n'
      '== Links\n'
      '\n'
      '[%hardbreaks]\n'
      'https://example.org/page[A webpage]\n'
      'link:../path/to/file.txt[A local file]\n'
      'xref:document.adoc[A sibling document]\n'
      'mailto:hello@example.org[Email to say hello!]\n'
      '\n'
      '== Anchors\n'
      '\n'
      '[[idname,reference text]]\n'
      '// or written using normal block attributes as `[#idname,reftext=reference text]`\n'
      'A paragraph (or any block) with an anchor (aka ID) and reftext.\n'
      '\n'
      'See <<idname>> or <<idname,optional text of internal link>>.\n'
      '\n'
      'xref:document.adoc#idname[Jumps to anchor in another document].\n'
      '\n'
      'This paragraph has a footnote.footnote:[This is the text of the footnote.]\n'
      '\n'
      '== Lists\n'
      '\n'
      '=== Unordered\n'
      '\n'
      '* level 1\n'
      '** level 2\n'
      '*** level 3\n'
      '**** level 4\n'
      '***** etc.\n'
      '* back at level 1\n'
      '+\n'
      'Attach a block or paragraph to a list item using a list continuation (which you can enclose in an open block).\n'
      '\n'
      '.Some Authors\n'
      '[circle]\n'
      '- Edgar Allan Poe\n'
      '- Sheri S. Tepper\n'
      '- Bill Bryson\n'
      '\n'
      '=== Ordered\n'
      '\n'
      '. Step 1\n'
      '. Step 2\n'
      '.. Step 2a\n'
      '.. Step 2b\n'
      '. Step 3\n'
      '\n'
      '.Remember your Roman numerals?\n'
      '[upperroman]\n'
      '. is one\n'
      '. is two\n'
      '. is three\n'
      '\n'
      '=== Checklist\n'
      '\n'
      '* [x] checked\n'
      '* [ ] not checked\n'
      '\n'
      '=== Callout\n'
      '\n'
      '// enable callout bubbles by adding `:icons: font` to the document header\n'
      '[,ruby]\n'
      '----\n'
      'puts \'Hello, World!\' # <1>\n'
      '----\n'
      '<1> Prints `Hello, World!` to the console.\n'
      '\n'
      '=== Description\n'
      '\n'
      'first term:: description of first term\n'
      'second term::\n'
      'description of second term\n'
      '\n'
      '== Document Structure\n'
      '\n'
      '=== Header\n'
      '\n'
      ' // header must be flush with left margin\n'
      ' = Document Title\n'
      ' Author Name <author@example.org>\n'
      ' v1.0, 2019-01-01\n'
      '\n'
      '=== Sections\n'
      '\n'
      ' // must be flush with left margin\n'
      ' = Document Title (Level 0)\n'
      ' == Level 1\n'
      ' === Level 2\n'
      ' ==== Level 3\n'
      ' ===== Level 4\n'
      ' ====== Level 5\n'
      ' == Back at Level 1\n'
      '\n'
      '=== Includes\n'
      '\n'
      ' // must be flush with left margin\n'
      ' include::basics.adoc[]\n'
      '\n'
      ' // define -a allow-uri-read to allow content to be read from URI\n'
      ' include::https://example.org/installation.adoc[]\n'
      '\n'
      '== Blocks\n'
      '\n'
      '--\n'
      'open - a general-purpose content wrapper; useful for enclosing content to attach to a list item\n'
      '--\n'
      '\n'
      '// recognized types include CAUTION, IMPORTANT, NOTE, TIP, and WARNING\n'
      '// enable admonition icons by setting `:icons: font` in the document header\n'
      '[NOTE]\n'
      '====\n'
      'admonition - a notice for the reader, ranging in severity from a tip to an alert\n'
      '====\n'
      '\n'
      '====\n'
      'example - a demonstration of the concept being documented\n'
      '====\n'
      '\n'
      '.Toggle Me\n'
      '[%collapsible]\n'
      '====\n'
      'collapsible - these details are revealed by clicking the title\n'
      '====\n'
      '\n'
      '****\n'
      'sidebar - auxiliary content that can be read independently of the main content\n'
      '****\n'
      '\n'
      '....\n'
      'literal - an exhibit that features program output\n'
      '....\n'
      '\n'
      '----\n'
      'listing - an exhibit that features program input, source code, or the contents of a file\n'
      '----\n'
      '\n'
      '[,language]\n'
      '----\n'
      'source - a listing that is embellished with (colorized) syntax highlighting\n'
      '----\n'
      '\n'
      '```language\n'
      'fenced code - a shorthand syntax for the source block\n'
      '```\n'
      '\n'
      '[,attribution,citetitle]\n'
      '____\n'
      'quote - a quotation or excerpt; attribution with title of source are optional\n'
      '____\n'
      '\n'
      '[verse,attribution,citetitle]\n'
      '____\n'
      'verse - a literary excerpt, often a poem; attribution with title of source are optional\n'
      '____\n'
      '\n'
      '++++\n'
      'pass - content passed directly to the output document; often raw HTML\n'
      '++++\n'
      '\n'
      '// activate stem support by adding `:stem:` to the document header\n'
      '[stem]\n'
      '++++\n'
      'x = y^2\n'
      '++++\n'
      '\n'
      '////\n'
      'comment - content which is not included in the output document\n'
      '////\n'
      '\n'
      '== Tables\n'
      '\n'
      '.Table Attributes\n'
      '[cols=>1h;2d,width=50%,frame=ends]\n'
      '|===\n'
      '| Attribute Name | Values\n'
      '\n'
      '| options\n'
      '| header,footer,autowidth\n'
      '\n'
      '| cols\n'
      '| colspec[;colspec;...]\n'
      '\n'
      '| grid\n'
      '| all \\| cols \\| rows \\| none\n'
      '\n'
      '| frame\n'
      '| all \\| sides \\| ends \\| none\n'
      '\n'
      '| stripes\n'
      '| all \\| even \\| odd \\| none\n'
      '\n'
      '| width\n'
      '| (0%..100%)\n'
      '\n'
      '| format\n'
      '| psv {vbar} csv {vbar} dsv\n'
      '|===\n'
      '\n'
      '== Multimedia\n'
      '\n'
      'image::screenshot.png[block image,800,450]\n'
      '\n'
      'Press image:reload.svg[reload,16,opts=interactive] to reload the page.\n'
      '\n'
      'video::movie.mp4[width=640,start=60,end=140,options=autoplay]\n'
      '\n'
      'video::aHjpOzsQ9YI[youtube]\n'
      '\n'
      'video::300817511[vimeo]\n'
      '\n'
      '== Breaks\n'
      '\n'
      '// thematic break (aka horizontal rule)\n'
      '---\n'
      '\n'
      '// page break\n'
      '<<<\n';
}
