// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated from `man/asciidart.1` and
// `vendor/asciidoctor/data/reference/syntax.adoc` (see
// `tool/embed_data.dart` for the
// escaping rules; concatenation reproduces each file exactly).
library;

/// Compile-time embedded copies of the `-h` topic files.
///
/// Used as a fallback when the checkout files cannot be found
/// (e.g. a standalone executable run outside the repository);
/// see `test/cli/help_topics_test.dart`.
abstract final class HelpTopics {
  /// The `man/asciidart.1` troff source, byte-identical.
  static const String manpage =
      '\'\\" t\n'
      '.\\"     Title: asciidart\n'
      '.\\"    Author: Noah Summers\n'
      '.\\" Generator: Asciidart 0.1.0\n'
      '.\\"      Date: 2026-10-06\n'
      '.\\"    Manual: asciidart Manual\n'
      '.\\"    Source: asciidart 0.1.0\n'
      '.\\"  Language: English\n'
      '.\\"\n'
      '.TH "ASCIIDART" "1" "2026-10-06" "asciidart 0.1.0" "asciidart Manual"\n'
      '.ie \\n(.g .ds Aq \\(aq\n'
      '.el       .ds Aq \'\n'
      '.ss \\n[.ss] 0\n'
      '.nh\n'
      '.ad l\n'
      '.de URL\n'
      '\\fI\\\\\$2\\fP <\\\\\$1>\\\\\$3\n'
      '..\n'
      '.als MTO URL\n'
      '.if \\n[.g] \\{\\\n'
      '.  mso www.tmac\n'
      '.  am URL\n'
      '.    ad l\n'
      '.  .\n'
      '.  am MTO\n'
      '.    ad l\n'
      '.  .\n'
      '.  LINKSTYLE blue R < >\n'
      '.\\}\n'
      '.SH "NAME"\n'
      'asciidart \\- convert AsciiDoc documents to HTML, DocBook and man pages\n'
      '.SH "SYNOPSIS"\n'
      '.sp\n'
      '\\fBasciidart\\fP [\\fIOPTION\\fP].\\|.\\|. \\fIFILE\\fP.\\|.\\|.\n'
      '.sp\n'
      '\\fBasciidart init\\-config\\fP [\\fIDIR\\fP] [\\fB\\-f\\fP]\n'
      '.SH "DESCRIPTION"\n'
      '.sp\n'
      '\\fBasciidart\\fP reads each AsciiDoc \\fIFILE\\fP and writes the converted document next to it, under the same name with the extension of the output format (for example, \\fIguide.adoc\\fP becomes \\fIguide.html\\fP).\n'
      'A \\fIFILE\\fP of \\fB\\-\\fP reads the document from standard input and writes the result to standard output.\n'
      'Arguments may be glob patterns (\\f(CR*\\fP, \\f(CR?\\fP, \\f(CR[...]\\fP and \\f(CR**\\fP), which \\fBasciidart\\fP expands itself.\n'
      '.sp\n'
      '\\fBasciidart\\fP is a re\\-implementation of Asciidoctor in Dart.\n'
      'It accepts the same documents, attributes and options as the \\fBasciidoctor\\fP command of Asciidoctor 2.0.26 and produces the same output, except for the deliberate differences listed in the project\\(cqs documentation.\n'
      '.sp\n'
      'Messages about the document (warnings, errors) go to standard error.\n'
      '.SH "OPTIONS"\n'
      '.SS "Output"\n'
      '.sp\n'
      '\\fB\\-b, \\-\\-backend\\fP=\\fIBACKEND\\fP\n'
      '.RS 4\n'
      'The output format: \\fBhtml5\\fP (the default), \\fBxhtml5\\fP, \\fBdocbook5\\fP, \\fBmanpage\\fP, \\fBepub3\\fP, \\fBpdf\\fP or \\fBmultipage_html5\\fP.\n'
      '\\fBepub3\\fP writes an EPUB 3 file (as asciidoctor\\-epub3 does), so it needs an output file rather than standard output; it is available in the native executable, not in the npm package.\n'
      '\\fBpdf\\fP writes a PDF file with asciidart\\(cqs own layout, reading asciidoctor\\-pdf\\(cqs YAML themes (\\fBpdf\\-theme\\fP, \\fBpdf\\-themesdir\\fP, \\fBpdf\\-fontsdir\\fP); justified text is hyphenated in the document\\(cqs language (\\fB\\-a hyphens!\\fP turns it off). Set the \\fBpdf\\-compat\\fP attribute (\\fB\\-a pdf\\-compat\\fP) to lay the document out as asciidoctor\\-pdf 2.3.27 does. Like \\fBepub3\\fP, it needs an output file and the native executable.\n'
      '\\fBmultipage_html5\\fP writes a website: the output file is the home page (the header, the preamble and a list of the pages), and each part and chapter (each section up to \\fBmultipage\\-level\\fP) is a page of its own beside it, named after its id, with links to the previous, enclosing and next pages; links reach across pages. Like \\fBepub3\\fP, it needs an output file and the native executable.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-d, \\-\\-doctype\\fP=\\fIDOCTYPE\\fP\n'
      '.RS 4\n'
      'How to interpret the document\\(cqs structure: \\fBarticle\\fP (the default), \\fBbook\\fP, \\fBmanpage\\fP or \\fBinline\\fP.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-e, \\-\\-embedded\\fP\n'
      '.RS 4\n'
      'Write only the converted body, without the surrounding page (for HTML: no \\fI<html>\\fP, \\fI<head>\\fP or footer).\n'
      'Useful for inserting the result into another page.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-s, \\-\\-no\\-header\\-footer\\fP\n'
      '.RS 4\n'
      'The same as \\fB\\-e\\fP.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-o, \\-\\-out\\-file\\fP=\\fIFILE\\fP\n'
      '.RS 4\n'
      'Write the output to \\fIFILE\\fP instead of the derived name.\n'
      'Use \\fB\\-\\fP to write to standard output.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-D, \\-\\-destination\\-dir\\fP=\\fIDIR\\fP\n'
      '.RS 4\n'
      'Write output files to \\fIDIR\\fP.\n'
      'Combined with \\fB\\-R\\fP, the input\\(cqs folder structure below the source directory is recreated below \\fIDIR\\fP.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-R, \\-\\-source\\-dir\\fP=\\fIDIR\\fP\n'
      '.RS 4\n'
      'The root of the input files, used with \\fB\\-D\\fP to compute where each output file goes.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-n, \\-\\-section\\-numbers\\fP\n'
      '.RS 4\n'
      'Number the section titles.\n'
      'The same as \\fB\\-a sectnums\\fP.\n'
      '.RE\n'
      '.SS "Document attributes"\n'
      '.sp\n'
      '\\fB\\-a, \\-\\-attribute\\fP=\\fINAME\\fP[=\\fIVALUE\\fP]\n'
      '.RS 4\n'
      'Set the document attribute \\fINAME\\fP, overriding any value the document assigns.\n'
      '\\fINAME\\fP alone sets it to an empty value; \\fINAME\\fP*!* unsets it.\n'
      'End the name or the value with \\fB@\\fP (\\fINAME\\fP@=\\fIVALUE\\fP or \\fINAME\\fP=\\fIVALUE\\fP@) to let the document override it instead.\n'
      'May be given more than once.\n'
      '.RE\n'
      '.SS "Safety"\n'
      '.sp\n'
      '\\fB\\-S, \\-\\-safe\\-mode\\fP=\\fIMODE\\fP\n'
      '.RS 4\n'
      'How much the document may reach outside itself: \\fBunsafe\\fP (the default for this command), \\fBsafe\\fP, \\fBserver\\fP or \\fBsecure\\fP.\n'
      'The stricter modes restrict include directives, file access outside the base directory and remote content.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-\\-safe\\fP\n'
      '.RS 4\n'
      'The same as \\fB\\-S safe\\fP.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-B, \\-\\-base\\-dir\\fP=\\fIDIR\\fP\n'
      '.RS 4\n'
      'The directory that relative paths in the document (includes, images) are resolved from.\n'
      'The default is the input file\\(cqs directory, or the working directory for standard input.\n'
      '.RE\n'
      '.SS "Custom converters"\n'
      '.sp\n'
      '\\fB\\-T, \\-\\-template\\-dir\\fP=\\fIDIR\\fP\n'
      '.RS 4\n'
      'Override how individual elements are converted with the Mustache templates in \\fIDIR\\fP.\n'
      'May be given more than once; later directories take precedence.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-E, \\-\\-template\\-engine\\fP=\\fINAME\\fP\n'
      '.RS 4\n'
      'The template engine for \\fB\\-T\\fP: \\fBmustache\\fP, or \\fBdart\\fP for converter functions compiled into a custom binary (see \\fBCustom binaries\\fP).\n'
      'Any other name fails once templates are in use.\n'
      '.RE\n'
      '.SS "Messages"\n'
      '.sp\n'
      '\\fB\\-\\-failure\\-level\\fP=\\fILEVEL\\fP\n'
      '.RS 4\n'
      'Exit with status 1 when a message of \\fILEVEL\\fP or higher is logged: \\fBINFO\\fP, \\fBWARN\\fP, \\fBERROR\\fP or \\fBFATAL\\fP (the default).\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-q, \\-\\-quiet\\fP\n'
      '.RS 4\n'
      'Print no messages about the document.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-v, \\-\\-verbose\\fP\n'
      '.RS 4\n'
      'Also print messages at the \\fBDEBUG\\fP and \\fBINFO\\fP levels.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-\\-trace\\fP\n'
      '.RS 4\n'
      'On an unexpected error, print the full stack trace.\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-t, \\-\\-timings\\fP\n'
      '.RS 4\n'
      'Print how long reading, parsing and converting each file took.\n'
      '.RE\n'
      '.SS "Information"\n'
      '.sp\n'
      '\\fB\\-h, \\-\\-help\\fP [\\fITOPIC\\fP]\n'
      '.RS 4\n'
      'Print the option summary.\n'
      'With \\fITOPIC\\fP \\fBsyntax\\fP, print an overview of the AsciiDoc syntax; with \\fBmanpage\\fP, print this manual page as troff source (view it with \\fBasciidart \\-h manpage | man \\-l \\-\\fP).\n'
      '.RE\n'
      '.sp\n'
      '\\fB\\-V, \\-\\-version\\fP\n'
      '.RS 4\n'
      'Print the version of \\fBasciidart\\fP, the Asciidoctor release it is compatible with, and the runtime.\n'
      '\\fB\\-v\\fP does the same when it is the only argument.\n'
      '.RE\n'
      '.SH "CUSTOM BINARIES"\n'
      '.sp\n'
      '\\fBasciidart init\\-config\\fP [\\fIDIR\\fP] creates a small Dart project in \\fIDIR\\fP (the working directory by default) whose program registers Dart functions as converters and then runs this command line.\n'
      'Compile it with \\fBdart compile exe\\fP to get a custom \\fBasciidart\\fP with those conversions built in.\n'
      '\\fB\\-f\\fP overwrites existing files.\n'
      '.SH "ENVIRONMENT"\n'
      '.sp\n'
      '\\fBSOURCE_DATE_EPOCH\\fP\n'
      '.RS 4\n'
      'When set to an integer number of seconds since the Unix epoch, it replaces the current time and the input files\\*(Aq modification times in the document\\(cqs date attributes, for reproducible output.\n'
      '.RE\n'
      '.sp\n'
      '\\fBASCIIDART_MANPAGE_PATH\\fP\n'
      '.RS 4\n'
      'The file \\fB\\-h manpage\\fP prints instead of the built\\-in manual page (plain or gzip\\-compressed).\n'
      '.RE\n'
      '.SH "EXIT STATUS"\n'
      '.sp\n'
      '\\fB0\\fP\n'
      '.RS 4\n'
      'The documents were converted (and no message reached the \\fB\\-\\-failure\\-level\\fP).\n'
      '.RE\n'
      '.sp\n'
      '\\fB1\\fP\n'
      '.RS 4\n'
      'Something failed: an invalid option, a missing or unreadable input file, a document that could not be converted, or a message at or above the \\fB\\-\\-failure\\-level\\fP.\n'
      '.RE\n'
      '.SH "BUGS"\n'
      '.sp\n'
      'Report problems at \\c\n'
      '.URL "https://github.com/nsmmrs/asciidart/issues" "" "."\n'
      '.SH "SEE ALSO"\n'
      '.sp\n'
      '\\fBasciidoctor\\fP(1), the Ruby implementation whose behavior \\fBasciidart\\fP follows: \\c\n'
      '.URL "https://asciidoctor.org" "" ""\n'
      '.SH "COPYING"\n'
      '.sp\n'
      'Copyright (C) 2026 Noah Summers.\n'
      '\\fBasciidart\\fP is free software under the MIT License; it includes data files from Asciidoctor, Copyright (C) 2012\\-present Dan Allen, Sarah White, Ryan Waldron, and the individual contributors to Asciidoctor, also under the MIT License.';

  /// The `vendor/asciidoctor/data/reference/syntax.adoc` source, byte-identical.
  static const String syntax =
      '= AsciiDoc Syntax\n'
      ':icons: font\n'
      ':stem:\n'
      ':toc: left\n'
      ':url-docs: https://asciidoctor.org/docs\n'
      ':url-gem: https://rubygems.org/gems/asciidoctor\n'
      '\n'
      'A brief reference of the most commonly used AsciiDoc syntax.\n'
      'You can find the full documentation for the AsciiDoc syntax at {url-docs}.\n'
      '\n'
      '== Paragraphs\n'
      '\n'
      'A normal paragraph.\n'
      'Line breaks are not preserved.\n'
      '// line comments, which are lines that start with //, are skipped\n'
      '\n'
      'A blank line separates paragraphs.\n'
      '\n'
      '[%hardbreaks]\n'
      'This paragraph is marked with the `hardbreaks` option.\n'
      'Notice how line breaks are now preserved.\n'
      '\n'
      ' An indented (literal) paragraph disables text formatting,\n'
      ' preserves spaces and line breaks, and is displayed in a\n'
      ' monospaced font.\n'
      '\n'
      '[sidebar#id.role]\n'
      'Adding a style, ID, and/or role gives a paragraph (or block) special meaning, like this sidebar.\n'
      '\n'
      'NOTE: An admonition paragraph, like this note, grabs the reader\'s attention.\n'
      '\n'
      'TIP: Convert this document using the `asciidoctor` command to see the output produced from it.\n'
      '\n'
      '== Text Formatting\n'
      ':hardbreaks-option:\n'
      '\n'
      '.Constrained (applied at word boundaries)\n'
      '*strong importance* (aka bold)\n'
      '_stress emphasis_ (aka italic)\n'
      '`monospaced` (aka typewriter text)\n'
      '"`double`" and \'`single`\' typographic quotes\n'
      '+passthrough text+ (substitutions disabled)\n'
      '`+literal text+` (monospaced with substitutions disabled)\n'
      'a #mark# to remember (highlighted for notation)\n'
      '\n'
      '.Unconstrained (applied anywhere)\n'
      '**C**reate, **R**ead, **U**pdate, and **D**elete (CRUD)\n'
      'fan__freakin__tastic\n'
      '``mono``culture\n'
      '##mark##up your text\n'
      '\n'
      '.Replacements\n'
      'A long time ago in a galaxy far, far away...\n'
      '(C) 1976 Arty Artisan\n'
      'I believe I shall--no, actually I won\'t.\n'
      '\n'
      '.ID and roles for phrases\n'
      '[.line-through]#delete me#\n'
      'the [.path]_images_ directory\n'
      'a [#wibble.term]*wibble* does wobble\n'
      '\n'
      '.Macros\n'
      '// where c=specialchars, q=quotes, a=attributes, r=replacements, m=macros, p=post_replacements, etc.\n'
      'The European icon:flag[role=blue] is blue & contains pass:[************] arranged in a icon:circle-o[role=yellow].\n'
      'The pass:c[->] operator is often referred to as the stabby lambda.\n'
      'Since `pass:[++]` has strong priority in AsciiDoc, you can rewrite pass:c,a,r[C++ => C{pp}].\n'
      '// activate stem support by adding `:stem:` to the document header\n'
      'stem:[sqrt(4) = 2]\n'
      '\n'
      ':!hardbreaks-option:\n'
      '== Attributes\n'
      '\n'
      ' // define attributes in the document header; must be flush with left margin\n'
      ' :name: value\n'
      '\n'
      'You can download and install Asciidoctor {asciidoctor-version} from {url-gem}.\n'
      'C{pp} is not required, only Ruby.\n'
      'Use a leading backslash to output a word enclosed in curly braces, like \\{name}.\n'
      '\n'
      '== Links\n'
      '\n'
      '[%hardbreaks]\n'
      'https://example.org/page[A webpage]\n'
      'link:../path/to/file.txt[A local file]\n'
      'xref:document.adoc[A sibling document]\n'
      'mailto:hello@example.org[Email to say hello!]\n'
      '\n'
      '== Anchors\n'
      '\n'
      '[[idname,reference text]]\n'
      '// or written using normal block attributes as `[#idname,reftext=reference text]`\n'
      'A paragraph (or any block) with an anchor (aka ID) and reftext.\n'
      '\n'
      'See <<idname>> or <<idname,optional text of internal link>>.\n'
      '\n'
      'xref:document.adoc#idname[Jumps to anchor in another document].\n'
      '\n'
      'This paragraph has a footnote.footnote:[This is the text of the footnote.]\n'
      '\n'
      '== Lists\n'
      '\n'
      '=== Unordered\n'
      '\n'
      '* level 1\n'
      '** level 2\n'
      '*** level 3\n'
      '**** level 4\n'
      '***** etc.\n'
      '* back at level 1\n'
      '+\n'
      'Attach a block or paragraph to a list item using a list continuation (which you can enclose in an open block).\n'
      '\n'
      '.Some Authors\n'
      '[circle]\n'
      '- Edgar Allan Poe\n'
      '- Sheri S. Tepper\n'
      '- Bill Bryson\n'
      '\n'
      '=== Ordered\n'
      '\n'
      '. Step 1\n'
      '. Step 2\n'
      '.. Step 2a\n'
      '.. Step 2b\n'
      '. Step 3\n'
      '\n'
      '.Remember your Roman numerals?\n'
      '[upperroman]\n'
      '. is one\n'
      '. is two\n'
      '. is three\n'
      '\n'
      '=== Checklist\n'
      '\n'
      '* [x] checked\n'
      '* [ ] not checked\n'
      '\n'
      '=== Callout\n'
      '\n'
      '// enable callout bubbles by adding `:icons: font` to the document header\n'
      '[,ruby]\n'
      '----\n'
      'puts \'Hello, World!\' # <1>\n'
      '----\n'
      '<1> Prints `Hello, World!` to the console.\n'
      '\n'
      '=== Description\n'
      '\n'
      'first term:: description of first term\n'
      'second term::\n'
      'description of second term\n'
      '\n'
      '== Document Structure\n'
      '\n'
      '=== Header\n'
      '\n'
      ' // header must be flush with left margin\n'
      ' = Document Title\n'
      ' Author Name <author@example.org>\n'
      ' v1.0, 2019-01-01\n'
      '\n'
      '=== Sections\n'
      '\n'
      ' // must be flush with left margin\n'
      ' = Document Title (Level 0)\n'
      ' == Level 1\n'
      ' === Level 2\n'
      ' ==== Level 3\n'
      ' ===== Level 4\n'
      ' ====== Level 5\n'
      ' == Back at Level 1\n'
      '\n'
      '=== Includes\n'
      '\n'
      ' // must be flush with left margin\n'
      ' include::basics.adoc[]\n'
      '\n'
      ' // define -a allow-uri-read to allow content to be read from URI\n'
      ' include::https://example.org/installation.adoc[]\n'
      '\n'
      '== Blocks\n'
      '\n'
      '--\n'
      'open - a general-purpose content wrapper; useful for enclosing content to attach to a list item\n'
      '--\n'
      '\n'
      '// recognized types include CAUTION, IMPORTANT, NOTE, TIP, and WARNING\n'
      '// enable admonition icons by setting `:icons: font` in the document header\n'
      '[NOTE]\n'
      '====\n'
      'admonition - a notice for the reader, ranging in severity from a tip to an alert\n'
      '====\n'
      '\n'
      '====\n'
      'example - a demonstration of the concept being documented\n'
      '====\n'
      '\n'
      '.Toggle Me\n'
      '[%collapsible]\n'
      '====\n'
      'collapsible - these details are revealed by clicking the title\n'
      '====\n'
      '\n'
      '****\n'
      'sidebar - auxiliary content that can be read independently of the main content\n'
      '****\n'
      '\n'
      '....\n'
      'literal - an exhibit that features program output\n'
      '....\n'
      '\n'
      '----\n'
      'listing - an exhibit that features program input, source code, or the contents of a file\n'
      '----\n'
      '\n'
      '[,language]\n'
      '----\n'
      'source - a listing that is embellished with (colorized) syntax highlighting\n'
      '----\n'
      '\n'
      '```language\n'
      'fenced code - a shorthand syntax for the source block\n'
      '```\n'
      '\n'
      '[,attribution,citetitle]\n'
      '____\n'
      'quote - a quotation or excerpt; attribution with title of source are optional\n'
      '____\n'
      '\n'
      '[verse,attribution,citetitle]\n'
      '____\n'
      'verse - a literary excerpt, often a poem; attribution with title of source are optional\n'
      '____\n'
      '\n'
      '++++\n'
      'pass - content passed directly to the output document; often raw HTML\n'
      '++++\n'
      '\n'
      '// activate stem support by adding `:stem:` to the document header\n'
      '[stem]\n'
      '++++\n'
      'x = y^2\n'
      '++++\n'
      '\n'
      '////\n'
      'comment - content which is not included in the output document\n'
      '////\n'
      '\n'
      '== Tables\n'
      '\n'
      '.Table Attributes\n'
      '[cols=>1h;2d,width=50%,frame=ends]\n'
      '|===\n'
      '| Attribute Name | Values\n'
      '\n'
      '| options\n'
      '| header,footer,autowidth\n'
      '\n'
      '| cols\n'
      '| colspec[;colspec;...]\n'
      '\n'
      '| grid\n'
      '| all \\| cols \\| rows \\| none\n'
      '\n'
      '| frame\n'
      '| all \\| sides \\| ends \\| none\n'
      '\n'
      '| stripes\n'
      '| all \\| even \\| odd \\| none\n'
      '\n'
      '| width\n'
      '| (0%..100%)\n'
      '\n'
      '| format\n'
      '| psv {vbar} csv {vbar} dsv\n'
      '|===\n'
      '\n'
      '== Multimedia\n'
      '\n'
      'image::screenshot.png[block image,800,450]\n'
      '\n'
      'Press image:reload.svg[reload,16,opts=interactive] to reload the page.\n'
      '\n'
      'video::movie.mp4[width=640,start=60,end=140,options=autoplay]\n'
      '\n'
      'video::aHjpOzsQ9YI[youtube]\n'
      '\n'
      'video::300817511[vimeo]\n'
      '\n'
      '== Breaks\n'
      '\n'
      '// thematic break (aka horizontal rule)\n'
      '---\n'
      '\n'
      '// page break\n'
      '<<<\n';
}
