/// `init-config` scaffold: generates an XMonad-style custom-binary project.
///
/// Dart-only tooling with no Ruby analog (ADR-0002 T6). Running
/// `asciidoctor init-config [DIR]` writes a user project (pubspec +
/// `lib/transforms.dart` stub + `bin/main.dart`) that registers Dart
/// functions and compiles with `dart compile exe`. The subcommand form
/// (rather than a flag) follows `git init` / `dart create` precedent; a
/// file literally named `init-config` can still be converted by spelling
/// it `./init-config`.
library;

import 'dart:io';

/// Usage text for `init-config` (printed by `--help` and on misuse).
const String initConfigUsage = '''
Usage: asciidoctor init-config [DIR] [options]

Generates a custom-binary project in DIR (default: the current directory).
The project registers its own Dart converter functions, then runs the
standard CLI, so logic-heavy overrides compile in (no -T directory needed):

  asciidoctor init-config my-config
  cd my-config
  dart pub get
  dart compile exe bin/main.dart -o asciidoctor-local

Options:
  -f, --force    overwrite existing scaffold files
  -h, --help     show this help
''';

/// Version constraint the scaffold puts on the `asciidoctor` dependency.
///
/// Bump with releases; `init_config_test.dart` asserts it matches this
/// package's own version.
const String scaffoldAsciidoctorConstraint = '^0.1.0';

/// SDK constraint the scaffold puts in the generated pubspec.
///
/// Mirrors this package's own constraint; asserted by
/// `init_config_test.dart`.
const String scaffoldSdkConstraint = '^3.13.0';

/// Generates a custom-binary project from the `init-config` arguments.
///
/// [args] are the arguments after `init-config` (an optional target
/// directory plus `-f/--force` / `-h/--help`); progress goes to [out]
/// (defaulting to stdout) and diagnostics to [err] (defaulting to
/// stderr). Returns the process exit code (0 on success).
int runInitConfig(List<String> args, {StringSink? out, StringSink? err}) {
  final stdoutSink = out ?? stdout;
  final stderrSink = err ?? stderr;
  var force = false;
  String? dir;
  for (final arg in args) {
    if (arg == '--help' || arg == '-h') {
      stdoutSink.write(initConfigUsage);
      return 0;
    } else if (arg == '--force' || arg == '-f') {
      force = true;
    } else if (arg.startsWith('-')) {
      stderrSink
        ..writeln('asciidoctor init-config: unknown option: $arg')
        ..write(initConfigUsage);
      return 1;
    } else if (dir == null) {
      dir = arg;
    } else {
      stderrSink.writeln(
        'asciidoctor init-config: expected at most one directory, '
        'got "$dir" and "$arg"',
      );
      stderrSink.write(initConfigUsage);
      return 1;
    }
  }
  final target = Directory(dir ?? '.');
  if (File(target.path).existsSync() && !Directory(target.path).existsSync()) {
    stderrSink.writeln(
      'asciidoctor init-config: ${target.path} exists and is not a directory',
    );
    return 1;
  }
  final name = _projectName(target);
  final files = <String, String>{
    'pubspec.yaml': _pubspec(name),
    'lib${Platform.pathSeparator}transforms.dart': _transforms(),
    'bin${Platform.pathSeparator}main.dart': _main(name),
    'README.md': _readme(name),
  };
  final existing = files.keys
      .where(
        (relative) =>
            File('${target.path}${Platform.pathSeparator}$relative')
                .existsSync(),
      )
      .toList();
  if (existing.isNotEmpty && !force) {
    stderrSink.writeln(
      'asciidoctor init-config: refusing to overwrite existing files in '
      '${target.path}: ${existing.join(', ')} (use --force to overwrite)',
    );
    return 1;
  }
  target.createSync(recursive: true);
  for (final entry in files.entries) {
    final file = File('${target.path}${Platform.pathSeparator}${entry.key}');
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(entry.value);
    stdoutSink.writeln('created ${file.path}');
  }
  stdoutSink.writeln('next: cd ${target.path} && dart pub get');
  return 0;
}

/// Derives a Dart package name from [target]'s basename.
String _projectName(Directory target) {
  final absolute = target.absolute.path;
  final segments = absolute
      .split(Platform.pathSeparator)
      .where((segment) => segment.isNotEmpty);
  final base = (segments.isEmpty ? '' : segments.last).toLowerCase();
  final sanitized = base.replaceAll(RegExp('[^a-z0-9_]'), '_');
  if (sanitized.isEmpty || RegExp('^[0-9]').hasMatch(sanitized)) {
    return 'asciidoctor_config';
  }
  return sanitized;
}

/// The scaffold `pubspec.yaml` for project [name].
String _pubspec(String name) =>
    '''
name: $name
description: Custom Asciidoctor CLI with compiled-in transforms (generated by `asciidoctor init-config`).

environment:
  sdk: $scaffoldSdkConstraint

dependencies:
  asciidoctor: $scaffoldAsciidoctorConstraint
''';

/// The scaffold `lib/transforms.dart` stub.
String _transforms() => r'''
/// Custom Asciidoctor transforms (path (a): code-first overrides).
///
/// Generated by `asciidoctor init-config`. Register one Dart function per
/// transform name (the node name, e.g. `paragraph`, `sidebar`, `outline`),
/// then compile a custom binary with `dart compile exe bin/main.dart`.
/// `bin/main.dart` calls [registerTransforms] before running the CLI, so
/// these overrides engage for every conversion without a -T directory.
library;

import 'package:asciidoctor/asciidoctor.dart';

/// Registers this project's custom transforms on [registry].
///
/// Defaults to [TemplateRegistry.global], which the converter factory
/// merges into every conversion. Pass an explicit registry to scope the
/// registrations to one [TemplateConverter] instead.
void registerTransforms([TemplateRegistry? registry]) {
  final target = registry ?? TemplateRegistry.global;
  // Example: render every paragraph with a custom wrapper. Delete or
  // adapt, then add one `registerFunction` per overridden transform.
  // (The handler accepts the optional per-call options map, like every
  // converter handler; it is unused here.)
  target.registerFunction('paragraph', (
    AbstractNode node, [
    Map<String, Object?>? opts,
  ]) {
    final content = (node as Block).content();
    return '<div class="paragraph custom">\n<p>$content</p>\n</div>';
  });
}
''';

/// The scaffold `bin/main.dart` for project [name].
String _main(String name) =>
    '''
/// Custom Asciidoctor CLI with compiled-in transforms (XMonad-style).
///
/// Generated by `asciidoctor init-config`. Registers this project's
/// transforms, then runs the standard CLI. Compile it with:
///
/// ```sh
/// dart compile exe bin/main.dart -o $name-local
/// ```
import 'package:asciidoctor/asciidoctor.dart';
import 'package:$name/transforms.dart';

Future<void> main(List<String> args) async {
  registerTransforms();
  await runCli(args);
}
''';

/// The scaffold `README.md` for project [name].
String _readme(String name) =>
    '''
# $name

Custom Asciidoctor CLI with compiled-in converter functions, generated by
`asciidoctor init-config`.

## Edit

`lib/transforms.dart` holds one `registerFunction` per overridden
transform (node name). The factory merges these over any `-T` Mustache
templates, and functions win per transform.

## Run (JIT)

```sh
dart pub get
dart run bin/main.dart --version
```

## Compile (AOT)

```sh
dart compile exe bin/main.dart -o $name-local
./$name-local --version
```

Note: `-j/--jobs` parallel conversion runs files on worker isolates,
which do not inherit these in-process registrations; use `-T` Mustache
templates (or a single job) when combining custom functions with `-j`.
''';
