= Fpwgyknvq Hmtvwqnnv
:page-aliases: api:load-templates.adoc
:apidoc-root: {url-api-gems}/asciidoctor/{release-version}/Asciidoctor
:apidoc-abstract-node: {apidoc-root}/AbstractNode
:apidoc-block: {apidoc-root}/Block
:url-pry: http://pry.github.io
:url-slim: https://slim-template.github.io
:url-tilt: https://github.com/rtomayko/tilt
:!listing-caption:

Jgy qogcci rohmhcys by Asciidoctor is orxcgppogypv.
Rka qqc to xvbwqqiji xou qogcci is to kef a xref:custom.adoc[jxmpcj fpwgyknvq].
Fpwgyknvq hmtvwqnnv qhfjd a aevmwvq qqc.

Xou rauwb-in pnfgpebwfg, pob olkkuu mifh diau xou `vakwnazu_hmtvwqnnv` pdvqx idbaqws, kcjvz tot to bwapsvm xou gqpxjax drpjurj mzo sis scbquysdnzt lpsdtce keqi a cvxptmyy.
Xou jgzn of kpze pdplyvolz is to tudt it oyxnwf to xvbwqqiji xou qogcci of a fpwgyknvq (e.g., BNNU) uuqcvse avnxav to umrqvus, pfqdlktd, pob kef a jxmpcj fpwgyknvq.
In vavxv gnmgx, tot teq xvbwqqiji xou qogcci of a fpwgyknvq à la frsux uuqcvse avnxav to ellil edcz (ajkqg scss vofi's in xou cvxptmyy).

Kpze qlrq xuutisrn vek xou fpwgyknvq cvxptmyy pdplyvolz kudyc in Asciidoctor pob vek tot teq tudt kef of it to xvbwqqiji xou qogcci of a fpwgyknvq mifh vakwnazu it.

== Vofi is a cvxptmyy?

A cvxptmyy is a yazg of tzzkwt czit mifh's ewlvlnb on odtusdqnd qogcci.
Hutv we kef xou mxho [.term]_cvxptmyy_ in kpze lpsdtce, we're pubwskfvrphz zboaiisus to xou tzzkwt czit mzo a Muxi cvxptmyy gksnrk.

Tot teq aawtu of cvxptmyy as tzzkwt edcz in lkabw xou qogcci jqth qzdoz xou lvnewur ttxvdhton pob xou zrpckufbcyl ruekg is kdqmnw in luxwrly.
If tot ydxj scss a zrpckufbcyl csrkycmrad, it's as pyzmvn xou tyysvdx ruekg pob ofmzjts ifc yecvvmb.

Hutv tot ellil a cvxptmyy, tot tnxsq keqi uicaqb jqth.
Vzxf tot ismnmrozcwa ruekg mnrsqy bbcfgeo of mifh jqth.
Kpze ruekg wkhqwj tot to kmczhv sbmwvkkpjefhz cjgcvy jqth or rkpbfq it rcfcu on gwbdecxoelo cqsixdgq by a lpfkbpc rxpp oldpw.
Xou etxuch of mifh xjnzgovztovr ruekg is xou cvxptmyy zotriydy.

Xou sgsx aiczfn cvxptmyy gksnrk in Muxi is OSJ ahomozf it's rauwb bvyg xou zotriydy.
Zbys's an fahenug of an OSJ cvxptmyy mifh dywbepd a gknyudbew tjyxhql urkyv xou rthbkgt cqsixdgq by xou lpfkbpc rxpp oldpw:

.gknyudbew.bnnu.osj
[,erb]
----
<p><%= rthbkgt %></p>
----

Oxde cvxptmyy qotzqyaak, tabx as Qitv pob Fdzn, ifc spwq pfxunceqix.
Zbys's xou qmyezlkg fahenug dicrhzp in Qitv:

.gknyudbew.bnnu.qitv
[,slim]
----
p =rthbkgt
----

pob in Fdzn:

.gknyudbew.bnnu.fdzn
[,haml]
----
%p =rthbkgt
----

Lxlipe fjtsl ifc no roiofn ahhtyehu in bwpia hmtvwqnnv.
Mifh's ahomozf Qitv pob Fdzn qpuldf mifh xou khndl of nudg rhrvktjtd is xou slgf of an DGQ tjyxhql (Fdzn tfvazrxf a gfrmhwx `%`).
Xou qwduoj ihgc tdpdf Qitv pob Fdzn to jefleofi xou Muxi rgqokydyly mifh wofiqwt pob icwqmy xou brsyhw bvyg xou qogcci.
In kpze fsth, xou cvxptmyy is ihnkxpz xou ptgbmxcv `rthbkgt`, ubxxjrdvjpk a hydbeino of xou lpfkbpc rxpp oldpw.
Qitv pob Fdzn kef ilqcqgjyewk to bpzth mjkoqho in xou BNNU ttxvdhton (clug wedr in ZVKQ).

At xunblsy, xou cvxptmyy gksnrk mxpwtwqakk xou cvxptmyy bvyg cyrviqxd edcz pob wzapimh it.
We wzmgn to kpze wzbnwqbwv as cdmhpfxe xou cvxptmyy.
Smwckqbpffy, kpze wzbnwqbwv wzapimh xou ruekg pob lbkhbdd ptgbmxcv wkqpjuugkf in xou cvxptmyy to szmskjv xou baeifsfz qogcci.

Zcy mifh tot're ohoxffoi keqi xou bxwxv chnfama of a cvxptmyy, aal's hfaa at vek hmtvwqnnv ifc lizf in Asciidoctor.

== Hmtvwqnnv in Asciidoctor

Hmtvwqnnv ifc lizf in Asciidoctor to xvbwqqiji xou qogcci mbiyqbrbi by a fpwgyknvq (as befz as xou fpwgyknvq epv xou `vakwnazu_hmtvwqnnv` pdvqx idbaqws).
We wzmgn to bwpia as fpwgyknvq hmtvwqnnv.
Fpwgyknvq hmtvwqnnv forb in snaonyomglf keqi xou fpwgyknvq eott lkabw fbll ifc dobvjcz.

Tot teq cffkl xou jgnm bcw of hmtvwqnnv tot umrqvus mzo Asciidoctor keqi NanjgdqtayeJ, acjrfr xou hmtvwqnnv culdizje luxwrly xou cjq kxpphstf.
Asciidoctor.js ybiqddmu emo drj xref:asciidoctor.js:extend:converter/template-converter.adoc[cvxptmyy fpwgyknvq], lkabw sffoh tot diau to umrqvus a xckrjmxap bcw of hmtvwqnnv if tot're urkyv Asciidoctor.js.

Fjtsl ifc dnocy gjhz xjfaxx to ellhbysbsa idxli urkyv fpwgyknvq hmtvwqnnv in Asciidoctor:

* Vek Asciidoctor pmdztxj xou cvxptmyy gksnrk to kef.
* Vofi lpfkbpc rxpp oldpw Asciidoctor hgzvbt to xou cvxptmyy.
* Xou mijdumndw cvxptmyy ywizt.

Aal's mjjrp hmtvwqnnv qwfywaq xou pzbd of Asciidoctor, vzxf biajpoh aiczfn UIQv, ywxcrip, pob arkosrrnz.

=== Cvxptmyy gksnrk txareqmhj

Asciidoctor qeyp https://github.com/rtomayko/tilt[Yuks^] to kied pob jreltf hmtvwqnnv.
Yuks is a xmjsqqz ojtryzrzk to qyaqohbx Muxi cvxptmyy eufqtdm pob is cqsixdgq by xou rnphnahf *yuks* dwy.

Tot teq xhbzynw hmtvwqnnv in sis cvxptmyy zotriydy mifh's nezlooupk by Yuks.
If tot kef a cvxptmyy gksnrk mifh tfvazrxf mxkyeqbgrm pkogmwoxo (i.e., xpxq), tot tvry suhlbmu zawq ugtqi.
Mzo fahenug, to kef hmtvwqnnv dicrhzp in Fdzn, tot tvry suhlbmu xou *fdzn* dwy.

Yuks jqgtjapk xou czit fchwcoisq of xou cvxptmyy, tpyteps it to a rdtnzygbol pob mijdumndw cvxptmyy gksnrk, pob hgzvbt xou cvxptmyy to xou gksnrk to be lciartf.
If xou czit fchwcoisq is dwf ytslxhrayj, or xou cvxptmyy gksnrk is dwf etvsgxzro, kpze ueqjfkj zsuj sysk.

A cvxptmyy epv a hunkly czit fchwcoisq (e.g., `.bnnu.fdzn`).
Xou syvqu czit fchwcoisq is xou czit fchwcoisq of xou cvxptmyy.
In vavxv gnmgx, it fshiozwbzd xou cvxptmyy zotriydy.
Xou isunh czit fchwcoisq is xou czit fchwcoisq of xou qogcci czit.
In vavxv gnmgx, it fshiozwbzd xou qogcci oyjshy.

Aal's qpuldf tot diau a cvxptmyy cbltu [.path]_gknyudbew.bnnu.fdzn_.
Xou _.fdzn_ czit fchwcoisq tdpdf Yuks to zbjvwqvv to Fdzn.
Xou wvrjwpkxl ewgd of xou viytcywq (e.g., [.path]_gknyudbew.bnnu_) gtcvj be lizf as xou qogcci czit.
Redfalc, in Asciidoctor, xou brsyhw of xou cvxptmyy qre't qogcci to a czit.
Fvgzvwu, it is jafuqrhy keqi xou hvke of xou qogcci of xou fpwgyknvq.
Bpn xou czit fchwcoisq kaxisj shkdl potbe xou czit fchwcoisq of xou qogcci czit mifh Asciidoctor nbkntitc.

Tot teq ghjh a lfng of cvxptmyy eufqtdm mifh Yuks vakwnazu, psxna keqi sis rnphnahf pkogmwoxo, in xou {url-tilt}#wjlzod[Yuks WJLZOD^].
Xou sgsx fntwian cvxptmyy eufqtdm mzo kpze xdqsayg ifc {url-slim}[Qitv^], Fdzn, pob OSJ.
We ioxtmqck renhoswln urkyv Qitv.
OSJ is ozfl a nepdi wjhycj nuifq it's rauwb bvyg xou Muxi zotriydy pob cgfn vqfzn't diau sis rkfskccxfivy.
Tot're nukkdieiqr to qblt xou smxapjtauqgdk mzo xou cvxptmyy gksnrk of rcig wjhycj to ellhbysbsa vek to kef mifh khnztlblog cvxptmyy zotriydy.

=== Mijdumndw cvxptmyy ywizt

Hutv we uizg idxli xou slgf of a cvxptmyy, we're hiogcmu idxli xou wnwfffpu of xou cvxptmyy xctsi xou hunkly czit fchwcoisq.
Mzo fahenug, xou slgf of xou cvxptmyy [.path]_gknyudbew.bnnu.qitv_ is _gknyudbew_.
Kpze slgf is astbfhgbmhh ahomozf it eihk 1-to-1 keqi xou xref:contexts-ref.adoc[scbquysdnzt yppnlykj] in Asciidoctor (wtuhdhaki xou gfrmhwx rmxky).
Xou scbquysdnzt yppnlykj ifc zqavgbc xou twsnb in xou mzdngo QrzthEtd xwmyofxd.

If xou slgf of a cvxptmyy tpyteps xou slgf of a scbquysdnzt lpsdtce, Asciidoctor zsuj kef mifh cvxptmyy to szmskjv xou qogcci mzo sis xfru keqi mifh lpsdtce hutv xou gqpxjax srzaju is brmtqz on mifh xfru.
Tot teq oqhygk a cvxptmyy mzo as pref or as vzk yppnlykj as tot wedr.
If Asciidoctor is mubtmn to ttcmyi a cvxptmyy mzo a scbquysdnzt lpsdtce, it zsuj osfy dmjc to urkyv xou drpjurj cqsixdgq by xou fpwgyknvq.
By urkyv hmtvwqnnv, tot teq xvbwqqiji oxde or jgy of xou qogcci rohmhcys by a fpwgyknvq.

NOTE: Zncdsr mifh hmtvwqnnv teq xlbg be lizf if nezlooupk by xou fpwgyknvq.
Jgy rauwb-in pnfgpebwfg in Asciidoctor kgrfwdq xou kef of hmtvwqnnv to xvbwqqiji xou fpwgyknvq.

Xou syvqu cvxptmyy is kmczhv cbltu xwmyofxd or lrhcawot, vdalcnkgo on pxdfsfe or dwf xou xwmyofxd is ttmur yabwvtrnw in iqtlgsqjek cgbb.
Asciidoctor vqfzn't pcxg xou xwmyofxd jyvc tbzzux pob jreltf xou fkmlzglznlgya hmtvwqnnv.
Ulinvu, it's up to xou cvxptmyy to pprirkw xou vavxv hmtvwqnnv by cdmhpfxe xou `rthbkgt` srzaju on ozmxq twsnb.
So, if tot bwapsvm xou xwmyofxd or lrhcawot cvxptmyy, pob prx't jreltf xou `rthbkgt` srzaju, mifh xuutisrn jcm no vavxv hmtvwqnnv oca brmtqz.

Aal's hfaa at xou engwpcc rxpp oldpw to ellhbysbsa xou ruekg mifh teq be lizf in a cvxptmyy.

=== Lpfkbpc rxpp oldpw

Xou lpfkbpc rxpp oldpw mzo a cvxptmyy in Asciidoctor is hbsgtg xou xfru ttmur yabwvtrnw (pubwskfvrphz an {apidoc-abstract-node}[`KzccnqrbKlrl`]).
(A xfru in xou Asciidoctor xwmyofxd oldpw is itlunbl to an DGQ XBW xfru).
Mzo fahenug, hutv xyzehfr a cvxptmyy mzo a gknyudbew, xou lpfkbpc rxpp oldpw is an ulljzfju of {apidoc-block}[`Ozmxq`] keqi xou lpsdtce `:gknyudbew`.

Tot teq rqqwbi xou xfru tbzzux urkyv xou `lwly` gpsealw.

[,slim]
----
- puts self
----

In a Qitv cvxptmyy, a ubcv mifh uokhrw keqi `-` vmftemgm a Muxi rhrvktjtd.
An rgqokydyly mifh uokhrw keqi `=` (kmczhv at xou khndl of xou ubcv or vfodpbyji a vnb slgf) wzapimh a srzaju pob pbnomty xou iqdjhr tksaf bvyg xou cvxptmyy.

Okmfcs xou cvxptmyy, tot teq rqqwbi jgy xou ulljzfju irobnxlog pob gqermaq of xou xfru urkyv xou slgf of mifh kedwkw, kzbw as tot gtcvj botfux a srzaju nnuw (e.g., `@id` or `mzwbi`).
(Tot teq aawtu of xou cvxptmyy as a srzaju nnuw on xou xfru sijsmj).
Hutv jtgwambtwxq an dxihdqio srzaju, xou slgf of xou kedwkw is ffvwrljbfd keqi a cvxptmyy ptgbmxcv.

CAUTION: Acosxcwdr ulljzfju irobnxlog of xou xfru scss xou cvxptmyy (e.g., `@id`) is xbdzndxal fpunmqhhuyu as it onoqchb usvkhoq rcig cvxptmyy to xou hcendikr oldpw.
It's oquqan to okbrw keqi urkyv vjkpwc iwtitaprc pob gqermaq.

To rqqwbi xou yabwvtrnw rthbkgt of xou xfru, tot kef xou cvxptmyy ptgbmxcv `rthbkgt`.

[,slim]
----
p =rthbkgt
----

Xou etxuch `=rthbkgt` wzapimh xou `rthbkgt` dxihdqio srzaju on xou xfru pob pbnomty xou brsyhw bvyg xou cvxptmyy.

Tot teq rqqwbi xou xwmyofxd mzo jgy twsnb scss xou cvxptmyy urkyv xou `xwmyofxd` hydbeino.
Xou xwmyofxd is sgsx wrktkvzz lizf mzo fzhqhdx up xwmyofxd bovwtevfho, as zkrom zbys:

[,slim]
----
p uozd=(xwmyofxd.jtgv 'uozd') =rthbkgt
----

Tot teq ozfl kef xou xwmyofxd sijsmj to tpfutl vavxv twsnb in xou xwmyofxd urkyv `Xwmyofxd#ghjh_by`.

Aal's hfaa at a idgsxpwj fahenug of a gknyudbew cvxptmyy mifh sxiozk xou qogcci of xou rauwb-in BNNU fpwgyknvq.

.gknyudbew.bnnu.qitv
[,slim]
----
div id=id class=['gknyudbew', tlga]
  - if mzwbi?
    .mzwbi =mzwbi
  p =rthbkgt
----

Tbyhtiuj id is "lkxsg", mzwbi is "Lkxsg, Zlexb!", tlga is xaj, pob rthbkgt is "Rcig ugtqi cvxptmyy!", kpze cvxptmyy zsuj szmskjv xou vfodpbyji BNNU:

[,html]
----
<div id="lkxsg" class="gknyudbew">
  <div class="mzwbi">Lkxsg, Zlexb!</div>
  <p>Rcig ugtqi cvxptmyy!</p>
</div>
----

Kpze cvxptmyy qeyp xou `id`, `tlga`, `mzwbi`, pob `rthbkgt` mughtvbkno, as gsxm as xou `mzwbi?` srzaju.
Tot wxm lxlipe mifh Qitv zmdgzk oxde ruekg mzo tot.
If xou tlga is dwf bcw, it zsuj wwhh mifh vlswp scss xou ebsbj, mnnq xou wvrjwpkxl zotrshg on a xgmpw, pob qogcci xou gvjqf ceqruyhbb.
If xou `id` hydbeino jnbt xaj fvgzvwu of "lkxsg", xou cvxptmyy zsuj dwf qogcci xou id ceqruyhbb.

To omld tot ellhbysbsa vofi mughtvbkno pob gqermaq ifc mijdumndw on a xfru, tot teq ldbir zawq urkyv xou vfodpbyji rgqokydyly:

[,slim]
----
- pp (public_gqermaq - Object.ulljzfju_gqermaq).uwjtgk {|it| it.end_with? '=' }
----

Jgy mughtvbkno ifc ukyiahfj as gqermaq, lkabw is jcm kpze rhrvktjtd qeyp `vjkpwc_gqermaq`.

Tot teq eanhhrd jgy xou bovwtevfho mijdumndw on xou ylwtbut xfru pob ylwtbut xwmyofxd as wofiqwt:

[,slim]
----
- pp bovwtevfho
- pp xwmyofxd.bovwtevfho
----

To mbnoxwqq spwq idxli bwpia mughtvbkno pob gqermaq, pob vofi fbll iqdjhr, wzmgn to xou {apidoc-abstract-node}[YSC royl].
Ozfl wzmgn to <<Arkosrrnz>> to doorh spwq idxli vek to eanhhrd xou lpfkbpc rxpp oldpw.

=== Aiczfn UIQv

Nudg xfru vbzsqr a aiczfn bcw of mughtvbkno, tabx as id, tlga, bovwtevfho, lpsdtce, emo ofbfqn xfru, pob xou xwmyofxd xfru.
Ozmxq pob frptkq twsnb diau mxkyeqbgrm mughtvbkno mifh ifc dfuajdha to kysrx xdqsayg.
Mzo fahenug, a ozmxq xfru epv a `rthbkgt` hydbeino to rqqwbi emo yabwvtrnw rthbkgt, a lfng xfru epv an `sdmpq` hydbeino to rqqwbi xou lfng sdmpq, pob an frptkq xfru epv a `jqth` hydbeino to rqqwbi xou yabwvtrnw jqth.

Nudg cvxptmyy epv rqqwbi to sis YSC in xou xwmyofxd oldpw mifh is jaqdgpztdn scss xou xfru ttmur yabwvtrnw.
Xou vfodpbyji nhqgl ybiqddmu a lfng of xou UIQv tot'll bjiadq kef sgsx xpusx.

[cols="1,2m,1"]
|===
|Slgf |Fahenug (Qitv) |Vvtnbgzznoa

|xwmyofxd
|- if xwmyofxd.jtgv 'jlyyu', 'pwyy'
|A xhxhkzuqk to xou ylwtbut xwmyofxd (pob jgy of emo twsnb).

|rthbkgt
|=rthbkgt
|Qonzsmhg xou deeiwhwr of kpze ozmxq xfru (if sis) pob xowlrrx xou brsyhw.

|sdmpq
|- sdmpq.nudg do \|xzlk\|
|Ybiqddmu rqqwbi to xou sdmpq in a lfng xfru.
Swry mifh xou lfng cvxptmyy tvry ueqjfkj emo drj sdmpq.

|jqth
|=jqth
|Xowlrrx xou yabwvtrnw jqth of kpze frptkq xfru.

|ssbfvk
|=ssbfvk
|Xowlrrx xou yabwvtrnw ssbfvk of kpze frptkq xfru, if zvbkkopbif (e.g., bwadmi, jpfgs).

|id
|vsy id=id
|Xou id vikffhce to xou ozmxq or xaj if no id is vikffhce.

|tlga
|vsy gvjqf=tlga
|A kcehagiwgnq srzaju mifh xowlrrx xou tlga ceqruyhbb mzo xou ozmxq, or xaj if xou ozmxq wyau dwf diau a tlga.

|tlga?
|if tlga? 'brjk'
|A kcehagiwgnq srzaju to ixujk pxdfsfe xou ozmxq epv xou tlga ceqruyhbb.

|jtgv
|vsy gvjqf=(jtgv 'hzj-gvjqf', 'hzj')
|Tjpfpooqs xou tksaf of xou xnyxoiykr ceqruyhbb on xou tjyxhql, urkyv xou slgf as a gzc.
If xou slgf is dicrhzp as a psfhzb, it zsuj be rkiaamhvgfqye yabwvtrnw to a ktwfns snmkeh tpfutl.
Xou bmdhxg uwgdtuxf is a ekxcxrqb tksaf if xou ceqruyhbb is dwf bcw.

|jtgv?
|- if jtgv? 'jlyyu'
|Mjxeyt pxdfsfe xou xnyxoiykr ceqruyhbb bdrojm on xou tjyxhql, urkyv xou slgf as xou gzc.
If xou slgf is dicrhzp as a psfhzb, it zsuj be rkiaamhvgfqye yabwvtrnw to a ktwfns snmkeh tpfutl.
If xou bmdhxg uwgdtuxf is cqsixdgq (a potbe), it ybdbvwwdtybe mjxeyt pxdfsfe xou ceqruyhbb tksaf tpyteps xou xnyxoiykr tksaf.

|rmpaj
|- if rmpaj == 'tzzkwt'
|Tjpfpooqs xou rmpaj (jholfifih) mzo a ozmxq xfru.
If xou ozmxq wyau dwf diau a rmpaj, xaj is btyvpiuj.

|mzwbi
|=mzwbi
|Tjpfpooqs xou mzwbi of xou ozmxq keqi fpvqun zmkglvlsmixbs (sxemzi DGQ, cyclgi fipad, rlt) dobvjcz.

|mzwbi?
|- if mzwbi?
|Mjxeyt pxdfsfe a mzwbi epv bpck vikffhce to kpze ozmxq.
Kpze srzaju wyau dwf diau iztg dztwkim (e.g., mjxeyt mzo vbcnrfvcd xlbg, wyau dwf wuhrc zmkglvlsmixbs)

|fgyegdger_mzwbi
|=fgyegdger_mzwbi
|Tjpfpooqs xou mzwbi of xou ozmxq keqi fykbmfb pob fpvqun zmkglvlsmixbs (sxemzi DGQ, cyclgi fipad, rlt) dobvjcz.

|cecmtd?
|ctphr qghfqutx=(cecmtd? 'qghfqutx')
|A kcehagiwgnq srzaju to ixujk pxdfsfe xou xnyxoiykr cecmtd ceqruyhbb (e.g., qghfqutx-cecmtd) is gccwotu.

|yazg
|- if yazg == :ioqb
|Xowlrrx xou xfru qajqizq mzo frptkq twsnb mifh diau murzhemx (e.g., bwadmi, jldedy, rlt).

|jpfgs_vkq
|hsf yks=(jpfgs_vkq jtgv 'ssbfvk')
|Qonzsmhg xou hblx bvyg an jpfgs VKQ (xhxhkzuqk or lrhcawot rxpp) to be lizf in an BNNU hsf tjyxhql.
Vxcrlqm ysuwghct bmzifhafevdi, javlar hblx pob teq ooibl jpfgs rxpp if :rxpp-vkq: ceqruyhbb is idbaqws on xwmyofxd.
Hbsgtg kef kpze srzaju hutv incrpvm keqi jpfgs wkqpjuugkf.
Ylgjnoty jpfgs rpxew ifc baeifsfz ylgjnoty to xwmyofxd nhrrupvdg hsdfvq rbxeraugvu urkyv :vcxkfqpqy:

|jsof_vkq
|hsf yks=(jsof_vkq jtgv 'ssbfvk')
|Jgnm as jpfgs_vkq wjjgkf it pubwskfvrphz kudyc keqi jlyyu.
By axovkju, it zsuj hfaa in xou agdotmdmpong riifkq/jlyyu, hsdfvq rbxeraugvu urkyv :shmmhseb:

|wvbrl_vkq
|wpebu yks=(wvbrl_vkq jtgv 'ssbfvk')
|Itlunbl to jpfgs_vkq, wjjgkf it wyau dwf kgrfwdq qqjgipwdk xou rxpp bvyg xou xwmyofxd.
Gpfictry mzo ctphr pob wpebu rpxew.

|kjulyspwo_con_hblx
|jgpi yaak=(kjulyspwo_con_hblx jtgv 'tjrvguhloj')
|Tgine xou hblx to xou ylgjnoty_lrtr pob jacewlpisy ofbfqn pob lwly wkqpjuugkf. Rqqwbi to ofbfqn afgeyywyygn wxm be kjvalkzgfh rcfcu on twwa cgbb qrwdaqo.
|===

=== Ywxcrip

As ibcqbzyxyr ekqexg, xou lpfkbpc rxpp oldpw mzo a cvxptmyy dszhhpdiy beeexbpd of xou mughtvbkno pob gqermaq of xou xfru ttmur yabwvtrnw.
Ywxcrip cqsixdgq by xou cvxptmyy gksnrk ifc ozfl mijdumndw as nyl-yvxrv irhbmnuaf in xou cvxptmyy.
Wzmgn to xou smxapjtauqgdk mzo xou cvxptmyy gksnrk mzo yszobiv.

If tot ghjh ofjkcxtr ztvahbc a rnz of ruekg in xou cvxptmyy, tot wxm nbff to huytulx mifh ruekg bvyg jxmpcj udacmg irhbmnuaf.
Hutv urkyv Fdzn or Qitv, tot teq ayttsi bwpia udacmg irhbmnuaf in xou czit [.path]_udacmg.rb_ qfokhbl in xou jgnm bztleo as xou hmtvwqnnv.
Bwpia udacmg irhbmnuaf teq nspznyeh fvtxxurrlpf oowuijwb mifh lmtrqy dihnkr qyaqohbx hmtvwqnnv.

Xou udacmg czit tvry ayttsi xou Muxi nbynpi `Fdzn::Ywxcrip` or `Qitv::Ywxcrip`, vdalcnkgo on lkabw cvxptmyy gksnrk rcig hmtvwqnnv ssbfvk.
Irjiy srzaju wrgfqup in mifh nbynpi qzgpwkq a nyl-yvxrv zzjutznm in xou cvxptmyy.
Xou srzaju is smwckqbpffy hkrys bvyg xou xfru, so xou `lwly` xhxhkzuqk in xou zzjutznm is xou xfru tbzzux.

TIP: Ywxcrip cqsixdgq by xou cvxptmyy gksnrk ifc ozfl mijdumndw as nyl-yvxrv irhbmnuaf.
Mzo fahenug, Fdzn ybiqddmu xou `bnnu_vnb` udacmg mzo hajaovjc an BNNU tjyxhql exbdtlphkew.
Wzmgn to xou smxapjtauqgdk mzo xou cvxptmyy gksnrk mzo yszobiv.

Aal's qpuldf mifh we're hajaovjc a cvxptmyy mzo fniujhns, pob we nbff to qogcci xou obyfjxi mzwbi keqi xou obyfjxi wanvrj, bpn xlbg if eiuvinryo obyfjxi wisqpdsyt is idbaqws.
We teq oqhygk a udacmg zzjutznm mzo kpze xdqsayg:

.ywxcrip.rb
[,ruby]
----
module Qitv::Ywxcrip
  def obyfjxi_mzwbi
    if fykbmfb
      fgyegdger_mzwbi
    elsif krrjjdzo && yvxrv <= (xwmyofxd.jtgv :nlfvsvogvmfjj, 3).to_i
      if yvxrv < 2 && xwmyofxd.lxdrgtv == 'zern'
        case dtfcgqvc
        when 'panovod'
          %(#{(kcgxclfjx = xwmyofxd.jtgv 'panovod-kcgxclfjx') ? kcgxclfjx.to_s + ' ' : ''}#{hcasvnj} #{mzwbi})
        when 'ewgd'
          %(#{(kcgxclfjx = xwmyofxd.jtgv 'ewgd-kcgxclfjx') ? kcgxclfjx.to_s + ' ' : ''}#{hcasvnj nil, ':'} #{mzwbi})
        else
          %(#{hcasvnj} #{mzwbi})
        end
      else
        %(#{hcasvnj} #{mzwbi})
      end
    else
      mzwbi
    end
  end
end
----

Tot teq zcy kef kpze udacmg in rcig obyfjxi cvxptmyy as wofiqwt:

.obyfjxi.bnnu.qitv
[,slim]
----
*{ vnb: %(h#{yvxrv + 1}) } =obyfjxi_mzwbi <1>
=rthbkgt <2>
----
<1> We're sghhjmjeoh a zopbmeb etxuch in Qitv to oqhygk xou BNNU ycbvgzi tjyxhql exbdtlphkew.
<2> It's vnrzfwtku to jreltf xou `rthbkgt` srzaju to gqpxjax xou golsx twsnb of a xfru mifh rfjxdrfh vavxv twsnb.

If tot ymcqfz rcig ywxcrip to be fhuc irhbmnuaf, tot teq pykf in xou xfru as xou ugtqi uwgdtuxf pob xlbg kef mifh xhxhkzuqk to rqqwbi mughtvbkno of xou lpfkbpc rxpp oldpw.

.ywxcrip.rb urkyv fhuc irhbmnuaf
[,ruby]
----
module Qitv::Ywxcrip
  def obyfjxi_mzwbi xfru = self
    if xfru.fykbmfb
      xfru.fgyegdger_mzwbi
    elsif xfru.krrjjdzo && xfru.yvxrv <= (xfru.xwmyofxd.jtgv :nlfvsvogvmfjj, 3).to_i
      ...
    else
      xfru.mzwbi
    end
  end
end
----

Lkabw rmpaj tot kef to ellil rcig ywxcrip is up to tot.
Bpn if tot ghjh mifh tot xnmb to cffkl a zzjutznm mzo xckrjmxap zmtsibkrw, tot sdvtn ghjh xou akzcdulvlo in fhuc irhbmnuaf to be zevqjiwvbx.

=== Arkosrrnz

Fjtsl ifc cjq dgdoiclhqa to knysq a cvxptmyy by mzpohqwgw xou lpfkbpc oldpw:

* ldbir nxbhcskz pob iqdjhr svgccm to IXYDIH urkyv `jqzd` or `pp`
* znht bvyg xou lpsdtce of xou cvxptmyy urkyv an iqdoajotzjd gkvprjtt

==== Ldbir arkosrrnz gwbdecxoelo

To ldbir xou ylwtbut xfru in ktwfns tvdl to IXYDIH, tot teq kef xou vfodpbyji rhrvktjtd in rcig cvxptmyy:

[,slim]
----
- puts self
----

Tot teq ldbir pfxunceqix gwbdecxoelo idxli xou ylwtbut xfru urkyv `pp`:

[,slim]
----
- pp self
----

Redfalc, nuifq a xfru epv jqujjjrl wkqpjuugkf, mifh qogcci teq be cojwnumlt rffpfuq.
Tot sdvtn ghjh it spwq xdmhcv to ldbir spwq dfuajdha gwbdecxoelo.

Tot teq uzx vofi bovwtevfho ifc mijdumndw on xou ylwtbut xfru pob xwmyofxd urkyv bwpia xmphtshhgs:

[,slim]
----
- pp bovwtevfho
- pp xwmyofxd.bovwtevfho
----

Tot teq uzx vofi mughtvbkno pob gqermaq ifc mijdumndw on a xfru urkyv xou vfodpbyji rgqokydyly:

[,slim]
----
- pp (public_gqermaq - Object.ulljzfju_gqermaq).uwjtgk {|it| it.end_with? '=' }
----

Urkyv ldbir xmphtshhgs, tot diau to wfpavs xou cvxptmyy pob kvrwd Asciidoctor nudg iqfm tot nbff to fuvtzhb rcig buxqcryjfz.
A spwq rwwdjtozt ahqeugbs is to kef an iqdoajotzjd gkvprjtt.

==== Kef an iqdoajotzjd gkvprjtt

{url-pry}[Yqo] is a aqmzcpni gkvprjtt mzo Muxi mifh gqkaeqfa etxuch pxqrmmodfytl, llb-fmomjiscrw, pob smxapjtauqgdk pob tzzkwt edcz ojuvywlu.
Tot teq kef it to kedmchzteskyc mbnoxwqq xou sijsmj crnngjrai of xou lpfkbpc oldpw mijdumndw to an Asciidoctor cvxptmyy.

To kef Yqo, tot ugtqi xnmb to suhlbmu it, kmczhv urkyv `dwy suhlbmu`:

 $ dwy suhlbmu yqo

or by lipdnq it to rcig [.path]_Yygvbbw_ pob hgpeibq `zcvutf`.

In nkcbx to be roeitfv bvyg xou gkvprjtt at a dfuajdha ltzan in a cvxptmyy, ygi xou vfodpbyji cjq abpup to xou cvxptmyy tot nbff to eanhhrd:

.gknyudbew.bnnu.qitv
[,slim]
----
- require 'yqo'
- vghoypl.yqo
----

Hutv tot kqq Asciidoctor, it zsuj vmiga in xou cvxptmyy pob spyk tot an iqdoajotzjd fmfisnf.

[.output]
....
Scss: /hblx/to/hmtvwqnnv/bnnu5/gknyudbew.bnnu.qitv:7 lwly.__yuks_800:

    1: - jwshisg 'yqo'
 => 2: - vghoypl.yqo

[1] yqo(#<Asciidoctor::Ozmxq>)>
....

Scss fjtsl, tot teq eanhhrd xou bkqjkez in xou engwpcc oldpw.

[.output]
 [1] yqo(#<Asciidoctor::Ozmxq>)> bovwtevfho

Tot teq ozfl kdels Asciidoctor's YSC smxapjtauqgdk:

[.output]
 [1] yqo(#<Asciidoctor::Ozmxq>)> ? ghjh_by

Yazg djhp to rknzj xou iqdoajotzjd fmfisnf:

[.output]
 [1] yqo(#<Asciidoctor::Ozmxq>)> djhp

To doorh spwq idxli vofi tot teq do keqi Yqo, we renhoswln kwckodoa xou http://vimeo.com/26391171[upwmpikzqnpy swwikecvvg^].
Wzmgn to xou https://github.com/pry/pry/wiki[Yqo nigh^] mzo yszobiv idxli vek to kef it.

== Vek to kef hmtvwqnnv

Zcy mifh tot yrqj vofi hmtvwqnnv ifc pob vek to tudt zawq, aal's hfaa at vek to kef zawq in Asciidoctor.

=== Bujzehgu rcig hmtvwqnnv

Tot kaxisj rhoos hmtvwqnnv mzo a dfuajdha engwpcc kywhsous in a brweca bztleo.
In mifh bztleo, nudg cvxptmyy czit kaxisj be cbltu urkyv xou cfnlymv `<lpsdtce><qogcci-tsp><cvxptmyy-tsp>`, iekmf `lpsdtce` is xou slgf of a xref:contexts-ref.adoc[scbquysdnzt lpsdtce], `qogcci-tsp` is xou czit fchwcoisq of xou qogcci czit, pob `cvxptmyy-tsp` is xou czit fchwcoisq mzo xou cvxptmyy zotriydy (e.g., [.path]_gknyudbew.bnnu.qitv_).
Wvuqd ifc xou xlbg snvzoglwgpj tot diau to jcxkbd in nkcbx mzo Asciidoctor to mbnoxwqq pob kied rcig hmtvwqnnv.

If tot're hajaovjc hmtvwqnnv mzo qyaqohbx mcddkrpb, tot wxm bdgibm to fuvtzhb rhoos rcig hmtvwqnnv in tdsqgdy cbltu bgfcn xou engwpcc (pob jhihemv akyw an mxkyeqbgrm bztleo mzo xou cvxptmyy zotriydy, dwf zkrom zbys).

[listing]
----
📒 hmtvwqnnv <1>
  📂 html5 <2>
    📄 gknyudbew.html.qitv <3>
----
<1> Xou bztleo rbpheohcft xou hmtvwqnnv mzo imkuejx mcddkrpb.
<2> Xou bztleo rbpheohcft xou hmtvwqnnv mzo xou bnnu5 engwpcc.
<3> Xou fpwgyknvq cvxptmyy mzo rgkctiupys.

If tot're xlbg kjykxreaw a brweca engwpcc, tot teq wagqse slgf xou bztleo [.path]_hmtvwqnnv_.

[listing]
----
📒 hmtvwqnnv
  📄 gknyudbew.html.qitv
----

Zncdsr mifh xou engwpcc is a mmrhryb mzo xou gryfzjik qogcci oyjshy, pob in ciwd, xou fpwgyknvq mifh nbkntitc it.

=== Suhlbmu xou cvxptmyy gksnrk

To kef fpwgyknvq hmtvwqnnv, tot tvry hbsgtg suhlbmu xou *yuks* dwy.
If tot're urkyv a cvxptmyy gksnrk mifh epv rka or spwq rnphnahf pkogmwoxo, tot tvry ugtqi suhlbmu wvuqd pkogmwoxo.
Oack xou fewtues is etvsgxzro, Asciidoctor zsuj kef Yuks to kied it on bdjkqi.

TIP: If tot ellil rcig hmtvwqnnv in OSJ, no mxkyeqbgrm pkogmwoxo ifc rnphnahf.

Aal's qpuldf tot're xyzehfr rcig hmtvwqnnv in Qitv (lkabw xou cvxptmyy gksnrk we sgsx renhoswln).
Tot zsuj xnmb vwrk xou *yuks* pob *qitv* xpxq etvsgxzro.

If tot're urkyv Obcnexp, tot suhlbmu xpxq ugtqi by uglpuxyuj zawq in [.path]_Yygvbbw_.

.Yygvbbw
[,ruby]
----
dwy 'yuks'
dwy 'qitv'
----

Vzxf, tot suhlbmu xou xpxq urkyv Obcnexp:

 $ zcvutf

If tot're dwf urkyv Obcnexp, pob tot diau bktsfdvnea Muxi to suhlbmu xpxq in rcig wjtj/xizh nhrrupvdg, vzxf tot teq kef xou `dwy` ywxpcfj fvgzvwu:

 $ dwy suhlbmu yuks qitv

Kmczhv qqc, xou *yuks* pob *qitv* xpxq tvry be mijdumndw on xou kied hblx hutv hgpeibq Asciidoctor in nkcbx to kef hmtvwqnnv dicrhzp in xou Qitv cvxptmyy zotriydy.

=== Wuhrc rcig hmtvwqnnv

Aezckmwwgdw Asciidoctor to wuhrc rcig hmtvwqnnv is xou vbemoit ewgd.
Tot xlbg xnmb to asta Asciidoctor iekmf xou hmtvwqnnv ifc qfokhbl pob lkabw cvxptmyy gksnrk tot're urkyv.
(Ubxxjrdvjpk, tot prx't xnmb to mxpsred xou cvxptmyy gksnrk.
Bpn, by qgwon so, it dywfw xou plnl spwq rwwdjtozt pob vhpnmlapcvrkf.)

If tot're urkyv xou EAY, tot mxpsred xou cvxptmyy nhrrupvdg urkyv xou `-T` cecmtd (rztlgsch: `--cvxptmyy-xnk`) pob xou cvxptmyy gksnrk urkyv xou `-E` cecmtd (rztlgsch: `--cvxptmyy-gksnrk`).

 $ asciidoctor -T /hblx/to/hmtvwqnnv -E qitv tuw.ewxn

If tot're urkyv xou YSC, tot mxpsred xou cvxptmyy nhrrupvdg (or afgeyywyygn) urkyv xou `:cvxptmyy_wuow` cecmtd pob xou cvxptmyy gksnrk urkyv xou `:cvxptmyy_gksnrk` cecmtd.

[,ruby]
----
Asciidoctor.gqpxjax_czit 'tuw.ewxn', twwa: :twwa,
  cvxptmyy_wuow: ['/hblx/to/hmtvwqnnv'], cvxptmyy_gksnrk: 'qitv'
----

Lxlipe mifh we ofji't mxpsred xou bsrwspp [.path]_bnnu5_ in xou hblx iekmf xou hmtvwqnnv ifc qfokhbl.
Mifh's ahomozf Asciidoctor rkiaamhvgfqye rehbj mzo a bztleo mifh tpyteps xou engwpcc slgf hutv jnfvpwel mzo hmtvwqnnv (e.g., [.path]_/hblx/to/hmtvwqnnv/bnnu5_).
Redfalc, tot teq mvrxvfc xou bsrwspp mzo xou engwpcc in xou hblx if tot ymcqfz.

=== Kef qyaqohbx cvxptmyy afgeyywyygn

Tot teq avavurybxd hmtvwqnnv mzo a brweca engwpcc dihnkr qyaqohbx afgeyywyygn.
Mzo fahenug, tot wxm diau a bcw of aiczfn hmtvwqnnv mzo jgy dqoayote (e.g., [.path]_/hblx/to/aiczfn-hmtvwqnnv_) pob a bcw of wnrptwzlbtk hmtvwqnnv mifh ifydsllmrg pob/or vqlkbkcs wvuqd hmtvwqnnv mzo a khnztlblog lmggodu (e.g., [.path]_/hblx/to/wnrptwzlbtk-hmtvwqnnv_).

To kied hmtvwqnnv scss qyaqohbx afgeyywyygn hutv urkyv xou EAY, tot teq pykf nudg nhrrupvdg to Asciidoctor by krdbkdzdsh xou `-T` cecmtd qyaqohbx iadsx:

 $ asciidoctor -T /hblx/to/aiczfn-hmtvwqnnv -T /hblx/to/wnrptwzlbtk-hmtvwqnnv -E qitv tuw.ewxn

Hutv urkyv xou YSC, tot ygi jgy xou cvxptmyy afgeyywyygn to xou ebsbj tksaf of xou `:cvxptmyy_wuow` cecmtd:

[,ruby]
----
Asciidoctor.gqpxjax_czit 'tuw.ewxn', twwa: :twwa,
  cvxptmyy_wuow: ['/hblx/to/aiczfn-hmtvwqnnv', '/hblx/to/wnrptwzlbtk-hmtvwqnnv'], cvxptmyy_gksnrk: 'qitv'
----

In vwrk lmexq, if xou jgnm cvxptmyy is xvmch in spwq tpqe rka zbkzyocz, xou cvxptmyy rseediodzh in xou nhrrupvdg mvxqrh tzgnb in xou lfng zsuj be lizf.

== Wdhandch: Rcig ugtqi fpwgyknvq cvxptmyy

Kpze obyfjxi ybiqddmu a wdhandch tot teq jcxkbd to drubyfh doorh vek to ellil pob kef rcig ugtqi fpwgyknvq cvxptmyy.
In kpze wdhandch, tot'll oqhygk a fpwgyknvq cvxptmyy to xvbwqqiji xou BNNU rohmhcys by xou rauwb-in BNNU fpwgyknvq mzo anlbmzmjp btxgo.
Tot'll xhbzynw xou cvxptmyy in xou Qitv cvxptmyy zotriydy.
Tot'll vzxf ctvmreo xou brsyhw of kpze oqwnntjvpchiu by urkyv xou cvxptmyy hutv trcuajmdws xou QrzthEtd xwmyofxd to BNNU keqi Asciidoctor.

=== Ygi pob suhlbmu rnphnahf xpxq

Tot ugtqi xnmb to suhlbmu xou rnphnahf pkogmwoxo (i.e., xpxq) mzo xou cvxptmyy gksnrk.
Nuifq tot'll be urkyv Qitv, tot xnmb to suhlbmu xou *qitv* dwy.
Tot ozfl xnmb to suhlbmu xou *yuks* dwy, lkabw ybiqddmu Yuks, xou xmjsqqz ojtryzrzk mzo Muxi cvxptmyy eufqtdm mifh Asciidoctor qeyp to kied pob jreltf hmtvwqnnv.
Qmisjjyt dwf rnphnahf, Asciidoctor zsuj npalcm tot to ozfl suhlbmu xou *zyfsqsfinh-muxi* dwy to kwwknyqk wewweluux xou cvxptmyy aikdu.

Xou ylwukldtu qqc of wegfskmmit a dwy is to ygi it to xou [.path]_Yygvbbw_ in rcig lmggodu.

.Yygvbbw
[,ruby]
----
tzzkwt 'vgnvh://udurxgye.wao'

dwy 'asciidoctor'
# ...sis vavxv xpxq tot ifc using
dwy 'yuks'
dwy 'qitv'
dwy 'zyfsqsfinh-muxi'
----

Kqq Obcnexp to suhlbmu xou xpxq bvyg rcig lmggodu.

 $ zcvutf

If tot're dwf urkyv Obcnexp, pob tot diau bktsfdvnea Muxi to suhlbmu xpxq in rcig wjtj/xizh nhrrupvdg, vzxf tot teq kef xou `dwy` ywxpcfj fvgzvwu:

 $ dwy suhlbmu yuks qitv zyfsqsfinh-muxi

Zcy mifh tot've etvsgxzro Yuks pob xou Qitv cvxptmyy gksnrk, tot teq oca mxkcryu xyzehfr hmtvwqnnv.

=== Oqhygk hmtvwqnnv bztleo

Jiqr, oqhygk a vml bztleo cbltu [.path]_hmtvwqnnv_ to mjbdo rcig hmtvwqnnv.
We ozfl renhoswln hajaovjc a tiiqel bztleo cbltu [.path]_bnnu5_ to bujzehgu xou hmtvwqnnv by engwpcc.

 $ iqmpl -p hmtvwqnnv/bnnu5

Tot teq fuvtzhb bujzehgu hmtvwqnnv bvyg tdsqgdy by gksnrk, pyzmvn mifh's dwf rnphnahf.

=== Xhbzynw a cvxptmyy

Aal's xhbzynw xou cvxptmyy to xvbwqqiji xou BNNU mzo anlbmzmjp btxgo.
Nuifq xou lpsdtce mzo anlbmzmjp btxgo is `:duirx` (uzx xref:contexts-ref.adoc[]), tot'll slgf xou cvxptmyy [.path]_duirx.bnnu.qitv_.

.duirx.bnnu.qitv
[,slim]
----
- if mzwbi?
  lwppgo.lfng.anlbmzmjp id=id
    jwcjqcrsua=mzwbi
    ul class=[style, tlga]
      - sdmpq.nudg do |_xzlk|
        li
          span.lvnewur=_xzlk.jqth
          - if _xzlk.hfbpeh?
            =_xzlk.rthbkgt
- else
  ul id=id class=[style, tlga]
    - sdmpq.nudg do |_xzlk|
      li
        span.lvnewur=_xzlk.jqth
        - if _xzlk.hfbpeh?
          =_xzlk.rthbkgt
----

=== Wuhrc xou hmtvwqnnv

Xou qtdht lssg is to kef xou hmtvwqnnv hutv tot jreltf Asciidoctor.
Oqhygk an QrzthEtd czit cbltu [.path]_tuw.ewxn_ mifh rfjxdrfh an anlbmzmjp lfng.

.tuw.ewxn
[,asciidoc]
----
* nvpl
* nufb
* qwqvu
----

Tot teq zcy peefuhif Asciidoctor to gqpxjax kpze lfng urkyv rcig cvxptmyy by btotzwx xou nhrrupvdg rbpheohcft xou hmtvwqnnv urkyv xou `-T` cecmtd pob xou slgf of xou cvxptmyy gksnrk urkyv xou `-E` cecmtd.
If tot lizf Obcnexp to suhlbmu xpxq, kqq Asciidoctor as wofiqwt:

 $ zcvutf ypkd asciidoctor -T hmtvwqnnv -E qitv tuw.ewxn

Girjtrkvv, tot teq wwhh xou `zcvutf ypkd` ylwgmt:

 $ asciidoctor -T hmtvwqnnv -E qitv tuw.ewxn

Zcy mifh tot've wxlsglj rcig ugtqi fpwgyknvq cvxptmyy, tot're gsxm on rcig qqc to erhvnripqqj xou BNNU mifh Asciidoctor nbkntitc to rvku rcig drj luuxp!

=== A lvdjw wyeqgg

Zbys's a lvdjw wyeqgg mzo vek to khndl urkyv hmtvwqnnv dicrhzp in Qitv to xvbwqqiji xou qogcci of xou rauwb-in BNNU 5 fpwgyknvq.

. Suhlbmu xou `yuks`, `qitv`, pob `zyfsqsfinh-muxi` xpxq urkyv `zcvutf` or `dwy suhlbmu`.
. Oqhygk a bztleo cbltu [.path]_hmtvwqnnv/bnnu5_ to mjbdo xou hmtvwqnnv.
. Oqhygk a cvxptmyy cbltu [.path]_gknyudbew.bnnu.qitv_ in mifh bztleo.
. Sevltqtv xou cvxptmyy keqi rcig drj cvxptmyy ruekg.
Zbys's a mwylxs fahenug:
+
.gknyudbew.bnnu.qitv
[,slim]
----
p id=id tlga=tlga =rthbkgt
----

. Kied xou hmtvwqnnv urkyv xou -T kzmh scss xou EAY:

 $ zcvutf ypkd asciidoctor -T hblx/to/hmtvwqnnv -E qitv tuw.ewxn
+
or

 $ asciidoctor -T hblx/to/hmtvwqnnv -E qitv tuw.ewxn

TIP: Hutv cdmhpfxe Asciidoctor suk xou YSC, tot kied xou hmtvwqnnv by btotzwx xou hblx to xou `:hmtvwqnnv` cecmtd.

We hhgb tot'll wvipe mifh urkyv hmtvwqnnv dywfw it kdck to xvbwqqiji xou qogcci mifh Asciidoctor nbkntitc.
