/// Generates `lib/src/patterns.g.dart` from `vendor/hyph-utf8`: the
/// languages' patterns, compiled to tries (`PatternTrie.encode`), and
/// their exceptions, compressed with Brotli (quality 11, by the `brotli`
/// tool) and base64-encoded, one stream per language
/// family (the German, Greek, English, Finnish, Latin, Norwegian and
/// Serbo-Croatian variants share theirs, which compresses them together
/// about as well as one stream for all), with each language's hyphenmins
/// and where its text is in the family's. The package decodes a family
/// when one of its languages is first used.
/// `tool/vendor_hyph_utf8.sh` runs it:
///
/// ```sh
/// dart run tool/generate_patterns.dart
/// ```
library;

import 'dart:convert';
import 'dart:io';

import 'package:plain_hyphenation/src/trie.dart';

Future<void> main() async {
  final root = File(Platform.script.toFilePath()).parent.parent;
  final vendor = Directory('${root.path}/vendor/hyph-utf8');
  final languages = jsonDecode(
    File('${vendor.path}/languages.json').readAsStringSync(),
  ) as Map<String, Object?>;
  Future<String> brotli(List<int> data) async {
    final brotli = await Process.start('brotli', ['-q', '11', '-c']);
    final out = brotli.stdout.fold(<int>[], (a, b) => a..addAll(b));
    brotli.stdin.add(data);
    await brotli.stdin.close();
    if (await brotli.exitCode != 0) throw StateError('brotli failed');
    return base64Encode(await out);
  }

  // A language's family: its primary subtag, Norwegian's for nb and nn.
  String family(String tag) => switch (tag.split('-').first) {
    'nb' || 'nn' => 'no',
    final primary => primary,
  };
  final families = <String, List<int>>{};
  final entries = <String>[];
  for (final MapEntry(key: tag, :value) in languages.entries) {
    final info = value! as Map<String, Object?>;
    final bytes = families.putIfAbsent(family(tag), () => <int>[]);
    (int, int) add(List<int> data) {
      final start = bytes.length;
      bytes.addAll(data);
      return (start, data.length);
    }

    final (trieAt, trieLength) = add(
      PatternTrie.parse(
        File('${vendor.path}/patterns/$tag.pat.txt').readAsStringSync(),
      ).encode(),
    );
    final exceptions = File('${vendor.path}/patterns/$tag.hyp.txt');
    final (exceptionsAt, exceptionsLength) = add(
      exceptions.existsSync() ? exceptions.readAsBytesSync() : const [],
    );
    entries.add(
      "  '$tag': (${info['left']}, ${info['right']}, '${family(tag)}', "
      '$trieAt, $trieLength, $exceptionsAt, $exceptionsLength),',
    );
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by `dart run tool/generate_patterns.dart` from')
    ..writeln(
      '// vendor/hyph-utf8 (${languages.length} languages; licences in '
      'vendor/hyph-utf8/NOTICES.md).',
    )
    ..writeln('// The patterns are long strings, one line each.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// The hyphenation patterns of hyph-utf8, by language tag.')
    ..writeln('library;')
    ..writeln()
    ..writeln(
      '/// Each language: its hyphenmins (left, right), its family, and',
    )
    ..writeln(
      '/// the byte offset and length of its trie (`PatternTrie.encode`)',
    )
    ..writeln("/// and of its exceptions (UTF-8) in the family's bytes.")
    ..writeln(
      'const Map<String, (int, int, String, int, int, int, int)> '
      'hyphenationPatterns = {',
    )
    ..writeAll(entries, '\n')
    ..writeln()
    ..writeln('};')
    ..writeln()
    ..writeln("/// Each family's bytes (the tries and exceptions of its")
    ..writeln('/// languages), Brotli-compressed, base64.')
    ..writeln('const Map<String, String> patternFamilies = {');
  var total = 0;
  for (final MapEntry(key: name, value: bytes) in families.entries) {
    final packed = await brotli(bytes);
    total += packed.length;
    out.writeln("  '$name': '$packed',");
  }
  out.writeln('};');
  final path = '${root.path}/lib/src/patterns.g.dart';
  File(path).writeAsStringSync('$out');
  await Process.run(Platform.resolvedExecutable, ['format', path]);
  stdout.writeln(
    'generate_patterns: ${languages.length} languages, '
    '${(total / 1024).round()} KiB of base64',
  );
}
