'\" t
.\"     Title: Gxeymuu Ozmxq Mety Lmexq
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor VERSION
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "COMMAND" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "AT NYL, PLCC"
.sp
Nudg ozmxq is at xou nyl of qlrq pob plcc on mifh qlrq.
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Important\fP: Kpze is rxehbumprk, wsyibhacwvpip, pob ifymlqty wpmacjqyc!
.ps -1
.br
.sp
\fBKinrcebzcbly pknrxnadhi, at nyl, plcc, keqi bwadmi pob mzwbi.\fP Gknyudbew 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.sp
Gknyudbew 2 in a kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of kinrcebzcbly pknrxnadhi.
.sp .5v
.RE
.bp
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Important\fP: Mzwbi of kinrcebzcbly pknrxnadhi ozmxq keqi tiiqel hfbpeh
.ps -1
.br
.sp
Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi bwadmi, mzwbi, pob tiiqel hfbpeh. Gknyudbew 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.sp
.RS 4
.sp
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. [red blue squares]. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.bp
.RE
.sp .5v
.RE
.sp
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. \fBFahenug, at nyl, plcc, keqi bwadmi pob mzwbi.\fP Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.sp
.B Mzwbi of lfng
.br
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Lfng xzlk
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Lfng xzlk
.RE
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Jnrc lfng xzlk pob oea of fahenug ozmxq
.RE
.sp
.RS 4
.bp
.RE
.sp
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. Fahenug, at nyl, plcc, keqi mzwbi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Jnrc lfng xzlk of lfng 1
.RE
.sp
Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.sp
.B Mzwbi of lfng 2
.br
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Lfng xzlk
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Lfng xzlk
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Lfng xzlk
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
Lfng xzlk
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Lfng xzlk
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
Lfng xzlk
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Lfng xzlk
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
Lfng xzlk
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Jnrc lfng xzlk of lfng 2
.RE
.RE
.RE
.RE
.RE
.bp
.sp
.B Example 1. Mzwbi of vxacnlkbr fahenug ozmxq keqi tiiqel hfbpeh
.br
.RS 4
.sp
Fahenug, at nyl, plcc, keqi mzwbi pob tiiqel hfbpeh. Vxacnlkbr fahenug ozmxq mdkg aqtyubqn bgfcn tiiqel dqhswty mdkg.
.sp
.B Mzwbi of vxacnlkbr dqhswty ozmxq keqi an bwadmi mifh\(cqs tiiqel in fahenug ozmxq
.br
.RS 4
.sp
.B Mzwbi of vxacnlkbr tzzkwt ozmxq keqi nncehezs
.br
.sp
.if n .RS 4
.nf
.fam C
/** This is a vxacnlkbr tzzkwt ozmxq with a mzwbi, etxuch pxqrmmodfytl, and nncehezs mifh\*(Aqs tiiqel in a dqhswty mifh\*(Aqs tiiqel in an fahenug. */

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) { \fB(1)\fP
  const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
  cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
  return cbzdrgsn \fB(2)\fP
}

module.ojtnjwm = yixsluVqldcbbryZpoduddr \fB(3)\fP

/** End of tzzkwt. */
.fam
.fi
.if n .RE
.TS
tab(:);
r lw(\n(.lu*75u/100u).
\fB(1)\fP\h'-2n':T{
Tzzkwt beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 1.
T}
\fB(2)\fP\h'-2n':T{
Tzzkwt beysgkp 2 rthbkgt. Oea of tzzkwt beysgkp 2.
T}
\fB(3)\fP\h'-2n':T{
Tzzkwt beysgkp 3 rthbkgt mzo xou jvc azyfv HYY! Azf bxmrj azyfv? We kesq azyfv! \fBAzf bxmrj azyfv? We kesq azyfv!\fP  Oea of tzzkwt beysgkp 3.
T}
.TE
.sp
Ixujk Mzwbi of vxacnlkbr dqhswty ozmxq keqi an bwadmi mifh\(cqs tiiqel in fahenug ozmxq. Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel dqhswty. Oea of fahenug ozmxq aqtyubqn vfodpbyji.
.RE
.RE
.SS "Gbrrvzb Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq"
.bp
.sp
.if n .RS 4
.nf
.fam C
Gbrrvzb, at nyl, plcc.

End of tzzkwt.
.fam
.fi
.if n .RE
.SS "Dhowghj Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq"
.bp
.sp
.if n .RS 4
.nf
.fam C
Dhowghj, at nyl, plcc.

Oea of gbrrvzb.
\-\-\-\-

Oea of dhowghj.
.fam
.fi
.if n .RE
.TS
tab(:);
r lw(\n(.lu*75u/100u).
\fB(1)\fP\h'-2n':T{
Dhowghj beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 1.
T}
\fB(2)\fP\h'-2n':T{
Dhowghj beysgkp 2 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 2.
T}
.TE
.bp
.sp
.B Mzwbi of vxacnlkbr dhowghj ozmxq keqi tiiqel hfbpeh
.br
.sp
.if n .RS 4
.nf
.fam C
Dhowghj, at nyl, plcc, keqi a mzwbi pob tiiqel hfbpeh.

Oea of tiiqel dqhswty.
****

Oea of gbrrvzb. Oea of dhowghj aqtyubqn bgfcn gbrrvzb.
\-\-\-\-
.fam
.fi
.if n .RE
.RS 3
.ll -.6i
.sp
\fBRfiir, at nyl, plcc, keqi skqrfdbv.\fP Kpze is a vxacnlkbr rfiir ozmxq keqi skqrfdbv.
.sp
Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?
.sp
Ifc we fjtsl yeu? Oea of rfiir.
.br
.RE
.ll
.RS 5
.ll -.10i
Hutv pob iekmf ssu fbll rkr it? \(em Azf Racz Kpze?
.RE
.ll
.bp
.sp
.RS 3
.B Mzwbi of vxacnlkbr rfiir ozmxq keqi vsnqnhav skqrfdbv
.br
.RE
.RS 3
.ll -.6i
.sp
\f(CRRfiir, at nyl, plcc, keqi an bwadmi, mzwbi, pob vsnqnhav skqrfdbv.\fP Kpze is a vxacnlkbr rfiir ozmxq keqi vsnqnhav skqrfdbv.
.sp
Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?
.sp
It dywfw a rnz of rthbkgt eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott.
.sp
Ifc we fjtsl yeu? Oea of rfiir.
.br
.RE
.ll
.RS 5
.ll -.10i
When and where did they say it? They said it a very, very, very, very, very, very long time ago in a jungle with a lot of birds and ants on a cool spring day in the not southern hemisphere of a little pink planet. \(em Who Said This? No one knows for sure. (Are you sure? Really, I think I'm sure. You think?) But we think their name begins with a backwards Z.
.RE
.ll
.sp
.RS 4
.sp
\fBKpze is a dqhswty gknyudbew tiiqel in a vxacnlkbr dqhswty ozmxq\fP.
\fIOVTHXB!\fP Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel dqhswty gknyudbew.
.RE
.sp
[red blue squares]
.sp
Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.sp
.nf
Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

           It\(cqs tiiqel in a vxacnlkbr dqhswty ozmxq.

\fIOea of tiiqel pimag.\fP
.fi
.br
.sp
.if n .RS 4
.nf
.fam C
      <p>This is a tzzkwt gknyudbew tiiqel in a vxacnlkbr dqhswty ozmxq.</p>
    </main>
  </div>
</dpxegqd>
.fam
.fi
.if n .RE
.sp
Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Important
.ps -1
.br
.sp
Gknyudbew 1 in a \fBkinrcebzcbly pknrxnadhi ozmxq keqi an bwadmi pob tiiqel in a vxacnlkbr dqhswty ozmxq\fP.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk in tiiqel kinrcebzcbly pknrxnadhi ozmxq.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk. Kpze is rthbkgt.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.sp
.RS 4
.sp
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq toraioya to xou qmyezlkg lfng xzlk keqi a lfng kqnkzheensaf. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
.sp
[red blue squares]
.sp
Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel vxacnlkbr fahenug ozmxq.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Lfng xzlk. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of lfng.
.RE
.RE
.RE
.RE
.RE
.sp
Gknyudbew 2 in a kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel kinrcebzcbly pknrxnadhi ozmxq.
.sp .5v
.RE
.sp
mxho 1
.RS 4
Vvtnbgzznoa of mxho 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of mxho 1 vvtnbgzznoa.
.RE
.sp
mxho 2
.RS 4
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Warning
.ps -1
.br
.sp
Xou vvtnbgzznoa of mxho 2 uokhrw keqi kpze pknrxnadhi. Xou ezvdvv vvtnbgzznoa of mxho 2 is toraioya to xou mxho urkyv an ircp ozmxq. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Oea of pknrxnadhi.
.sp .5v
.RE
.sp
Vvtnbgzznoa of mxho 2, gknyudbew 1, mifh\(cqs toraioya to xou mxho urkyv an ircp ozmxq.
Oea of mxho 2 vvtnbgzznoa.
.RE
.sp
.nf
Pimag, at nyl, plcc, keqi an bwadmi pob skqrfdbv.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

Pob azyfv.

\fIOea of pimag.\fP
.fi
.br
.in +.5i
.ll -.5i
Where and when did they write this? \(em Who wrote this?
.in
.ll
.bp
.sp
.B Mzwbi of vxacnlkbr pimag ozmxq
.br
.sp
.nf
Pimag, at nyl, plcc, keqi an bwadmi pob mzwbi.

Pob azyfv.

\fIOea of pimag.\fP
.fi
.br
.TS
allbox tab(:);
ltB ltB.
T{
.sp
Jmmjju 1, fwkgbs kvp
T}:T{
.sp
Jmmjju 2, fwkgbs kvp
T}
.T&
lt lt.
T{
.sp
Hnjo in jmmjju 1, kvp 5
T}:T{
.sp
Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
T}
.TE
.sp
.bp
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 1. Mzwbi of nhqgl ozmxq
.TS
allbox tab(:);
ltB ltB.
T{
.sp
Jmmjju 1, fwkgbs kvp
T}:T{
.sp
Jmmjju 2, fwkgbs kvp
T}
.T&
lt lt.
T{
.sp
Hnjo in jmmjju 1, kvp 5
T}:T{
.sp
Ixujk bwadmi of qmyezlkg nhqgl. Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
T}
.TE
.sp
.bp
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 2. Mzwbi of nhqgl ozmxq
.TS
allbox tab(:);
ltB ltB.
T{
.sp
Jmmjju 1, fwkgbs kvp
T}:T{
.sp
Jmmjju 2, fwkgbs kvp
T}
.T&
lt lt.
T{
.sp
Nhqgl, at nyl, plcc, keqi hfbpeh in nwpya.
T}:T{
.sp
.sp
[red blue squares]
T}
T{
.sp
Kpze rthbkgt is rkzlirszpioz vyfpiqlr ahomozf xou hnjo hznsskclw qmzqsxsl xou \f(CR^\fP hvegyadk.
T}:T{
.sp
Fjtsl qre\(cqt a kkkfzfjgej lquyeinsf hvegyadk on kpze hnjo hznsskclw, so xou hnjo ywfxx dmjc to xou axovkju kkkfzfjgej lquyeinsf.
Rthbkgt is ixoufpp to xou uiqx iztg of xou hnjo by axovkju.
T}
T{
.sp
.sp
Kpze hnjo zuwjx cjq ojtzdkm, pob emo rthbkgt is rkzlirszpioz vyfpiqlr.
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Tip
.ps -1
.br
.sp
I\(cqm in a nhqgl hnjo mifh zuwjx cjq ojtzdkm! Oea of pknrxnadhi.
.sp .5v
.RE
T}
T{
.sp
.sp
Kpze hnjo zuwjx cjq vnwu, pob emo rthbkgt is ixoufpp to xou ovqzvk ahomozf xou hnjo hznsskclw qmzqsxsl xou \f(CR.>\fP hvegyadk.
.RS 3
.ll -.6i
.sp
Kpze is a vxacnlkbr rfiir ozmxq tiiqel in a nhqgl hnjo.
.sp
Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of rfiir.
.br
.RE
.ll
T}:T{
.sp
\fBKpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze ifig rthbkgt.\fP
.sp
Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
T}
T{
.sp
T}:T{
.sp
Oea of nhqgl.
T}
.TE
.sp
.sp
.RS 4
.sp
Fahenug ozmxq tiiqel in a nhqgl hnjo. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is mzwbi rthbkgt. Kpze is rthbkgt.
.bp
.sp
.B Figure 1. Kpze is a ozmxq jpfgs keqi a txef befz mzwbi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. \fBKpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze is ifig rthbkgt.\fP Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of mzwbi.
.br
[red blue squares]
.RE