description = "Anchor: a pool document cut down and sanitized."
source = "pool:asciidoctor.js/packages/core/test/fixtures/semantic-html5-scenarios/icon-font-custom-prefix.adoc"
formats = ["epub3"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
