/// Generates `lib/src/case_data.g.dart` from the Unicode Character Database
/// files in `vendor/ucd/17.0.0`: each code point's full upper and lower
/// case mapping (UnicodeData.txt, overridden by the unconditional entries
/// of SpecialCasing.txt), and the Cased and Case_Ignorable properties
/// (DerivedCoreProperties.txt) that the Final_Sigma rule needs.
///
/// ```sh
/// dart run tool/generate_case_mapping.dart
/// ```
library;

import 'dart:io';

const String _version = '17.0.0';

Future<void> main() async {
  final root = File(Platform.script.toFilePath()).parent.parent.path;
  final ucd = '$root/vendor/ucd/$_version';
  final upper = <int, List<int>>{};
  final lower = <int, List<int>>{};
  for (final line in File('$ucd/UnicodeData.txt').readAsLinesSync()) {
    final f = line.split(';');
    final cp = int.parse(f[0], radix: 16);
    if (f[12].isNotEmpty) upper[cp] = [int.parse(f[12], radix: 16)];
    if (f[13].isNotEmpty) lower[cp] = [int.parse(f[13], radix: 16)];
  }
  for (final raw in File('$ucd/SpecialCasing.txt').readAsLinesSync()) {
    final line = raw.split('#').first.trim();
    if (line.isEmpty) continue;
    final f = [for (final field in line.split(';')) field.trim()];
    // Conditional entries (a fifth field: a language or a context such as
    // Final_Sigma) are left out: the rule applies them, or no one does.
    if (f.length > 4 && f[4].isNotEmpty) continue;
    final cp = int.parse(f[0], radix: 16);
    List<int> parse(String s) => [
      for (final h in s.split(' '))
        if (h.isNotEmpty) int.parse(h, radix: 16),
    ];
    lower[cp] = parse(f[1]);
    upper[cp] = parse(f[3]);
  }
  final cased = <(int, int)>[];
  final ignorable = <(int, int)>[];
  for (final raw in File('$ucd/DerivedCoreProperties.txt').readAsLinesSync()) {
    final line = raw.split('#').first.trim();
    if (line.isEmpty) continue;
    // (Some properties take a value: `range; InCB; Linker`.)
    final fields = [for (final f in line.split(';')) f.trim()];
    final range = fields[0];
    final property = fields[1];
    final ends = range.split('..');
    final start = int.parse(ends.first, radix: 16);
    final end = int.parse(ends.last, radix: 16);
    if (property == 'Cased') cased.add((start, end));
    if (property == 'Case_Ignorable') ignorable.add((start, end));
  }

  String table(Map<int, List<int>> map) => [
    for (final cp in map.keys.toList()..sort())
      // Only the mappings that change something.
      if (!(map[cp]!.length == 1 && map[cp]!.single == cp))
        '${cp.toRadixString(36)}:${_base36(map[cp]!)}',
  ].join(',');
  String ranges(List<(int, int)> list) {
    list.sort((a, b) => a.$1.compareTo(b.$1));
    final merged = <(int, int)>[];
    for (final r in list) {
      if (merged.isNotEmpty && r.$1 <= merged.last.$2 + 1) {
        final last = merged.removeLast();
        merged.add((last.$1, r.$2 > last.$2 ? r.$2 : last.$2));
      } else {
        merged.add(r);
      }
    }
    return [
      for (final (a, b) in merged)
        '${a.toRadixString(36)}-${b.toRadixString(36)}',
    ].join(',');
  }

  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/generate_case_mapping.dart from the Unicode',
    )
    ..writeln('// Character Database $_version (vendor/ucd/$_version). Do not')
    ..writeln('// edit.')
    ..writeln('// The tables are long strings: one line each.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// The Unicode version of the case mappings.')
    ..writeln("const String caseMappingUnicodeVersion = '$_version';")
    ..writeln()
    ..writeln('/// Full upper case mappings that change a code point, in base')
    ..writeln('/// 36: `cp:mapped mapped,...`.')
    ..writeln("const String upperTable = '${table(upper)}';")
    ..writeln()
    ..writeln('/// Full lower case mappings that change a code point (without')
    ..writeln('/// the Final_Sigma context).')
    ..writeln("const String lowerTable = '${table(lower)}';")
    ..writeln()
    ..writeln('/// Ranges of Cased code points: `start-end,...` in base 36.')
    ..writeln("const String casedRanges = '${ranges(cased)}';")
    ..writeln()
    ..writeln('/// Ranges of Case_Ignorable code points.')
    ..writeln("const String caseIgnorableRanges = '${ranges(ignorable)}';");
  const path = 'lib/src/case_data.g.dart';
  File('$root/$path').writeAsStringSync('$out');
  await Process.run(Platform.resolvedExecutable, ['format', '$root/$path']);
  stdout.writeln('generate_case_mapping: wrote $path');
}

String _base36(List<int> codePoints) =>
    codePoints.map((c) => c.toRadixString(36)).join(' ');
