/// Generates `lib/src/case_data.g.dart` from the Unicode Character Database
/// files in `vendor/ucd/17.0.0`: each code point's full upper and lower
/// case mapping (UnicodeData.txt, overridden by the unconditional entries
/// of SpecialCasing.txt), and the Cased and Case_Ignorable properties
/// (DerivedCoreProperties.txt) that the Final_Sigma rule needs.
///
/// ```sh
/// dart run tool/generate_case_mapping.dart
/// ```
library;

import 'dart:io';

const String _version = '17.0.0';

Future<void> main() async {
  final root = File(Platform.script.toFilePath()).parent.parent.path;
  final ucd = '$root/vendor/ucd/$_version';
  final upper = <int, List<int>>{};
  final lower = <int, List<int>>{};
  for (final line in File('$ucd/UnicodeData.txt').readAsLinesSync()) {
    final f = line.split(';');
    final cp = int.parse(f[0], radix: 16);
    if (f[12].isNotEmpty) upper[cp] = [int.parse(f[12], radix: 16)];
    if (f[13].isNotEmpty) lower[cp] = [int.parse(f[13], radix: 16)];
  }
  for (final raw in File('$ucd/SpecialCasing.txt').readAsLinesSync()) {
    final line = raw.split('#').first.trim();
    if (line.isEmpty) continue;
    final f = [for (final field in line.split(';')) field.trim()];
    // Conditional entries (a fifth field: a language or a context such as
    // Final_Sigma) are left out: the rule applies them, or no one does.
    if (f.length > 4 && f[4].isNotEmpty) continue;
    final cp = int.parse(f[0], radix: 16);
    List<int> parse(String s) => [
      for (final h in s.split(' '))
        if (h.isNotEmpty) int.parse(h, radix: 16),
    ];
    lower[cp] = parse(f[1]);
    upper[cp] = parse(f[3]);
  }
  final cased = <(int, int)>[];
  final ignorable = <(int, int)>[];
  for (final raw in File('$ucd/DerivedCoreProperties.txt').readAsLinesSync()) {
    final line = raw.split('#').first.trim();
    if (line.isEmpty) continue;
    // (Some properties take a value: `range; InCB; Linker`.)
    final fields = [for (final f in line.split(';')) f.trim()];
    final range = fields[0];
    final property = fields[1];
    final ends = range.split('..');
    final start = int.parse(ends.first, radix: 16);
    final end = int.parse(ends.last, radix: 16);
    if (property == 'Cased') cased.add((start, end));
    if (property == 'Case_Ignorable') ignorable.add((start, end));
  }

  // Single code point mappings come in runs: consecutive or alternating
  // code points with the same offset (`start:delta:count:stride`, base 36,
  // the delta signed). Mappings to several code points are listed
  // (`cp=mapped mapped`). ASCII is left out: the code maps it directly.
  String table(Map<int, List<int>> map) {
    final singles = <(int, int)>[];
    final entries = <String>[];
    for (final cp in map.keys.toList()..sort()) {
      final mapped = map[cp]!;
      if (cp < 0x80 || (mapped.length == 1 && mapped.single == cp)) continue;
      if (mapped.length == 1) {
        singles.add((cp, mapped.single - cp));
      } else {
        entries.add('${cp.toRadixString(36)}=${_base36(mapped)}');
      }
    }
    for (var i = 0; i < singles.length;) {
      final (start, delta) = singles[i];
      var count = 1;
      var stride = 1;
      if (i + 1 < singles.length &&
          singles[i + 1].$2 == delta &&
          singles[i + 1].$1 - start <= 2) {
        stride = singles[i + 1].$1 - start;
        while (i + count < singles.length &&
            singles[i + count].$2 == delta &&
            singles[i + count].$1 == start + count * stride) {
          count++;
        }
      }
      entries.add(
        '${start.toRadixString(36)}:${delta.toRadixString(36)}:'
        '${count.toRadixString(36)}:$stride',
      );
      i += count;
    }
    return entries.join(',');
  }

  String ranges(List<(int, int)> list) {
    list.sort((a, b) => a.$1.compareTo(b.$1));
    final merged = <(int, int)>[];
    for (final r in list) {
      if (merged.isNotEmpty && r.$1 <= merged.last.$2 + 1) {
        final last = merged.removeLast();
        merged.add((last.$1, r.$2 > last.$2 ? r.$2 : last.$2));
      } else {
        merged.add(r);
      }
    }
    return [
      for (final (a, b) in merged)
        '${a.toRadixString(36)}-${b.toRadixString(36)}',
    ].join(',');
  }

  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/generate_case_mapping.dart from the Unicode',
    )
    ..writeln('// Character Database $_version (vendor/ucd/$_version). Do not')
    ..writeln('// edit.')
    ..writeln('// The tables are long strings: one line each.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// The Unicode version of the case mappings.')
    ..writeln("const String caseMappingUnicodeVersion = '$_version';")
    ..writeln()
    ..writeln('/// Full upper case mappings of non-ASCII code points: runs')
    ..writeln('/// (`start:delta:count:stride`) and mappings to several code')
    ..writeln('/// points (`cp=mapped mapped`), in base 36.')
    ..writeln("const String upperTable = '${table(upper)}';")
    ..writeln()
    ..writeln('/// Full lower case mappings that change a code point (without')
    ..writeln('/// the Final_Sigma context).')
    ..writeln("const String lowerTable = '${table(lower)}';")
    ..writeln()
    ..writeln('/// Ranges of Cased code points: `start-end,...` in base 36.')
    ..writeln("const String casedRanges = '${ranges(cased)}';")
    ..writeln()
    ..writeln('/// Ranges of Case_Ignorable code points.')
    ..writeln("const String caseIgnorableRanges = '${ranges(ignorable)}';");
  const path = 'lib/src/case_data.g.dart';
  File('$root/$path').writeAsStringSync('$out');
  await Process.run(Platform.resolvedExecutable, ['format', '$root/$path']);
  stdout.writeln('generate_case_mapping: wrote $path');
}

String _base36(List<int> codePoints) =>
    codePoints.map((c) => c.toRadixString(36)).join(' ');
