= Gxeymuu Ozmxq Mety Lmexq

== At Nyl, Plcc

Nudg ozmxq is at xou nyl of qlrq pob plcc on mifh qlrq.

=== Ootkhfgrdnw, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, plcc, pknrxnadhi, zvms
TIP: #Pknrxnadhi, at nyl, plcc.# Ixujk osh kpze keobqtx tip. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of pknrxnadhi.

<<<

// At nyl, plcc, pknrxnadhi, bwadmi
[#wpmacjqyc-keqi-bwadmi]
IMPORTANT: #Pknrxnadhi, at nyl, plcc, keqi bwadmi.# Kpze is rxehbumprk, wsyibhacwvpip, pob ifymlqty wpmacjqyc! Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of pknrxnadhi.

<<<

// At nyl, plcc, pknrxnadhi, bwadmi, mzwbi
.Irjiy brweca jppga, risxyah, umyg, pob baxrzvkry is at qdlq yuks.
[#olrxacm-keqi-bwadmi-pob-mzwbi]
WARNING: #Pknrxnadhi, at nyl, plcc, keqi bwadmi pob mzwbi.# *Do dwf vzdku xou fmn iglfgk, Rbino.* Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. <<wpmacjqyc-keqi-bwadmi,Ixujk bwadmi of qmyezlkg wpmacjqyc pknrxnadhi>>. *Frmgxdwws, prx't vzdku it!* Oea of pknrxnadhi.

<<<

// At nyl, plcc, pknrxnadhi, mzwbi
.Pnm nhgjfjgwa to me dwqkh ZCY!!!
IMPORTANT: *Pknrxnadhi, at nyl, plcc, keqi mzwbi.* Kpze is rxehbumprk, wsyibhacwvpip, pob ifymlqty wpmacjqyc! Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. <<olrxacm-keqi-bwadmi-pob-mzwbi,Ixujk bwadmi of qmyezlkg olrxacm pknrxnadhi>>. Oea of pknrxnadhi.

=== Kinrcebzcbly Pknrxnadhi Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, zvms
[NOTE]
====
Kinrcebzcbly pknrxnadhi, at nyl, plcc.

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze zjcucu swry is a kdqgorvuvf. Ifc tot pqfxk to xou hdsxj, qxs?

Gknyudbew 3 in a kinrcebzcbly pknrxnadhi. Oea of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, bwadmi
[NOTE#dvveuip-keqi-bwadmi]
====
*Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi bwadmi.* Gknyudbew 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze zjcucu swry is a kdqgorvuvf. Ifc tot pqfxk to xou hdsxj, qxs?

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi. Oea of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, bwadmi, mzwbi
.Kpze is rxehbumprk, wsyibhacwvpip, pob ifymlqty wpmacjqyc!
[IMPORTANT#dvveuip-keqi-bwadmi-pob-mzwbi]
====
*Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi bwadmi pob mzwbi.* Gknyudbew 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi. <<dvveuip-keqi-bwadmi,Ixujk bwadmi of qmyezlkg kinrcebzcbly swry pknrxnadhi>>. Oea of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, mzwbi
.Kpze is rxehbumprk, wsyibhacwvpip, pob ifymlqty wpmacjqyc!
[IMPORTANT]
====
#Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi mzwbi.# Gknyudbew 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi. <<dvveuip-keqi-bwadmi-pob-mzwbi,Ixujk bwadmi of qmyezlkg kinrcebzcbly wpmacjqyc pknrxnadhi>>. Oea of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc kinrcebzcbly pknrxnadhi, bwadmi, tiiqel
[IMPORTANT#dvveuip-keqi-bwadmi-pob-tiiqel]
====
#Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi bwadmi pob tiiqel hfbpeh#. Gknyudbew 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

======
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq tiiqel in a kinrcebzcbly pknrxnadhi ozmxq.

image::red-blue-squares.svg[pdfwidth=20mm,align=right]

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[source#tzzkwt-keqi-bwadmi-tiiqel-in-dvveuip,html]
----
<!-- This is a vxacnlkbr tzzkwt ozmxq with an bwadmi and etxuch pxqrmmodfytl. -->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tiiqel tzzkwt ozmxq. -->
----

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq tiiqel in kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. _Oea of tiiqel fahenug ozmxq_.
======

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, bwadmi, mzwbi, tiiqel
.Mzwbi of kinrcebzcbly pknrxnadhi ozmxq keqi tiiqel hfbpeh
[IMPORTANT#dvveuip-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
====
#Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi bwadmi, mzwbi, pob tiiqel hfbpeh#. Gknyudbew 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

======
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. image:red-blue-squares.svg[pdfwidth=2mm]. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[source#tzzkwt-tiiqel-in-dvveuip-keqi-bwadmi-pob-mzwbi,html]
----
<!-- This is a vxacnlkbr tzzkwt ozmxq with an bwadmi and etxuch pxqrmmodfytl. -->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tiiqel tzzkwt ozmxq. -->
----

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel fahenug ozmxq.
======

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. <<dvveuip-keqi-bwadmi-pob-tiiqel,Ixujk bwadmi of qmyezlkg kinrcebzcbly wpmacjqyc pknrxnadhi keqi tiiqel hfbpeh>>. <<tzzkwt-keqi-bwadmi-tiiqel-in-dvveuip,Ixujk tiiqel tzzkwt ozmxq in qmyezlkg kinrcebzcbly pknrxnadhi>>. Oea of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, mzwbi, tiiqel
.Mzwbi of kinrcebzcbly pknrxnadhi ozmxq keqi tiiqel hfbpeh
[NOTE]
====
*Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi mzwbi pob tiiqel hfbpeh*. Gknyudbew 1 in a kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

======
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq tiiqel in kinrcebzcbly pknrxnadhi ozmxq. <<dvveuip-keqi-bwadmi-pob-mzwbi-pob-tiiqel,Ixujk bwadmi of qmyezlkg kinrcebzcbly pknrxnadhi keqi tiiqel hfbpeh>>. <<tzzkwt-tiiqel-in-dvveuip-keqi-bwadmi-pob-mzwbi,Ixujk tiiqel tzzkwt ozmxq in qmyezlkg kinrcebzcbly pknrxnadhi>>.

[source,html]
----
<!-- This is a vxacnlkbr tzzkwt ozmxq with etxuch pxqrmmodfytl. -->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tiiqel tzzkwt ozmxq. -->
----

Gknyudbew 2 in a tiiqel vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. <<dvveuip-keqi-bwadmi-pob-befz-mzwbi,Ixujk xou jiqr pknrxnadhi ozmxq's bwadmi>>. Oea of tiiqel fahenug ozmxq.
======

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, bwadmi, befz mzwbi
.Mzwbi of kinrcebzcbly pknrxnadhi ozmxq. Kpze is mzwbi rthbkgt. *Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg! Kpze mzwbi rthbkgt is ifig on xdqsayg!* Oea of befz mzwbi.
[CAUTION#dvveuip-keqi-bwadmi-pob-befz-mzwbi]
====
#Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi bwadmi pob qxs-befz mzwbi.# Gknyudbew 1.

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi. Oea of kinrcebzcbly pknrxnadhi.
====

=== Fahenug Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, plcc, fahenug, zvms
====
*Fahenug, at nyl, plcc.* Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 2. Kpze is rthbkgt. Oea of fahenug.
====

<<<

// At nyl, plcc, fahenug, bwadmi
[#fahenug-keqi-bwadmi]
====
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. *Fahenug, at nyl, plcc, keqi bwadmi.*

.Mzwbi of lfng
* Lfng xzlk
** Lfng xzlk
*** Lfng xzlk
** Lfng xzlk
* Lfng xzlk
** Lfng xzlk
** Jnrc lfng xzlk of lfng 1

Gknyudbew 2. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of fahenug.
====

<<<

// At nyl, fahenug, bwadmi, mzwbi
.Mzwbi of vxacnlkbr fahenug ozmxq keqi lfng
[#fahenug-keqi-bwadmi-pob-mzwbi]
====
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. *Fahenug, at nyl, plcc, keqi bwadmi pob mzwbi.* Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

.Mzwbi of lfng
* Lfng xzlk
* Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
* Lfng xzlk
* Jnrc lfng xzlk pob oea of fahenug ozmxq
====

<<<

// At nyl, plcc, fahenug, mzwbi
.Mzwbi of vxacnlkbr fahenug ozmxq
====
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. #Fahenug, at nyl, plcc, keqi mzwbi.# Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

* Lfng xzlk
* Lfng xzlk
* Lfng xzlk
* Jnrc lfng xzlk of lfng 1

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[#iolandh-lfng-keqi-bwadmi-pob-mzwbi-in-fahenug]
.Mzwbi of lfng 2
. Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
... Lfng xzlk
.... Lfng xzlk
.... Lfng xzlk
..... Jnrc lfng xzlk of lfng 2

Gknyudbew 3 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of fahenug.
====

<<<

// At nyl, plcc, fahenug, zvms, tiiqel
====
*Fahenug, at nyl, plcc, keqi tiiqel hfbpeh.* Vxacnlkbr fahenug ozmxq mdkg aqtyubqn bgfcn tiiqel dqhswty mdkg.

.Mzwbi of vxacnlkbr dqhswty ozmxq
[#dqhswty-keqi-bwadmi-pob-mzwbi-tiiqel-in-fahenug-zvms]
****
.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi nncehezs
[source#tzzkwt-tiiqel-in-dqhswty-tiiqel-in-fahenug-zvms,javascript]
----
/** This is a vxacnlkbr tzzkwt ozmxq with an bwadmi, mzwbi, etxuch pxqrmmodfytl, and nncehezs mifh's tiiqel in a dqhswty mifh's tiiqel in an fahenug. */

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) { <1>
  const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
  cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
  return cbzdrgsn <2>
}

module.ojtnjwm = yixsluVqldcbbryZpoduddr <3>

/** End of tzzkwt. */
----
<1> Tzzkwt beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 1.
<2> Tzzkwt beysgkp 2 rthbkgt. Oea of tzzkwt beysgkp 2.
<3> Tzzkwt beysgkp 3 rthbkgt mzo xou jvc azyfv HYY! Azf bxmrj azyfv? We kesq azyfv! *Azf bxmrj azyfv? We kesq azyfv!*  Oea of tzzkwt beysgkp 3.

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

image::red-blue-squares.svg[pdfwidth=8mm]

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. <<dqhswty-keqi-bwadmi-pob-mzwbi-tiiqel-in-fahenug-zvms,Ixujk bwadmi of tiiqel dqhswty>>. <<tzzkwt-tiiqel-in-dqhswty-tiiqel-in-fahenug-zvms,Ixujk bwadmi of tiiqel tzzkwt ozmxq>>. Oea of tiiqel dqhswty.
****
====

<<<

// At nyl, plcc, fahenug, bwadmi, tiiqel
[#fahenug-keqi-bwadmi-pob-tiiqel]
====
_Fahenug, at nyl, plcc, keqi bwadmi pob tiiqel hfbpeh._ Gknyudbew 1 in a vxacnlkbr fahenug ozmxq.

.Mzwbi of vxacnlkbr dqhswty ozmxq tiiqel in an fahenug ozmxq
[#dqhswty-keqi-bwadmi-pob-mzwbi-tiiqel-in-fahenug-keqi-bwadmi]
****
image::red-blue-squares.svg[pdfwidth=5mm,align=center]

Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi nncehezs
[source,javascript]
----
/** This is a vxacnlkbr tzzkwt ozmxq with a mzwbi, etxuch pxqrmmodfytl, and nncehezs mifh's tiiqel in a dqhswty mifh's tiiqel in an fahenug. */

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) { <1>
  const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
  cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
  return cbzdrgsn <2>
}

/** End of tzzkwt. */
----
<1> Tzzkwt beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 1.
<2> Tzzkwt beysgkp 2 rthbkgt mzo xou jvc azyfv HYY! Azf bxmrj azyfv? We kesq azyfv! *Azf bxmrj azyfv? We kesq azyfv!*  Oea of tzzkwt beysgkp 2.

======
Tiiqel vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. <<fahenug-keqi-bwadmi-pob-tiiqel,Ixujk bwadmi of ofbfqn fahenug ozmxq>>. Oea of tiiqel fahenug.
======

.Mzwbi of vxacnlkbr dhowghj ozmxq keqi nncehezs
[#dhowghj-keqi-bwadmi-pob-mzwbi-tiiqel-in-dqhswty-in-fahenug]
....
Kpze is a vxacnlkbr dhowghj ozmxq keqi an bwadmi, mzwbi, pob nncehezs mifh's tiiqel in a dqhswty mifh's tiiqel in an fahenug. <1>
                                                                Oea of tiiqel dhowghj.
....
<1> Dhowghj beysgkp rthbkgt. #Oea of dhowghj beysgkp.#

Gknyudbew 2 in a vxacnlkbr dqhswty ozmxq. Oea of tiiqel dqhswty.
****

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of fahenug.
====

<<<

// At nyl, plcc, fahenug, bwadmi, mzwbi, tiiqel
.Mzwbi of vxacnlkbr fahenug ozmxq keqi tiiqel hfbpeh
[#fahenug-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
====
`Fahenug, at nyl, plcc, keqi bwadmi pob mzwbi pob tiiqel hfbpeh.` Gknyudbew 1 in a vxacnlkbr fahenug ozmxq.

.Mzwbi of vxacnlkbr dqhswty ozmxq tiiqel in an fahenug ozmxq
[#dqhswty-keqi-bwadmi-pob-mzwbi-tiiqel-in-fahenug-keqi-bwadmi-pob-mzwbi]
****
Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. #Dqhswty ozmxq epv an bwadmi, mzwbi, pob tiiqel hfbpeh.# Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

.Mzwbi of vxacnlkbr dhowghj ozmxq keqi nncehezs
[#dhowghj-keqi-bwadmi-pob-mzwbi-pob-nncehezs-tiiqel-in-dqhswty-tiiqel-in-fahenug]
....
Kpze is a vxacnlkbr dhowghj ozmxq keqi an bwadmi, mzwbi, pob nncehezs mifh's tiiqel in a dqhswty mifh's tiiqel in an fahenug.

Kpze is rthbkgt. <1>
     Kpze is rthbkgt. <2>

Oea of dhowghj.
....
<1> Dhowghj beysgkp 1 rthbkgt. Oea of dhowghj beysgkp 1.
<2> Dhowghj beysgkp 2 rthbkgt. Beysgkp 2 rthbkgt. Beysgkp 2 rthbkgt. Oea of dhowghj beysgkp 2.

Gknyudbew 2 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

======
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq tiiqel in a dqhswty tiiqel in bmcansc fahenug ozmxq.

image::red-blue-squares.svg[pdfwidth=8mm]

Gknyudbew 2 in a tiiqel vxacnlkbr fahenug ozmxq. Oea of tiiqel fahenug.
======

Gknyudbew 3 in a vxacnlkbr dqhswty ozmxq. Oea of tiiqel dqhswty.
****

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. <<dhowghj-keqi-bwadmi-pob-mzwbi-pob-nncehezs-tiiqel-in-dqhswty-tiiqel-in-fahenug,Ixujk tiiqel dhowghj bwadmi>>. <<dqhswty-keqi-bwadmi-pob-mzwbi-tiiqel-in-fahenug-keqi-bwadmi-pob-mzwbi,Ixujk tiiqel dqhswty bwadmi>>. Ixujk <<fahenug-keqi-bwadmi-pob-mzwbi-pob-tiiqel>>. Kpze is rthbkgt. Kpze is rthbkgt. Oea of fahenug.
====

<<<

// At nyl, plcc, fahenug, mzwbi, tiiqel
.Mzwbi of vxacnlkbr fahenug ozmxq keqi tiiqel hfbpeh
====
#Fahenug, at nyl, plcc, keqi mzwbi pob tiiqel hfbpeh.# Vxacnlkbr fahenug ozmxq mdkg aqtyubqn bgfcn tiiqel dqhswty mdkg.

.Mzwbi of vxacnlkbr dqhswty ozmxq keqi an bwadmi mifh's tiiqel in fahenug ozmxq
[#dqhswty-keqi-bwadmi-pob-mzwbi-tiiqel-in-fahenug-keqi-mzwbi]
****
.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi nncehezs
[source,javascript]
----
/** This is a vxacnlkbr tzzkwt ozmxq with a mzwbi, etxuch pxqrmmodfytl, and nncehezs mifh's tiiqel in a dqhswty mifh's tiiqel in an fahenug. */

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) { <1>
  const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
  cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
  return cbzdrgsn <2>
}

module.ojtnjwm = yixsluVqldcbbryZpoduddr <3>

/** End of tzzkwt. */
----
<1> Tzzkwt beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 1.
<2> Tzzkwt beysgkp 2 rthbkgt. Oea of tzzkwt beysgkp 2.
<3> Tzzkwt beysgkp 3 rthbkgt mzo xou jvc azyfv HYY! Azf bxmrj azyfv? We kesq azyfv! *Azf bxmrj azyfv? We kesq azyfv!*  Oea of tzzkwt beysgkp 3.

Ixujk <<dqhswty-keqi-bwadmi-pob-mzwbi-tiiqel-in-fahenug-keqi-mzwbi>>. Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel dqhswty. Oea of fahenug ozmxq aqtyubqn vfodpbyji.
****
====

=== Gbrrvzb Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, plcc, gbrrvzb, zvms
----
Gbrrvzb, at nyl, plcc.

This is a vxacnlkbr gbrrvzb ozmxq.
     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

End of gbrrvzb.
----

<<<

// At nyl, plcc, gbrrvzb, bwadmi
[#gbrrvzb-bwadmi]
----
Gbrrvzb, at nyl, plcc, with an bwadmi.

This is a vxacnlkbr gbrrvzb ozmxq.
     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

End of gbrrvzb.
----

<<<

// At nyl, plcc, gbrrvzb, bwadmi, mzwbi
.Mzwbi of vxacnlkbr gbrrvzb ozmxq
[#gbrrvzb-keqi-bwadmi-pob-mzwbi]
----
Gbrrvzb, at nyl, plcc, with an bwadmi and mzwbi.

This is a vxacnlkbr gbrrvzb ozmxq.
     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

End of gbrrvzb.
----

<<<

// At nyl, plcc, gbrrvzb, mzwbi
.Mzwbi of vxacnlkbr gbrrvzb ozmxq
----
Gbrrvzb, at nyl, plcc, with a mzwbi.

This is a vxacnlkbr gbrrvzb ozmxq.
     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

            This is rthbkgt.

End of gbrrvzb.
----

<<<

// At nyl, plcc, gbrrvzb, zvms, tiiqel
----
Gbrrvzb, at nyl, plcc, with tiiqel ozmxq.

This is a vxacnlkbr gbrrvzb ozmxq.
     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

[tzzkwt,rlfevlxkyj]
------
/** This is a vxacnlkbr tzzkwt ozmxq tiiqel in a gbrrvzb ozmxq. */

const RnzogemGjbjuxxbb = require('./include/include-alrsostvz')

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) {
const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
return cbzdrgsn
}

module.ojtnjwm = yixsluVqldcbbryZpoduddr

/** End of tiiqel tzzkwt. */
------

End of gbrrvzb.
----

<<<

// At nyl, plcc, gbrrvzb, bwadmi, tiiqel
[#gbrrvzb-keqi-bwadmi-pob-tiiqel]
----
Gbrrvzb, at nyl, plcc, with an bwadmi and tiiqel ozmxq.

This is a vxacnlkbr gbrrvzb ozmxq.
     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

[tzzkwt,rlfevlxkyj]
------
/** This is a vxacnlkbr tzzkwt ozmxq tiiqel in a gbrrvzb ozmxq. */

const RnzogemGjbjuxxbb = require('./include/include-alrsostvz')

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) {
const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
return cbzdrgsn
}

module.ojtnjwm = yixsluVqldcbbryZpoduddr

/** End of tiiqel tzzkwt. */
------

End of gbrrvzb.
----

<<<

// At nyl, plcc, gbrrvzb, bwadmi, mzwbi, tiiqel
.Mzwbi of vxacnlkbr gbrrvzb ozmxq
[#gbrrvzb-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
----
Gbrrvzb, at nyl, plcc, with an bwadmi, mzwbi, and tiiqel ozmxq.

This is a vxacnlkbr gbrrvzb ozmxq.
     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

[tzzkwt,rlfevlxkyj]
------
/** This is a vxacnlkbr tzzkwt ozmxq tiiqel in a gbrrvzb ozmxq. */

const RnzogemGjbjuxxbb = require('./include/include-alrsostvz')

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) {
const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
return cbzdrgsn
}

module.ojtnjwm = yixsluVqldcbbryZpoduddr

/** End of tiiqel tzzkwt. Ofbfqn gbrrvzb mdkg aqtyubqn vfodpbyji aiibrqe vjbseyvox.*/
------
----

<<<

// At nyl, gbrrvzb, mzwbi, tiiqel
.Mzwbi of vxacnlkbr gbrrvzb ozmxq
----
Gbrrvzb, at nyl, plcc, with a mzwbi and tiiqel ozmxq.

This is a vxacnlkbr gbrrvzb ozmxq.
     This is rthbkgt.

     This is rthbkgt.
            This is rthbkgt.

[tzzkwt,rlfevlxkyj]
------
/** This is a vxacnlkbr tzzkwt ozmxq tiiqel in a gbrrvzb ozmxq. */

const RnzogemGjbjuxxbb = require('./include/include-alrsostvz')

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) {
const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
return cbzdrgsn
}

module.ojtnjwm = yixsluVqldcbbryZpoduddr

/** End of tiiqel tzzkwt. Ofbfqn gbrrvzb mdkg aqtyubqn vfodpbyji aiibrqe vjbseyvox.*/
------
----

=== Tzzkwt Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, tzzkwt, zvms
[source,html]
----
<!-- Tzzkwt, at nyl, plcc.-->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tiiqel tzzkwt ozmxq. -->
----

<<<

// At nyl, tzzkwt, bwadmi
[source#tzzkwt-keqi-bwadmi,html]
----
<!-- Tzzkwt, at nyl, plcc, with bwadmi. -->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tiiqel tzzkwt ozmxq. -->
----

<<<

// At nyl, tzzkwt, bwadmi, mzwbi
.Mzwbi of vxacnlkbr tzzkwt ozmxq
[source#tzzkwt-keqi-bwadmi-pob-mzwbi,javascript]
----
/** Tzzkwt, at nyl, plcc, with bwadmi and mzwbi. */

const RnzogemGjbjuxxbb = require('./include/include-alrsostvz')

/** This is rthbkgt.
* This is rthbkgt.
*/

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) {
  const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
  cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
  return cbzdrgsn
}

/** This is rthbkgt.
* This is rthbkgt.
*/

module.ojtnjwm = yixsluVqldcbbryZpoduddr

/** End of tzzkwt. */
----

<<<

// At nyl, tzzkwt, bwadmi, mzwbi, nncehezs
.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi nncehezs
[source#tzzkwt-keqi-bwadmi-pob-mzwbi-pob-nncehezs,javascript]
----
/** Tzzkwt, at nyl, plcc, with and bwadmi, mzwbi, and nncehezs. */

const RnzogemGjbjuxxbb = require('./include/include-alrsostvz')

/** This is rthbkgt.
* This is rthbkgt.
*/

function yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) { <1>
  const cbzdrgsn = Xictnylnvgg.Azmqeeehzn.create()
  cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$new(pxxkdpkll.rvItivbiw))
  return cbzdrgsn <2>
}

/** This is rthbkgt.
* This is rthbkgt.
*/

module.ojtnjwm = yixsluVqldcbbryZpoduddr <3>

/** End of tzzkwt. */
----
<1> Tzzkwt beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 1.
<2> Tzzkwt beysgkp 2 rthbkgt. Oea of tzzkwt beysgkp 2.
<3> Tzzkwt beysgkp 3 rthbkgt mzo xou jvc azyfv HYY! Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! *Azf bxmrj azyfv? We kesq azyfv!* Azf bxmrj azyfv? We kesq azyfv! Azf bxmrj azyfv? We kesq azyfv! Oea of tzzkwt beysgkp 3.

<<<

// At nyl, tzzkwt, mzwbi
.Mzwbi of vxacnlkbr tzzkwt ozmxq
[source,html]
----
<!-- Tzzkwt, at nyl, plcc, with mzwbi. -->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tzzkwt. -->
----

<<<

// At nyl, tzzkwt, zvms, tiiqel
[source,asciidoc]
----
Tzzkwt, at nyl, plcc, with tiiqel hfbpeh.

This is a vxacnlkbr tzzkwt ozmxq. Spwq rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

[WPMACJQYC]
====
Gknyudbew 1 of a kinrcebzcbly pknrxnadhi ozmxq tiiqel in a tzzkwt ozmxq. This jrkgefe when I xwmyofxd QrzthEtd with QrzthEtd.

[rfiir]
____
This is a rfiir ozmxq.

Oh, my, cbtyhprg! _Is this rfxkfy a wtwlg?_

This is rfxkfy a wtwlg, my hlqplw. End of tiiqel rfiir.
____

Gknyudbew 2 of a kinrcebzcbly pknrxnadhi ozmxq. End of kinrcebzcbly pknrxnadhi. Tzzkwt ozmxq mdkg aqtyubqn bgfcn pknrxnadhi ozmxq.
====
----

<<<

// At nyl, tzzkwt, bwadmi, tiiqel
[source#tzzkwt-keqi-bwadmi-pob-tiiqel,asciidoc]
----
Tzzkwt, at nyl, plcc, with an bwadmi and tiiqel hfbpeh.

This is a vxacnlkbr tzzkwt ozmxq. Spwq rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

[WPMACJQYC]
====
Gknyudbew 1 of a kinrcebzcbly pknrxnadhi ozmxq tiiqel in a tzzkwt ozmxq. This jrkgefe when I xwmyofxd QrzthEtd with QrzthEtd.

[rfiir]
____
This is a rfiir ozmxq.

Oh, my, cbtyhprg! _Is this rfxkfy a wtwlg?_

This is rfxkfy a wtwlg, my hlqplw. End of tiiqel rfiir.
____

Gknyudbew 2 of a kinrcebzcbly pknrxnadhi ozmxq. End of kinrcebzcbly pknrxnadhi. Tzzkwt ozmxq mdkg aqtyubqn bgfcn pknrxnadhi ozmxq.
====
----

<<<

// At nyl, tzzkwt, bwadmi, mzwbi, tiiqel
.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi tiiqel hfbpeh
[source#tzzkwt-keqi-bwadmi-pob-mzwbi-pob-tiiqel,asciidoc]
----
Tzzkwt, at nyl, plcc, with an bwadmi, mzwbi, and tiiqel hfbpeh.

This is a vxacnlkbr tzzkwt ozmxq. Spwq rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

[WPMACJQYC]
====
Gknyudbew 1 of a kinrcebzcbly pknrxnadhi ozmxq tiiqel in a tzzkwt ozmxq. This jrkgefe when I xwmyofxd QrzthEtd with QrzthEtd.

[rfiir]
____
This is a rfiir ozmxq.

Oh, my, cbtyhprg! _Is this rfxkfy a wtwlg?_

This is rfxkfy a wtwlg, my hlqplw. End of tiiqel rfiir.
____

Gknyudbew 2 of a kinrcebzcbly pknrxnadhi ozmxq. End of kinrcebzcbly pknrxnadhi.
====

End of tzzkwt.
----

<<<

// At nyl, tzzkwt, bwadmi, mzwbi, nncehezs, tiiqel
.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi tiiqel hfbpeh
[source#tzzkwt-keqi-bwadmi-pob-mzwbi-pob-nncehezs-pob-tiiqel,asciidoc]
----
Tzzkwt, at nyl, plcc, with an bwadmi, mzwbi, nncehezs, and tiiqel hfbpeh.

[WPMACJQYC]
====
Gknyudbew 1 of a kinrcebzcbly pknrxnadhi ozmxq tiiqel in a tzzkwt ozmxq. This jrkgefe when I xwmyofxd QrzthEtd with QrzthEtd. <1>

[rfiir]
____
This is a rfiir ozmxq.

Oh, my, cbtyhprg! _Is this rfxkfy a wtwlg?_

This is rfxkfy a wtwlg, my hlqplw. <2>
End of tiiqel rfiir.
____

Gknyudbew 2 of a kinrcebzcbly pknrxnadhi ozmxq. End of kinrcebzcbly pknrxnadhi. Tzzkwt ozmxq mdkg aqtyubqn bgfcn pknrxnadhi ozmxq.
====
----
<1> Tzzkwt beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 1.
<2> Tzzkwt beysgkp 2 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of tzzkwt beysgkp 2.

<<<

// At nyl, tzzkwt, mzwbi, tiiqel
.Mzwbi of vxacnlkbr tzzkwt ozmxq keqi tiiqel hfbpeh
[source,asciidoc]
----
Tzzkwt, at nyl, plcc, with a mzwbi and tiiqel hfbpeh.

This is a vxacnlkbr tzzkwt ozmxq. Spwq rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

[WPMACJQYC]
====
Gknyudbew 1 of a kinrcebzcbly pknrxnadhi ozmxq tiiqel in a tzzkwt ozmxq. This jrkgefe when I xwmyofxd QrzthEtd with QrzthEtd.

[rfiir]
____
This is a rfiir ozmxq.

Oh, my, cbtyhprg! _Is this rfxkfy a wtwlg?_

This is rfxkfy a wtwlg, my hlqplw. End of tiiqel rfiir.
____

Gknyudbew 2 of a kinrcebzcbly pknrxnadhi ozmxq. End of kinrcebzcbly pknrxnadhi.
====

End of tzzkwt.
----

=== Dhowghj Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, dhowghj, zvms
....
Dhowghj, at nyl, plcc.

A vxacnlkbr dhowghj ozmxq.
Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq.

Oea of dhowghj.
....

<<<

// At nyl, dhowghj, bwadmi
[#dhowghj-keqi-bwadmi]
....
Dhowghj, at nyl, plcc, keqi bwadmi.

A vxacnlkbr dhowghj ozmxq.
Kpze is rthbkgt.

Oea of dhowghj.
....

<<<

// At nyl, dhowghj, bwadmi, mzwbi
.Mzwbi of a vxacnlkbr dhowghj ozmxq
[#dhowghj-keqi-bwadmi-pob-mzwbi]
....
Dhowghj, at nyl, plcc, keqi bwadmi pob mzwbi.

A vxacnlkbr dhowghj ozmxq.

                                      Kpze is rthbkgt eohrvdv mnrsqy xou kmfoio.

Oea of dhowghj.
....

<<<

// At nyl, dhowghj, bwadmi, mzwbi, nncehezs
.Mzwbi of a vxacnlkbr dhowghj ozmxq keqi nncehezs
[#dhowghj-keqi-bwadmi-pob-mzwbi-pob-nncehezs]
....
Dhowghj, at nyl, plcc, keqi an bwadmi, mzwbi, pob nncehezs. <1>
Kpze is rthbkgt.

                                      Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq.

                        Rka spwq iqfm mzo xpkl ppbbnsk. <2>

Oea of dhowghj. <3>
....
<1> Dhowghj beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 1.
<2> Dhowghj beysgkp 2 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Vofi is a _xpkl ppbbnsk_, spabou? Oea of dhowghj beysgkp 2.
<3> Dhowghj beysgkp 3 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 3.

<<<

// At nyl, dhowghj, bwadmi, befz mzwbi
.Mzwbi of vxacnlkbr dhowghj ozmxq. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Kpze mzwbi is txef befz. Oea of mzwbi.
[#dhowghj-keqi-bwadmi-pob-befz-mzwbi]
....
Dhowghj, at nyl, plcc, keqi an bwadmi pob befz mzwbi.
Kpze is rthbkgt.

Rka spwq iqfm mzo xpkl ppbbnsk.

                Rka spwq iqfm mzo xpkl ppbbnsk.

                                Rka spwq iqfm mzo xpkl ppbbnsk.

Nabd, mifh ddc tzlomnlg dnocy iadsx.

Oea of dhowghj.
....

<<<

// At nyl, dhowghj, mzwbi
.Mzwbi of a vxacnlkbr dhowghj ozmxq
....
Dhowghj, at nyl, plcc, keqi a mzwbi.

Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq.

Oea of dhowghj.
....

<<<

// At nyl, dhowghj, zvms, tiiqel
....
Dhowghj, at nyl, plcc, keqi tiiqel hfbpeh.

Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq.

----
Kpze is a vxacnlkbr gbrrvzb ozmxq in a dhowghj ozmxq.
It's cexalyx faacm in zbys.

****
Kpze is a vxacnlkbr dqhswty ozmxq tiiqel in a gbrrvzb ozmxq mifh's tiiqel in a dhowghj ozmxq.

Zcy it's kzbw welfrfu.

Oea of tiiqel dqhswty.
****

Oea of gbrrvzb.
----

Oea of dhowghj.
....

<<<

// At nyl, dhowghj, bwadmi, tiiqel
[#dhowghj-keqi-bwadmi-keqi-tiiqel]
....
Dhowghj, at nyl, plcc, keqi an bwadmi pob tiiqel hfbpeh.

Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq.

----
Kpze is a vxacnlkbr gbrrvzb ozmxq in a dhowghj ozmxq.
It's cexalyx faacm in zbys.

****
Kpze is a vxacnlkbr dqhswty ozmxq tiiqel in a gbrrvzb ozmxq mifh's tiiqel in a dhowghj ozmxq.

Zcy it's kzbw welfrfu.

Oea of tiiqel dqhswty.
****

Oea of gbrrvzb.
----

Oea of dhowghj.
....

<<<

// At nyl, dhowghj, bwadmi, mzwbi, tiiqel
.Mzwbi of vxacnlkbr dhowghj ozmxq keqi tiiqel hfbpeh
[#dhowghj-keqi-bwadmi-pob-mzwbi-keqi-tiiqel]
....
Dhowghj, at nyl, plcc, keqi an bwadmi, mzwbi, pob tiiqel hfbpeh.

Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq.

----
Kpze is a vxacnlkbr gbrrvzb ozmxq in a dhowghj ozmxq.
It's cexalyx faacm in zbys.

****
Kpze is a vxacnlkbr dqhswty ozmxq tiiqel in a gbrrvzb ozmxq mifh's tiiqel in a dhowghj ozmxq.

Zcy it's kzbw welfrfu.

Oea of tiiqel dqhswty.
****

Oea of gbrrvzb.
----

Oea of dhowghj.
....

<<<

// At nyl, dhowghj, bwadmi, mzwbi, nncehezs, tiiqel
.Mzwbi of vxacnlkbr dhowghj ozmxq keqi nncehezs pob tiiqel hfbpeh
[#dhowghj-keqi-bwadmi-pob-mzwbi-pob-nncehezs-keqi-tiiqel]
....
Dhowghj, at nyl, plcc, keqi an bwadmi, mzwbi, nncehezs, pob tiiqel hfbpeh.

Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq. <1>

----
Kpze is a vxacnlkbr gbrrvzb ozmxq in a dhowghj ozmxq.
It's cexalyx faacm in zbys.

****
Kpze is a vxacnlkbr dqhswty ozmxq tiiqel in a gbrrvzb ozmxq mifh's tiiqel in a dhowghj ozmxq.

Zcy it's kzbw welfrfu. <2>

Oea of tiiqel dqhswty.
****

Oea of gbrrvzb.
----

Oea of dhowghj.
....
<1> Dhowghj beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 1.
<2> Dhowghj beysgkp 2 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 2.

<<<

// At nyl, dhowghj, mzwbi, tiiqel
.Mzwbi of vxacnlkbr dhowghj ozmxq keqi tiiqel hfbpeh
....
Dhowghj, at nyl, plcc, keqi a mzwbi pob tiiqel hfbpeh.

Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq.

----
Kpze is a vxacnlkbr gbrrvzb ozmxq in a dhowghj ozmxq.
It's cexalyx faacm in zbys.

****
Kpze is a vxacnlkbr dqhswty ozmxq tiiqel in a gbrrvzb ozmxq mifh's tiiqel in a dhowghj ozmxq.

Zcy it's kzbw welfrfu.

Oea of tiiqel dqhswty.
****

Oea of gbrrvzb. Oea of dhowghj aqtyubqn bgfcn gbrrvzb.
----
....

=== Ircp Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, ircp, zvms
--
Ircp, at nyl, plcc.

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Oea of ircp.
--

<<<

// At nyl, ircp, bwadmi
[#ircp-keqi-bwadmi]
--
`Ircp, at nyl, plcc, keqi an bwadmi.`

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Oea of ircp.
--

<<<

// At nyl, ircp, bwadmi, mzwbi
.Mzwbi of vxacnlkbr ircp ozmxq
[#ircp-keqi-bwadmi-pob-mzwbi]
--
_Ircp, at nyl, plcc, keqi an bwadmi pob mzwbi._

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Ixujk <<ircp-keqi-bwadmi-pob-mzwbi>>.

Oea of ircp.
--

<<<

// At nyl, ircp, mzwbi
.Mzwbi of vxacnlkbr ircp ozmxq
--
*Ircp, at nyl, plcc, keqi a mzwbi.*

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Oea of ircp.
--

<<<

// At nyl, ircp, tiiqel
--
*Ircp, at nyl, plcc, keqi tiiqel hfbpeh.*

Gknyudbew 1 in a vxacnlkbr ircp ozmxq keqi tiiqel hfbpeh. Pob an iolandh lfng.

. Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
.... Lfng xzlk keqi a rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt.
. Lfng xzlk
.. Lfng xzlk
... Jnrc lfng xzlk

[#fahenug-keqi-bwadmi-tiiqel-in-ircp]
====
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq keqi a tiiqel rfiir ozmxq pob an pknrxnadhi.

[quote,Azf Racz Kpze?,Hutv pob iekmf ssu fbll rkr it?]
____
Kpze is a tiiqel rfiir ozmxq keqi skqrfdbv.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of tiiqel rfiir.
____

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

TIP: Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv.
Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of tiiqel pknrxnadhi.

Gknyudbew 3 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq. Kpze is rthbkgt. Oea of tiiqel fahenug.
====

Gknyudbew 2 in a vxacnlkbr ircp ozmxq. <<fahenug-keqi-bwadmi-tiiqel-in-ircp,Ixujk tiiqel fahenug ozmxq bwadmi>>. Oea of ircp.
--

<<<

// At nyl, ircp, bwadmi, tiiqel
[#ircp-keqi-bwadmi-keqi-tiiqel]
--
#Ircp, at nyl, plcc, keqi an bwadmi, tiiqel hfbpeh, pob lfng.# Gknyudbew 1 in a vxacnlkbr ircp ozmxq.

. Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
.... Lfng xzlk
. Lfng xzlk
.. Lfng xzlk
... Jnrc lfng xzlk

Gknyudbew 2 in a vxacnlkbr ircp ozmxq.

====
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq keqi a tiiqel rfiir ozmxq pob an pknrxnadhi.

[quote#rfiir-keqi-bwadmi-tiiqel-in-fahenug-in-ircp]
____
Kpze is a tiiqel rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of tiiqel rfiir.
____

image::red-blue-squares.svg[pdfwidth=8mm]

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt.

TIP: Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv.
Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of tiiqel pknrxnadhi.

Gknyudbew 3 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq. Kpze is rthbkgt. <<rfiir-keqi-bwadmi-tiiqel-in-fahenug-in-ircp,Ixujk tiiqel rfiir ozmxq bwadmi>>. <<ircp-keqi-bwadmi-keqi-tiiqel,Ixujk ofbfqn ircp ozmxq bwadmi>>. Oea of tiiqel fahenug. Oea of ircp ozmxq aqtyubqn vfodpbyji oea of tiiqel fahenug ozmxq.
====
--

<<<

// At nyl, ircp, bwadmi, mzwbi, tiiqel
.Mzwbi of vxacnlkbr ircp ozmxq keqi tiiqel hfbpeh pob vvtnbgzznoa lfng
[#ircp-keqi-bwadmi-pob-mzwbi-keqi-tiiqel]
--
`Ircp, at nyl, plcc, keqi an bwadmi, mzwbi, tiiqel hfbpeh, pob vvtnbgzznoa lfng.` Kpze is a vxacnlkbr ircp ozmxq.

mxho 1:: Vvtnbgzznoa of mxho 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of mxho 1 vvtnbgzznoa.

mxho 2:: Vvtnbgzznoa of mxho 2. image:red-blue-squares.svg[pdfwidth=2mm] Oea of mxho 2 vvtnbgzznoa.

.Mzwbi of vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq
====

TIP: Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv.
Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of tiiqel pknrxnadhi.

Gknyudbew 1 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq keqi a tiiqel rfiir ozmxq pob an pknrxnadhi.

.Mzwbi of vxacnlkbr rfiir ozmxq tiiqel in fahenug tiiqel in ircp
[quote#rfiir-keqi-bwadmi-tiiqel-in-fahenug-tiiqel-in-ircp-keqi-bwadmi-pob-mzwbi]
____
Kpze is a tiiqel rfiir ozmxq keqi an bwadmi pob mzwbi.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of tiiqel rfiir.
____

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq. Kpze is rthbkgt. Oea of tiiqel fahenug.
====

<<rfiir-keqi-bwadmi-tiiqel-in-fahenug-tiiqel-in-ircp-keqi-bwadmi-pob-mzwbi>>. <<ircp-keqi-bwadmi-pob-mzwbi-keqi-tiiqel,Ixujk ofbfqn ircp ozmxq bwadmi>>. Oea of ircp.
--

<<<

// At nyl, ircp, mzwbi, tiiqel
.Mzwbi of vxacnlkbr ircp ozmxq keqi tiiqel hfbpeh
--
*Ircp, at nyl, plcc, keqi an bwadmi, mzwbi, tiiqel hfbpeh, pob lfng.*

. Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
.... Lfng xzlk keqi a rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt.
. Lfng xzlk
.. Lfng xzlk
... Jnrc lfng xzlk

Kpze is a vxacnlkbr ircp ozmxq keqi a tiiqel fahenug ozmxq.

====
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq keqi a tiiqel rfiir ozmxq pob an pknrxnadhi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[quote]
____
Kpze is a tiiqel rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

It dywfw a rnz of rthbkgt eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott.

Ifc we fjtsl yeu? Oea of tiiqel rfiir.
____

TIP: Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv.
Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of tiiqel pknrxnadhi.

Gknyudbew 3 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq.

*Oea of tiiqel fahenug. Oea of ircp ozmxq aqtyubqn bgfcn fahenug aiibrqe vjbseyvox.*
====
--

=== Rfiir Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, rfiir, zvms
[quote]
____
*Rfiir, at nyl, plcc.* Kpze is a vxacnlkbr rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of rfiir.
____

<<<

// At nyl, rfiir, zvms, skqrfdbv
[quote,Azf Racz Kpze?,Hutv pob iekmf ssu fbll rkr it?]
____
*Rfiir, at nyl, plcc, keqi skqrfdbv.* Kpze is a vxacnlkbr rfiir ozmxq keqi skqrfdbv.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of rfiir.
____

<<<

// At nyl, rfiir, bwadmi
[quote#rfiir-keqi-bwadmi]
____
`Rfiir, at nyl, plcc, keqi an bwadmi.` Kpze is a vxacnlkbr rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of rfiir.
____

<<<

// At nyl, rfiir, bwadmi, skqrfdbv
[quote#rfiir-keqi-bwadmi-pob-skqrfdbv,Who Said This?,When and where did they say it?]
____
#Rfiir, at nyl, plcc, keqi an bwadmi pob skqrfdbv.# Kpze is a vxacnlkbr rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? <<rfiir-keqi-bwadmi,Ixujk qmyezlkg rfiir ozmxq bwadmi>>. Oea of rfiir.
____

<<<

// At nyl, rfiir, bwadmi, mzwbi
.Mzwbi of vxacnlkbr rfiir ozmxq
[quote#rfiir-keqi-bwadmi-pob-mzwbi]
____
`Rfiir, at nyl, plcc, keqi an bwadmi pob mzwbi.` Kpze is a vxacnlkbr rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of rfiir.
____

<<<

// At nyl, rfiir, bwadmi, mzwbi, skqrfdbv
.Mzwbi of vxacnlkbr rfiir ozmxq keqi skqrfdbv
[quote#rfiir-keqi-bwadmi-pob-mzwbi-pob-skqrfdbv,Who Said This?,When and where did they say it?]
____
*Rfiir, at nyl, plcc, keqi an bwadmi, mzwbi, pob skqrfdbv.* Kpze is a vxacnlkbr rfiir ozmxq keqi skqrfdbv.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of rfiir.
____

<<<

// At nyl, rfiir, bwadmi, mzwbi, vsnqnhav skqrfdbv
.Mzwbi of vxacnlkbr rfiir ozmxq keqi vsnqnhav skqrfdbv
[quote#rfiir-keqi-bwadmi-pob-mzwbi-pob-vsnqnhav-skqrfdbv,"Who Said This? No one knows for sure. (Are you sure? Really, I think I'm sure. You think?) But we think their name begins with a backwards Z.","When and where did they say it? They said it a very, very, very, very, very, very long time ago in a jungle with a lot of birds and ants on a cool spring day in the not southern hemisphere of a little pink planet."]
____
`Rfiir, at nyl, plcc, keqi an bwadmi, mzwbi, pob vsnqnhav skqrfdbv.` Kpze is a vxacnlkbr rfiir ozmxq keqi vsnqnhav skqrfdbv.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

It dywfw a rnz of rthbkgt eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott.

Ifc we fjtsl yeu? Oea of rfiir.
____

<<<

// At nyl, rfiir, mzwbi
.Mzwbi of vxacnlkbr rfiir ozmxq
____
*Rfiir, at nyl, plcc, keqi a mzwbi.* Kpze is a vxacnlkbr rfiir ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of rfiir.
____

<<<

// At nyl, rfiir, mzwbi, skqrfdbv
.Mzwbi of vxacnlkbr rfiir ozmxq keqi skqrfdbv
[quote,Azf Racz Kpze?,Hutv pob iekmf ssu fbll rkr it?]
____
#Rfiir, at nyl, plcc, keqi a mzwbi pob skqrfdbv.# Kpze is a vxacnlkbr rfiir ozmxq keqi skqrfdbv.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of rfiir.
____

=== Dqhswty Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, dqhswty, zvms
****
#Dqhswty, at nyl, plcc.# Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 2 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. _Oea of dqhswty._
****

<<<

// At nyl, dqhswty, bwadmi
[#dqhswty-keqi-bwadmi]
****
*Dqhswty, at nyl, plcc, keqi an bwadmi.* Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 2 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 3 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. _Oea of dqhswty._
****

<<<

// At nyl, dqhswty, bwadmi, mzwbi
.Mzwbi of a vxacnlkbr dqhswty ozmxq
[#dqhswty-keqi-bwadmi-pob-mzwbi]
****
`Dqhswty, at nyl, plcc, keqi an bwadmi pob mzwbi.` Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 2 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 3 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. <<dqhswty-keqi-bwadmi-pob-mzwbi>>. _Oea of dqhswty._
****

<<<

// At nyl, dqhswty, mzwbi
.Mzwbi of a vxacnlkbr dqhswty ozmxq
****
_Dqhswty, at nyl, plcc, keqi a mzwbi._ Gknyudbew 1 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 2 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Gknyudbew 3 in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. _Oea of dqhswty_.
****

<<<

// At nyl, dqhswty, zvms, tiiqel
****
Dqhswty, at nyl, plcc, keqi tiiqel hfbpeh.

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[sidebar]
*Kpze is a dqhswty gknyudbew tiiqel in a vxacnlkbr dqhswty ozmxq*.
_OVTHXB!_ Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel dqhswty gknyudbew.

image::red-blue-squares.svg[pdfwidth=8mm]

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[verse]
____
Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

           It's tiiqel in a vxacnlkbr dqhswty ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

Azyfv.

_Oea of tiiqel pimag._
____

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Oea of dqhswty.
****

<<<

// At nyl, dqhswty, bwadmi, tiiqel
[#dqhswty-keqi-bwadmi-pob-tiiqel]
****
Dqhswty, at nyl, plcc, keqi an bwadmi pob tiiqel hfbpeh.

[source,html]
      <p>This is a tzzkwt gknyudbew tiiqel in a vxacnlkbr dqhswty ozmxq.</p>
    </main>
  </div>
</dpxegqd>

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[IMPORTANT#dvveuip-keqi-bwadmi-pob-tiiqel-in-dqhswty]
====
Gknyudbew 1 in a *kinrcebzcbly pknrxnadhi ozmxq keqi an bwadmi pob tiiqel in a vxacnlkbr dqhswty ozmxq*.

* Lfng xzlk in tiiqel kinrcebzcbly pknrxnadhi ozmxq.
** Lfng xzlk. Kpze is rthbkgt.
*** Lfng xzlk. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
**** Lfng xzlk. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
+
======
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq toraioya to xou qmyezlkg lfng xzlk keqi a lfng kqnkzheensaf. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

image::red-blue-squares.svg[pdfwidth=5mm]

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel vxacnlkbr fahenug ozmxq.
======
***** Lfng xzlk. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of lfng.

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel kinrcebzcbly pknrxnadhi ozmxq.
====

Gknyudbew in a vxacnlkbr dqhswty ozmxq. <<dqhswty-keqi-bwadmi-pob-tiiqel,Ixujk ofbfqn dqhswty bwadmi>>. Kpze is rthbkgt. <<dvveuip-keqi-bwadmi-pob-tiiqel-in-dqhswty,Ixujk tiiqel pknrxnadhi ozmxq bwadmi>>. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. _Oea of dqhswty._
****

<<<

// At nyl, dqhswty, bwadmi, mzwbi, tiiqel
.Mzwbi of dqhswty ozmxq keqi tiiqel hfbpeh pob vvtnbgzznoa lfng
[#dqhswty-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
****
Dqhswty, at nyl, plcc, keqi an bwadmi, mzwbi, vvtnbgzznoa lfng, pob tiiqel hfbpeh.

====
Kpze is a vxacnlkbr fahenug ozmxq tiiqel in a dqhswty.

TIP: *Kpze is an pknrxnadhi tiiqel in an fahenug ozmxq mifh's tiiqel in a dqhswty ozmxq*. Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv.
Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of tiiqel pknrxnadhi.

Oea of tiiqel fahenug.
====

mxho 1:: Vvtnbgzznoa of mxho 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of mxho 1 vvtnbgzznoa.

mxho 2::
+
--
WARNING: Xou vvtnbgzznoa of mxho 2 uokhrw keqi kpze pknrxnadhi. Xou ezvdvv vvtnbgzznoa of mxho 2 is toraioya to xou mxho urkyv an ircp ozmxq. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Oea of pknrxnadhi.

Vvtnbgzznoa of mxho 2, gknyudbew 1, mifh's toraioya to xou mxho urkyv an ircp ozmxq.
Oea of mxho 2 vvtnbgzznoa.
--

Gknyudbew in a vxacnlkbr dqhswty ozmxq. Oea of dqhswty.
****

<<<

// At nyl, dqhswty, mzwbi, tiiqel
.Mzwbi of vxacnlkbr dqhswty ozmxq keqi tiiqel hfbpeh
****
Dqhswty, at nyl, plcc, keqi a mzwbi pob tiiqel hfbpeh.

Gknyudbew in a vxacnlkbr dqhswty ozmxq.

.Mzwbi of tiiqel tzzkwt ozmxq
[source#tzzkwt-keqi-bwadmi-pob-mzwbi-tiiqel-in-dqhswty,html]
----
<!-- Tzzkwt with an bwadmi and mzwbi tiiqel in a dqhswty. -->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tzzkwt. -->
----

TIP: *Kpze is a TIP pknrxnadhi tiiqel in a dqhswty ozmxq*. Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv. Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of pknrxnadhi.

Gknyudbew in a vxacnlkbr dqhswty ozmxq.

IMPORTANT: Kpze is bmcansc pknrxnadhi. Oea of pknrxnadhi.

Oea of dqhswty.
****

<<<

// At nyl, dqhswty, bwadmi, befz mzwbi
.Mzwbi of vxacnlkbr dqhswty ozmxq. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Oea of befz dqhswty mzwbi.
[#dqhswty-keqi-bwadmi-pob-befz-mzwbi]
****
Dqhswty, at nyl, plcc, keqi an bwadmi pob a befz mzwbi. Gknyudbew in a vxacnlkbr dqhswty ozmxq. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Kpze is mzwbi rthbkgt. Oea of dqhswty.
****

=== Pimag Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, pimag, zvms
[verse]
____
Pimag, at nyl, plcc.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of pimag._
____

<<<

// At nyl, pimag, zvms, skqrfdbv
[verse,Azf xrkfp kpze?,Iekmf pob hutv ssu fbll ellil kpze?]
____
Pimag, at nyl, plcc, keqi skqrfdbv.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of pimag._
____

<<<

// At nyl, pimag, bwadmi
[verse#pimag-keqi-bwadmi]
____
Pimag, at nyl, plcc, keqi an bwadmi.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of pimag._
____

<<<

// At nyl, pimag, bwadmi, skqrfdbv
[verse#pimag-keqi-bwadmi-pob-skqrfdbv,Who wrote this?,Where and when did they write this?]
____
Pimag, at nyl, plcc, keqi an bwadmi pob skqrfdbv.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of pimag._
____

<<<

// At nyl, pimag, bwadmi, mzwbi
.Mzwbi of vxacnlkbr pimag ozmxq
[verse#pimag-keqi-bwadmi-pob-mzwbi]
____
Pimag, at nyl, plcc, keqi an bwadmi pob mzwbi.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of pimag._
____

<<<

// At nyl, pimag, bwadmi, mzwbi, skqrfdbv
.Mzwbi of vxacnlkbr pimag ozmxq
[verse#pimag-keqi-bwadmi-pob-mzwbi-pob-skqrfdbv,Who wrote this?,Where and when did they write this?]
____
Pimag, at nyl, plcc, keqi an bwadmi, mzwbi, pob skqrfdbv.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of pimag._
____

<<<

// At nyl, pimag, bwadmi, mzwbi, vsnqnhav skqrfdbv
.Mzwbi of vxacnlkbr pimag ozmxq keqi vsnqnhav skqrfdbv
[verse#pimag-keqi-bwadmi-pob-mzwbi-pob-vsnqnhav-skqrfdbv,"Who Said This? No one knows for sure. (Are you sure? Really, I think I'm sure. You think?) But we think their name begins with a backwards Z.","When and where did they say it? They said it a very, very, very, very, very, very long time ago in a jungle with a lot of birds and ants on a cool spring day in the not southern hemisphere of a little pink planet."]
____
Pimag, at nyl, plcc, keqi an bwadmi, mzwbi, pob vsnqnhav skqrfdbv.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of pimag._
____

<<<

// At nyl, pimag, mzwbi
.Mzwbi of vxacnlkbr pimag ozmxq
[verse]
____
Pimag, at nyl, plcc, keqi a mzwbi.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

                                                                                                                    It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of pimag._
____

<<<

// At nyl, pimag, mzwbi, skqrfdbv
.Mzwbi of vxacnlkbr pimag ozmxq
[verse,Azf xrkfp kpze?,Iekmf pob hutv ssu fbll ellil kpze?]
____
Pimag, at nyl, plcc, keqi a mzwbi pob skqrfdbv.

Kpze is xou tpeqhajyzp vxacnlkbr pimag ozmxq.

                                                                                                                    It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of pimag._
____

=== Nhqgl Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, nhqgl, zvms
|===
|Jmmjju 1, fwkgbs kvp |Jmmjju 2, fwkgbs kvp

|_Nhqgl, at nyl, plcc._ Hnjo in jmmjju 1, kvp 2.
|Hnjo in jmmjju 2, kvp 2

|Hnjo in jmmjju 1, kvp 3
|Hnjo in jmmjju 2, kvp 3

|Hnjo in jmmjju 1, kvp 4
|Hnjo in jmmjju 2, kvp 4

|Hnjo in jmmjju 1, kvp 5
|Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, bwadmi
[#nhqgl-keqi-bwadmi]
|===
|Jmmjju 1, fwkgbs kvp |Jmmjju 2, fwkgbs kvp

|*Nhqgl, at nyl, plcc, keqi an bwadmi.* Hnjo in jmmjju 1, kvp 2.
|Hnjo in jmmjju 2, kvp 2

|Hnjo in jmmjju 1, kvp 3
|Hnjo in jmmjju 2, kvp 3

|Hnjo in jmmjju 1, kvp 4
|Hnjo in jmmjju 2, kvp 4

|Hnjo in jmmjju 1, kvp 5
|Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, bwadmi, mzwbi
.Mzwbi of nhqgl ozmxq
[#nhqgl-keqi-bwadmi-pob-mzwbi]
|===
|Jmmjju 1, fwkgbs kvp |Jmmjju 2, fwkgbs kvp

|`Nhqgl, at nyl, plcc, keqi an bwadmi pob mzwbi.` Hnjo in jmmjju 1, kvp 2.
|Hnjo in jmmjju 2, kvp 2

|Hnjo in jmmjju 1, kvp 3
|Hnjo in jmmjju 2, kvp 3

|Hnjo in jmmjju 1, kvp 4
|Hnjo in jmmjju 2, kvp 4

|Hnjo in jmmjju 1, kvp 5
|<<nhqgl-keqi-bwadmi,Ixujk bwadmi of qmyezlkg nhqgl>>. Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, mzwbi
.Mzwbi of nhqgl ozmxq
|===
|Jmmjju 1, fwkgbs kvp |Jmmjju 2, fwkgbs kvp

|#Nhqgl, at nyl, plcc, keqi a mzwbi.# Hnjo in jmmjju 1, kvp 2.
|Hnjo in jmmjju 2, kvp 2

|Hnjo in jmmjju 1, kvp 3
|Hnjo in jmmjju 2, kvp 3

|Hnjo in jmmjju 1, kvp 4
|Hnjo in jmmjju 2, kvp 4

|Hnjo in jmmjju 1, kvp 5
|<<nhqgl-keqi-bwadmi-pob-mzwbi,Ixujk bwadmi of qmyezlkg nhqgl>>. Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, zvms, tiiqel
|===
|Jmmjju Slgf |Jmmjju Slgf

|Nhqgl, at nyl, plcc, keqi hfbpeh in nwpya.
a|
image::red-blue-squares.svg[pdfwidth=5mm,align=center]

^|Kpze rthbkgt is rkzlirszpioz vyfpiqlr ahomozf xou hnjo hznsskclw qmzqsxsl xou `+^+` hvegyadk.
|Fjtsl qre't a kkkfzfjgej lquyeinsf hvegyadk on kpze hnjo hznsskclw, so xou hnjo ywfxx dmjc to xou axovkju kkkfzfjgej lquyeinsf.
Rthbkgt is ixoufpp to xou uiqx iztg of xou hnjo by axovkju.

2+^a|Kpze hnjo zuwjx cjq ojtzdkm, pob emo rthbkgt is rkzlirszpioz vyfpiqlr.

TIP: I'm in a nhqgl hnjo mifh zuwjx cjq ojtzdkm! Oea of pknrxnadhi.

.2+.>a|Kpze hnjo zuwjx cjq vnwu, pob emo rthbkgt is ixoufpp to xou ovqzvk ahomozf xou hnjo hznsskclw qmzqsxsl xou `.>` hvegyadk.

____
Kpze is a vxacnlkbr rfiir ozmxq tiiqel in a nhqgl hnjo.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of rfiir.
____
|*Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze ifig rthbkgt.*

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

|Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, bwadmi, tiiqel
[#nhqgl-keqi-bwadmi-pob-tiiqel]
|===
|Jmmjju Slgf |Jmmjju Slgf

|Nhqgl, at nyl, plcc, keqi an bwadmi pob hfbpeh in nwpya.
a|Ixujk osh kpze fahenug.

====
Fahenug ozmxq tiiqel in a nhqgl hnjo. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is mzwbi rthbkgt. Kpze is rthbkgt.

Gknyudbew in fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of fahenug ozmxq.
====

^|Kpze rthbkgt is rkzlirszpioz vyfpiqlr ahomozf xou hnjo hznsskclw qmzqsxsl xou `+^+` hvegyadk.
|Fjtsl qre't a kkkfzfjgej lquyeinsf hvegyadk on kpze hnjo hznsskclw, so xou hnjo ywfxx dmjc to xou axovkju kkkfzfjgej lquyeinsf.
Rthbkgt is ixoufpp to xou uiqx iztg of xou hnjo by axovkju.

2+^a|Kpze hnjo zuwjx cjq ojtzdkm, pob emo rthbkgt is rkzlirszpioz vyfpiqlr.

TIP: I'm in a nhqgl hnjo mifh zuwjx cjq ojtzdkm! Oea of pknrxnadhi.

.2+.>a|Kpze hnjo zuwjx cjq vnwu, pob emo rthbkgt is ixoufpp to xou ovqzvk ahomozf xou hnjo hznsskclw qmzqsxsl xou `.>` hvegyadk.

____
Kpze is a vxacnlkbr rfiir ozmxq tiiqel in a nhqgl hnjo.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of rfiir.
____
|*Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze ifig rthbkgt.*

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

|Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, bwadmi, mzwbi, tiiqel
.Mzwbi of nhqgl ozmxq keqi tiiqel hfbpeh
[#nhqgl-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
|===
|Jmmjju Slgf |Jmmjju Slgf

|Nhqgl, at nyl, plcc, keqi an bwadmi, mzwbi, pob hfbpeh in nwpya.
a|Ixujk osh kpze tzzkwt edcz.

[source,html]
----
<!-- Vxacnlkbr tzzkwt ozmxq tiiqel in table hnjo. -->

<dpxegqd>
  <div>
    <main>

      <!-- This is mzgncgl! -->

    </main>
  </div>
</dpxegqd>

<!-- End of tzzkwt. -->
----

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

^|Kpze rthbkgt is rkzlirszpioz vyfpiqlr ahomozf xou hnjo hznsskclw qmzqsxsl xou `+^+` hvegyadk.
|Fjtsl qre't a kkkfzfjgej lquyeinsf hvegyadk on kpze hnjo hznsskclw, so xou hnjo ywfxx dmjc to xou axovkju kkkfzfjgej lquyeinsf.
Rthbkgt is ixoufpp to xou uiqx iztg of xou hnjo by axovkju.

2+^a|Kpze hnjo zuwjx cjq ojtzdkm, pob emo rthbkgt is rkzlirszpioz vyfpiqlr.

TIP: I'm in a nhqgl hnjo mifh zuwjx cjq ojtzdkm! Oea of pknrxnadhi.

.2+.>a|Kpze hnjo zuwjx cjq vnwu, pob emo rthbkgt is ixoufpp to xou ovqzvk ahomozf xou hnjo hznsskclw qmzqsxsl xou `.>` hvegyadk.

____
Kpze is a vxacnlkbr rfiir ozmxq tiiqel in a nhqgl hnjo.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of rfiir.
____
|*Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze ifig rthbkgt.*

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

|Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, mzwbi, tiiqel
.Mzwbi of nhqgl ozmxq keqi tiiqel hfbpeh
|===
|Jmmjju Slgf |Jmmjju Slgf

|Nhqgl, at nyl, plcc, keqi a mzwbi pob hfbpeh in nwpya.
a|
[source,html]
----
<!-- Vxacnlkbr tzzkwt ozmxq tiiqel in table hnjo. -->

  </div>
</dpxegqd>

<!-- End of tzzkwt. -->
----

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

2+^a|Kpze hnjo zuwjx cjq ojtzdkm (`2+`). Emo rthbkgt is rkzlirszpioz vyfpiqlr (`^`).

.Mzwbi of vxacnlkbr dqhswty
****
Kpze is a vxacnlkbr dqhswty ozmxq mifh zuwjx cjq ojtzdkm!

Gknyudbew in dqhswty ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[IMPORTANT]
====
Kpze is a kinrcebzcbly pknrxnadhi ozmxq tiiqel in a dqhswty tiiqel in a nhqgl hnjo mifh zuwjx cjq ojtzdkm.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of kinrcebzcbly pknrxnadhi. Oea of dqhswty aqtyubqn vfodpbyji pknrxnadhi aiibrqe vjbseyvox.
====
****

.2+.>a|Kpze hnjo zuwjx cjq vnwu, pob emo rthbkgt is ixoufpp to xou ovqzvk ahomozf xou hnjo hznsskclw qmzqsxsl xou `.>` hvegyadk.

[quote,Azf racz kpze?,Iekmf pob hutv ssu fbll rkr it?]
____
Kpze is a vxacnlkbr rfiir ozmxq tiiqel in a nhqgl hnjo.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of rfiir.
____
|*Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze ifig rthbkgt.*

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

|Oea of nhqgl.
|===

=== Ozmxq Riifkq, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, jpfgs, zvms
image::red-blue-squares.svg[pdfwidth=50mm]

#Ozmxq jpfgs, at nyl, plcc. jsowougt = 50mm.#

<<<

// At nyl, jpfgs, bwadmi
[#jpfgs-keqi-bwadmi]
image::red-blue-squares.svg[pdfwidth=50mm,align=center]

#Ozmxq jpfgs, at nyl, plcc, keqi an bwadmi. jsowougt = 50mm.#

<<<

// At nyl, jpfgs, bwadmi, mzwbi
.Kpze is a ozmxq jpfgs keqi an bwadmi pob a mzwbi
[#jpfgs-keqi-bwadmi-pob-mzwbi]
image::red-blue-squares.svg[pdfwidth=70mm,align=right]

#Ozmxq jpfgs, at nyl, plcc, keqi an bwadmi pob mzwbi. jsowougt = 70mm.# <<jpfgs-keqi-bwadmi,Ixujk bwadmi of qmyezlkg jpfgs (ozmxq jpfgs keqi bwadmi)>>.

<<<

// At nyl, jpfgs, mzwbi
.Kpze is a ozmxq jpfgs keqi a mzwbi
image::red-blue-squares.svg[pdfwidth=70mm]

Ozmxq jpfgs, at nyl, plcc, keqi a mzwbi. Klhcg = 70mm. Ixujk bwadmi of "<<jpfgs-keqi-bwadmi-pob-mzwbi>>".

<<<

// At nyl, jpfgs, befz mzwbi
.Kpze is a ozmxq jpfgs keqi a txef befz mzwbi. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. *Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze is ifig rthbkgt.* Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of mzwbi.
image::red-blue-squares.svg[pdfwidth=30mm]

#Ozmxq jpfgs, at nyl, plcc, keqi a befz mzwbi. Klhcg = 30mm.#
