description = "Anchor: a pool document cut down and sanitized."
source = "pool:capture-asciidoctor-2.0.26/lists_test.rb:5415.1"
formats = ["manpage"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = ""
