description = "Anchor: a pool document cut down and sanitized."
source = "pool:asciidoc-docs/docs/modules/lists/examples/complex.adoc"
formats = ["manpage"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
