description = "Anchor: a pool document cut down and sanitized."
source = "pool:capture-asciidoctor-main/attributes_test.rb:611.2"
formats = ["docbook5"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"toc" = "header"
"linkcss" = ""
