/// Generates `lib/src/pdf/hyphenation.g.dart` from `vendor/hyph-utf8`:
/// each language's patterns and exceptions (zlib-compressed) and its
/// hyphenmins, embedded so the PDF backend reads no files of its own.
/// Run from the repository root (`tool/vendor_hyph_utf8.sh` runs it):
///
/// ```sh
/// dart run tool/embed_hyphenation.dart
/// ```
library;

import 'dart:convert';
import 'dart:io';

import 'package:plain_compression/plain_compression.dart' show zlibEncode;

void main() {
  final root = File(Platform.script.toFilePath()).parent.parent;
  final vendor = Directory('${root.path}/vendor/hyph-utf8');
  final languages = jsonDecode(
    File('${vendor.path}/languages.json').readAsStringSync(),
  ) as Map<String, Object?>;
  String pack(File file) => file.existsSync()
      ? base64Encode(zlibEncode(file.readAsBytesSync(), level: 9))
      : '';
  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by `dart run tool/embed_hyphenation.dart`.')
    ..writeln(
      '// Source: `vendor/hyph-utf8` (${languages.length} languages; '
      'licences in vendor/hyph-utf8/NOTICES.md).',
    )
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// The hyphenation patterns of hyph-utf8, by language tag.')
    ..writeln('library;')
    ..writeln()
    ..writeln(
      '/// Each language: its hyphenmins (left, right), its patterns and',
    )
    ..writeln('/// exceptions (zlib-compressed, base64).')
    ..writeln(
      'const Map<String, (int, int, String, String)> hyphenationPatterns = {',
    );
  for (final MapEntry(key: tag, :value) in languages.entries) {
    final info = value! as Map<String, Object?>;
    out.writeln(
      "  '$tag': (${info['left']}, ${info['right']}, "
      "'${pack(File('${vendor.path}/patterns/$tag.pat.txt'))}', "
      "'${pack(File('${vendor.path}/patterns/$tag.hyp.txt'))}'),",
    );
  }
  out.writeln('};');
  File('${root.path}/lib/src/pdf/hyphenation.g.dart')
      .writeAsStringSync(out.toString());
  stdout.writeln('embed_hyphenation: ${languages.length} languages');
}
