description = "Anchor: a pool document cut down and sanitized."
source = "pool:asciidoctor-pdf/spec/fixtures/arrange-block-at-top-does-not-fit.adoc"
formats = ["pdf"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
