description = "Anchor: a pool document cut down and sanitized."
source = "pool:asciidoctor.js/packages/core/test/fixtures/semantic-html5-scenarios/image-inline-with-align.adoc"
formats = ["pdf"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
