/// Generates `lib/src/epub3/assets.g.dart` from `vendor/asciidoctor-epub3`:
/// the stylesheets, fonts, images and icon map the EPUB3 backend writes
/// into every EPUB, embedded so the backend never reads files of its own at
/// conversion time. Run from the repository root (`tool/vendor_epub3.sh`
/// runs it):
///
/// ```sh
/// dart run tool/embed_epub3.dart
/// ```
library;

import 'dart:convert';
import 'dart:io';

void main() {
  final root = File(Platform.script.toFilePath()).parent.parent;
  final vendor = Directory('${root.path}/vendor/asciidoctor-epub3');
  if (!vendor.existsSync()) {
    stderr.writeln('embed_epub3: ${vendor.path} not found');
    exitCode = 1;
    return;
  }
  final files = [
    for (final dir in ['styles', 'fonts', 'images'])
      ...Directory('${vendor.path}/$dir')
          .listSync(recursive: true)
          .whereType<File>(),
  ]..sort((a, b) => a.path.compareTo(b.path));

  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by `dart run tool/embed_epub3.dart`.')
    ..writeln('// Source: `vendor/asciidoctor-epub3` (${files.length} files).')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// The asciidoctor-epub3 data the EPUB3 backend embeds.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'dart:convert';")
    ..writeln()
    ..writeln('/// The files of asciidoctor-epub3 the EPUB3 backend writes, by')
    ..writeln('/// path relative to its `data/` directory (`fonts/x.ttf`).')
    ..writeln('abstract final class Epub3Assets {')
    ..writeln('  /// The bytes of the file at [path], or `null`.')
    ..writeln('  static List<int>? bytes(String path) {')
    ..writeln('    final encoded = _files[path];')
    ..writeln('    return encoded == null ? null : base64Decode(encoded);')
    ..writeln('  }')
    ..writeln()
    ..writeln('  /// The text of the file at [path] (UTF-8), or `null`.')
    ..writeln('  static String? text(String path) {')
    ..writeln('    final content = bytes(path);')
    ..writeln('    return content == null ? null : utf8.decode(content);')
    ..writeln('  }')
    ..writeln()
    ..writeln('  static const Map<String, String> _files = {');
  for (final file in files) {
    final path = file.path.substring(vendor.path.length + 1);
    final encoded = base64Encode(file.readAsBytesSync());
    out.writeln("    '$path':");
    for (var i = 0; i < encoded.length; i += 4000) {
      final end = i + 4000 < encoded.length ? i + 4000 : encoded.length;
      final last = end == encoded.length;
      out.writeln("        '${encoded.substring(i, end)}'${last ? ',' : ''}");
    }
  }
  out
    ..writeln('  };')
    ..writeln('}');
  File('${root.path}/lib/src/epub3/assets.g.dart')
      .writeAsStringSync(out.toString());
  stdout.writeln('embed_epub3: ${files.length} files');
}
