/// Generates `lib/src/data.g.dart` from the repository `data/` directory.
///
/// The Dart port embeds `data/locale/*.adoc` and `data/stylesheets/*` as
/// compile-time string constants so converted documents and stylesheets never
/// depend on runtime file lookup. Run from the `dart/` directory:
///
/// ```sh
/// dart run tool/embed_data.dart
/// ```
///
/// See `README.md` ("Regenerating the embedded data") for details.
library;

import 'dart:convert';
import 'dart:io';

/// Subdirectories of `data/` to embed, mapped to the filename filter applied
/// within each (a file is embedded when its name ends with the filter, or when
/// the filter is empty).
const Map<String, String> _embeddedDirs = {
  'locale': '.adoc',
  'stylesheets': '',
};

void main() {
  final scriptFile = File(Platform.script.toFilePath());
  // tool/embed_data.dart -> tool/ -> repo root
  final repoRoot = scriptFile.parent.parent;
  final dataDir = Directory('${repoRoot.path}/data');
  if (!dataDir.existsSync()) {
    stderr.writeln('embed_data: data/ directory not found: ${dataDir.path}');
    exitCode = 1;
    return;
  }

  final entries = <String, List<int>>{};
  for (final MapEntry(key: dirName, value: suffix) in _embeddedDirs.entries) {
    final dir = Directory('${dataDir.path}/$dirName');
    if (!dir.existsSync()) {
      stderr.writeln('embed_data: directory not found: ${dir.path}');
      exitCode = 1;
      return;
    }
    final files =
        dir
            .listSync()
            .whereType<File>()
            .where((file) => _basename(file.path).endsWith(suffix))
            .toList()
          ..sort((a, b) => _basename(a.path).compareTo(_basename(b.path)));
    for (final file in files) {
      entries['$dirName/${_basename(file.path)}'] = file.readAsBytesSync();
    }
  }

  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by `dart run tool/embed_data.dart`.')
    ..writeln(
      '// Source: the repository `data/` directory '
      '(${entries.length} files).',
    )
    ..writeln('library;')
    ..writeln()
    ..writeln('/// Compile-time embedded copies of the `data/` files.')
    ..writeln('///')
    ..writeln(
      '/// Keys are paths relative to `data/` using `/` separators '
      '(e.g.',
    )
    ..writeln(
      '/// `locale/attributes-en.adoc`). Values are byte-identical to '
      'the',
    )
    ..writeln('/// source files; see `test/stylesheets_test.dart`.')
    ..writeln('abstract final class EmbeddedData {')
    ..writeln('  /// All embedded files by path relative to `data/`.')
    ..writeln('  static const Map<String, String> files = {');

  for (final MapEntry(key: key, value: bytes) in entries.entries) {
    out.writeln("    '$key':");
    final chunks = _encode(utf8.decode(bytes)).toList();
    if (chunks.isEmpty) {
      out.writeln("        '',");
    } else {
      for (var i = 0; i < chunks.length; i++) {
        out.writeln(
          "        '${chunks[i]}'${i == chunks.length - 1 ? ',' : ''}",
        );
      }
    }
  }

  out
    ..writeln('  };')
    ..writeln()
    ..writeln(
      '  /// Returns the embedded contents of the file at '
      '[relativePath]',
    )
    ..writeln('  /// (e.g. `locale/attributes-en.adoc`).')
    ..writeln(
      '  static String file(String relativePath) => '
      'files[relativePath]!;',
    )
    ..writeln('}');

  final target = File('${repoRoot.path}/lib/src/data.g.dart');
  target.writeAsStringSync(out.toString());
  // ignore: avoid_print
  print('embed_data: wrote ${target.path} (${entries.length} files)');
}

/// Splits [content] into escaped single-quoted-literal chunks, one per source
/// line. Concatenating the chunks reproduces [content] exactly.
Iterable<String> _encode(String content) sync* {
  final chunk = StringBuffer();
  for (final rune in content.runes) {
    chunk.write(_escapeRune(rune));
    if (rune == 0x0a) {
      yield chunk.toString();
      chunk.clear();
    }
  }
  if (chunk.isNotEmpty) {
    yield chunk.toString();
  }
}

String _escapeRune(int rune) {
  switch (rune) {
    case 0x09:
      return r'\t';
    case 0x0a:
      return r'\n';
    case 0x0d:
      return r'\r';
    case 0x24:
      return r'\$';
    case 0x27:
      return r"\'";
    case 0x5c:
      return r'\\';
    default:
      if (rune >= 0x20 && rune <= 0x7e) {
        return String.fromCharCode(rune);
      }
      if (rune <= 0xff) {
        return '\\x${rune.toRadixString(16).padLeft(2, '0')}';
      }
      if (rune <= 0xffff) {
        return '\\u${rune.toRadixString(16).padLeft(4, '0')}';
      }
      return '\\u{${rune.toRadixString(16)}}';
  }
}

String _basename(String path) => path.replaceAll(r'\', '/').split('/').last;
