/// Generates `lib/src/data.g.dart` from the vendored `data/` directory
/// (`vendor/asciidoctor/data`), and
/// `lib/src/cli/help_topics.g.dart` from `man/ptome.1` and
/// `vendor/asciidoctor/data/reference/syntax.adoc`.
///
/// The Dart port embeds `data/locale/*.adoc` and `data/stylesheets/*` as
/// compile-time string constants so converted documents and stylesheets never
/// depend on runtime file lookup, and embeds the `-h` topic files so
/// `-h manpage`/`-h syntax` work outside a checkout. Run from the repository
/// root:
///
/// ```sh
/// dart run tool/embed_data.dart
/// ```
///
/// See `CONTRIBUTING.md` ("Embedded data") for details.
library;

import 'dart:convert';
import 'dart:io';

/// Subdirectories of `data/` to embed, mapped to the filename filter applied
/// within each (a file is embedded when its name ends with the filter, or when
/// the filter is empty).
const Map<String, String> _embeddedDirs = {
  'locale': '.adoc',
  'stylesheets': '',
};

void main() {
  final scriptFile = File(Platform.script.toFilePath());
  // tool/embed_data.dart -> tool/ -> repo root
  final repoRoot = scriptFile.parent.parent;
  final dataDir = Directory('${repoRoot.path}/vendor/asciidoctor/data');
  if (!dataDir.existsSync()) {
    stderr.writeln('embed_data: data directory not found: ${dataDir.path}');
    exitCode = 1;
    return;
  }

  final entries = <String, List<int>>{};
  for (final MapEntry(key: dirName, value: suffix) in _embeddedDirs.entries) {
    final dir = Directory('${dataDir.path}/$dirName');
    if (!dir.existsSync()) {
      stderr.writeln('embed_data: directory not found: ${dir.path}');
      exitCode = 1;
      return;
    }
    final files =
        dir
            .listSync()
            .whereType<File>()
            .where((file) => _basename(file.path).endsWith(suffix))
            .toList()
          ..sort((a, b) => _basename(a.path).compareTo(_basename(b.path)));
    for (final file in files) {
      entries['$dirName/${_basename(file.path)}'] = file.readAsBytesSync();
    }
  }

  // Ptome's own stylesheets (the house style, ADR-0011), beside
  // Asciidoctor's.
  final own = Directory('${repoRoot.path}/data/stylesheets');
  if (own.existsSync()) {
    final files = own.listSync().whereType<File>().toList()
      ..sort((a, b) => _basename(a.path).compareTo(_basename(b.path)));
    for (final file in files) {
      entries['stylesheets/${_basename(file.path)}'] = file.readAsBytesSync();
    }
  }

  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by `dart run tool/embed_data.dart`.')
    ..writeln(
      '// Source: `vendor/asciidoctor/data` and `data/` '
      '(${entries.length} files).',
    )
    ..writeln('library;')
    ..writeln()
    ..writeln('/// Compile-time embedded copies of the `data/` files.')
    ..writeln('///')
    ..writeln(
      '/// Keys are paths relative to `data/` using `/` separators '
      '(e.g.',
    )
    ..writeln(
      '/// `locale/attributes-en.adoc`). Values are byte-identical to '
      'the',
    )
    ..writeln('/// source files; see `test/stylesheets_test.dart`.')
    ..writeln('abstract final class EmbeddedData {')
    ..writeln('  /// All embedded files by path relative to `data/`.')
    ..writeln('  static const Map<String, String> files = {');

  for (final MapEntry(:key, value: bytes) in entries.entries) {
    out.writeln("    '$key':");
    final chunks = _encode(utf8.decode(bytes)).toList();
    if (chunks.isEmpty) {
      out.writeln("        '',");
    } else {
      for (var i = 0; i < chunks.length; i++) {
        out.writeln(
          "        '${chunks[i]}'${i == chunks.length - 1 ? ',' : ''}",
        );
      }
    }
  }

  out
    ..writeln('  };')
    ..writeln()
    ..writeln(
      '  /// Returns the embedded contents of the file at '
      '[relativePath]',
    )
    ..writeln('  /// (e.g. `locale/attributes-en.adoc`).')
    ..writeln(
      '  static String file(String relativePath) => '
      'files[relativePath]!;',
    )
    ..writeln('}');

  final target = (File('${repoRoot.path}/lib/src/data.g.dart'))
    ..writeAsStringSync(out.toString());
  stdout.writeln('embed_data: wrote ${target.path} (${entries.length} files)');

  _writeHelpTopics(repoRoot);
}

/// The `-h` topic files embedded in `help_topics.g.dart`, as
/// (constant name, path relative to the repository root).
const List<(String, String)> _helpTopics = [
  ('manpage', 'man/ptome.1'),
  ('syntax', 'vendor/asciidoctor/data/reference/syntax.adoc'),
];

void _writeHelpTopics(Directory repoRoot) {
  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated from `man/ptome.1` and')
    ..writeln('// `vendor/asciidoctor/data/reference/syntax.adoc` (see')
    ..writeln('// `tool/embed_data.dart` for the')
    ..writeln('// escaping rules; concatenation reproduces each file exactly).')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// Compile-time embedded copies of the `-h` topic files.')
    ..writeln('///')
    ..writeln('/// Used as a fallback when the checkout files cannot be found')
    ..writeln('/// (e.g. a standalone executable run outside the repository);')
    ..writeln('/// see `test/cli/help_topics_test.dart`.')
    ..writeln('abstract final class HelpTopics {');
  for (final (i, (name, path)) in _helpTopics.indexed) {
    final file = File('${repoRoot.path}/$path');
    if (!file.existsSync()) {
      stderr.writeln('embed_data: help topic not found: ${file.path}');
      exitCode = 1;
      return;
    }
    if (i > 0) out.writeln();
    final description = path.endsWith('.1') ? 'troff source' : 'source';
    out
      ..writeln('  /// The `$path` $description, byte-identical.')
      ..writeln('  static const String $name =');
    final chunks = _encode(utf8.decode(file.readAsBytesSync())).toList();
    for (var c = 0; c < chunks.length; c++) {
      out.writeln("      '${chunks[c]}'${c == chunks.length - 1 ? ';' : ''}");
    }
  }
  out.writeln('}');
  final target = File('${repoRoot.path}/lib/src/cli/help_topics.g.dart')
    ..writeAsStringSync(out.toString());
  stdout.writeln(
    'embed_data: wrote ${target.path} (${_helpTopics.length} topics)',
  );
}

/// Splits [content] into escaped single-quoted-literal chunks, one per source
/// line. Concatenating the chunks reproduces [content] exactly.
Iterable<String> _encode(String content) sync* {
  final chunk = StringBuffer();
  for (final rune in content.runes) {
    chunk.write(_escapeRune(rune));
    if (rune == 0x0a) {
      yield chunk.toString();
      chunk.clear();
    }
  }
  if (chunk.isNotEmpty) {
    yield chunk.toString();
  }
}

String _escapeRune(int rune) {
  switch (rune) {
    case 0x09:
      return r'\t';
    case 0x0a:
      return r'\n';
    case 0x0d:
      return r'\r';
    case 0x24:
      return r'\$';
    case 0x27:
      return r"\'";
    case 0x5c:
      return r'\\';
    default:
      if (rune >= 0x20 && rune <= 0x7e) {
        return String.fromCharCode(rune);
      }
      if (rune <= 0xff) {
        return '\\x${rune.toRadixString(16).padLeft(2, '0')}';
      }
      if (rune <= 0xffff) {
        return '\\u${rune.toRadixString(16).padLeft(4, '0')}';
      }
      return '\\u{${rune.toRadixString(16)}}';
  }
}

String _basename(String path) => path.replaceAll(r'\', '/').split('/').last;
