/// Generates `lib/src/pdf/assets.g.dart` from `vendor/asciidoctor-pdf`:
/// the bundled themes and fonts, and the icon fonts with their name maps,
/// embedded so the PDF backend never reads files of its own at conversion
/// time. Run from the repository root (`tool/vendor_asciidoctor_pdf.sh`
/// runs it):
///
/// ```sh
/// dart run tool/embed_pdf.dart
/// ```
library;

import 'dart:convert';
import 'dart:io';

void main() {
  final root = File(Platform.script.toFilePath()).parent.parent;
  final vendor = Directory('${root.path}/vendor/asciidoctor-pdf');
  if (!vendor.existsSync()) {
    stderr.writeln('embed_pdf: ${vendor.path} not found');
    exitCode = 1;
    return;
  }
  final files = [
    for (final dir in ['data/themes', 'data/fonts', 'icons'])
      ...Directory('${vendor.path}/$dir')
          .listSync(recursive: true)
          .whereType<File>(),
  ]..sort((a, b) => a.path.compareTo(b.path));
  // asciidart's own themes (`data/pdf-themes`, the house style,
  // ADR-0011), embedded as bundled themes beside asciidoctor-pdf's.
  final own = Directory('${root.path}/data/pdf-themes');
  final ownFiles = own.existsSync()
      ? (own.listSync().whereType<File>().toList()
          ..sort((a, b) => a.path.compareTo(b.path)))
      : <File>[];

  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by `dart run tool/embed_pdf.dart`.')
    ..writeln(
      '// Source: `vendor/asciidoctor-pdf` and `data/pdf-themes` '
      '(${files.length + ownFiles.length} files).',
    )
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// The asciidoctor-pdf data the PDF backend embeds.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'dart:convert';")
    ..writeln()
    ..writeln('/// The themes, fonts and icons of asciidoctor-pdf, by path')
    ..writeln('/// relative to `vendor/asciidoctor-pdf` (`data/fonts/x.ttf`).')
    ..writeln('abstract final class PdfAssets {')
    ..writeln('  /// The bytes of the file at [path], or `null`.')
    ..writeln('  static List<int>? bytes(String path) {')
    ..writeln('    final encoded = _files[path];')
    ..writeln('    return encoded == null ? null : base64Decode(encoded);')
    ..writeln('  }')
    ..writeln()
    ..writeln('  /// The text of the file at [path] (UTF-8), or `null`.')
    ..writeln('  static String? text(String path) {')
    ..writeln('    final content = bytes(path);')
    ..writeln('    return content == null ? null : utf8.decode(content);')
    ..writeln('  }')
    ..writeln()
    ..writeln('  /// The paths of the embedded files.')
    ..writeln('  static Iterable<String> get paths => _files.keys;')
    ..writeln()
    ..writeln('  static const Map<String, String> _files = {');
  for (final file in [...files, ...ownFiles]) {
    final path = file.path.startsWith(own.path)
        ? 'data/themes/${file.path.substring(own.path.length + 1)}'
        : file.path.substring(vendor.path.length + 1);
    final encoded = base64Encode(file.readAsBytesSync());
    out.writeln("    '$path':");
    for (var i = 0; i < encoded.length; i += 4000) {
      final end = i + 4000 < encoded.length ? i + 4000 : encoded.length;
      final last = end == encoded.length;
      out.writeln("        '${encoded.substring(i, end)}'${last ? ',' : ''}");
    }
  }
  out
    ..writeln('  };')
    ..writeln('}');
  File('${root.path}/lib/src/pdf/assets.g.dart')
      .writeAsStringSync(out.toString());
  stdout.writeln('embed_pdf: ${files.length + ownFiles.length} files');
}
