# Generates lib/src/case_mapping.g.dart: Ruby's String#upcase and
# String#downcase for every non-ASCII code point they change. The port uses
# it instead of the platform's case mapping, which differs between the Dart
# VM (old Unicode tables, no special casing), JavaScript (final sigma) and
# Ruby. Run with the Ruby the parity oracle uses:
#
#   ruby tool/gen_case_mapping.rb && dart format lib/src/case_mapping.g.dart
def table(method)
  (0x80..0x10FFFF).filter_map do |cp|
    next if cp.between?(0xD800, 0xDFFF)
    char = cp.chr('UTF-8')
    mapped = char.public_send(method)
    next if mapped == char
    "#{cp.to_s(36)}:#{mapped.codepoints.map { |c| c.to_s(36) }.join(' ')}"
  end.join(',')
end

out = File.join(__dir__, '..', 'lib', 'src', 'case_mapping.g.dart')
File.write(out, <<~DART)
  // GENERATED by tool/gen_case_mapping.rb from Ruby #{RUBY_VERSION}
  // (Unicode #{RbConfig::CONFIG['UNICODE_VERSION']}). Do not edit.
  //
  // Code point and mapping in base 36: `cp:mapped mapped,...`.

  /// Ruby's `upcase` of the non-ASCII code points it changes.
  const String upcaseTable =
      '#{table(:upcase)}';

  /// Ruby's `downcase` of the non-ASCII code points it changes.
  const String downcaseTable =
      '#{table(:downcase)}';
DART
puts "wrote #{out}"
