// GENERATED by tool/generate_js.dart from the public Dart API. Do not edit.
// ignore_for_file: type=lint

/// The JavaScript projection of the public API: wrappers, conversions and
/// factories (see tool/generate_js.dart).
library;

import 'dart:async';
import 'dart:js_interop';
import 'dart:js_interop_unsafe';

import 'package:ptome/ptome.dart' as api;
import 'package:ptome/io.dart' as api;
import 'package:ptome/src/js/runtime.dart' as rt;

/// The JavaScript object for the public Dart object [o].
JSObject wrap(Object o) => switch (o) {
  api.Video() => rt.handle(o, 'Video'),
  api.Verse() => rt.handle(o, 'Verse'),
  api.UnorderedList() => rt.handle(o, 'UnorderedList'),
  api.ThematicBreak() => rt.handle(o, 'ThematicBreak'),
  api.TableOfContents() => rt.handle(o, 'TableOfContents'),
  api.TableCell() => rt.handle(o, 'TableCell'),
  api.Table() => rt.handle(o, 'Table'),
  api.Stem() => rt.handle(o, 'Stem'),
  api.Sidebar() => rt.handle(o, 'Sidebar'),
  api.Section() => rt.handle(o, 'Section'),
  api.Quote() => rt.handle(o, 'Quote'),
  api.Preamble() => rt.handle(o, 'Preamble'),
  api.Passthrough() => rt.handle(o, 'Passthrough'),
  api.Paragraph() => rt.handle(o, 'Paragraph'),
  api.PageBreak() => rt.handle(o, 'PageBreak'),
  api.OtherBlock() => rt.handle(o, 'OtherBlock'),
  api.OrderedList() => rt.handle(o, 'OrderedList'),
  api.Open() => rt.handle(o, 'Open'),
  api.Menu() => rt.handle(o, 'Menu'),
  api.Literal() => rt.handle(o, 'Literal'),
  api.Listing() => rt.handle(o, 'Listing'),
  api.ListItem() => rt.handle(o, 'ListItem'),
  api.Link() => rt.handle(o, 'Link'),
  api.LineBreak() => rt.handle(o, 'LineBreak'),
  api.Keyboard() => rt.handle(o, 'Keyboard'),
  api.InlineStem() => rt.handle(o, 'InlineStem'),
  api.InlineImage() => rt.handle(o, 'InlineImage'),
  api.InlineAnchor() => rt.handle(o, 'InlineAnchor'),
  api.IndexTerm() => rt.handle(o, 'IndexTerm'),
  api.Image() => rt.handle(o, 'Image'),
  api.Icon() => rt.handle(o, 'Icon'),
  api.Formatted() => rt.handle(o, 'Formatted'),
  api.Footnote() => rt.handle(o, 'Footnote'),
  api.Example() => rt.handle(o, 'Example'),
  api.Document() => rt.handle(o, 'Document'),
  api.DiscreteHeading() => rt.handle(o, 'DiscreteHeading'),
  api.DescriptionList() => rt.handle(o, 'DescriptionList'),
  api.CrossReference() => rt.handle(o, 'CrossReference'),
  api.CalloutList() => rt.handle(o, 'CalloutList'),
  api.Callout() => rt.handle(o, 'Callout'),
  api.Button() => rt.handle(o, 'Button'),
  api.BibliographyAnchor() => rt.handle(o, 'BibliographyAnchor'),
  api.Audio() => rt.handle(o, 'Audio'),
  api.Admonition() => rt.handle(o, 'Admonition'),
  api.TreeProcessor() => rt.handle(o, 'TreeProcessor'),
  api.Preprocessor() => rt.handle(o, 'Preprocessor'),
  api.Postprocessor() => rt.handle(o, 'Postprocessor'),
  api.InlineMacro() => rt.handle(o, 'InlineMacro'),
  api.IncludeResolver() => rt.handle(o, 'IncludeResolver'),
  api.Docinfo() => rt.handle(o, 'Docinfo'),
  api.CustomBlock() => rt.handle(o, 'CustomBlock'),
  api.BlockMacro() => rt.handle(o, 'BlockMacro'),
  api.TableColumn() => rt.handle(o, 'TableColumn'),
  api.SourceLocation() => rt.handle(o, 'SourceLocation'),
  api.SourceCode() => rt.handle(o, 'SourceCode'),
  api.Ptome() => rt.handle(o, 'Ptome'),
  api.InlineText() => rt.handle(o, 'InlineText'),
  api.InlineMacroContext() => rt.handle(o, 'InlineMacroContext'),
  api.IndexLetter() => rt.handle(o, 'IndexLetter'),
  api.IndexEntry() => rt.handle(o, 'IndexEntry'),
  api.IncludeRequest() => rt.handle(o, 'IncludeRequest'),
  api.HtmlDefaults() => rt.handle(o, 'HtmlDefaults'),
  api.FontFile() => rt.handle(o, 'FontFile'),
  api.FileConversion() => rt.handle(o, 'FileConversion'),
  api.Diagnostic() => rt.handle(o, 'Diagnostic'),
  api.DescriptionListEntry() => rt.handle(o, 'DescriptionListEntry'),
  api.CustomBlockContext() => rt.handle(o, 'CustomBlockContext'),
  api.BlockMacroContext() => rt.handle(o, 'BlockMacroContext'),
  api.Author() => rt.handle(o, 'Author'),
  api.Attributes() => rt.handle(o, 'Attributes'),
  _HighlighterFromJs(:final js) => js,
  _ => throw ArgumentError(
    'no JavaScript projection for '
    '${o.runtimeType}',
  ),
};

/// The Dart [Highlighter] for a JavaScript object: a projected Dart object, or
/// an object implementing it in JavaScript.
api.Highlighter unwrapHighlighter(JSAny? value) {
  return rt.tryUnwrap<api.Highlighter>(value) ??
      _HighlighterFromJs(value! as JSObject);
}

final class _HighlighterFromJs extends api.Highlighter {
  _HighlighterFromJs(this.js);
  final JSObject js;
  @override
  String? get head => js.has('head')
      ? (rt.isMissing(js['head']) ? null : rt.str(js['head']))
      : super.head;
  @override
  String? get footer => js.has('footer')
      ? (rt.isMissing(js['footer']) ? null : rt.str(js['footer']))
      : super.footer;
  @override
  String highlight(api.SourceCode code) =>
      rt.str(rt.invokeMethod(js, 'highlight', [wrap(code)]));
}

/// The object the npm package calls into.
@JSExport()
final class Core {
  JSAny? describe(JSAny? self) {
    try {
      return rt.unwrap<Object>(self).toString().toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Attributes$get$names(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Attributes>(self).names) x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Attributes$get(JSAny? self, JSAny? name) {
    try {
      return ((rt.unwrap<api.Attributes>(self)[rt.str(name)]) == null
          ? null
          : (rt.unwrap<api.Attributes>(self)[rt.str(name)])!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Attributes$set(JSAny? self, JSAny? name, JSAny? value) {
    try {
      return (() {
        (rt.unwrap<api.Attributes>(self)[rt.str(name)] = rt.str(value));
        return null;
      })();
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Attributes$remove(JSAny? self, JSAny? name) {
    try {
      return ((rt.unwrap<api.Attributes>(self).remove(rt.str(name))) == null
          ? null
          : (rt.unwrap<api.Attributes>(self).remove(rt.str(name)))!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Attributes$has(JSAny? self, JSAny? name) {
    try {
      return rt.unwrap<api.Attributes>(self).has(rt.str(name)).toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Attributes$intValue(JSAny? self, JSAny? name) {
    try {
      return ((rt.unwrap<api.Attributes>(self).intValue(rt.str(name))) == null
          ? null
          : (rt.unwrap<api.Attributes>(self).intValue(rt.str(name)))!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Attributes$listValue(JSAny? self, JSAny? name) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Attributes>(self).listValue(rt.str(name)))
          x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Attributes$toMap(JSAny? self) {
    try {
      return rt.jsObject({
        for (final e in rt.unwrap<api.Attributes>(self).toMap().entries)
          e.key: e.value.toJS,
      });
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Author$get$name(JSAny? self) {
    try {
      return ((rt.unwrap<api.Author>(self).name) == null
          ? null
          : (rt.unwrap<api.Author>(self).name)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Author$get$email(JSAny? self) {
    try {
      return ((rt.unwrap<api.Author>(self).email) == null
          ? null
          : (rt.unwrap<api.Author>(self).email)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Author$get$firstName(JSAny? self) {
    try {
      return ((rt.unwrap<api.Author>(self).firstName) == null
          ? null
          : (rt.unwrap<api.Author>(self).firstName)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Author$get$middleName(JSAny? self) {
    try {
      return ((rt.unwrap<api.Author>(self).middleName) == null
          ? null
          : (rt.unwrap<api.Author>(self).middleName)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Author$get$lastName(JSAny? self) {
    try {
      return ((rt.unwrap<api.Author>(self).lastName) == null
          ? null
          : (rt.unwrap<api.Author>(self).lastName)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacroContext$get$target(JSAny? self) {
    try {
      return rt.unwrap<api.BlockMacroContext>(self).target.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacroContext$get$attributes(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.BlockMacroContext>(self).attributes);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacroContext$get$parent(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.BlockMacroContext>(self).parent);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacroContext$get$document(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.BlockMacroContext>(self).document);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacroContext$paragraph(
    JSAny? self,
    JSAny? text, [
    JSAny? options,
  ]) {
    try {
      return wrap(
        rt
            .unwrap<api.BlockMacroContext>(self)
            .paragraph(
              rt.str(text),
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacroContext$html(JSAny? self, JSAny? html) {
    try {
      return wrap(rt.unwrap<api.BlockMacroContext>(self).html(rt.str(html)));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacroContext$listing(
    JSAny? self,
    JSAny? source, [
    JSAny? options,
  ]) {
    try {
      return wrap(
        rt
            .unwrap<api.BlockMacroContext>(self)
            .listing(
              rt.str(source),
              language: rt.hasOption(options, 'language')
                  ? (rt.isMissing(rt.option(options, 'language'))
                        ? null
                        : rt.str(rt.option(options, 'language')))
                  : null,
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacroContext$image(JSAny? self, JSAny? target, [JSAny? options]) {
    try {
      return wrap(
        rt
            .unwrap<api.BlockMacroContext>(self)
            .image(
              rt.str(target),
              alt: rt.hasOption(options, 'alt')
                  ? (rt.isMissing(rt.option(options, 'alt'))
                        ? null
                        : rt.str(rt.option(options, 'alt')))
                  : null,
              title: rt.hasOption(options, 'title')
                  ? (rt.isMissing(rt.option(options, 'title'))
                        ? null
                        : rt.str(rt.option(options, 'title')))
                  : null,
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacroContext$asciidoc(JSAny? self, JSAny? source) {
    try {
      return wrap(
        rt.unwrap<api.BlockMacroContext>(self).asciidoc(rt.str(source)),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$get$lines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.CustomBlockContext>(self).lines) x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.CustomBlockContext>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$get$attributes(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.CustomBlockContext>(self).attributes);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$get$parent(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.CustomBlockContext>(self).parent);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$get$document(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.CustomBlockContext>(self).document);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$paragraph(
    JSAny? self,
    JSAny? text, [
    JSAny? options,
  ]) {
    try {
      return wrap(
        rt
            .unwrap<api.CustomBlockContext>(self)
            .paragraph(
              rt.str(text),
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$html(JSAny? self, JSAny? html) {
    try {
      return wrap(rt.unwrap<api.CustomBlockContext>(self).html(rt.str(html)));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$listing(
    JSAny? self,
    JSAny? source, [
    JSAny? options,
  ]) {
    try {
      return wrap(
        rt
            .unwrap<api.CustomBlockContext>(self)
            .listing(
              rt.str(source),
              language: rt.hasOption(options, 'language')
                  ? (rt.isMissing(rt.option(options, 'language'))
                        ? null
                        : rt.str(rt.option(options, 'language')))
                  : null,
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$image(
    JSAny? self,
    JSAny? target, [
    JSAny? options,
  ]) {
    try {
      return wrap(
        rt
            .unwrap<api.CustomBlockContext>(self)
            .image(
              rt.str(target),
              alt: rt.hasOption(options, 'alt')
                  ? (rt.isMissing(rt.option(options, 'alt'))
                        ? null
                        : rt.str(rt.option(options, 'alt')))
                  : null,
              title: rt.hasOption(options, 'title')
                  ? (rt.isMissing(rt.option(options, 'title'))
                        ? null
                        : rt.str(rt.option(options, 'title')))
                  : null,
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlockContext$asciidoc(JSAny? self, JSAny? source) {
    try {
      return wrap(
        rt.unwrap<api.CustomBlockContext>(self).asciidoc(rt.str(source)),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? DescriptionListEntry$get$terms(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.DescriptionListEntry>(self).terms)
          wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? DescriptionListEntry$get$description(JSAny? self) {
    try {
      return ((rt.unwrap<api.DescriptionListEntry>(self).description) == null
          ? null
          : wrap((rt.unwrap<api.DescriptionListEntry>(self).description)!));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Diagnostic$get$severity(JSAny? self) {
    try {
      return rt.unwrap<api.Diagnostic>(self).severity.name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Diagnostic$get$message(JSAny? self) {
    try {
      return rt.unwrap<api.Diagnostic>(self).message.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Diagnostic$get$code(JSAny? self) {
    try {
      return rt.unwrap<api.Diagnostic>(self).code.name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Diagnostic$get$location(JSAny? self) {
    try {
      return ((rt.unwrap<api.Diagnostic>(self).location) == null
          ? null
          : wrap((rt.unwrap<api.Diagnostic>(self).location)!));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? FileConversion$get$inputPath(JSAny? self) {
    try {
      return rt.unwrap<api.FileConversion>(self).inputPath.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? FileConversion$get$outputPath(JSAny? self) {
    try {
      return rt.unwrap<api.FileConversion>(self).outputPath.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? FileConversion$get$document(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.FileConversion>(self).document);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? FontFile$get$name(JSAny? self) {
    try {
      return rt.unwrap<api.FontFile>(self).name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? FontFile$get$bytes(JSAny? self) {
    try {
      return rt.jsBytes(rt.unwrap<api.FontFile>(self).bytes);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? HtmlDefaults$render(JSAny? self, JSAny? node) {
    try {
      return rt
          .unwrap<api.HtmlDefaults>(self)
          .render(rt.unwrap<api.Node>(node))
          .toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? HtmlDefaults$content(JSAny? self, JSAny? block) {
    try {
      return rt
          .unwrap<api.HtmlDefaults>(self)
          .content(rt.unwrap<api.Block>(block))
          .toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IncludeRequest$get$target(JSAny? self) {
    try {
      return rt.unwrap<api.IncludeRequest>(self).target.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IncludeRequest$get$document(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.IncludeRequest>(self).document);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IndexEntry$get$term(JSAny? self) {
    try {
      return rt.unwrap<api.IndexEntry>(self).term.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IndexEntry$get$uses(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.IndexEntry>(self).uses) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IndexEntry$get$see(JSAny? self) {
    try {
      return ((rt.unwrap<api.IndexEntry>(self).see) == null
          ? null
          : (rt.unwrap<api.IndexEntry>(self).see)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IndexEntry$get$seeAlso(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.IndexEntry>(self).seeAlso) x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IndexEntry$get$subentries(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.IndexEntry>(self).subentries) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IndexLetter$get$letter(JSAny? self) {
    try {
      return rt.unwrap<api.IndexLetter>(self).letter.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IndexLetter$get$entries(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.IndexLetter>(self).entries) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacroContext$get$target(JSAny? self) {
    try {
      return rt.unwrap<api.InlineMacroContext>(self).target.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacroContext$get$attributes(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.InlineMacroContext>(self).attributes);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacroContext$get$text(JSAny? self) {
    try {
      return ((rt.unwrap<api.InlineMacroContext>(self).text) == null
          ? null
          : (rt.unwrap<api.InlineMacroContext>(self).text)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacroContext$get$parent(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.InlineMacroContext>(self).parent);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacroContext$get$document(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.InlineMacroContext>(self).document);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacroContext$link(JSAny? self, JSAny? url, [JSAny? options]) {
    try {
      return wrap(
        rt
            .unwrap<api.InlineMacroContext>(self)
            .link(
              rt.str(url),
              text: rt.hasOption(options, 'text')
                  ? (rt.isMissing(rt.option(options, 'text'))
                        ? null
                        : rt.str(rt.option(options, 'text')))
                  : null,
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacroContext$html(JSAny? self, JSAny? html) {
    try {
      return wrap(rt.unwrap<api.InlineMacroContext>(self).html(rt.str(html)));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacroContext$formatted(JSAny? self, JSAny? text, JSAny? kind) {
    try {
      return wrap(
        rt
            .unwrap<api.InlineMacroContext>(self)
            .formatted(
              rt.str(text),
              api.FormattedKind.values.byName(rt.str(kind)),
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineText$get$html(JSAny? self) {
    try {
      return rt.unwrap<api.InlineText>(self).html.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineText$get$text(JSAny? self) {
    try {
      return rt.unwrap<api.InlineText>(self).text.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Node$get$parent(JSAny? self) {
    try {
      return ((rt.unwrap<api.Node>(self).parent) == null
          ? null
          : wrap((rt.unwrap<api.Node>(self).parent)!));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Node$get$document(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.Node>(self).document);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Node$get$id(JSAny? self) {
    try {
      return ((rt.unwrap<api.Node>(self).id) == null
          ? null
          : (rt.unwrap<api.Node>(self).id)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  void Node$set$id(JSAny? self, JSAny? value) {
    try {
      rt.unwrap<api.Node>(self).id = (rt.isMissing(value)
          ? null
          : rt.str(value));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Node$get$roles(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Node>(self).roles) x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Node$get$attributes(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.Node>(self).attributes);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Node$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Node>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Node$hasOption(JSAny? self, JSAny? name) {
    try {
      return rt.unwrap<api.Node>(self).hasOption(rt.str(name)).toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$safe(JSAny? self) {
    try {
      return rt.unwrap<api.Ptome>(self).safe.name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$attributes(JSAny? self) {
    try {
      return rt.jsObject({
        for (final e in rt.unwrap<api.Ptome>(self).attributes.entries)
          e.key: e.value.toJS,
      });
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$extensions(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Ptome>(self).extensions) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$html(JSAny? self) {
    try {
      return ((rt.unwrap<api.Ptome>(self).html) == null
          ? null
          : ((String Function(api.Node, api.HtmlDefaults) _f) =>
                ((JSAny? a0, JSAny? a1) => _f(
                  rt.unwrap<api.Node>(a0),
                  rt.unwrap<api.HtmlDefaults>(a1),
                ).toJS).toJS)((rt.unwrap<api.Ptome>(self).html)!));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$templateDirs(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Ptome>(self).templateDirs) x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$highlighters(JSAny? self) {
    try {
      return rt.jsObject({
        for (final e in rt.unwrap<api.Ptome>(self).highlighters.entries)
          e.key: wrap(e.value),
      });
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$baseDir(JSAny? self) {
    try {
      return ((rt.unwrap<api.Ptome>(self).baseDir) == null
          ? null
          : (rt.unwrap<api.Ptome>(self).baseDir)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$onDiagnostic(JSAny? self) {
    try {
      return ((rt.unwrap<api.Ptome>(self).onDiagnostic) == null
          ? null
          : ((void Function(api.Diagnostic) _f) => ((JSAny? a0) => (() {
              _f(rt.unwrap<api.Diagnostic>(a0));
              return null;
            })()).toJS)((rt.unwrap<api.Ptome>(self).onDiagnostic)!));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$fonts(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Ptome>(self).fonts) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$pageFonts(JSAny? self) {
    try {
      return rt.unwrap<api.Ptome>(self).pageFonts.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$get$localFonts(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Ptome>(self).localFonts) x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$loadBackend(JSAny? self, JSAny? backend) {
    try {
      return rt.promise(
        rt
            .unwrap<api.Ptome>(self)
            .loadBackend(api.Backend.values.byName(rt.str(backend))),
        (x) => (() {
          x;
          return null;
        })(),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$convertToBytes(JSAny? self, JSAny? source, [JSAny? options]) {
    try {
      return rt.jsBytes(
        rt
            .unwrap<api.Ptome>(self)
            .convertToBytes(
              rt.str(source),
              backend: api.Backend.values.byName(
                rt.str(rt.option(options, 'backend')),
              ),
              path: rt.hasOption(options, 'path')
                  ? (rt.isMissing(rt.option(options, 'path'))
                        ? null
                        : rt.str(rt.option(options, 'path')))
                  : null,
              doctype: rt.hasOption(options, 'doctype')
                  ? (rt.isMissing(rt.option(options, 'doctype'))
                        ? null
                        : api.Doctype.values.byName(
                            rt.str(rt.option(options, 'doctype')),
                          ))
                  : null,
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$convertToBytesAsync(
    JSAny? self,
    JSAny? source, [
    JSAny? options,
  ]) {
    try {
      return rt.promise(
        rt
            .unwrap<api.Ptome>(self)
            .convertToBytesAsync(
              rt.str(source),
              backend: api.Backend.values.byName(
                rt.str(rt.option(options, 'backend')),
              ),
              path: rt.hasOption(options, 'path')
                  ? (rt.isMissing(rt.option(options, 'path'))
                        ? null
                        : rt.str(rt.option(options, 'path')))
                  : null,
              doctype: rt.hasOption(options, 'doctype')
                  ? (rt.isMissing(rt.option(options, 'doctype'))
                        ? null
                        : api.Doctype.values.byName(
                            rt.str(rt.option(options, 'doctype')),
                          ))
                  : null,
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
        (x) => rt.jsBytes(x),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$parse(JSAny? self, JSAny? source, [JSAny? options]) {
    try {
      return wrap(
        rt
            .unwrap<api.Ptome>(self)
            .parse(
              rt.str(source),
              path: rt.hasOption(options, 'path')
                  ? (rt.isMissing(rt.option(options, 'path'))
                        ? null
                        : rt.str(rt.option(options, 'path')))
                  : null,
              backend: rt.hasOption(options, 'backend')
                  ? api.Backend.values.byName(
                      rt.str(rt.option(options, 'backend')),
                    )
                  : api.Backend.html5,
              doctype: rt.hasOption(options, 'doctype')
                  ? (rt.isMissing(rt.option(options, 'doctype'))
                        ? null
                        : api.Doctype.values.byName(
                            rt.str(rt.option(options, 'doctype')),
                          ))
                  : null,
              standalone: rt.hasOption(options, 'standalone')
                  ? rt.boolean(rt.option(options, 'standalone'))
                  : false,
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$parseHeader(JSAny? self, JSAny? source, [JSAny? options]) {
    try {
      return wrap(
        rt
            .unwrap<api.Ptome>(self)
            .parseHeader(
              rt.str(source),
              path: rt.hasOption(options, 'path')
                  ? (rt.isMissing(rt.option(options, 'path'))
                        ? null
                        : rt.str(rt.option(options, 'path')))
                  : null,
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$convert(JSAny? self, JSAny? source, [JSAny? options]) {
    try {
      return rt
          .unwrap<api.Ptome>(self)
          .convert(
            rt.str(source),
            path: rt.hasOption(options, 'path')
                ? (rt.isMissing(rt.option(options, 'path'))
                      ? null
                      : rt.str(rt.option(options, 'path')))
                : null,
            backend: rt.hasOption(options, 'backend')
                ? api.Backend.values.byName(
                    rt.str(rt.option(options, 'backend')),
                  )
                : api.Backend.html5,
            doctype: rt.hasOption(options, 'doctype')
                ? (rt.isMissing(rt.option(options, 'doctype'))
                      ? null
                      : api.Doctype.values.byName(
                          rt.str(rt.option(options, 'doctype')),
                        ))
                : null,
            standalone: rt.hasOption(options, 'standalone')
                ? rt.boolean(rt.option(options, 'standalone'))
                : false,
            attributes: rt.hasOption(options, 'attributes')
                ? {
                    for (final e in rt.entries(
                      rt.option(options, 'attributes'),
                    ))
                      e.key: rt.str(e.value),
                  }
                : const {},
          )
          .toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$parseAsync(JSAny? self, JSAny? source, [JSAny? options]) {
    try {
      return rt.promise(
        rt
            .unwrap<api.Ptome>(self)
            .parseAsync(
              rt.str(source),
              path: rt.hasOption(options, 'path')
                  ? (rt.isMissing(rt.option(options, 'path'))
                        ? null
                        : rt.str(rt.option(options, 'path')))
                  : null,
              backend: rt.hasOption(options, 'backend')
                  ? api.Backend.values.byName(
                      rt.str(rt.option(options, 'backend')),
                    )
                  : api.Backend.html5,
              doctype: rt.hasOption(options, 'doctype')
                  ? (rt.isMissing(rt.option(options, 'doctype'))
                        ? null
                        : api.Doctype.values.byName(
                            rt.str(rt.option(options, 'doctype')),
                          ))
                  : null,
              standalone: rt.hasOption(options, 'standalone')
                  ? rt.boolean(rt.option(options, 'standalone'))
                  : false,
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
        (x) => wrap(x),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$convertAsync(JSAny? self, JSAny? source, [JSAny? options]) {
    try {
      return rt.promise(
        rt
            .unwrap<api.Ptome>(self)
            .convertAsync(
              rt.str(source),
              path: rt.hasOption(options, 'path')
                  ? (rt.isMissing(rt.option(options, 'path'))
                        ? null
                        : rt.str(rt.option(options, 'path')))
                  : null,
              backend: rt.hasOption(options, 'backend')
                  ? api.Backend.values.byName(
                      rt.str(rt.option(options, 'backend')),
                    )
                  : api.Backend.html5,
              doctype: rt.hasOption(options, 'doctype')
                  ? (rt.isMissing(rt.option(options, 'doctype'))
                        ? null
                        : api.Doctype.values.byName(
                            rt.str(rt.option(options, 'doctype')),
                          ))
                  : null,
              standalone: rt.hasOption(options, 'standalone')
                  ? rt.boolean(rt.option(options, 'standalone'))
                  : false,
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
        (x) => x.toJS,
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$parseFile(JSAny? self, JSAny? path, [JSAny? options]) {
    try {
      return rt.promise(
        rt
            .unwrap<api.Ptome>(self)
            .parseFile(
              rt.str(path),
              backend: rt.hasOption(options, 'backend')
                  ? api.Backend.values.byName(
                      rt.str(rt.option(options, 'backend')),
                    )
                  : api.Backend.html5,
              doctype: rt.hasOption(options, 'doctype')
                  ? (rt.isMissing(rt.option(options, 'doctype'))
                        ? null
                        : api.Doctype.values.byName(
                            rt.str(rt.option(options, 'doctype')),
                          ))
                  : null,
              standalone: rt.hasOption(options, 'standalone')
                  ? rt.boolean(rt.option(options, 'standalone'))
                  : false,
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
        (x) => wrap(x),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$convertFile(JSAny? self, JSAny? path, [JSAny? options]) {
    try {
      return rt.promise(
        rt
            .unwrap<api.Ptome>(self)
            .convertFile(
              rt.str(path),
              toFile: rt.hasOption(options, 'toFile')
                  ? (rt.isMissing(rt.option(options, 'toFile'))
                        ? null
                        : rt.str(rt.option(options, 'toFile')))
                  : null,
              toDir: rt.hasOption(options, 'toDir')
                  ? (rt.isMissing(rt.option(options, 'toDir'))
                        ? null
                        : rt.str(rt.option(options, 'toDir')))
                  : null,
              mkdirs: rt.hasOption(options, 'mkdirs')
                  ? rt.boolean(rt.option(options, 'mkdirs'))
                  : false,
              backend: rt.hasOption(options, 'backend')
                  ? api.Backend.values.byName(
                      rt.str(rt.option(options, 'backend')),
                    )
                  : api.Backend.html5,
              doctype: rt.hasOption(options, 'doctype')
                  ? (rt.isMissing(rt.option(options, 'doctype'))
                        ? null
                        : api.Doctype.values.byName(
                            rt.str(rt.option(options, 'doctype')),
                          ))
                  : null,
              standalone: rt.hasOption(options, 'standalone')
                  ? rt.boolean(rt.option(options, 'standalone'))
                  : true,
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
        (x) => wrap(x),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Ptome$convertTree(JSAny? self, JSAny? directory, [JSAny? options]) {
    try {
      return rt.asyncIterable(
        rt
            .unwrap<api.Ptome>(self)
            .convertTree(
              rt.str(directory),
              toDir: rt.str(rt.option(options, 'toDir')),
              backend: rt.hasOption(options, 'backend')
                  ? api.Backend.values.byName(
                      rt.str(rt.option(options, 'backend')),
                    )
                  : api.Backend.html5,
              doctype: rt.hasOption(options, 'doctype')
                  ? (rt.isMissing(rt.option(options, 'doctype'))
                        ? null
                        : api.Doctype.values.byName(
                            rt.str(rt.option(options, 'doctype')),
                          ))
                  : null,
              attributes: rt.hasOption(options, 'attributes')
                  ? {
                      for (final e in rt.entries(
                        rt.option(options, 'attributes'),
                      ))
                        e.key: rt.str(e.value),
                    }
                  : const {},
            ),
        (x) => wrap(x),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? SourceCode$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.SourceCode>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? SourceCode$get$language(JSAny? self) {
    try {
      return ((rt.unwrap<api.SourceCode>(self).language) == null
          ? null
          : (rt.unwrap<api.SourceCode>(self).language)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? SourceCode$get$highlightLines(JSAny? self) {
    try {
      return rt.jsBytes(rt.unwrap<api.SourceCode>(self).highlightLines);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? SourceLocation$get$path(JSAny? self) {
    try {
      return ((rt.unwrap<api.SourceLocation>(self).path) == null
          ? null
          : (rt.unwrap<api.SourceLocation>(self).path)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? SourceLocation$get$line(JSAny? self) {
    try {
      return rt.unwrap<api.SourceLocation>(self).line.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TableColumn$get$number(JSAny? self) {
    try {
      return rt.unwrap<api.TableColumn>(self).number.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TableColumn$get$width(JSAny? self) {
    try {
      return ((rt.unwrap<api.TableColumn>(self).width) == null
          ? null
          : (rt.unwrap<api.TableColumn>(self).width)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TableColumn$get$style(JSAny? self) {
    try {
      return ((rt.unwrap<api.TableColumn>(self).style) == null
          ? null
          : (rt.unwrap<api.TableColumn>(self).style)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$get$title(JSAny? self) {
    try {
      return ((rt.unwrap<api.Block>(self).title) == null
          ? null
          : (rt.unwrap<api.Block>(self).title)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  void Block$set$title(JSAny? self, JSAny? value) {
    try {
      rt.unwrap<api.Block>(self).title = (rt.isMissing(value)
          ? null
          : rt.str(value));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$get$sourceTitle(JSAny? self) {
    try {
      return ((rt.unwrap<api.Block>(self).sourceTitle) == null
          ? null
          : (rt.unwrap<api.Block>(self).sourceTitle)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$get$style(JSAny? self) {
    try {
      return ((rt.unwrap<api.Block>(self).style) == null
          ? null
          : (rt.unwrap<api.Block>(self).style)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$get$location(JSAny? self) {
    try {
      return ((rt.unwrap<api.Block>(self).location) == null
          ? null
          : wrap((rt.unwrap<api.Block>(self).location)!));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$get$blocks(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Block>(self).blocks) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$get$titleInlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Block>(self).titleInlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Block>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$append(JSAny? self, JSAny? block) {
    try {
      return (() {
        rt.unwrap<api.Block>(self).append(rt.unwrap<api.Block>(block));
        return null;
      })();
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$remove(JSAny? self) {
    try {
      return (() {
        rt.unwrap<api.Block>(self).remove();
        return null;
      })();
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$descendants(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Block>(self).descendants<api.Node>())
          wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Block$convert(JSAny? self) {
    try {
      return rt.unwrap<api.Block>(self).convert().toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacro$get$name(JSAny? self) {
    try {
      return rt.unwrap<api.BlockMacro>(self).name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BlockMacro$get$process(JSAny? self) {
    try {
      return ((api.Block? Function(api.BlockMacroContext) _f) =>
          ((JSAny? a0) => ((_f(rt.unwrap<api.BlockMacroContext>(a0))) == null
                  ? null
                  : wrap((_f(rt.unwrap<api.BlockMacroContext>(a0)))!)))
              .toJS)(rt.unwrap<api.BlockMacro>(self).process);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlock$get$name(JSAny? self) {
    try {
      return rt.unwrap<api.CustomBlock>(self).name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlock$get$on(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.CustomBlock>(self).on) x.name.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CustomBlock$get$process(JSAny? self) {
    try {
      return ((api.Block? Function(api.CustomBlockContext) _f) =>
          ((JSAny? a0) => ((_f(rt.unwrap<api.CustomBlockContext>(a0))) == null
                  ? null
                  : wrap((_f(rt.unwrap<api.CustomBlockContext>(a0)))!)))
              .toJS)(rt.unwrap<api.CustomBlock>(self).process);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Docinfo$get$content(JSAny? self) {
    try {
      return ((String? Function(api.Document) _f) =>
          ((JSAny? a0) => ((_f(rt.unwrap<api.Document>(a0))) == null
                  ? null
                  : (_f(rt.unwrap<api.Document>(a0)))!.toJS))
              .toJS)(rt.unwrap<api.Docinfo>(self).content);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Docinfo$get$location(JSAny? self) {
    try {
      return rt.unwrap<api.Docinfo>(self).location.name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IncludeResolver$get$resolve(JSAny? self) {
    try {
      return ((FutureOr<String?> Function(api.IncludeRequest) _f) =>
          ((JSAny? a0) => rt.jsFutureOr(
            _f(rt.unwrap<api.IncludeRequest>(a0)),
            (x) => ((x) == null ? null : (x)!.toJS),
          )).toJS)(rt.unwrap<api.IncludeResolver>(self).resolve);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Inline$get$text(JSAny? self) {
    try {
      return ((rt.unwrap<api.Inline>(self).text) == null
          ? null
          : (rt.unwrap<api.Inline>(self).text)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Inline$get$children(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Inline>(self).children) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Inline$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Inline>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacro$get$name(JSAny? self) {
    try {
      return rt.unwrap<api.InlineMacro>(self).name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineMacro$get$process(JSAny? self) {
    try {
      return ((api.Inline? Function(api.InlineMacroContext) _f) =>
          ((JSAny? a0) => ((_f(rt.unwrap<api.InlineMacroContext>(a0))) == null
                  ? null
                  : wrap((_f(rt.unwrap<api.InlineMacroContext>(a0)))!)))
              .toJS)(rt.unwrap<api.InlineMacro>(self).process);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Postprocessor$get$process(JSAny? self) {
    try {
      return ((String Function(String, api.Document) _f) =>
          ((JSAny? a0, JSAny? a1) => _f(
            rt.str(a0),
            rt.unwrap<api.Document>(a1),
          ).toJS).toJS)(rt.unwrap<api.Postprocessor>(self).process);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Preprocessor$get$process(JSAny? self) {
    try {
      return ((List<String> Function(List<String>, api.Document) _f) =>
          ((JSAny? a0, JSAny? a1) => rt.jsArray([
            for (final x in _f([
              for (final x in rt.list(a0)) rt.str(x),
            ], rt.unwrap<api.Document>(a1)))
              x.toJS,
          ])).toJS)(rt.unwrap<api.Preprocessor>(self).process);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TreeProcessor$get$process(JSAny? self) {
    try {
      return ((void Function(api.Document) _f) => ((JSAny? a0) => (() {
        _f(rt.unwrap<api.Document>(a0));
        return null;
      })()).toJS)(rt.unwrap<api.TreeProcessor>(self).process);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Admonition$get$kind(JSAny? self) {
    try {
      return rt.unwrap<api.Admonition>(self).kind.name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Admonition$get$content(JSAny? self) {
    try {
      return rt.unwrap<api.Admonition>(self).content.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Admonition$get$inlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Admonition>(self).inlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Admonition$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Admonition>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Audio$get$target(JSAny? self) {
    try {
      return rt.unwrap<api.Audio>(self).target.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  void Audio$set$target(JSAny? self, JSAny? value) {
    try {
      rt.unwrap<api.Audio>(self).target = rt.str(value);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? BibliographyAnchor$get$anchorId(JSAny? self) {
    try {
      return rt.unwrap<api.BibliographyAnchor>(self).anchorId.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Callout$get$number(JSAny? self) {
    try {
      return rt.unwrap<api.Callout>(self).number.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CalloutList$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.CalloutList>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CalloutList$get$items(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.CalloutList>(self).items) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CrossReference$get$refid(JSAny? self) {
    try {
      return rt.unwrap<api.CrossReference>(self).refid.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CrossReference$get$path(JSAny? self) {
    try {
      return ((rt.unwrap<api.CrossReference>(self).path) == null
          ? null
          : (rt.unwrap<api.CrossReference>(self).path)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? CrossReference$get$target(JSAny? self) {
    try {
      return rt.unwrap<api.CrossReference>(self).target.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? DescriptionList$get$entries(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.DescriptionList>(self).entries) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? DescriptionList$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.DescriptionList>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? DiscreteHeading$get$level(JSAny? self) {
    try {
      return rt.unwrap<api.DiscreteHeading>(self).level.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? DiscreteHeading$get$title(JSAny? self) {
    try {
      return rt.unwrap<api.DiscreteHeading>(self).title.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  void DiscreteHeading$set$title(JSAny? self, JSAny? value) {
    try {
      rt.unwrap<api.DiscreteHeading>(self).title = rt.str(value);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? DiscreteHeading$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.DiscreteHeading>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$document(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.Document>(self).document);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$title(JSAny? self) {
    try {
      return ((rt.unwrap<api.Document>(self).title) == null
          ? null
          : (rt.unwrap<api.Document>(self).title)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  void Document$set$title(JSAny? self, JSAny? value) {
    try {
      rt.unwrap<api.Document>(self).title = (rt.isMissing(value)
          ? null
          : rt.str(value));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$sourceTitle(JSAny? self) {
    try {
      return ((rt.unwrap<api.Document>(self).sourceTitle) == null
          ? null
          : (rt.unwrap<api.Document>(self).sourceTitle)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$titleInlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Document>(self).titleInlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$headerAttributes(JSAny? self) {
    try {
      return rt.jsObject({
        for (final e in rt.unwrap<api.Document>(self).headerAttributes.entries)
          e.key: ((e.value) == null ? null : (e.value)!.toJS),
      });
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.Document>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$authors(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Document>(self).authors) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$doctype(JSAny? self) {
    try {
      return rt.unwrap<api.Document>(self).doctype.name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$diagnostics(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Document>(self).diagnostics) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$index(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Document>(self).index) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$get$attributes(JSAny? self) {
    try {
      return wrap(rt.unwrap<api.Document>(self).attributes);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$withAttribute(JSAny? self, JSAny? name, JSAny? value) {
    try {
      return wrap(
        rt
            .unwrap<api.Document>(self)
            .withAttribute(rt.str(name), rt.str(value)),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$withoutAttribute(JSAny? self, JSAny? name) {
    try {
      return wrap(rt.unwrap<api.Document>(self).withoutAttribute(rt.str(name)));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$convert(JSAny? self, [JSAny? options]) {
    try {
      return rt
          .unwrap<api.Document>(self)
          .convert(
            standalone: rt.hasOption(options, 'standalone')
                ? (rt.isMissing(rt.option(options, 'standalone'))
                      ? null
                      : rt.boolean(rt.option(options, 'standalone')))
                : null,
          )
          .toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Document$toHtml(JSAny? self, [JSAny? options]) {
    try {
      return rt
          .unwrap<api.Document>(self)
          .toHtml(
            standalone: rt.hasOption(options, 'standalone')
                ? (rt.isMissing(rt.option(options, 'standalone'))
                      ? null
                      : rt.boolean(rt.option(options, 'standalone')))
                : null,
          )
          .toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Footnote$get$number(JSAny? self) {
    try {
      return ((rt.unwrap<api.Footnote>(self).number) == null
          ? null
          : (rt.unwrap<api.Footnote>(self).number)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Footnote$get$isReference(JSAny? self) {
    try {
      return rt.unwrap<api.Footnote>(self).isReference.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Formatted$get$kind(JSAny? self) {
    try {
      return rt.unwrap<api.Formatted>(self).kind.name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Icon$get$name(JSAny? self) {
    try {
      return rt.unwrap<api.Icon>(self).name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Image$get$target(JSAny? self) {
    try {
      return rt.unwrap<api.Image>(self).target.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  void Image$set$target(JSAny? self, JSAny? value) {
    try {
      rt.unwrap<api.Image>(self).target = rt.str(value);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Image$get$alt(JSAny? self) {
    try {
      return rt.unwrap<api.Image>(self).alt.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Image$get$width(JSAny? self) {
    try {
      return ((rt.unwrap<api.Image>(self).width) == null
          ? null
          : (rt.unwrap<api.Image>(self).width)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Image$get$height(JSAny? self) {
    try {
      return ((rt.unwrap<api.Image>(self).height) == null
          ? null
          : (rt.unwrap<api.Image>(self).height)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Image$get$link(JSAny? self) {
    try {
      return ((rt.unwrap<api.Image>(self).link) == null
          ? null
          : (rt.unwrap<api.Image>(self).link)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Image$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Image>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IndexTerm$get$terms(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.IndexTerm>(self).terms) x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? IndexTerm$get$isVisible(JSAny? self) {
    try {
      return rt.unwrap<api.IndexTerm>(self).isVisible.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineAnchor$get$anchorId(JSAny? self) {
    try {
      return rt.unwrap<api.InlineAnchor>(self).anchorId.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineImage$get$target(JSAny? self) {
    try {
      return rt.unwrap<api.InlineImage>(self).target.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineImage$get$alt(JSAny? self) {
    try {
      return rt.unwrap<api.InlineImage>(self).alt.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineImage$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.InlineImage>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? InlineStem$get$notation(JSAny? self) {
    try {
      return rt.unwrap<api.InlineStem>(self).notation.name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Keyboard$get$keys(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Keyboard>(self).keys) x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Keyboard$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Keyboard>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Link$get$target(JSAny? self) {
    try {
      return rt.unwrap<api.Link>(self).target.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? ListItem$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.ListItem>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? ListItem$get$content(JSAny? self) {
    try {
      return rt.unwrap<api.ListItem>(self).content.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? ListItem$get$inlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.ListItem>(self).inlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? ListItem$get$checked(JSAny? self) {
    try {
      return ((rt.unwrap<api.ListItem>(self).checked) == null
          ? null
          : (rt.unwrap<api.ListItem>(self).checked)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? ListItem$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.ListItem>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Listing$get$language(JSAny? self) {
    try {
      return ((rt.unwrap<api.Listing>(self).language) == null
          ? null
          : (rt.unwrap<api.Listing>(self).language)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Listing$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.Listing>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Listing$get$content(JSAny? self) {
    try {
      return rt.unwrap<api.Listing>(self).content.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Listing$get$inlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Listing>(self).inlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Listing$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Listing>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Literal$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.Literal>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Literal$get$content(JSAny? self) {
    try {
      return rt.unwrap<api.Literal>(self).content.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Literal$get$inlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Literal>(self).inlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Literal$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Literal>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Menu$get$menu(JSAny? self) {
    try {
      return rt.unwrap<api.Menu>(self).menu.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Menu$get$submenus(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Menu>(self).submenus) x.toJS,
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Menu$get$item(JSAny? self) {
    try {
      return ((rt.unwrap<api.Menu>(self).item) == null
          ? null
          : (rt.unwrap<api.Menu>(self).item)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Menu$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Menu>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? OrderedList$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.OrderedList>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? OrderedList$get$items(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.OrderedList>(self).items) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? OrderedList$get$start(JSAny? self) {
    try {
      return rt.unwrap<api.OrderedList>(self).start.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? OtherBlock$get$context(JSAny? self) {
    try {
      return rt.unwrap<api.OtherBlock>(self).context.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Paragraph$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.Paragraph>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Paragraph$get$content(JSAny? self) {
    try {
      return rt.unwrap<api.Paragraph>(self).content.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Paragraph$get$inlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Paragraph>(self).inlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Paragraph$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Paragraph>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Passthrough$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.Passthrough>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Passthrough$get$content(JSAny? self) {
    try {
      return rt.unwrap<api.Passthrough>(self).content.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Passthrough$get$inlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Passthrough>(self).inlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Passthrough$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Passthrough>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Quote$get$attribution(JSAny? self) {
    try {
      return ((rt.unwrap<api.Quote>(self).attribution) == null
          ? null
          : (rt.unwrap<api.Quote>(self).attribution)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Quote$get$citation(JSAny? self) {
    try {
      return ((rt.unwrap<api.Quote>(self).citation) == null
          ? null
          : (rt.unwrap<api.Quote>(self).citation)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Quote$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Quote>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Section$get$level(JSAny? self) {
    try {
      return rt.unwrap<api.Section>(self).level.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Section$get$title(JSAny? self) {
    try {
      return rt.unwrap<api.Section>(self).title.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  void Section$set$title(JSAny? self, JSAny? value) {
    try {
      rt.unwrap<api.Section>(self).title = rt.str(value);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Section$get$number(JSAny? self) {
    try {
      return ((rt.unwrap<api.Section>(self).number) == null
          ? null
          : (rt.unwrap<api.Section>(self).number)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Section$get$sectionName(JSAny? self) {
    try {
      return rt.unwrap<api.Section>(self).sectionName.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Section$get$isSpecial(JSAny? self) {
    try {
      return rt.unwrap<api.Section>(self).isSpecial.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Stem$get$notation(JSAny? self) {
    try {
      return rt.unwrap<api.Stem>(self).notation.name.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Stem$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.Stem>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Stem$get$content(JSAny? self) {
    try {
      return rt.unwrap<api.Stem>(self).content.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Stem$get$inlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Stem>(self).inlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Stem$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Stem>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Table$get$head(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Table>(self).head)
          rt.jsArray([for (final x in x) wrap(x)]),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Table$get$body(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Table>(self).body)
          rt.jsArray([for (final x in x) wrap(x)]),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Table$get$foot(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Table>(self).foot)
          rt.jsArray([for (final x in x) wrap(x)]),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Table$get$columns(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Table>(self).columns) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Table$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Table>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TableCell$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.TableCell>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TableCell$get$content(JSAny? self) {
    try {
      return rt.unwrap<api.TableCell>(self).content.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TableCell$get$colspan(JSAny? self) {
    try {
      return rt.unwrap<api.TableCell>(self).colspan.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TableCell$get$rowspan(JSAny? self) {
    try {
      return rt.unwrap<api.TableCell>(self).rowspan.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TableCell$get$blocks(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.TableCell>(self).blocks) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? TableCell$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.TableCell>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? UnorderedList$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.UnorderedList>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? UnorderedList$get$items(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.UnorderedList>(self).items) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? UnorderedList$get$isChecklist(JSAny? self) {
    try {
      return rt.unwrap<api.UnorderedList>(self).isChecklist.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Verse$get$attribution(JSAny? self) {
    try {
      return ((rt.unwrap<api.Verse>(self).attribution) == null
          ? null
          : (rt.unwrap<api.Verse>(self).attribution)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Verse$get$citation(JSAny? self) {
    try {
      return ((rt.unwrap<api.Verse>(self).citation) == null
          ? null
          : (rt.unwrap<api.Verse>(self).citation)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Verse$get$source(JSAny? self) {
    try {
      return rt.unwrap<api.Verse>(self).source.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Verse$get$content(JSAny? self) {
    try {
      return rt.unwrap<api.Verse>(self).content.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Verse$get$inlines(JSAny? self) {
    try {
      return rt.jsArray([
        for (final x in rt.unwrap<api.Verse>(self).inlines) wrap(x),
      ]);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Verse$get$plainText(JSAny? self) {
    try {
      return rt.unwrap<api.Verse>(self).plainText.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Video$get$target(JSAny? self) {
    try {
      return rt.unwrap<api.Video>(self).target.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  void Video$set$target(JSAny? self, JSAny? value) {
    try {
      rt.unwrap<api.Video>(self).target = rt.str(value);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? Video$get$service(JSAny? self) {
    try {
      return ((rt.unwrap<api.Video>(self).service) == null
          ? null
          : (rt.unwrap<api.Video>(self).service)!.toJS);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? get asciidoc {
    try {
      return wrap(api.asciidoc);
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? get asciidoctorVersion {
    try {
      return api.asciidoctorVersion.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  JSAny? get ptomeVersion {
    try {
      return api.ptomeVersion.toJS;
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('FontFile')
  JSAny? new$FontFile(JSAny? name, JSAny? bytes) {
    try {
      return wrap(api.FontFile(rt.str(name), rt.bytes(bytes)));
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('Ptome')
  JSAny? new$Ptome([JSAny? options]) {
    try {
      return wrap(
        api.Ptome(
          safe: rt.hasOption(options, 'safe')
              ? api.SafeMode.values.byName(rt.str(rt.option(options, 'safe')))
              : api.SafeMode.secure,
          attributes: rt.hasOption(options, 'attributes')
              ? {
                  for (final e in rt.entries(rt.option(options, 'attributes')))
                    e.key: rt.str(e.value),
                }
              : const {},
          extensions: rt.hasOption(options, 'extensions')
              ? [
                  for (final x in rt.list(rt.option(options, 'extensions')))
                    rt.unwrap<api.Extension>(x),
                ]
              : const [],
          html: rt.hasOption(options, 'html')
              ? (rt.isMissing(rt.option(options, 'html'))
                    ? null
                    : ((JSFunction f) =>
                          (api.Node a0, api.HtmlDefaults a1) => rt.str(
                            rt.invoke(f, [wrap(a0), wrap(a1)]),
                          ))(rt.fn(rt.option(options, 'html'))))
              : null,
          templateDirs: rt.hasOption(options, 'templateDirs')
              ? [
                  for (final x in rt.list(rt.option(options, 'templateDirs')))
                    rt.str(x),
                ]
              : const [],
          highlighters: rt.hasOption(options, 'highlighters')
              ? {
                  for (final e in rt.entries(
                    rt.option(options, 'highlighters'),
                  ))
                    e.key: unwrapHighlighter(e.value),
                }
              : const {},
          baseDir: rt.hasOption(options, 'baseDir')
              ? (rt.isMissing(rt.option(options, 'baseDir'))
                    ? null
                    : rt.str(rt.option(options, 'baseDir')))
              : null,
          onDiagnostic: rt.hasOption(options, 'onDiagnostic')
              ? (rt.isMissing(rt.option(options, 'onDiagnostic'))
                    ? null
                    : ((JSFunction f) => (api.Diagnostic a0) {
                        rt.invoke(f, [wrap(a0)]);
                      })(rt.fn(rt.option(options, 'onDiagnostic'))))
              : null,
          fonts: rt.hasOption(options, 'fonts')
              ? [
                  for (final x in rt.list(rt.option(options, 'fonts')))
                    rt.unwrap<api.FontFile>(x),
                ]
              : const [],
          pageFonts: rt.hasOption(options, 'pageFonts')
              ? rt.boolean(rt.option(options, 'pageFonts'))
              : true,
          localFonts: rt.hasOption(options, 'localFonts')
              ? [
                  for (final x in rt.list(rt.option(options, 'localFonts')))
                    rt.str(x),
                ]
              : const [],
        ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('BlockMacro')
  JSAny? new$BlockMacro(JSAny? name, JSAny? process) {
    try {
      return wrap(
        api.BlockMacro(
          rt.str(name),
          ((JSFunction f) =>
              (api.BlockMacroContext a0) =>
                  (rt.isMissing(rt.invoke(f, [wrap(a0)]))
                  ? null
                  : rt.unwrap<api.Block>(rt.invoke(f, [wrap(a0)]))))(
            rt.fn(process),
          ),
        ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('CustomBlock')
  JSAny? new$CustomBlock(JSAny? name, JSAny? process, [JSAny? options]) {
    try {
      return wrap(
        api.CustomBlock(
          rt.str(name),
          ((JSFunction f) =>
              (api.CustomBlockContext a0) =>
                  (rt.isMissing(rt.invoke(f, [wrap(a0)]))
                  ? null
                  : rt.unwrap<api.Block>(rt.invoke(f, [wrap(a0)]))))(
            rt.fn(process),
          ),
          on: rt.hasOption(options, 'on')
              ? {
                  for (final x in rt.list(rt.option(options, 'on')))
                    api.BlockKind.values.byName(rt.str(x)),
                }
              : const {api.BlockKind.open, api.BlockKind.paragraph},
        ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('Docinfo')
  JSAny? new$Docinfo(JSAny? content, [JSAny? options]) {
    try {
      return wrap(
        api.Docinfo(
          ((JSFunction f) =>
              (api.Document a0) => (rt.isMissing(rt.invoke(f, [wrap(a0)]))
              ? null
              : rt.str(rt.invoke(f, [wrap(a0)]))))(rt.fn(content)),
          location: rt.hasOption(options, 'location')
              ? api.DocinfoLocation.values.byName(
                  rt.str(rt.option(options, 'location')),
                )
              : api.DocinfoLocation.head,
        ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('IncludeResolver')
  JSAny? new$IncludeResolver(JSAny? resolve) {
    try {
      return wrap(
        api.IncludeResolver(
          ((JSFunction f) =>
              (api.IncludeRequest a0) => rt.futureOr(
                rt.invoke(f, [wrap(a0)]),
                (x) => (rt.isMissing(x) ? null : rt.str(x)),
              ))(rt.fn(resolve)),
        ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('InlineMacro')
  JSAny? new$InlineMacro(JSAny? name, JSAny? process) {
    try {
      return wrap(
        api.InlineMacro(
          rt.str(name),
          ((JSFunction f) =>
              (api.InlineMacroContext a0) =>
                  (rt.isMissing(rt.invoke(f, [wrap(a0)]))
                  ? null
                  : rt.unwrap<api.Inline>(rt.invoke(f, [wrap(a0)]))))(
            rt.fn(process),
          ),
        ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('Postprocessor')
  JSAny? new$Postprocessor(JSAny? process) {
    try {
      return wrap(
        api.Postprocessor(
          ((JSFunction f) =>
              (String a0, api.Document a1) =>
                  rt.str(rt.invoke(f, [a0.toJS, wrap(a1)])))(rt.fn(process)),
        ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('Preprocessor')
  JSAny? new$Preprocessor(JSAny? process) {
    try {
      return wrap(
        api.Preprocessor(
          ((JSFunction f) =>
              (List<String> a0, api.Document a1) => [
                for (final x in rt.list(
                  rt.invoke(f, [
                    rt.jsArray([for (final x in a0) x.toJS]),
                    wrap(a1),
                  ]),
                ))
                  rt.str(x),
              ])(rt.fn(process)),
        ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }

  @JSExport('TreeProcessor')
  JSAny? new$TreeProcessor(JSAny? process) {
    try {
      return wrap(
        api.TreeProcessor(
          ((JSFunction f) => (api.Document a0) {
            rt.invoke(f, [wrap(a0)]);
          })(rt.fn(process)),
        ),
      );
    } catch (e, s) {
      rt.fail(e, s);
    }
  }
}
