description = "Anchor: a pool document cut down and sanitized."
source = "pool:capture-asciidoctor-2.0.26/invoker_test.rb:153.1"
formats = ["html5"]

[options]
input = "./input.adoc"
safe = "unsafe"
standalone = true

[attributes]
"stylesheet!" = ""
"docfile" = "/home/nes/.cache/ascii-docs/refs/asciidoctor-2.0.26/test/fixtures/sample-pipe.adoc"
"docdir" = "/home/nes/.cache/ascii-docs/refs/asciidoctor-2.0.26/test/fixtures"
"docfilesuffix" = ".adoc"
"docname" = "sample-pipe"
