name: ptome
description: A processor for AsciiDoc documents, compatible with Asciidoctor 2.1.0.alpha.0 and fixing bugs it still has. Converts AsciiDoc to HTML 5, DocBook 5, man pages, PDF and EPUB.
version: 0.1.0
repository: https://github.com/nsmmrs/ptome/tree/master/packages/ptome
issue_tracker: https://github.com/nsmmrs/ptome/issues
topics:
  - asciidoc
  - documentation
  - converter
  - markup

environment:
  sdk: ^3.13.0

resolution: workspace

executables:
  ptome: ptome

dependencies:
  args: ^2.4.0
  meta: ^1.16.0
  mustache_template: ^2.0.6
  plain_compression: ^0.1.0-dev
  plain_fonts: ^0.1.0-dev
  plain_highlighting: ^0.1.0
  plain_pdf: ^0.1.0-dev
  plain_unicode: ^0.1.0-dev
  yaml: ^3.1.4

dev_dependencies:
  analyzer: ^14.0.0
  test: ^1.32.0
  very_good_analysis: ^11.0.0
  vm_service: ^15.0.0
