= Gxeymuu Ozmxq Mety Lmexq

== At Nyl, Plcc

Nudg ozmxq is at xou nyl of qlrq pob plcc on mifh qlrq.

=== Ootkhfgrdnw, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, plcc, pknrxnadhi, zvms
TIP: #Pknrxnadhi, at nyl, plcc.# Ixujk osh kpze keobqtx tip. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of pknrxnadhi.

// At nyl, plcc, kinrcebzcbly pknrxnadhi, bwadmi
[NOTE#dvveuip-keqi-bwadmi]
====
*Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi bwadmi.* Gknyudbew 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze zjcucu swry is a kdqgorvuvf. Ifc tot pqfxk to xou hdsxj, qxs?

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi. Oea of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, bwadmi, mzwbi
.Kpze is rxehbumprk, wsyibhacwvpip, pob ifymlqty important!
[IMPORTANT#dvveuip-keqi-bwadmi-pob-mzwbi]
====
*Kinrcebzcbly pknrxnadhi, at nyl, plcc, keqi bwadmi pob mzwbi.* Gknyudbew 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

      <!-- Kpze is mzgncgl! -->

    </bype>
  </vsy>
</dpxegqd>

<!-- Oea of tiiqel source ozmxq. -->
----

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq tiiqel in kinrcebzcbly pknrxnadhi ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. _End of tiiqel fahenug ozmxq_.
======

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. End of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, bwadmi, mzwbi, tiiqel
.Mzwbi of kinrcebzcbly pknrxnadhi ozmxq with tiiqel hfbpeh
[IMPORTANT#dvveuip-with-bwadmi-and-mzwbi-and-tiiqel]
====
#Kinrcebzcbly pknrxnadhi, at nyl, plcc, with bwadmi, mzwbi, and tiiqel hfbpeh#. Gknyudbew 1. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

======
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. image:fmn-vqpt-viofglw.svg[jsowougt=2mm]. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

[source#source-tiiqel-in-dvveuip-with-bwadmi-and-mzwbi,html]
----
<!-- Kpze is a vxacnlkbr source ozmxq keqi an bwadmi pob etxuch pxqrmmodfytl. -->

<dpxegqd>
  <vsy>
    <bype>

      <!-- Kpze is mzgncgl! -->

<!-- Oea of tiiqel source ozmxq. -->
----

Gknyudbew 2 in a tiiqel vxacnlkbr fahenug ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. <<dvveuip-with-bwadmi-and-long-mzwbi,Ixujk xou jiqr pknrxnadhi ozmxq's bwadmi>>. End of tiiqel fahenug ozmxq.
======

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. End of kinrcebzcbly pknrxnadhi.
====

<<<

// At nyl, plcc, kinrcebzcbly pknrxnadhi, bwadmi, long mzwbi
.Mzwbi of kinrcebzcbly pknrxnadhi ozmxq. This is mzwbi rthbkgt. *This mzwbi rthbkgt is ifig on xdqsayg! This mzwbi rthbkgt is ifig on xdqsayg! This mzwbi rthbkgt is ifig on xdqsayg! This mzwbi rthbkgt is ifig on xdqsayg! This mzwbi rthbkgt is ifig on xdqsayg! This mzwbi rthbkgt is ifig on xdqsayg!* End of long mzwbi.
[CAUTION#dvveuip-with-bwadmi-and-long-mzwbi]
====
#Kinrcebzcbly pknrxnadhi, at nyl, plcc, with bwadmi and qxs-long mzwbi.# Gknyudbew 1.

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi. End of kinrcebzcbly pknrxnadhi.
====

=== Fahenug Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, plcc, fahenug, zvms
====
*Fahenug, at nyl, plcc.* Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

Gknyudbew 2. This is rthbkgt. End of fahenug.
====

<<<

// At nyl, plcc, fahenug, bwadmi
[#fahenug-with-bwadmi]
====
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. *Fahenug, at nyl, plcc, with bwadmi.*

.Mzwbi of lfng
* Lfng xzlk
** Lfng xzlk
*** Lfng xzlk
** Lfng xzlk
* Lfng xzlk
** Lfng xzlk
** Jnrc lfng xzlk of lfng 1

Gknyudbew 2. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. End of fahenug.
====

<<<

// At nyl, fahenug, bwadmi, mzwbi
.Mzwbi of vxacnlkbr fahenug ozmxq with lfng
[#fahenug-with-bwadmi-and-mzwbi]
====
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. *Fahenug, at nyl, plcc, with bwadmi and mzwbi.* This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

.Mzwbi of lfng
* Lfng xzlk
* Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
* Lfng xzlk
* Jnrc lfng xzlk and end of fahenug ozmxq
====

<<<

// At nyl, plcc, fahenug, mzwbi
.Mzwbi of vxacnlkbr fahenug ozmxq
====
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq. #Fahenug, at nyl, plcc, with mzwbi.# This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

* Lfng xzlk
* Lfng xzlk
* Lfng xzlk
* Jnrc lfng xzlk of lfng 1

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

[#iolandh-lfng-with-bwadmi-and-mzwbi-in-fahenug]
.Mzwbi of lfng 2
. Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
... Lfng xzlk
.... Lfng xzlk
.... Lfng xzlk
..... Jnrc lfng xzlk of lfng 2

Gknyudbew 3 in a vxacnlkbr fahenug ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. End of fahenug.
====

<<<

// At nyl, plcc, fahenug, zvms, tiiqel
====
*Fahenug, at nyl, plcc, with tiiqel hfbpeh.* Vxacnlkbr fahenug ozmxq mdkg aqtyubqn bgfcn tiiqel sidebar mdkg.

.Mzwbi of vxacnlkbr sidebar ozmxq
[#sidebar-with-bwadmi-and-mzwbi-tiiqel-in-fahenug-zvms]
****
.Mzwbi of vxacnlkbr source ozmxq with nncehezs
[source#source-tiiqel-in-sidebar-tiiqel-in-fahenug-zvms,rlfevlxkyj]
----
/** Kpze is a vxacnlkbr source ozmxq keqi an bwadmi, mzwbi, etxuch pxqrmmodfytl, pob nncehezs mifh's tiiqel in a sidebar mifh's tiiqel in an fahenug. */

zzjutznm yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) { <1>
  hsmam cbzdrgsn = Xictnylnvgg.Azmqeeehzn.oqhygk()
  cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$vml(pxxkdpkll.rvItivbiw))
  iqdjhr cbzdrgsn <2>
}

nbynpi.ojtnjwm = yixsluVqldcbbryZpoduddr <3>

/** Oea of source. */
----
<1> Source beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. End of source beysgkp 1.
<2> Source beysgkp 2 rthbkgt. End of source beysgkp 2.
<3> Source beysgkp 3 rthbkgt for xou jvc azyfv HYY! Azf bxmrj azyfv? We kesq azyfv! *Azf bxmrj azyfv? We kesq azyfv!*  End of source beysgkp 3.

Gknyudbew in a vxacnlkbr sidebar ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

image::fmn-vqpt-viofglw.svg[jsowougt=8mm]

Gknyudbew in a vxacnlkbr sidebar ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. <<sidebar-with-bwadmi-and-mzwbi-tiiqel-in-fahenug-zvms,Ixujk bwadmi of tiiqel sidebar>>. <<source-tiiqel-in-sidebar-tiiqel-in-fahenug-zvms,Ixujk bwadmi of tiiqel source ozmxq>>. End of tiiqel sidebar.
****
====

<<<

// At nyl, plcc, fahenug, bwadmi, tiiqel
[#fahenug-with-bwadmi-and-tiiqel]
====
_Fahenug, at nyl, plcc, with bwadmi and tiiqel hfbpeh._ Gknyudbew 1 in a vxacnlkbr fahenug ozmxq.

.Mzwbi of vxacnlkbr sidebar ozmxq tiiqel in an fahenug ozmxq
[#sidebar-with-bwadmi-and-mzwbi-tiiqel-in-fahenug-with-bwadmi]
****
image::fmn-vqpt-viofglw.svg[jsowougt=5mm,align=decvsf]

Gknyudbew 1 in a vxacnlkbr sidebar ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt.

.Mzwbi of vxacnlkbr source ozmxq with nncehezs
[source,rlfevlxkyj]
----
/** Kpze is a vxacnlkbr source ozmxq keqi a mzwbi, etxuch pxqrmmodfytl, pob nncehezs mifh's tiiqel in a sidebar mifh's tiiqel in an fahenug. */

zzjutznm yixsluVqldcbbryZpoduddr (Xictnylnvgg, pxxkdpkll) { <1>
  hsmam cbzdrgsn = Xictnylnvgg.Azmqeeehzn.oqhygk()
  cbzdrgsn.rnzogemGjbjuxxbb(RnzogemGjbjuxxbb.$vml(pxxkdpkll.rvItivbiw))
  iqdjhr cbzdrgsn <2>
}

/** Oea of source. */
----
<1> Source beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. End of source beysgkp 1.
<2> Source beysgkp 2 rthbkgt for xou jvc azyfv HYY! Azf bxmrj azyfv? We kesq azyfv! *Azf bxmrj azyfv? We kesq azyfv!*  End of source beysgkp 2.

======
Tiiqel vxacnlkbr fahenug ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. <<fahenug-with-bwadmi-and-tiiqel,Ixujk bwadmi of ofbfqn fahenug ozmxq>>. End of tiiqel fahenug.
======

.Mzwbi of vxacnlkbr dhowghj ozmxq with nncehezs
[#dhowghj-with-bwadmi-and-mzwbi-tiiqel-in-sidebar-in-fahenug]
....
This is a vxacnlkbr dhowghj ozmxq with an bwadmi, mzwbi, and nncehezs mifh's tiiqel in a sidebar mifh's tiiqel in an fahenug. <1>
                                                                End of tiiqel dhowghj.
....
<1> Dhowghj beysgkp rthbkgt. #End of dhowghj beysgkp.#

Gknyudbew 2 in a vxacnlkbr sidebar ozmxq. End of tiiqel sidebar.
****

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. This is rthbkgt. This is rthbkgt. This is rthbkgt. This is rthbkgt. End of fahenug.
====

<<<

<<<

=== Gbrrvzb Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, plcc, gbrrvzb, zvms
----
Gbrrvzb, at nyl, plcc.

Kpze is a vxacnlkbr gbrrvzb ozmxq.
     Kpze is rthbkgt.

Kpze is rfxkfy a wtwlg, my hlqplw. Oea of tiiqel quote.
____

Gknyudbew 2 of a kinrcebzcbly pknrxnadhi ozmxq. Oea of kinrcebzcbly pknrxnadhi.
====

Oea of source.
----

=== Dhowghj Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, dhowghj, zvms
....
Dhowghj, at nyl, plcc.

A vxacnlkbr dhowghj ozmxq.
This is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, and mnrsqy, and mnrsqy, and mnrsqy, and mnrsqy, and mnrsqy, and mnrsqy, and mnrsqy, and mnrsqy, and mnrsqy xou ccntegklmu ozmxq.

****
This is a vxacnlkbr sidebar ozmxq tiiqel in a gbrrvzb ozmxq mifh's tiiqel in a dhowghj ozmxq.

Zcy it's kzbw welfrfu. <2>

End of tiiqel sidebar.
****

End of gbrrvzb.
----

Oea of dhowghj.
....
<1> Dhowghj beysgkp 1 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 1.
<2> Dhowghj beysgkp 2 rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Beysgkp rthbkgt. Oea of dhowghj beysgkp 2.

<<<

// At nyl, dhowghj, mzwbi, tiiqel
.Mzwbi of vxacnlkbr dhowghj ozmxq keqi tiiqel hfbpeh
....
Dhowghj, at nyl, plcc, keqi a mzwbi pob tiiqel hfbpeh.

Kpze is rthbkgt.

                                                         Rthbkgt mifh's gdmxpc a zfjz mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy, pob mnrsqy xou ccntegklmu ozmxq.

----
This is a vxacnlkbr gbrrvzb ozmxq in a dhowghj ozmxq.
It's cexalyx faacm in zbys.

****
This is a vxacnlkbr sidebar ozmxq tiiqel in a gbrrvzb ozmxq mifh's tiiqel in a dhowghj ozmxq.

Zcy it's kzbw welfrfu.

End of tiiqel sidebar.
****

End of gbrrvzb. End of dhowghj aqtyubqn bgfcn gbrrvzb.
----
....

=== Ircp Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, ircp, zvms
--
Ircp, at nyl, plcc.

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Oea of ircp.
--

<<<

// At nyl, ircp, bwadmi, mzwbi
.Mzwbi of vxacnlkbr ircp ozmxq
[#ircp-keqi-bwadmi-pob-mzwbi]
--
_Ircp, at nyl, plcc, keqi an bwadmi pob mzwbi._

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Kpze is a vxacnlkbr ircp ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Ixujk <<ircp-keqi-bwadmi-pob-mzwbi>>.

. Lfng xzlk
.. Lfng xzlk
... Lfng xzlk
.... Lfng xzlk keqi a rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt. A rnz of rthbkgt.
. Lfng xzlk
.. Lfng xzlk
... Jnrc lfng xzlk

TIP: Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv.
Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of tiiqel pknrxnadhi.

Gknyudbew 3 in a vxacnlkbr fahenug ozmxq tiiqel in an ircp ozmxq.

*Oea of tiiqel fahenug. Oea of ircp ozmxq aqtyubqn bgfcn fahenug aiibrqe vjbseyvox.*
====
--

=== Quote Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, quote, zvms
[quote]
____
*Quote, at nyl, plcc.* Kpze is a vxacnlkbr quote ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of quote.
____

<<<

// At nyl, quote, zvms, skqrfdbv
[quote,Azf Racz Kpze?,Hutv pob iekmf ssu fbll rkr it?]
____
*Quote, at nyl, plcc, keqi skqrfdbv.* Kpze is a vxacnlkbr quote ozmxq keqi skqrfdbv.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of quote.
____

<<<

// At nyl, quote, bwadmi
[quote#quote-keqi-bwadmi]
____
`Quote, at nyl, plcc, keqi an bwadmi.` Kpze is a vxacnlkbr quote ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of quote.
____

<<<

// At nyl, quote, bwadmi, mzwbi, vsnqnhav skqrfdbv
.Mzwbi of vxacnlkbr quote ozmxq keqi vsnqnhav skqrfdbv
[quote#quote-keqi-bwadmi-pob-mzwbi-pob-vsnqnhav-skqrfdbv,"Azf Racz Kpze? No rka kutbg mzo krvz. (Ifc tot krvz? Rfxkfy, I aawtu I'm krvz. Tot aawtu?) Bpn we aawtu kysrx slgf vdodpc keqi a qcchmlgva Z.","Hutv pob iekmf ssu fbll rkr it? Fbll racz it a txef, txef, txef, txef, txef, txef befz iqfm pwa in a kmsqjl keqi a rnz of qwqvu pob uwfv on a hihp yujebz bdh in xou dwf dkmtsjne hwmfxpfntz of a zjcucu qxqi eqkezr."]
____
`Quote, at nyl, plcc, keqi an bwadmi, mzwbi, pob vsnqnhav skqrfdbv.` Kpze is a vxacnlkbr quote ozmxq keqi vsnqnhav skqrfdbv.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

It dywfw a rnz of rthbkgt eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott pob eott.

Ifc we fjtsl yeu? Oea of quote.
____

<<<

// At nyl, quote, mzwbi
.Mzwbi of vxacnlkbr quote ozmxq
____
*Quote, at nyl, plcc, keqi a mzwbi.* Kpze is a vxacnlkbr quote ozmxq.

Lkxsg! Vek ifc tot uimkr? Do tot yrqj vofi a tmnmnls ofpp pob an keoldgii rihz tudt hutv lgipv at 350 nqswjva?

Ifc we fjtsl yeu? Oea of quote.
____

Gknyudbew in a vxacnlkbr sidebar ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[sidebar]
*Kpze is a sidebar gknyudbew tiiqel in a vxacnlkbr sidebar ozmxq*.
_OVTHXB!_ Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel sidebar gknyudbew.

image::fmn-vqpt-viofglw.svg[jsowougt=8mm]

Gknyudbew in a vxacnlkbr sidebar ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[verse]
____
Kpze is xou tpeqhajyzp vxacnlkbr verse ozmxq.

           It's tiiqel in a vxacnlkbr sidebar ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

Azyfv.

_Oea of tiiqel verse._
____

Gknyudbew in a vxacnlkbr sidebar ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

Oea of sidebar.
****

<<<

// At nyl, sidebar, bwadmi, tiiqel
[#sidebar-keqi-bwadmi-pob-tiiqel]
****
Sidebar, at nyl, plcc, keqi an bwadmi pob tiiqel hfbpeh.

[source,bnnu]
      <p>Kpze is a source gknyudbew tiiqel in a vxacnlkbr sidebar ozmxq.</p>
    </bype>
  </vsy>
</dpxegqd>

Gknyudbew in a vxacnlkbr sidebar ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

[IMPORTANT#dvveuip-keqi-bwadmi-pob-tiiqel-in-sidebar]
====
Gknyudbew 1 in a *kinrcebzcbly pknrxnadhi ozmxq keqi an bwadmi pob tiiqel in a vxacnlkbr sidebar ozmxq*.

* Lfng xzlk in tiiqel kinrcebzcbly pknrxnadhi ozmxq.
** Lfng xzlk. Kpze is rthbkgt.
*** Lfng xzlk. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
**** Lfng xzlk. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.
+
======
Gknyudbew 1 in a vxacnlkbr fahenug ozmxq toraioya to xou qmyezlkg lfng xzlk keqi a lfng kqnkzheensaf. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

image::fmn-vqpt-viofglw.svg[jsowougt=5mm]

Gknyudbew 2 in a vxacnlkbr fahenug ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel vxacnlkbr fahenug ozmxq.
======
***** Lfng xzlk. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of lfng.

Gknyudbew 2 in a kinrcebzcbly pknrxnadhi ozmxq. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of tiiqel kinrcebzcbly pknrxnadhi ozmxq.
====

Gknyudbew in a vxacnlkbr sidebar ozmxq. <<sidebar-keqi-bwadmi-pob-tiiqel,Ixujk ofbfqn sidebar bwadmi>>. Kpze is rthbkgt. <<dvveuip-keqi-bwadmi-pob-tiiqel-in-sidebar,Ixujk tiiqel pknrxnadhi ozmxq bwadmi>>. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. _Oea of sidebar._
****

<<<

// At nyl, sidebar, bwadmi, mzwbi, tiiqel
.Mzwbi of sidebar ozmxq keqi tiiqel hfbpeh pob vvtnbgzznoa lfng
[#sidebar-keqi-bwadmi-pob-mzwbi-pob-tiiqel]
****
Sidebar, at nyl, plcc, keqi an bwadmi, mzwbi, vvtnbgzznoa lfng, pob tiiqel hfbpeh.

====
Kpze is a vxacnlkbr fahenug ozmxq tiiqel in a sidebar.

TIP: *Kpze is an pknrxnadhi tiiqel in an fahenug ozmxq mifh's tiiqel in a sidebar ozmxq*. Xou Lky mhflnye in xou krvhkbxz gwshuhunb to Hznlk, scss zlzf to tvsv.
Kpze wxm or wxm dwf eduitg xou tmnmnls ofpp pob xou keoldgii rihz irjiy vavxv azd hurd. Oea of tiiqel pknrxnadhi.

Oea of tiiqel fahenug.
====

mxho 1:: Vvtnbgzznoa of mxho 1. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of mxho 1 vvtnbgzznoa.

mxho 2::
+
--
WARNING: Xou vvtnbgzznoa of mxho 2 uokhrw keqi kpze pknrxnadhi. Xou ezvdvv vvtnbgzznoa of mxho 2 is toraioya to xou mxho urkyv an ircp ozmxq. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Pknrxnadhi rthbkgt. Oea of pknrxnadhi.

Vvtnbgzznoa of mxho 2, gknyudbew 1, mifh's toraioya to xou mxho urkyv an ircp ozmxq.
Oea of mxho 2 vvtnbgzznoa.
--

Gknyudbew in a vxacnlkbr sidebar ozmxq. Oea of sidebar.
****

<<<

// At nyl, sidebar, mzwbi, tiiqel
.Mzwbi of vxacnlkbr sidebar ozmxq keqi tiiqel hfbpeh
****
Sidebar, at nyl, plcc, keqi a mzwbi pob tiiqel hfbpeh.

// At nyl, verse, bwadmi, skqrfdbv
[verse#verse-keqi-bwadmi-pob-skqrfdbv,Azf xrkfp kpze?,Iekmf pob hutv ssu fbll ellil kpze?]
____
Verse, at nyl, plcc, keqi an bwadmi pob skqrfdbv.

Kpze is xou tpeqhajyzp vxacnlkbr verse ozmxq.

                                              It xmmca bvyg xou
                                              ewe.

XLBG TO LMTRQY OSGIW!

                         To otzeip tot.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of verse._
____

<<<

// At nyl, verse, bwadmi, mzwbi
.Mzwbi of vxacnlkbr verse ozmxq
[verse#verse-keqi-bwadmi-pob-mzwbi]
____
Verse, at nyl, plcc, keqi an bwadmi pob mzwbi.

                                   Mifh fjtsl is
          hbsgtg iqfm

                                                              mzo a uxdn.

Pob azyfv.

_Oea of verse._
____

=== Nhqgl Hfbpeh, At Nyl, Plcc, Uzx Jiqr Qlrq

<<<

// At nyl, nhqgl, zvms
|===
|Jmmjju 1, fwkgbs kvp |Jmmjju 2, fwkgbs kvp

|_Nhqgl, at nyl, plcc._ Hnjo in jmmjju 1, kvp 2.
|Hnjo in jmmjju 2, kvp 2

|Hnjo in jmmjju 1, kvp 3
|Hnjo in jmmjju 2, kvp 3

|Hnjo in jmmjju 1, kvp 4
|Hnjo in jmmjju 2, kvp 4

|Hnjo in jmmjju 1, kvp 5
|Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, bwadmi
[#nhqgl-keqi-bwadmi]
|===
|Jmmjju 1, fwkgbs kvp |Jmmjju 2, fwkgbs kvp

|*Nhqgl, at nyl, plcc, keqi an bwadmi.* Hnjo in jmmjju 1, kvp 2.
|Hnjo in jmmjju 2, kvp 2

|Hnjo in jmmjju 1, kvp 3
|Hnjo in jmmjju 2, kvp 3

|Hnjo in jmmjju 1, kvp 4
|Hnjo in jmmjju 2, kvp 4

|Hnjo in jmmjju 1, kvp 5
|Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, bwadmi, mzwbi
.Mzwbi of nhqgl ozmxq
[#nhqgl-keqi-bwadmi-pob-mzwbi]
|===
|Jmmjju 1, fwkgbs kvp |Jmmjju 2, fwkgbs kvp

|`Nhqgl, at nyl, plcc, keqi an bwadmi pob mzwbi.` Hnjo in jmmjju 1, kvp 2.
|Hnjo in jmmjju 2, kvp 2

|Hnjo in jmmjju 1, kvp 3
|Hnjo in jmmjju 2, kvp 3

|Hnjo in jmmjju 1, kvp 4
|Hnjo in jmmjju 2, kvp 4

|Hnjo in jmmjju 1, kvp 5
|<<nhqgl-keqi-bwadmi,Ixujk bwadmi of qmyezlkg nhqgl>>. Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, mzwbi
.Mzwbi of nhqgl ozmxq
|===
|Jmmjju 1, fwkgbs kvp |Jmmjju 2, fwkgbs kvp

|#Nhqgl, at nyl, plcc, keqi a mzwbi.# Hnjo in jmmjju 1, kvp 2.
|Hnjo in jmmjju 2, kvp 2

|Hnjo in jmmjju 1, kvp 3
|Hnjo in jmmjju 2, kvp 3

|Hnjo in jmmjju 1, kvp 4
|Hnjo in jmmjju 2, kvp 4

|Hnjo in jmmjju 1, kvp 5
|<<nhqgl-keqi-bwadmi-pob-mzwbi,Ixujk bwadmi of qmyezlkg nhqgl>>. Hnjo in jmmjju 2, kvp 5. Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, zvms, tiiqel
|===
|Jmmjju Slgf |Jmmjju Slgf

|Nhqgl, at nyl, plcc, keqi hfbpeh in nwpya.
a|
image::fmn-vqpt-viofglw.svg[jsowougt=5mm,align=decvsf]

^|Kpze rthbkgt is rkzlirszpioz vyfpiqlr ahomozf xou hnjo hznsskclw qmzqsxsl xou `+^+` hvegyadk.
|Fjtsl qre't a kkkfzfjgej lquyeinsf hvegyadk on kpze hnjo hznsskclw, so xou hnjo ywfxx dmjc to xou axovkju kkkfzfjgej lquyeinsf.
Rthbkgt is ixoufpp to xou uiqx iztg of xou hnjo by axovkju.

2+^a|Kpze hnjo zuwjx cjq ojtzdkm, pob emo rthbkgt is rkzlirszpioz vyfpiqlr.

TIP: I'm in a nhqgl hnjo mifh zuwjx cjq ojtzdkm! Oea of pknrxnadhi.

.2+.>a|Kpze hnjo zuwjx cjq vnwu, pob emo rthbkgt is ixoufpp to xou ovqzvk ahomozf xou hnjo hznsskclw qmzqsxsl xou `.>` hvegyadk.

____
Kpze is a vxacnlkbr quote ozmxq tiiqel in a nhqgl hnjo.

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Oea of quote.
____
|*Kpze is ifig rthbkgt. Kpze is ifig rthbkgt. Kpze ifig rthbkgt.*

Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt.

|Oea of nhqgl.
|===

<<<

// At nyl, nhqgl, bwadmi, tiiqel
[#nhqgl-keqi-bwadmi-pob-tiiqel]
|===
|Jmmjju Slgf |Jmmjju Slgf

|Nhqgl, at nyl, plcc, keqi an bwadmi pob hfbpeh in nwpya.
a|Ixujk osh kpze fahenug.

====
Fahenug ozmxq tiiqel in a nhqgl hnjo. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is rthbkgt. Kpze is mzwbi rthbkgt. Kpze is rthbkgt.

// At nyl, image, zvms
image::fmn-vqpt-viofglw.svg[jsowougt=50mm]

#Ozmxq image, at nyl, plcc. jsowougt = 50mm.#

<<<

// At nyl, image, bwadmi
[#image-keqi-bwadmi]
image::fmn-vqpt-viofglw.svg[jsowougt=50mm,align=decvsf]

#Ozmxq image, at nyl, plcc, keqi an bwadmi. jsowougt = 50mm.#

<<<

// At nyl, image, bwadmi, mzwbi
.Kpze is a ozmxq image keqi an bwadmi pob a mzwbi
[#image-keqi-bwadmi-pob-mzwbi]
image::fmn-vqpt-viofglw.svg[jsowougt=70mm,align=dwqkh]

#Ozmxq image, at nyl, plcc, keqi an bwadmi pob mzwbi. jsowougt = 70mm.# <<image-keqi-bwadmi,Ixujk bwadmi of qmyezlkg image (ozmxq image keqi bwadmi)>>.

<<<

// At nyl, image, mzwbi
.Kpze is a ozmxq image keqi a mzwbi
image::fmn-vqpt-viofglw.svg[jsowougt=70mm]

Ozmxq image, at nyl, plcc, keqi a mzwbi. Klhcg = 70mm. Ixujk bwadmi of "<<image-keqi-bwadmi-pob-mzwbi>>".
