/// `init-config` scaffold: generates an XMonad-style custom-binary project.
///
/// Specific to Ptome (ADR-0002 T6). Running
/// `ptome init-config [DIR]` writes a user project (pubspec,
/// `lib/config.dart` holding a `Ptome` configuration, and
/// `bin/main.dart` running the command line with it) that compiles with
/// `dart compile exe`. The subcommand form
/// (rather than a flag) follows `git init` / `dart create` precedent; a
/// file literally named `init-config` can still be converted by spelling
/// it `./init-config`.
library;

import 'package:ptome/src/io.dart' as io;
import 'package:ptome/src/path_resolver.dart';

/// Usage text for `init-config` (printed by `--help` and on misuse).
const String initConfigUsage = '''
Usage: ptome init-config [DIR] [options]

Generates a custom-command project in DIR (default: the current directory).
The project runs the standard command line with its own configuration
(extensions, HTML overrides, highlighters) compiled in:

  ptome init-config my-config
  cd my-config
  dart pub get
  dart compile exe bin/main.dart -o ptome-local

Options:
  -f, --force    overwrite existing scaffold files
  -h, --help     show this help
''';

/// Version constraint the scaffold puts on the `ptome` dependency.
///
/// Bump with releases; `init_config_test.dart` asserts it matches this
/// package's own version.
const String scaffoldPtomeConstraint = '^0.1.0';

/// SDK constraint the scaffold puts in the generated pubspec.
///
/// Mirrors this package's own constraint; asserted by
/// `init_config_test.dart`.
const String scaffoldSdkConstraint = '^3.13.0';

/// Generates a custom-binary project from the `init-config` arguments.
///
/// [args] are the arguments after `init-config` (an optional target
/// directory plus `-f/--force` / `-h/--help`); progress goes to [out]
/// (defaulting to stdout) and diagnostics to [err] (defaulting to
/// stderr). Returns the process exit code (0 on success).
int runInitConfig(List<String> args, {StringSink? out, StringSink? err}) {
  final stdoutSink = out ?? io.standardOutput;
  final stderrSink = err ?? io.standardError;
  var force = false;
  String? dir;
  for (final arg in args) {
    if (arg == '--help' || arg == '-h') {
      stdoutSink.write(initConfigUsage);
      return 0;
    } else if (arg == '--force' || arg == '-f') {
      force = true;
    } else if (arg.startsWith('-')) {
      stderrSink
        ..writeln('ptome init-config: unknown option: $arg')
        ..write(initConfigUsage);
      return 1;
    } else if (dir == null) {
      dir = arg;
    } else {
      stderrSink
        ..writeln(
          'ptome init-config: expected at most one directory, '
          'got "$dir" and "$arg"',
        )
        ..write(initConfigUsage);
      return 1;
    }
  }
  final target = dir ?? '.';
  if (io.exists(target) && !io.isDirectory(target)) {
    stderrSink.writeln(
      'ptome init-config: $target exists and is not a directory',
    );
    return 1;
  }
  final separator = io.pathSeparator;
  final name = _projectName(target);
  final files = <String, String>{
    'pubspec.yaml': _pubspec(name),
    'lib${separator}config.dart': _config(),
    'bin${separator}main.dart': _main(name),
    'README.md': _readme(name),
  };
  final existing = files.keys
      .where((relative) => io.isFile('$target$separator$relative'))
      .toList();
  if (existing.isNotEmpty && !force) {
    stderrSink.writeln(
      'ptome init-config: refusing to overwrite existing files in '
      '$target: ${existing.join(', ')} (use --force to overwrite)',
    );
    return 1;
  }
  io.createDirectories(target);
  for (final entry in files.entries) {
    final path = '$target$separator${entry.key}';
    io.createDirectories(path.substring(0, path.lastIndexOf(separator)));
    io.writeString(path, entry.value);
    stdoutSink.writeln('created $path');
  }
  stdoutSink.writeln('next: cd $target && dart pub get');
  return 0;
}

/// Derives a Dart package name from the basename of the [target]
/// directory.
String _projectName(String target) {
  final resolver = PathResolver();
  final absolute = resolver.expandPath(
    resolver.isRoot(target)
        ? target
        : resolver.joinPath([io.currentDirectory, target]),
  );
  final segments = absolute.split('/').where((segment) => segment.isNotEmpty);
  final base = (segments.isEmpty ? '' : segments.last).toLowerCase();
  final sanitized = base.replaceAll(RegExp('[^a-z0-9_]'), '_');
  if (sanitized.isEmpty || RegExp('^[0-9]').hasMatch(sanitized)) {
    return 'ptome_config';
  }
  return sanitized;
}

/// The scaffold `pubspec.yaml` for project [name].
String _pubspec(String name) =>
    '''
name: $name
description: Custom ptome command with a compiled-in configuration (generated by `ptome init-config`).

environment:
  sdk: $scaffoldSdkConstraint

dependencies:
  ptome: $scaffoldPtomeConstraint
''';

/// The scaffold `lib/config.dart`: the command's configuration.
String _config() => r'''
/// The configuration compiled into this custom Ptome command:
/// extensions, HTML overrides and syntax highlighters.
///
/// Generated by `ptome init-config`. `bin/main.dart` runs the standard
/// command line with this configuration, so it applies to every
/// conversion. See `doc/api.md` in the Ptome repository for what an
/// `Ptome` configuration can hold.
library;

import 'package:ptome/ptome.dart';

/// This command's configuration.
final ptome = Ptome(
  // Example: give every paragraph a custom class. Delete or adapt it.
  html: (node, defaults) => switch (node) {
    final Paragraph p =>
      '<div class="paragraph custom">\n<p>${p.content}</p>\n</div>',
    _ => defaults.render(node),
  },
  extensions: [
    // Example: issue:42[] links to an issue tracker. Delete or adapt it.
    InlineMacro(
      'issue',
      (m) => m.link(
        'https://example.org/issues/${m.target}',
        text: '#${m.target}',
      ),
    ),
  ],
);
''';

/// The scaffold `bin/main.dart` for project [name].
String _main(String name) =>
    '''
/// Custom Ptome command with a compiled-in configuration.
///
/// Generated by `ptome init-config`. Runs the standard command line
/// with the configuration in `lib/config.dart`. Compile it with:
///
/// ```sh
/// dart compile exe bin/main.dart -o $name-local
/// ```
import 'package:ptome/cli.dart';
import 'package:$name/config.dart';

Future<void> main(List<String> args) => runCli(args, ptome: ptome);
''';

/// The scaffold `README.md` for project [name].
String _readme(String name) =>
    '''
# $name

Custom ptome CLI with compiled-in converter functions, generated by
`ptome init-config`.

## Edit

`lib/config.dart` holds the command's configuration: a `Ptome` with
HTML overrides, extensions and highlighters. They apply to every
conversion, together with the options given on the command line.

## Run (JIT)

```sh
dart pub get
dart run bin/main.dart --version
```

## Compile (AOT)

```sh
dart compile exe bin/main.dart -o $name-local
./$name-local --version
```
''';
