// GENERATED by tool/generate_js.dart from the public Dart API. Do not edit.
// The JavaScript projection of ptome: the same names and shapes as the
// Dart API (see npm/README.md and tool/generate_js.dart).

import { core, errorClasses, filterByClass, registerClasses } from './core.js'

export class Attributes {
  constructor() {
    throw new TypeError('Attributes objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get names() {
    return core.Attributes$get$names(this)
  }
  get(...args) {
    return core.Attributes$get(this, ...args)
  }
  set(...args) {
    return core.Attributes$set(this, ...args)
  }
  remove(...args) {
    return core.Attributes$remove(this, ...args)
  }
  has(...args) {
    return core.Attributes$has(this, ...args)
  }
  intValue(...args) {
    return core.Attributes$intValue(this, ...args)
  }
  listValue(...args) {
    return core.Attributes$listValue(this, ...args)
  }
  toMap(...args) {
    return core.Attributes$toMap(this, ...args)
  }
}

export class Author {
  constructor() {
    throw new TypeError('Author objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get name() {
    return core.Author$get$name(this)
  }
  get email() {
    return core.Author$get$email(this)
  }
  get firstName() {
    return core.Author$get$firstName(this)
  }
  get middleName() {
    return core.Author$get$middleName(this)
  }
  get lastName() {
    return core.Author$get$lastName(this)
  }
}

export class BlockMacroContext {
  constructor() {
    throw new TypeError('BlockMacroContext objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get target() {
    return core.BlockMacroContext$get$target(this)
  }
  get attributes() {
    return core.BlockMacroContext$get$attributes(this)
  }
  get parent() {
    return core.BlockMacroContext$get$parent(this)
  }
  get document() {
    return core.BlockMacroContext$get$document(this)
  }
  paragraph(...args) {
    return core.BlockMacroContext$paragraph(this, ...args)
  }
  html(...args) {
    return core.BlockMacroContext$html(this, ...args)
  }
  listing(...args) {
    return core.BlockMacroContext$listing(this, ...args)
  }
  image(...args) {
    return core.BlockMacroContext$image(this, ...args)
  }
  asciidoc(...args) {
    return core.BlockMacroContext$asciidoc(this, ...args)
  }
}

export class CustomBlockContext {
  constructor() {
    throw new TypeError('CustomBlockContext objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get lines() {
    return core.CustomBlockContext$get$lines(this)
  }
  get source() {
    return core.CustomBlockContext$get$source(this)
  }
  get attributes() {
    return core.CustomBlockContext$get$attributes(this)
  }
  get parent() {
    return core.CustomBlockContext$get$parent(this)
  }
  get document() {
    return core.CustomBlockContext$get$document(this)
  }
  paragraph(...args) {
    return core.CustomBlockContext$paragraph(this, ...args)
  }
  html(...args) {
    return core.CustomBlockContext$html(this, ...args)
  }
  listing(...args) {
    return core.CustomBlockContext$listing(this, ...args)
  }
  image(...args) {
    return core.CustomBlockContext$image(this, ...args)
  }
  asciidoc(...args) {
    return core.CustomBlockContext$asciidoc(this, ...args)
  }
}

export class DescriptionListEntry {
  constructor() {
    throw new TypeError('DescriptionListEntry objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get terms() {
    return core.DescriptionListEntry$get$terms(this)
  }
  get description() {
    return core.DescriptionListEntry$get$description(this)
  }
}

export class Diagnostic {
  constructor() {
    throw new TypeError('Diagnostic objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get severity() {
    return core.Diagnostic$get$severity(this)
  }
  get message() {
    return core.Diagnostic$get$message(this)
  }
  get code() {
    return core.Diagnostic$get$code(this)
  }
  get location() {
    return core.Diagnostic$get$location(this)
  }
}

export class Extension {
  constructor() {
    throw new TypeError('Extension objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
}

export class FileConversion {
  constructor() {
    throw new TypeError('FileConversion objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get inputPath() {
    return core.FileConversion$get$inputPath(this)
  }
  get outputPath() {
    return core.FileConversion$get$outputPath(this)
  }
  get document() {
    return core.FileConversion$get$document(this)
  }
}

export class FontFile {
  constructor(...args) {
    return core.FontFile(...args)
  }
  toString() {
    return core.describe(this)
  }
  get name() {
    return core.FontFile$get$name(this)
  }
  get bytes() {
    return core.FontFile$get$bytes(this)
  }
}

export class Highlighter {
}

export class HtmlDefaults {
  constructor() {
    throw new TypeError('HtmlDefaults objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  render(...args) {
    return core.HtmlDefaults$render(this, ...args)
  }
  content(...args) {
    return core.HtmlDefaults$content(this, ...args)
  }
}

export class IncludeRequest {
  constructor() {
    throw new TypeError('IncludeRequest objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get target() {
    return core.IncludeRequest$get$target(this)
  }
  get document() {
    return core.IncludeRequest$get$document(this)
  }
}

export class IndexEntry {
  constructor() {
    throw new TypeError('IndexEntry objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get term() {
    return core.IndexEntry$get$term(this)
  }
  get uses() {
    return core.IndexEntry$get$uses(this)
  }
  get see() {
    return core.IndexEntry$get$see(this)
  }
  get seeAlso() {
    return core.IndexEntry$get$seeAlso(this)
  }
  get subentries() {
    return core.IndexEntry$get$subentries(this)
  }
}

export class IndexLetter {
  constructor() {
    throw new TypeError('IndexLetter objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get letter() {
    return core.IndexLetter$get$letter(this)
  }
  get entries() {
    return core.IndexLetter$get$entries(this)
  }
}

export class InlineMacroContext {
  constructor() {
    throw new TypeError('InlineMacroContext objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get target() {
    return core.InlineMacroContext$get$target(this)
  }
  get attributes() {
    return core.InlineMacroContext$get$attributes(this)
  }
  get text() {
    return core.InlineMacroContext$get$text(this)
  }
  get parent() {
    return core.InlineMacroContext$get$parent(this)
  }
  get document() {
    return core.InlineMacroContext$get$document(this)
  }
  link(...args) {
    return core.InlineMacroContext$link(this, ...args)
  }
  html(...args) {
    return core.InlineMacroContext$html(this, ...args)
  }
  formatted(...args) {
    return core.InlineMacroContext$formatted(this, ...args)
  }
}

export class InlineText {
  constructor() {
    throw new TypeError('InlineText objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get html() {
    return core.InlineText$get$html(this)
  }
  get text() {
    return core.InlineText$get$text(this)
  }
}

export class Node {
  constructor() {
    throw new TypeError('Node objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get parent() {
    return core.Node$get$parent(this)
  }
  get document() {
    return core.Node$get$document(this)
  }
  get id() {
    return core.Node$get$id(this)
  }
  set id(value) {
    core.Node$set$id(this, value)
  }
  get roles() {
    return core.Node$get$roles(this)
  }
  get attributes() {
    return core.Node$get$attributes(this)
  }
  get plainText() {
    return core.Node$get$plainText(this)
  }
  hasOption(...args) {
    return core.Node$hasOption(this, ...args)
  }
}

export class Ptome {
  constructor(...args) {
    return core.Ptome(...args)
  }
  toString() {
    return core.describe(this)
  }
  get safe() {
    return core.Ptome$get$safe(this)
  }
  get attributes() {
    return core.Ptome$get$attributes(this)
  }
  get extensions() {
    return core.Ptome$get$extensions(this)
  }
  get html() {
    return core.Ptome$get$html(this)
  }
  get templateDirs() {
    return core.Ptome$get$templateDirs(this)
  }
  get highlighters() {
    return core.Ptome$get$highlighters(this)
  }
  get baseDir() {
    return core.Ptome$get$baseDir(this)
  }
  get onDiagnostic() {
    return core.Ptome$get$onDiagnostic(this)
  }
  get fonts() {
    return core.Ptome$get$fonts(this)
  }
  get pageFonts() {
    return core.Ptome$get$pageFonts(this)
  }
  get localFonts() {
    return core.Ptome$get$localFonts(this)
  }
  loadBackend(...args) {
    return core.Ptome$loadBackend(this, ...args)
  }
  convertToBytes(...args) {
    return core.Ptome$convertToBytes(this, ...args)
  }
  convertToBytesAsync(...args) {
    return core.Ptome$convertToBytesAsync(this, ...args)
  }
  parse(...args) {
    return core.Ptome$parse(this, ...args)
  }
  parseHeader(...args) {
    return core.Ptome$parseHeader(this, ...args)
  }
  convert(...args) {
    return core.Ptome$convert(this, ...args)
  }
  parseAsync(...args) {
    return core.Ptome$parseAsync(this, ...args)
  }
  convertAsync(...args) {
    return core.Ptome$convertAsync(this, ...args)
  }
  parseFile(...args) {
    return core.Ptome$parseFile(this, ...args)
  }
  convertFile(...args) {
    return core.Ptome$convertFile(this, ...args)
  }
  convertTree(...args) {
    return core.Ptome$convertTree(this, ...args)
  }
}

export class PtomeException extends Error {
  constructor(message) {
    super(message)
    this.name = 'PtomeException'
  }
}

export class SourceCode {
  constructor() {
    throw new TypeError('SourceCode objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get source() {
    return core.SourceCode$get$source(this)
  }
  get language() {
    return core.SourceCode$get$language(this)
  }
  get highlightLines() {
    return core.SourceCode$get$highlightLines(this)
  }
}

export class SourceLocation {
  constructor() {
    throw new TypeError('SourceLocation objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get path() {
    return core.SourceLocation$get$path(this)
  }
  get line() {
    return core.SourceLocation$get$line(this)
  }
}

export class TableColumn {
  constructor() {
    throw new TypeError('TableColumn objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get number() {
    return core.TableColumn$get$number(this)
  }
  get width() {
    return core.TableColumn$get$width(this)
  }
  get style() {
    return core.TableColumn$get$style(this)
  }
}

export class Unit {
  constructor() {
    throw new TypeError('Unit objects come from ptome; they cannot be created with new')
  }
  toString() {
    return core.describe(this)
  }
  get scheme() {
    return core.Unit$get$scheme(this)
  }
  get level() {
    return core.Unit$get$level(this)
  }
  get depth() {
    return core.Unit$get$depth(this)
  }
  get labels() {
    return core.Unit$get$labels(this)
  }
  get id() {
    return core.Unit$get$id(this)
  }
  get reftext() {
    return core.Unit$get$reftext(this)
  }
  get citation() {
    return core.Unit$get$citation(this)
  }
  get path() {
    return core.Unit$get$path(this)
  }
  get line() {
    return core.Unit$get$line(this)
  }
}

export class Block extends Node {
  constructor() {
    throw new TypeError('Block objects come from ptome; they cannot be created with new')
  }
  get title() {
    return core.Block$get$title(this)
  }
  set title(value) {
    core.Block$set$title(this, value)
  }
  get sourceTitle() {
    return core.Block$get$sourceTitle(this)
  }
  get style() {
    return core.Block$get$style(this)
  }
  get location() {
    return core.Block$get$location(this)
  }
  get blocks() {
    return core.Block$get$blocks(this)
  }
  get titleInlines() {
    return core.Block$get$titleInlines(this)
  }
  get plainText() {
    return core.Block$get$plainText(this)
  }
  append(...args) {
    return core.Block$append(this, ...args)
  }
  remove(...args) {
    return core.Block$remove(this, ...args)
  }
  descendants(type) {
    return filterByClass(core.Block$descendants(this), type)
  }
  convert(...args) {
    return core.Block$convert(this, ...args)
  }
}

export class BlockMacro extends Extension {
  constructor(...args) {
    return core.BlockMacro(...args)
  }
  get name() {
    return core.BlockMacro$get$name(this)
  }
  get process() {
    return core.BlockMacro$get$process(this)
  }
}

export class CustomBlock extends Extension {
  constructor(...args) {
    return core.CustomBlock(...args)
  }
  get name() {
    return core.CustomBlock$get$name(this)
  }
  get on() {
    return core.CustomBlock$get$on(this)
  }
  get process() {
    return core.CustomBlock$get$process(this)
  }
}

export class Docinfo extends Extension {
  constructor(...args) {
    return core.Docinfo(...args)
  }
  get content() {
    return core.Docinfo$get$content(this)
  }
  get location() {
    return core.Docinfo$get$location(this)
  }
}

export class IncludeResolver extends Extension {
  constructor(...args) {
    return core.IncludeResolver(...args)
  }
  get resolve() {
    return core.IncludeResolver$get$resolve(this)
  }
}

export class Inline extends Node {
  constructor() {
    throw new TypeError('Inline objects come from ptome; they cannot be created with new')
  }
  get text() {
    return core.Inline$get$text(this)
  }
  get children() {
    return core.Inline$get$children(this)
  }
  get plainText() {
    return core.Inline$get$plainText(this)
  }
}

export class InlineMacro extends Extension {
  constructor(...args) {
    return core.InlineMacro(...args)
  }
  get name() {
    return core.InlineMacro$get$name(this)
  }
  get process() {
    return core.InlineMacro$get$process(this)
  }
}

export class Postprocessor extends Extension {
  constructor(...args) {
    return core.Postprocessor(...args)
  }
  get process() {
    return core.Postprocessor$get$process(this)
  }
}

export class Preprocessor extends Extension {
  constructor(...args) {
    return core.Preprocessor(...args)
  }
  get process() {
    return core.Preprocessor$get$process(this)
  }
}

export class TreeProcessor extends Extension {
  constructor(...args) {
    return core.TreeProcessor(...args)
  }
  get process() {
    return core.TreeProcessor$get$process(this)
  }
}

export class Admonition extends Block {
  constructor() {
    throw new TypeError('Admonition objects come from ptome; they cannot be created with new')
  }
  get kind() {
    return core.Admonition$get$kind(this)
  }
  get content() {
    return core.Admonition$get$content(this)
  }
  get inlines() {
    return core.Admonition$get$inlines(this)
  }
  get plainText() {
    return core.Admonition$get$plainText(this)
  }
}

export class Audio extends Block {
  constructor() {
    throw new TypeError('Audio objects come from ptome; they cannot be created with new')
  }
  get target() {
    return core.Audio$get$target(this)
  }
  set target(value) {
    core.Audio$set$target(this, value)
  }
}

export class BibliographyAnchor extends Inline {
  constructor() {
    throw new TypeError('BibliographyAnchor objects come from ptome; they cannot be created with new')
  }
  get anchorId() {
    return core.BibliographyAnchor$get$anchorId(this)
  }
}

export class Button extends Inline {
  constructor() {
    throw new TypeError('Button objects come from ptome; they cannot be created with new')
  }
}

export class Callout extends Inline {
  constructor() {
    throw new TypeError('Callout objects come from ptome; they cannot be created with new')
  }
  get number() {
    return core.Callout$get$number(this)
  }
}

export class CalloutList extends Block {
  constructor() {
    throw new TypeError('CalloutList objects come from ptome; they cannot be created with new')
  }
  get plainText() {
    return core.CalloutList$get$plainText(this)
  }
  get items() {
    return core.CalloutList$get$items(this)
  }
}

export class CrossReference extends Inline {
  constructor() {
    throw new TypeError('CrossReference objects come from ptome; they cannot be created with new')
  }
  get refid() {
    return core.CrossReference$get$refid(this)
  }
  get path() {
    return core.CrossReference$get$path(this)
  }
  get target() {
    return core.CrossReference$get$target(this)
  }
}

export class DescriptionList extends Block {
  constructor() {
    throw new TypeError('DescriptionList objects come from ptome; they cannot be created with new')
  }
  get entries() {
    return core.DescriptionList$get$entries(this)
  }
  get plainText() {
    return core.DescriptionList$get$plainText(this)
  }
}

export class DiscreteHeading extends Block {
  constructor() {
    throw new TypeError('DiscreteHeading objects come from ptome; they cannot be created with new')
  }
  get level() {
    return core.DiscreteHeading$get$level(this)
  }
  get title() {
    return core.DiscreteHeading$get$title(this)
  }
  set title(value) {
    core.DiscreteHeading$set$title(this, value)
  }
  get plainText() {
    return core.DiscreteHeading$get$plainText(this)
  }
}

export class Document extends Block {
  constructor() {
    throw new TypeError('Document objects come from ptome; they cannot be created with new')
  }
  get document() {
    return core.Document$get$document(this)
  }
  get title() {
    return core.Document$get$title(this)
  }
  set title(value) {
    core.Document$set$title(this, value)
  }
  get sourceTitle() {
    return core.Document$get$sourceTitle(this)
  }
  get titleInlines() {
    return core.Document$get$titleInlines(this)
  }
  get headerAttributes() {
    return core.Document$get$headerAttributes(this)
  }
  get source() {
    return core.Document$get$source(this)
  }
  get authors() {
    return core.Document$get$authors(this)
  }
  get doctype() {
    return core.Document$get$doctype(this)
  }
  get units() {
    return core.Document$get$units(this)
  }
  get diagnostics() {
    return core.Document$get$diagnostics(this)
  }
  get index() {
    return core.Document$get$index(this)
  }
  get attributes() {
    return core.Document$get$attributes(this)
  }
  withAttribute(...args) {
    return core.Document$withAttribute(this, ...args)
  }
  withoutAttribute(...args) {
    return core.Document$withoutAttribute(this, ...args)
  }
  unit(...args) {
    return core.Document$unit(this, ...args)
  }
  convert(...args) {
    return core.Document$convert(this, ...args)
  }
  toHtml(...args) {
    return core.Document$toHtml(this, ...args)
  }
}

export class Example extends Block {
  constructor() {
    throw new TypeError('Example objects come from ptome; they cannot be created with new')
  }
}

export class Footnote extends Inline {
  constructor() {
    throw new TypeError('Footnote objects come from ptome; they cannot be created with new')
  }
  get number() {
    return core.Footnote$get$number(this)
  }
  get isReference() {
    return core.Footnote$get$isReference(this)
  }
  get stream() {
    return core.Footnote$get$stream(this)
  }
  get caller() {
    return core.Footnote$get$caller(this)
  }
}

export class Formatted extends Inline {
  constructor() {
    throw new TypeError('Formatted objects come from ptome; they cannot be created with new')
  }
  get kind() {
    return core.Formatted$get$kind(this)
  }
}

export class Icon extends Inline {
  constructor() {
    throw new TypeError('Icon objects come from ptome; they cannot be created with new')
  }
  get name() {
    return core.Icon$get$name(this)
  }
}

export class Image extends Block {
  constructor() {
    throw new TypeError('Image objects come from ptome; they cannot be created with new')
  }
  get target() {
    return core.Image$get$target(this)
  }
  set target(value) {
    core.Image$set$target(this, value)
  }
  get alt() {
    return core.Image$get$alt(this)
  }
  get width() {
    return core.Image$get$width(this)
  }
  get height() {
    return core.Image$get$height(this)
  }
  get link() {
    return core.Image$get$link(this)
  }
  get plainText() {
    return core.Image$get$plainText(this)
  }
}

export class IndexTerm extends Inline {
  constructor() {
    throw new TypeError('IndexTerm objects come from ptome; they cannot be created with new')
  }
  get terms() {
    return core.IndexTerm$get$terms(this)
  }
  get isVisible() {
    return core.IndexTerm$get$isVisible(this)
  }
}

export class InlineAnchor extends Inline {
  constructor() {
    throw new TypeError('InlineAnchor objects come from ptome; they cannot be created with new')
  }
  get anchorId() {
    return core.InlineAnchor$get$anchorId(this)
  }
}

export class InlineImage extends Inline {
  constructor() {
    throw new TypeError('InlineImage objects come from ptome; they cannot be created with new')
  }
  get target() {
    return core.InlineImage$get$target(this)
  }
  get alt() {
    return core.InlineImage$get$alt(this)
  }
  get plainText() {
    return core.InlineImage$get$plainText(this)
  }
}

export class InlineStem extends Inline {
  constructor() {
    throw new TypeError('InlineStem objects come from ptome; they cannot be created with new')
  }
  get notation() {
    return core.InlineStem$get$notation(this)
  }
}

export class Keyboard extends Inline {
  constructor() {
    throw new TypeError('Keyboard objects come from ptome; they cannot be created with new')
  }
  get keys() {
    return core.Keyboard$get$keys(this)
  }
  get plainText() {
    return core.Keyboard$get$plainText(this)
  }
}

export class LineBreak extends Inline {
  constructor() {
    throw new TypeError('LineBreak objects come from ptome; they cannot be created with new')
  }
}

export class Link extends Inline {
  constructor() {
    throw new TypeError('Link objects come from ptome; they cannot be created with new')
  }
  get target() {
    return core.Link$get$target(this)
  }
}

export class ListItem extends Block {
  constructor() {
    throw new TypeError('ListItem objects come from ptome; they cannot be created with new')
  }
  get source() {
    return core.ListItem$get$source(this)
  }
  get content() {
    return core.ListItem$get$content(this)
  }
  get inlines() {
    return core.ListItem$get$inlines(this)
  }
  get checked() {
    return core.ListItem$get$checked(this)
  }
  get plainText() {
    return core.ListItem$get$plainText(this)
  }
}

export class Listing extends Block {
  constructor() {
    throw new TypeError('Listing objects come from ptome; they cannot be created with new')
  }
  get language() {
    return core.Listing$get$language(this)
  }
  get source() {
    return core.Listing$get$source(this)
  }
  get content() {
    return core.Listing$get$content(this)
  }
  get inlines() {
    return core.Listing$get$inlines(this)
  }
  get plainText() {
    return core.Listing$get$plainText(this)
  }
}

export class Literal extends Block {
  constructor() {
    throw new TypeError('Literal objects come from ptome; they cannot be created with new')
  }
  get source() {
    return core.Literal$get$source(this)
  }
  get content() {
    return core.Literal$get$content(this)
  }
  get inlines() {
    return core.Literal$get$inlines(this)
  }
  get plainText() {
    return core.Literal$get$plainText(this)
  }
}

export class Menu extends Inline {
  constructor() {
    throw new TypeError('Menu objects come from ptome; they cannot be created with new')
  }
  get menu() {
    return core.Menu$get$menu(this)
  }
  get submenus() {
    return core.Menu$get$submenus(this)
  }
  get item() {
    return core.Menu$get$item(this)
  }
  get plainText() {
    return core.Menu$get$plainText(this)
  }
}

export class NoteCall extends Inline {
  constructor() {
    throw new TypeError('NoteCall objects come from ptome; they cannot be created with new')
  }
  get stream() {
    return core.NoteCall$get$stream(this)
  }
  get caller() {
    return core.NoteCall$get$caller(this)
  }
}

export class NoteEntry extends Inline {
  constructor() {
    throw new TypeError('NoteEntry objects come from ptome; they cannot be created with new')
  }
  get stream() {
    return core.NoteEntry$get$stream(this)
  }
}

export class Open extends Block {
  constructor() {
    throw new TypeError('Open objects come from ptome; they cannot be created with new')
  }
}

export class OrderedList extends Block {
  constructor() {
    throw new TypeError('OrderedList objects come from ptome; they cannot be created with new')
  }
  get plainText() {
    return core.OrderedList$get$plainText(this)
  }
  get items() {
    return core.OrderedList$get$items(this)
  }
  get start() {
    return core.OrderedList$get$start(this)
  }
}

export class OtherBlock extends Block {
  constructor() {
    throw new TypeError('OtherBlock objects come from ptome; they cannot be created with new')
  }
  get context() {
    return core.OtherBlock$get$context(this)
  }
}

export class PageBreak extends Block {
  constructor() {
    throw new TypeError('PageBreak objects come from ptome; they cannot be created with new')
  }
}

export class Paragraph extends Block {
  constructor() {
    throw new TypeError('Paragraph objects come from ptome; they cannot be created with new')
  }
  get source() {
    return core.Paragraph$get$source(this)
  }
  get content() {
    return core.Paragraph$get$content(this)
  }
  get inlines() {
    return core.Paragraph$get$inlines(this)
  }
  get plainText() {
    return core.Paragraph$get$plainText(this)
  }
}

export class Passthrough extends Block {
  constructor() {
    throw new TypeError('Passthrough objects come from ptome; they cannot be created with new')
  }
  get source() {
    return core.Passthrough$get$source(this)
  }
  get content() {
    return core.Passthrough$get$content(this)
  }
  get inlines() {
    return core.Passthrough$get$inlines(this)
  }
  get plainText() {
    return core.Passthrough$get$plainText(this)
  }
}

export class Preamble extends Block {
  constructor() {
    throw new TypeError('Preamble objects come from ptome; they cannot be created with new')
  }
}

export class Quote extends Block {
  constructor() {
    throw new TypeError('Quote objects come from ptome; they cannot be created with new')
  }
  get attribution() {
    return core.Quote$get$attribution(this)
  }
  get citation() {
    return core.Quote$get$citation(this)
  }
  get plainText() {
    return core.Quote$get$plainText(this)
  }
}

export class Section extends Block {
  constructor() {
    throw new TypeError('Section objects come from ptome; they cannot be created with new')
  }
  get level() {
    return core.Section$get$level(this)
  }
  get title() {
    return core.Section$get$title(this)
  }
  set title(value) {
    core.Section$set$title(this, value)
  }
  get number() {
    return core.Section$get$number(this)
  }
  get sectionName() {
    return core.Section$get$sectionName(this)
  }
  get isSpecial() {
    return core.Section$get$isSpecial(this)
  }
}

export class Sidebar extends Block {
  constructor() {
    throw new TypeError('Sidebar objects come from ptome; they cannot be created with new')
  }
}

export class Stem extends Block {
  constructor() {
    throw new TypeError('Stem objects come from ptome; they cannot be created with new')
  }
  get notation() {
    return core.Stem$get$notation(this)
  }
  get source() {
    return core.Stem$get$source(this)
  }
  get content() {
    return core.Stem$get$content(this)
  }
  get inlines() {
    return core.Stem$get$inlines(this)
  }
  get plainText() {
    return core.Stem$get$plainText(this)
  }
}

export class Table extends Block {
  constructor() {
    throw new TypeError('Table objects come from ptome; they cannot be created with new')
  }
  get head() {
    return core.Table$get$head(this)
  }
  get body() {
    return core.Table$get$body(this)
  }
  get foot() {
    return core.Table$get$foot(this)
  }
  get columns() {
    return core.Table$get$columns(this)
  }
  get plainText() {
    return core.Table$get$plainText(this)
  }
}

export class TableCell extends Block {
  constructor() {
    throw new TypeError('TableCell objects come from ptome; they cannot be created with new')
  }
  get source() {
    return core.TableCell$get$source(this)
  }
  get content() {
    return core.TableCell$get$content(this)
  }
  get colspan() {
    return core.TableCell$get$colspan(this)
  }
  get rowspan() {
    return core.TableCell$get$rowspan(this)
  }
  get blocks() {
    return core.TableCell$get$blocks(this)
  }
  get plainText() {
    return core.TableCell$get$plainText(this)
  }
}

export class TableOfContents extends Block {
  constructor() {
    throw new TypeError('TableOfContents objects come from ptome; they cannot be created with new')
  }
}

export class ThematicBreak extends Block {
  constructor() {
    throw new TypeError('ThematicBreak objects come from ptome; they cannot be created with new')
  }
}

export class UnitBlock extends Block {
  constructor() {
    throw new TypeError('UnitBlock objects come from ptome; they cannot be created with new')
  }
  get scheme() {
    return core.UnitBlock$get$scheme(this)
  }
  get level() {
    return core.UnitBlock$get$level(this)
  }
  get citation() {
    return core.UnitBlock$get$citation(this)
  }
}

export class UnitMark extends Inline {
  constructor() {
    throw new TypeError('UnitMark objects come from ptome; they cannot be created with new')
  }
  get isStart() {
    return core.UnitMark$get$isStart(this)
  }
  get scheme() {
    return core.UnitMark$get$scheme(this)
  }
  get level() {
    return core.UnitMark$get$level(this)
  }
  get citation() {
    return core.UnitMark$get$citation(this)
  }
  get reftext() {
    return core.UnitMark$get$reftext(this)
  }
  get label() {
    return core.UnitMark$get$label(this)
  }
}

export class UnorderedList extends Block {
  constructor() {
    throw new TypeError('UnorderedList objects come from ptome; they cannot be created with new')
  }
  get plainText() {
    return core.UnorderedList$get$plainText(this)
  }
  get items() {
    return core.UnorderedList$get$items(this)
  }
  get isChecklist() {
    return core.UnorderedList$get$isChecklist(this)
  }
}

export class Verse extends Block {
  constructor() {
    throw new TypeError('Verse objects come from ptome; they cannot be created with new')
  }
  get attribution() {
    return core.Verse$get$attribution(this)
  }
  get citation() {
    return core.Verse$get$citation(this)
  }
  get source() {
    return core.Verse$get$source(this)
  }
  get content() {
    return core.Verse$get$content(this)
  }
  get inlines() {
    return core.Verse$get$inlines(this)
  }
  get plainText() {
    return core.Verse$get$plainText(this)
  }
}

export class Video extends Block {
  constructor() {
    throw new TypeError('Video objects come from ptome; they cannot be created with new')
  }
  get target() {
    return core.Video$get$target(this)
  }
  set target(value) {
    core.Video$set$target(this, value)
  }
  get service() {
    return core.Video$get$service(this)
  }
}

registerClasses({ Attributes, Author, BlockMacroContext, CustomBlockContext, DescriptionListEntry, Diagnostic, FileConversion, FontFile, HtmlDefaults, IncludeRequest, IndexEntry, IndexLetter, InlineMacroContext, InlineText, Ptome, SourceCode, SourceLocation, TableColumn, Unit, BlockMacro, CustomBlock, Docinfo, IncludeResolver, InlineMacro, Postprocessor, Preprocessor, TreeProcessor, Admonition, Audio, BibliographyAnchor, Button, Callout, CalloutList, CrossReference, DescriptionList, DiscreteHeading, Document, Example, Footnote, Formatted, Icon, Image, IndexTerm, InlineAnchor, InlineImage, InlineStem, Keyboard, LineBreak, Link, ListItem, Listing, Literal, Menu, NoteCall, NoteEntry, Open, OrderedList, OtherBlock, PageBreak, Paragraph, Passthrough, Preamble, Quote, Section, Sidebar, Stem, Table, TableCell, TableOfContents, ThematicBreak, UnitBlock, UnitMark, UnorderedList, Verse, Video })

export const AdmonitionKind = Object.freeze({
  note: 'note',
  tip: 'tip',
  important: 'important',
  caution: 'caution',
  warning: 'warning',
})

export const Backend = Object.freeze({
  html5: 'html5',
  xhtml5: 'xhtml5',
  docbook5: 'docbook5',
  manpage: 'manpage',
  pdf: 'pdf',
  epub3: 'epub3',
})

export const BlockKind = Object.freeze({
  paragraph: 'paragraph',
  listing: 'listing',
  literal: 'literal',
  open: 'open',
  example: 'example',
  sidebar: 'sidebar',
  quote: 'quote',
  passthrough: 'passthrough',
})

export const DiagnosticCode = Object.freeze({
  unknownReference: 'unknownReference',
  duplicateId: 'duplicateId',
  includeNotFound: 'includeNotFound',
  missingAttribute: 'missingAttribute',
  sectionOutOfSequence: 'sectionOutOfSequence',
  unterminatedBlock: 'unterminatedBlock',
  listNumbering: 'listNumbering',
  tableStructure: 'tableStructure',
  missingAsset: 'missingAsset',
  other: 'other',
})

export const DocinfoLocation = Object.freeze({
  head: 'head',
  footer: 'footer',
})

export const Doctype = Object.freeze({
  article: 'article',
  book: 'book',
  manpage: 'manpage',
  inline: 'inline',
})

export const FormattedKind = Object.freeze({
  strong: 'strong',
  emphasis: 'emphasis',
  monospace: 'monospace',
  mark: 'mark',
  superscript: 'superscript',
  subscript: 'subscript',
  doubleQuoted: 'doubleQuoted',
  singleQuoted: 'singleQuoted',
  unquoted: 'unquoted',
})

export const SafeMode = Object.freeze({
  unsafe: 'unsafe',
  safe: 'safe',
  server: 'server',
  secure: 'secure',
})

export const Severity = Object.freeze({
  debug: 'debug',
  info: 'info',
  warning: 'warning',
  error: 'error',
  fatal: 'fatal',
})

export const StemNotation = Object.freeze({
  latexmath: 'latexmath',
  asciimath: 'asciimath',
})

export const asciidoc = core.asciidoc
export const asciidoctorVersion = core.asciidoctorVersion
export const ptomeVersion = core.ptomeVersion
errorClasses.PtomeException = PtomeException
