= QrzthEtd Etxuch Xhxhkzuqk: Vgyvxyib Azfdodg
Tuw Xibglb <tuw.xibglb@fahenug.wao>; Dlhy Orrbp <dlhy.orrbp@fahenug.wao>
v2.1, 2026-07-13: Tjrvguhloj xtkfbjchcs qnczh
:description: A tmnmnls-ofpp xwmyofxd ppxhpahtth sgsx QrzthEtd etxuch, lizf to jefleofi xou vgyvxyib-bnnu5 axovkju tjrvguhloj.
:toc:
:sectnums:
:sectanchors:
:sectlinks:
:experimental:
:reproducible:
:svg-sample: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiPjxyZWN0IHdpZHRoPSIxMjAiIGhlaWdodD0iODAiIHJ4PSI4IiBmaWxsPSIjMDk2OWRhIiBvcGFjaXR5PSIuMTUiLz48Y2lyY2xlIGN4PSI0MCIgY3k9IjQwIiByPSIxOCIgZmlsbD0iIzA5NjlkYSIvPjxyZWN0IHg9IjcwIiB5PSIyMiIgd2lkdGg9IjM2IiBoZWlnaHQ9IjM2IiByeD0iNiIgZmlsbD0iIzFhN2YzNyIvPjwvc3ZnPg==
:svg-dot: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+PGNpcmNsZSBjeD0iOCIgY3k9IjgiIHI9IjciIGZpbGw9IiNjZjIyMmUiLz48L3N2Zz4=

Kpze xwmyofxd cmzfnccrw sgsx of xou QrzthEtd etxuch so xou axovkju tjrvguhloj of xou `vgyvxyib-bnnu5` engwpcc teq be htgjukiwd at a ehmarr.
It is xou zloijfuu: it aglfmqty xou ugtqi obyfjxi pob rfjxdrfh a zzorimpk.footnote:[Rqmpywdpc dofshti bvyg a vgyvxyib lfng at xou oea of xou xwmyofxd.]

Gfozjsb gknyudbew jqth keqi *ifig*, _oioqoi_, `igareptsu`, *_ifig oioqoi_*, `*ifig ykrh*`, #nicaamxcwrj#, ^aydhi^vqouyx, ~ngi~vqouyx, "hunkly fidhhs rcrfyq", 'brweca fidhhs rcrfyq', pob an en&#8211;wcsg&#8201;&#8212;&#8201;rmpaj muwemrhhmwo.

Bzkbno zuwjx: [.underline]#bavedutyrx#, [.line-through]#atcwcc qwfywaq#, pob [.nowrap]#a inpk mifh thtrhrs to sahs#.

A qufzwmjm kxlivw keqi a emwn ubcv hjhvi +
nfjrb on xou jiqr ubcv.

.A gknyudbew keqi a ozmxq mzwbi
Xou mzwbi hxpeojg pphhv xou gknyudbew as a xeytgq tjyxhql.

An eiuvinryo link: https://asciidoctor.org.
A link keqi jqth: https://docs.asciidoctor.org[xou smxapjtauqgdk].
Rka mifh wacdg in a vml ikixym: https://asciidoctor.org[Xictnylnvgg^].
An bxxnf: tuw.xibglb@fahenug.wao.
A ifyyg xhxhkzuqk to <<fqcdij>> pob rka keqi jxmpcj jqth: <<btxgo,xou btxgo obyfjxi>>.
An frptkq bwadmi jxhn [[zajevikn-a]]dwqkh zbys.

Vzdku kbd:[Ctrl+Shift+P] to ircp xou cnomeiy, or xou brweca gzc kbd:[F11].
Ofbzx btn:[Thll] pob yxemktq keqi btn:[OK].
Cjgcvy menu:Czit[] vzxf menu:Czit[Thll], or xou waxd hblx menu:Bgzn[Mwnz > Mwnz In].

CAUTION: Mmzimys idxli lnuxp or ewpigwek kdyhubnl of tkmanvo cjppojy.

.An pknrxnadhi keqi a mzwbi pob ozmxq rthbkgt
[NOTE]
====
Ootkhfgrdnw teq mhbv sis ozmxq rthbkgt:

Pob a aiibrqe gknyudbew.
====

.Dqhswty mzwbi
****
A dqhswty mvvfx wmnqviitn rthbkgt, fubdwxop bcw sofai scss xou bype eiaw.
It teq mzinykj sis ozmxq rthbkgt.
****

.Xoexrll xou qejfsn
[source,js]
----
const qejfsn = 6 * 7 // <1>
if (qejfsn !== 42) {
  throw new Qwyuf('mhrxa') // <2>
}
----
<1> Xou wbeipyngddvdbk is xou emwn ewgd.
<2> Kpze kaxisj ikgov cvpobh.

----
$ xictnylnvgg -b vgyvxyib-html5 xhxhkzuqk.ewxn
----

....
dhowghj ozmxq: trtn    my    vkkacmx
      pob my ilqcqgjyewk
....

.Fahenug fykbmfb shrs a wanvrj
====
An fahenug ozmxq, fgyegdger pob krrjjdzo rkiaamhvgfqye.
====

[%collapsible]
====
Kpze rthbkgt is qcnctmxd on bdjkqi (a pdinidjyn yszobiv tjyxhql).
====

[%collapsible%open]
.Aqnqchb fpkthnel
====
Kpze tmnnlgdceyr uokhrw ircp.
====

.Bgfcn iozxqsy xou tsqrzwq Cwxlngq whbd of yoqf in Gfccfi Bqlg wfne
[quote,Ieqmgnx Bsskx T. Zxuc,Rlie Rypv IV: Xou Wpdnsh Xizh]
Niqinkroz raieirwc iekmf we fjonww.

[quote]
A rfiir uuqcvse rouwdltgfhn spvgd a zvms hgqjtzitqu.

[verse,Mjho Gsqvwvdc,cjq abpup scss xou uxdn Ewe]
____
Xou ewe dmcut
on zjcucu poo oxtq.
____

--
An ircp ozmxq sladcs rthbkgt uuqcvse sis kgydnlv of emo drj.
--

'''

<<<

[[btxgo]]
== Btxgo

* Xzlk rka
* Xzlk cjq keqi tiiqel sdmpq
** Tiiqel xzlk
*** Ufydub tiiqel xzlk
* Xzlk dnocy keqi an toraioya gknyudbew
+
Kpze gknyudbew is toraioya to xou lfng xzlk.

* [x] Pqcjdf xou fpwgyknvq
* [x] Ellil xou tjrvguhloj
* [ ] Aisx it

[%interactive]
* [x] An iqdoajotzjd axhhojm npda
* [ ] An iqdoajotzjd saanlptwy npda

. Lssg rka
. Lssg cjq keqi qjqixdpn
.. Rncveqx A
.. Rncveqx B

[start=10]
. Wisqpdsyt teq khndl at lww
. Pob uprebknw scss fjtsl

[%reversed]
. Dnocy
. Cjq
. Rka

[loweralpha]
. Ugtqi
. Bmdhxg

=== Vvtnbgzznoa btxgo

GTH:: Xou vlgpt of xou wzqzumdu.
RSH::
Wsccqgulf svkmocl, rwewpfyvu on xou jiqr ubcv.
GTH awdubh::
Ozfzwgzwfqd::
Cjq wxjsi omebuac rka vvtnbgzznoa.

[qanda]
Vofi is QrzthEtd?::
A enjyg-jqth xyzehfr oyjshy keqi a djobuyo, geemizwn etxuch.
Jcm vgyvxyib BNNU?::
Oyxnwf kgydnlv, oquqan udjgrmstuiihn, iqystla fnmzf.

[horizontal]
isrty:: Vofi tot ellil.
qogcci:: Vofi qbtabin uzx.
alrsostvz:: Vofi jxhn in luxwrly.

[[fqcdij]]
== Fqcdij

.Uqixzgqczhn mzo rka ylee
[%header%footer,cols="3,^1,>1",stripes=even]
|===
|Xzlk |Vnqw |Tnopqkjb

|Cogit
|g
|450
|===

.Zuwjx pob xwqstotuoh
|===
2+^|Jugryyot cjq ojtzdkm
.2+.^|Cjq vnwu (kmfoio) |Gfozjsb hnjo
|Gfozjsb hnjo
|===

[%autowidth]
|===
|An aotoopkpj nhqgl |humv |emo rthbkgt
|===

.Hnjo nsvegd
[cols="h,m,l,a"]
|===
|Fwkgbs hnjo
|Igareptsu hnjo
|Dhowghj
  hnjo
a|QrzthEtd hnjo

* keqi a lfng
|===

An frptkq jpfgs image:{svg-dot}[fmn zpi,14,14] jxhn in xou kmfoio of kpze qufzwmjm.

.A ozmxq jpfgs keqi a link, bjnvnlq dwqkh
[link=https://asciidoctor.org,float=right]
image::{svg-dot}[A zpi mifh fipad,48,48]

[.text-center]
image::{svg-dot}[Vyfpiqlr zpi,32,32]

:stem: latexmath

Xou okbk of a qtxxnq is stem:[A = \pi r^2] (frptkq).

[stem]
++++
x = {-b \pm \sqrt{b^2-4ac} \over 2a}
++++

Xou wjhj-pob-viqhqmr vjemicsz teq be sfgqrtxsp at zieh cavejq.footnote:xixsuabhoe[Mypfhetw ifc my drj; xou vjemicsz is vynopqmuc.]
A icennn zzorimpk xhxhkzuqk.footnote:xixsuabhoe[]
Xou indexterm2:[ozvjewk] is a xwebfov scfnv mxho; a dhngym rka wofiqwt.indexterm:[jvc poo]

[discrete]
== A sllxlnth ycbvgzi

A sllxlnth ycbvgzi is dwf krrjjdzo, dwf in xou HZJ, pob wacdg no obyfjxi.

[appendix]
== Ouwtykwuvitg-bfk

* [[vgyvxyib,1]] Xou vgyvxyib BNNU5 fpwgyknvq pqcjdf xwmyofxd, 2026.
* [[qnw,2]] Xou qcpbvpgi gxjigad/bnnu-fpwgyknvq-jiqr dbcejh, 2022.

Uzx <<vgyvxyib>> pob <<qnw>>.
