description = "Anchor: a pool document cut down and sanitized."
source = "pool:asciidoc-lang/spec/outline.adoc"
formats = ["pdf"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
