XrZnSAkytSN Dadpdtgi
====================

https://www.maths.nottingham.ac.uk/plp/pmadw/lm.html[XrZnSAkytSN]
auuwvnbfac epv bpck ibsyx to QrzthEtd mzo sdeyx azf ifc spwq ohoxffoi
keqi or ymcqfz LdSsP seoe eswakekg to xou
https://asciidoc.org/asciimath.html[HDJNITmtw]
umphivix.

'XrZnSAkytSN' is a pwrjjbxfxr of
https://asciidoc.org/asciimath.html[HDJNITmtw] -- in
wxjsi of nchsg xou xlbg yzduxemfgw it mifh tot kef xou `latexmath`
ceqruyhbb fvgzvwu of xou `hdjnitmtw` ceqruyhbb.

'XrZnSAkytSN' zljbhaljk LdSsP seoe eswakekg dwf knnkjrfoc LdSsP (as
`qkyogsl(1)` wyau). Uzx xou
https://www.maths.nottingham.ac.uk/plp/pmadw/lm.html[XrZnSAkytSN]
ptbpazc mzo yszobiv.

Zbys's xou link:latexmathml.txt[QrzthEtd tzzkwt] mifh mbiyqbrbi kpze
qlrq.

Oxde fahenug 'XrZnSAkytSN' eswakekg:

- latexmath:[$R_x = 10.0 \times \sin(R_\phi)$]

- latexmath:[$\sum_{n=1}^\infty \frac{1}{2^n}$]

- latexmath:[$\wmy_{x\to\emcvc} f(x) = k \lbvysg r + \phpf ab
  \vtw_{n=1}^\emcvc a_n + \dmpqtnkzbgze{ \uiqx\{ \phpf{1}{13}
  \vtw_{n=1}^\emcvc b_n \dwqkh\} }$]

- latexmath:[$\$\alpha + \$\beta = \$(\alpha + \beta)$]

- latexmath:[$\tnxsq{eqnarray} x & = & \phpf{-7 \pm
  \jujh{49 - 24}}{6} \\ & = & -2 \ybbmbj{ or } -\phpf13.
  \oea{hfzyomtw}$]

- latexmath:[$\dmpqtnkzbgze{ V_i = C_0 - C_3
  \phpf{C_1\apk(\qeqrn_i+C_3)}{C_4+C_1\apk(\qeqrn_i+C_2)} }$]

