// GENERATED by tool/generate_js.dart from the public Dart API. Do not edit.
// Types of Ptome for JavaScript: the same names and shapes as the Dart
// API.

/**
 * The kinds of admonition.
 */
export type AdmonitionKind = 'note' | 'tip' | 'important' | 'caution' | 'warning';
export declare const AdmonitionKind: {
  /**
   * `NOTE`
   */
  readonly note: 'note';
  /**
   * `TIP`
   */
  readonly tip: 'tip';
  /**
   * `IMPORTANT`
   */
  readonly important: 'important';
  /**
   * `CAUTION`
   */
  readonly caution: 'caution';
  /**
   * `WARNING`
   */
  readonly warning: 'warning';
};

/**
 * The output formats.
 */
export type Backend = 'html5' | 'xhtml5' | 'docbook5' | 'manpage' | 'pdf' | 'epub3';
export declare const Backend: {
  /**
   * HTML 5 (the default).
   */
  readonly html5: 'html5';
  /**
   * HTML 5 written as XML (XHTML).
   */
  readonly xhtml5: 'xhtml5';
  /**
   * DocBook 5.
   */
  readonly docbook5: 'docbook5';
  /**
   * A man page (troff).
   */
  readonly manpage: 'manpage';
  /**
   * A PDF file (see {@link Ptome.convertToBytes}).
   */
  readonly pdf: 'pdf';
  /**
   * An EPUB 3 file (see {@link Ptome.convertToBytes}).
   */
  readonly epub3: 'epub3';
};

/**
 * The block kinds a {@link CustomBlock} can handle.
 */
export type BlockKind = 'paragraph' | 'listing' | 'literal' | 'open' | 'example' | 'sidebar' | 'quote' | 'passthrough';
export declare const BlockKind: {
  /**
   * A paragraph.
   */
  readonly paragraph: 'paragraph';
  /**
   * A listing block (`----`).
   */
  readonly listing: 'listing';
  /**
   * A literal block (`....`).
   */
  readonly literal: 'literal';
  /**
   * An open block (`--`).
   */
  readonly open: 'open';
  /**
   * An example block (`====`).
   */
  readonly example: 'example';
  /**
   * A sidebar (`****`).
   */
  readonly sidebar: 'sidebar';
  /**
   * A quote block (`____`).
   */
  readonly quote: 'quote';
  /**
   * A passthrough block (`++++`).
   */
  readonly passthrough: 'passthrough';
};

/**
 * What a {@link Diagnostic} is about, for the messages that are worth telling
 * apart in code; {@link other} for the rest.
 */
export type DiagnosticCode = 'unknownReference' | 'duplicateId' | 'includeNotFound' | 'missingAttribute' | 'sectionOutOfSequence' | 'unterminatedBlock' | 'listNumbering' | 'tableStructure' | 'missingAsset' | 'other';
export declare const DiagnosticCode: {
  /**
   * A cross reference to an ID that is not defined.
   */
  readonly unknownReference: 'unknownReference';
  /**
   * An ID that is already used by another element.
   */
  readonly duplicateId: 'duplicateId';
  /**
   * An include whose target cannot be found or read.
   */
  readonly includeNotFound: 'includeNotFound';
  /**
   * A reference to an attribute that is not set.
   */
  readonly missingAttribute: 'missingAttribute';
  /**
   * A section whose level skips one (for example `===` right after `=`).
   */
  readonly sectionOutOfSequence: 'sectionOutOfSequence';
  /**
   * A delimited block without its closing delimiter.
   */
  readonly unterminatedBlock: 'unterminatedBlock';
  /**
   * List items numbered out of sequence.
   */
  readonly listNumbering: 'listNumbering';
  /**
   * A table row or cell that does not fit the table's columns.
   */
  readonly tableStructure: 'tableStructure';
  /**
   * An image or other asset that cannot be found or read.
   */
  readonly missingAsset: 'missingAsset';
  /**
   * Any other message.
   */
  readonly other: 'other';
};

/**
 * Where {@link Docinfo} content goes.
 */
export type DocinfoLocation = 'head' | 'footer';
export declare const DocinfoLocation: {
  /**
   * At the end of the HTML `<head>` (or the DocBook `<info>`).
   */
  readonly head: 'head';
  /**
   * At the end of the document body.
   */
  readonly footer: 'footer';
};

/**
 * The kinds of AsciiDoc document.
 */
export type Doctype = 'article' | 'book' | 'manpage' | 'inline';
export declare const Doctype: {
  /**
   * A single article (the default).
   */
  readonly article: 'article';
  /**
   * A book: parts, chapters, appendixes.
   */
  readonly book: 'book';
  /**
   * A man page.
   */
  readonly manpage: 'manpage';
  /**
   * A single paragraph or block, converted without any wrapper.
   */
  readonly inline: 'inline';
};

/**
 * The kinds of formatted text.
 */
export type FormattedKind = 'strong' | 'emphasis' | 'monospace' | 'mark' | 'superscript' | 'subscript' | 'doubleQuoted' | 'singleQuoted' | 'unquoted';
export declare const FormattedKind: {
  /**
   * `*strong*`
   */
  readonly strong: 'strong';
  /**
   * `_emphasis_`
   */
  readonly emphasis: 'emphasis';
  /**
   * `` `monospace` ``
   */
  readonly monospace: 'monospace';
  /**
   * `#mark#`
   */
  readonly mark: 'mark';
  /**
   * `^superscript^`
   */
  readonly superscript: 'superscript';
  /**
   * `~subscript~`
   */
  readonly subscript: 'subscript';
  /**
   * `"`double quotes`"`
   */
  readonly doubleQuoted: 'doubleQuoted';
  /**
   * `'`single quotes`'`
   */
  readonly singleQuoted: 'singleQuoted';
  /**
   * `[.role]#text#`: text with a role and no other formatting.
   */
  readonly unquoted: 'unquoted';
};

/**
 * How much a document may reach outside itself.
 */
export type SafeMode = 'unsafe' | 'safe' | 'server' | 'secure';
export declare const SafeMode: {
  /**
   * No restrictions: includes and assets may come from anywhere.
   */
  readonly unsafe: 'unsafe';
  /**
   * Includes and assets only from below the base directory.
   */
  readonly safe: 'safe';
  /**
   * Like {@link safe}, and the document may not set attributes that change how
   * it is processed (such as `docinfo`).
   */
  readonly server: 'server';
  /**
   * Like {@link server}, and no file is read at all: `include::` directives
   * become links. The default for the API.
   */
  readonly secure: 'secure';
};

/**
 * How serious a {@link Diagnostic} is.
 */
export type Severity = 'debug' | 'info' | 'warning' | 'error' | 'fatal';
export declare const Severity: {
  /**
   * Detail useful when debugging a document.
   */
  readonly debug: 'debug';
  /**
   * Information about the conversion.
   */
  readonly info: 'info';
  /**
   * A problem in the document; the output may not be what was intended.
   */
  readonly warning: 'warning';
  /**
   * A problem that drops or breaks part of the output.
   */
  readonly error: 'error';
  /**
   * A problem that stops the conversion.
   */
  readonly fatal: 'fatal';
};

/**
 * The math notations.
 */
export type StemNotation = 'latexmath' | 'asciimath';
export declare const StemNotation: {
  /**
   * LaTeX math.
   */
  readonly latexmath: 'latexmath';
  /**
   * AsciiMath.
   */
  readonly asciimath: 'asciimath';
};

/**
 * A piece of inline content: text, or an inline element.
 *
 * {@link Block.titleInlines} and the `inlines` of paragraphs, other blocks of
 * text and list items give the content of a text as a list of these, for
 * code that renders it without parsing HTML.
 */
export type InlineContent = InlineText | Inline;

/**
 * The attributes of a node or document: names to string values.
 *
 * An attribute set without a value (`:toc:`) has the empty string as its
 * value. The typed getters read common value shapes.
 */
export declare class Attributes {
  protected constructor();
  /**
   * The names of the set attributes.
   */
  readonly names: string[];
  /**
   * The value of {@link name}, or `null` when it is not set.
   */
  get(name: string): string | null;
  /**
   * Sets {@link name} to {@link value}.
   */
  set(name: string, value: string): void;
  /**
   * Unsets {@link name}, returning its previous value.
   */
  remove(name: string): string | null;
  /**
   * Whether {@link name} is set (with any value, including the empty string).
   */
  has(name: string): boolean;
  /**
   * The value of {@link name} as an integer, or `null` when it is not set or not
   * an integer.
   */
  intValue(name: string): number | null;
  /**
   * The value of {@link name} split at commas, each item trimmed, empty items
   * dropped (`'a, b,c'` becomes `['a', 'b', 'c']`); empty when not set.
   */
  listValue(name: string): string[];
  /**
   * The attributes as an unmodifiable map.
   */
  toMap(): Record<string, string>;
}

/**
 * An author named in a document header.
 */
export declare class Author {
  protected constructor();
  readonly name: string | null;
  readonly email: string | null;
  readonly firstName: string | null;
  readonly middleName: string | null;
  readonly lastName: string | null;
}

/**
 * What a {@link BlockMacro} receives: the target and attributes of the macro,
 * and ways to create the block that replaces it.
 */
export declare class BlockMacroContext {
  protected constructor();
  readonly target: string;
  /**
   * The attributes in the brackets: positional ones under `1`, `2`, ...,
   * named ones under their names.
   */
  readonly attributes: Attributes;
  /**
   * The block containing the macro.
   */
  readonly parent: Block;
  /**
   * The document being parsed.
   */
  readonly document: Document;
  /**
   * A paragraph with {@link text} (AsciiDoc inline markup is applied).
   */
  paragraph(text: string, options?: { attributes?: Record<string, string> }): Block;
  /**
   * A passthrough block: {@link html} goes to the output as is.
   */
  html(html: string): Block;
  /**
   * A listing block with {@link source}; a source block when {@link language} is
   * given.
   */
  listing(source: string, options?: { language?: string | null }): Block;
  /**
   * An image block showing {@link target}.
   */
  image(target: string, options?: { alt?: string | null; title?: string | null }): Block;
  /**
   * An open block containing {@link source} parsed as AsciiDoc.
   */
  asciidoc(source: string): Block;
}

/**
 * What a {@link CustomBlock} receives: the block's content and attributes, and
 * ways to create the block that replaces it.
 */
export declare class CustomBlockContext {
  protected constructor();
  readonly lines: string[];
  /**
   * The block's content.
   */
  readonly source: string;
  /**
   * The block's attributes.
   */
  readonly attributes: Attributes;
  /**
   * The block containing this one.
   */
  readonly parent: Block;
  /**
   * The document being parsed.
   */
  readonly document: Document;
  /**
   * A paragraph with {@link text} (AsciiDoc inline markup is applied).
   */
  paragraph(text: string, options?: { attributes?: Record<string, string> }): Block;
  /**
   * A passthrough block: {@link html} goes to the output as is.
   */
  html(html: string): Block;
  /**
   * A listing block with {@link source}; a source block when {@link language} is
   * given.
   */
  listing(source: string, options?: { language?: string | null }): Block;
  /**
   * An image block showing {@link target}.
   */
  image(target: string, options?: { alt?: string | null; title?: string | null }): Block;
  /**
   * An open block containing {@link source} parsed as AsciiDoc.
   */
  asciidoc(source: string): Block;
}

/**
 * One entry of a {@link DescriptionList}.
 */
export declare class DescriptionListEntry {
  protected constructor();
  readonly terms: ListItem[];
  readonly description: ListItem | null;
}

/**
 * A message about a document, reported while parsing or converting it.
 */
export declare class Diagnostic {
  protected constructor();
  readonly severity: Severity;
  readonly message: string;
  readonly code: DiagnosticCode;
  readonly location: SourceLocation | null;
}

/**
 * An extension: code that adds syntax to AsciiDoc or changes how documents
 * are processed. Pass extensions to {@link Ptome.new}.
 */
export declare abstract class Extension {
  protected constructor();
}

/**
 * The result of converting one file with {@link PtomeFiles.convertTree}.
 */
export declare class FileConversion {
  protected constructor();
  readonly inputPath: string;
  readonly outputPath: string;
  readonly document: Document;
}

/**
 * A font given to a conversion as bytes: a TrueType, OpenType, WOFF or
 * WOFF2 file and its name (`Inter-Regular.ttf`). PDFs and EPUBs find it
 * as they find installed fonts, by the file's name, then by the family it
 * names.
 */
export declare class FontFile {
  /**
   * The font file {@link name} with {@link bytes}.
   */
  constructor(name: string, bytes: Uint8Array);
  readonly name: string;
  readonly bytes: Uint8Array;
}

/**
 * A syntax highlighter, registered with {@link Ptome.new} under the name the
 * `source-highlighter` attribute selects.
 */
export declare abstract class Highlighter {
  constructor();
  /**
   * Markup to add to the HTML `<head>` (a stylesheet, for example), if
   * any.
   */
  head?: string | null;
  /**
   * Markup to add at the end of the HTML body (a script, for example), if
   * any.
   */
  footer?: string | null;
  /**
   * The HTML for {@link code}: the content of its `<code>` element, with
   * special characters escaped.
   */
  abstract highlight(code: SourceCode): string;
}

/**
 * Ptome's own HTML, for an {@link HtmlOverride}.
 */
export declare class HtmlDefaults {
  protected constructor();
  /**
   * Ptome's HTML for {@link node}.
   */
  render(node: Node): string;
  /**
   * The HTML of what is inside {@link block}: its converted text, or its child
   * blocks (converted with the override in effect).
   */
  content(block: Block): string;
}

/**
 * What an {@link IncludeResolver} is asked for.
 */
export declare class IncludeRequest {
  protected constructor();
  readonly target: string;
  readonly document: Document;
}

/**
 * A term of a document's index (see {@link Document.index}).
 */
export declare class IndexEntry {
  protected constructor();
  readonly term: string;
  readonly uses: Block[];
  readonly see: string | null;
  readonly seeAlso: string[];
  readonly subentries: IndexEntry[];
}

/**
 * The terms of a document's index under one letter (see
 * {@link Document.index}).
 */
export declare class IndexLetter {
  protected constructor();
  readonly letter: string;
  readonly entries: IndexEntry[];
}

/**
 * What an {@link InlineMacro} receives: the target and attributes of the macro,
 * and ways to create the inline element that replaces it.
 */
export declare class InlineMacroContext {
  protected constructor();
  readonly target: string;
  /**
   * The attributes in the brackets: positional ones under `1`, `2`, ...,
   * named ones under their names.
   */
  readonly attributes: Attributes;
  /**
   * The text in the brackets, when the macro has no named attributes.
   */
  readonly text: string | null;
  /**
   * The block containing the macro.
   */
  readonly parent: Block;
  /**
   * The document being parsed.
   */
  readonly document: Document;
  /**
   * A link to {@link url}, showing {@link text} (default: the URL).
   */
  link(url: string, options?: { text?: string | null }): Inline;
  /**
   * {@link html}, output as is.
   */
  html(html: string): Inline;
  /**
   * {@link text} (already converted HTML) with {@link kind} formatting.
   */
  formatted(text: string, kind: FormattedKind): Inline;
}

/**
 * Text between inline elements.
 */
export declare class InlineText {
  protected constructor();
  readonly html: string;
  /**
   * The text itself: character references decoded (and the tags of any
   * raw HTML passed through left out).
   */
  readonly text: string;
}

/**
 * A node of a document: the document itself, a block, a list item, a
 * table cell, or an inline element.
 *
 * The hierarchy is sealed, so a `switch` over a node can cover every kind.
 */
export declare abstract class Node {
  protected constructor();
  /**
   * The node containing this one, or `null` for a document.
   */
  readonly parent: Node | null;
  /**
   * The document this node belongs to.
   */
  readonly document: Document;
  /**
   * The ID of this node, if it has one.
   */
  id: string | null;
  /**
   * The roles (CSS classes) of this node.
   */
  readonly roles: string[];
  /**
   * The attributes of this node.
   */
  readonly attributes: Attributes;
  /**
   * The text of this node as a reader sees it: converted, with markup
   * removed and character references decoded.
   */
  readonly plainText: string;
  /**
   * Whether the `name` option is set (`[%name]` or `options=name`).
   */
  hasOption(name: string): boolean;
}

/**
 * Parses and converts AsciiDoc with one configuration.
 *
 * An instance holds everything that shapes a conversion: the safe mode,
 * attributes, extensions, output overrides and highlighters. It keeps no
 * state between documents, so one instance can be used for any number of
 * them, and two instances never affect each other.
 *
 * ```dart
 * final ad = Ptome(attributes: {'icons': 'font'});
 * final html = ad.convert('NOTE: Hello');
 * ```
 */
export declare class Ptome {
  /**
   * Creates a configuration.
   *
   * {@link attributes} apply to every document (and win over the document's own
   * assignments, as `-a` does on the command line, unless the value ends
   * in `@`); a key ending in `!` unsets the attribute. {@link html} overrides
   * the HTML of individual nodes. {@link templateDirs} holds Mustache templates
   * that replace the built-in HTML of the nodes they name, as `-T` does.
   * {@link highlighters} adds syntax highlighters, by the `source-highlighter`
   * value that selects them. {@link baseDir} is where relative paths in
   * documents are resolved from (default: the document's directory, or
   * the working directory). {@link onDiagnostic} sees every message as it is
   * reported, including those of {@link convert}, which returns only the
   * output. {@link fonts} are found by PDFs and EPUBs before the installed
   * fonts; in a browser, so are the page's web fonts ({@link pageFonts}) and
   * the {@link localFonts} families of the visitor's fonts.
   */
  constructor(options?: { safe?: SafeMode; attributes?: Record<string, string>; extensions?: Extension[]; html?: ((node: Node, defaults: HtmlDefaults) => string) | null; templateDirs?: string[]; highlighters?: Record<string, Highlighter>; baseDir?: string | null; onDiagnostic?: ((diagnostic: Diagnostic) => void) | null; fonts?: FontFile[]; pageFonts?: boolean; localFonts?: string[] });
  readonly safe: SafeMode;
  readonly attributes: Record<string, string>;
  readonly extensions: Extension[];
  readonly html: ((node: Node, defaults: HtmlDefaults) => string) | null;
  readonly templateDirs: string[];
  readonly highlighters: Record<string, Highlighter>;
  readonly baseDir: string | null;
  readonly onDiagnostic: ((diagnostic: Diagnostic) => void) | null;
  readonly fonts: FontFile[];
  readonly pageFonts: boolean;
  readonly localFonts: string[];
  /**
   * Loads the code of {@link backend}. On the Dart VM every backend is there;
   * on JavaScript the PDF and EPUB backends load the first time an
   * asynchronous conversion needs them, and {@link convertToBytes} needs them
   * loaded.
   */
  loadBackend(backend: Backend): Promise<void>;
  /**
   * Converts {@link source} to a file of {@link backend}'s format, a PDF or an EPUB:
   * the file's bytes. {@link path} names the source (for messages, and as the
   * base for relative paths, images included); {@link attributes} add to the
   * instance's.
   *
   * On JavaScript the backend must have been loaded ({@link loadBackend}, or
   * any {@link convertToBytesAsync}).
   */
  convertToBytes(source: string, options: { backend: Backend; path?: string | null; doctype?: Doctype | null; attributes?: Record<string, string> }): Uint8Array;
  /**
   * Like {@link convertToBytes}, loading the backend when it isn't, waiting for
   * {@link IncludeResolver}s that return a `Future`, fetching remote content
   * when the `allow-uri-read` attribute is set, and doing the work that
   * doesn't depend on order (images, compression) on other cores.
   *
   * In a browser, which has no file system, the files the conversion
   * reads (images, a theme) are fetched relative to the page instead: its
   * directory stands for the root of the file system. Includes are not.
   */
  convertToBytesAsync(source: string, options: { backend: Backend; path?: string | null; doctype?: Doctype | null; attributes?: Record<string, string> }): Promise<Uint8Array>;
  /**
   * Parses {@link source} into a {@link Document}.
   *
   * {@link path} names the source (for messages, and as the base for relative
   * paths); {@link backend}, {@link doctype} and {@link standalone} set what the document
   * is parsed for, as some attributes depend on them; {@link attributes} add to
   * the instance's attributes.
   */
  parse(source: string, options?: { path?: string | null; backend?: Backend; doctype?: Doctype | null; standalone?: boolean; attributes?: Record<string, string> }): Document;
  /**
   * Parses only the header of {@link source} (title, authors, attributes) into a
   * {@link Document} without blocks; much faster than {@link parse} for reading
   * metadata.
   */
  parseHeader(source: string, options?: { path?: string | null; attributes?: Record<string, string> }): Document;
  /**
   * Converts {@link source}: the body only, or a complete document when
   * {@link standalone} is `true`. {@link backend} makes text ({@link convertToBytes} makes
   * PDFs and EPUBs).
   */
  convert(source: string, options?: { path?: string | null; backend?: Backend; doctype?: Doctype | null; standalone?: boolean; attributes?: Record<string, string> }): string;
  /**
   * Like {@link parse}, waiting for {@link IncludeResolver}s that return a `Future`,
   * and fetching remote content (includes, and assets read from a URI)
   * when the `allow-uri-read` attribute is set.
   */
  parseAsync(source: string, options?: { path?: string | null; backend?: Backend; doctype?: Doctype | null; standalone?: boolean; attributes?: Record<string, string> }): Promise<Document>;
  /**
   * Like {@link convert}, waiting for {@link IncludeResolver}s that return a `Future`,
   * and fetching remote content when the `allow-uri-read` attribute is
   * set.
   */
  convertAsync(source: string, options?: { path?: string | null; backend?: Backend; doctype?: Doctype | null; standalone?: boolean; attributes?: Record<string, string> }): Promise<string>;
  /**
   * Parses the AsciiDoc file at {@link path}.
   *
   * Waits for {@link IncludeResolver}s that return a `Future`, and fetches
   * remote content when the `allow-uri-read` attribute is set, like
   * {@link Ptome.parseAsync}.
   */
  parseFile(path: string, options?: { backend?: Backend; doctype?: Doctype | null; standalone?: boolean; attributes?: Record<string, string> }): Promise<Document>;
  /**
   * Converts the AsciiDoc file at {@link path} and writes the result: to
   * {@link toFile} when given (relative to {@link toDir}, if any), else into {@link toDir},
   * else next to the input file, named after it with the extension of the
   * output format (a PDF or an EPUB too). {@link mkdirs} creates missing output
   * directories. The output is a complete document unless {@link standalone} is
   * `false`.
   *
   * Returns the converted document, with its diagnostics.
   */
  convertFile(path: string, options?: { toFile?: string | null; toDir?: string | null; mkdirs?: boolean; backend?: Backend; doctype?: Doctype | null; standalone?: boolean; attributes?: Record<string, string> }): Promise<Document>;
  /**
   * Converts every AsciiDoc file (`*.adoc`) below {@link directory} into
   * {@link toDir}, keeping the folder structure, and reports each result as it
   * is written.
   *
   * Files and folders whose names start with `_` or `.` are skipped:
   * by convention they hold partials meant to be included, not documents
   * of their own.
   */
  convertTree(directory: string, options: { toDir: string; backend?: Backend; doctype?: Doctype | null; attributes?: Record<string, string> }): AsyncIterable<FileConversion>;
}

/**
 * A problem that stops a document from being parsed or converted.
 */
export declare class PtomeException extends Error {
  constructor(message: string);
  readonly message: string;
}

/**
 * Source code to highlight.
 */
export declare class SourceCode {
  protected constructor();
  readonly source: string;
  readonly language: string | null;
  readonly highlightLines: Uint8Array;
}

/**
 * Where in the source something is.
 */
export declare class SourceLocation {
  protected constructor();
  readonly path: string | null;
  readonly line: number;
}

/**
 * A column of a {@link Table}.
 */
export declare class TableColumn {
  protected constructor();
  readonly number: number;
  /**
   * The width as a percentage of the table width.
   */
  readonly width: number | null;
  readonly style: string | null;
}

/**
 * A numbered unit of a document written in units (`:units:` in its
 * header; see `doc/units.md`): a verse, a chapter, a section, a line.
 */
export declare class Unit {
  protected constructor();
  readonly scheme: string;
  readonly level: string;
  readonly depth: number;
  readonly labels: Record<string, string>;
  readonly id: string;
  readonly reftext: string;
  readonly citation: string;
  readonly path: string;
  readonly line: number;
}

/**
 * A block: a section, paragraph, list, table, delimited block, and so on.
 *
 * Blocks nest: {@link blocks} are the blocks directly inside this one.
 */
export declare abstract class Block extends Node {
  protected constructor();
  /**
   * The title of this block (`.Title` above it, or a section's title), with
   * inline markup converted; `null` when it has none.
   */
  title: string | null;
  /**
   * The title of this block as written in the source; `null` when it has
   * none.
   */
  readonly sourceTitle: string | null;
  /**
   * The style of this block (the first positional attribute, such as
   * `source` or `quote`), if any.
   */
  readonly style: string | null;
  /**
   * Where the block starts in the source.
   */
  readonly location: SourceLocation | null;
  /**
   * The blocks directly inside this one.
   */
  readonly blocks: Block[];
  /**
   * The block's title as inline content (see {@link InlineContent}); empty
   * without a title. Applies the title substitutions.
   */
  readonly titleInlines: InlineContent[];
  readonly plainText: string;
  /**
   * Adds {@link block} as the last block inside this one.
   */
  append(block: Block): void;
  /**
   * Removes this block from its parent.
   */
  remove(): void;
  /**
   * Every node of type {@link T} inside this block (not including itself), in
   * document order: nested blocks, list items, description list terms and
   * descriptions, and table cells.
   */
  descendants<T extends Node = Node>(type?: { prototype: T }): T[];
  /**
   * This block converted to the document's output format.
   */
  convert(): string;
}

/**
 * Handles a block macro (`name::target{@link attributes}` on a line of its own).
 */
export declare class BlockMacro extends Extension {
  /**
   * Handles `name::` macros with {@link process}, which returns the block to put
   * in the macro's place (or `null` to drop it).
   */
  constructor(name: string, process: (macro: BlockMacroContext) => Block | null);
  readonly name: string;
  readonly process: (macro: BlockMacroContext) => Block | null;
}

/**
 * Handles blocks with a custom style (`{@link name}` above a paragraph or a
 * delimited block).
 */
export declare class CustomBlock extends Extension {
  /**
   * Handles `{@link name}` blocks of the kinds in {@link on} with {@link process}, which
   * returns the block to put in their place (or `null` to drop it).
   */
  constructor(name: string, process: (block: CustomBlockContext) => Block | null, options?: { on?: BlockKind[] });
  readonly name: string;
  readonly on: BlockKind[];
  readonly process: (block: CustomBlockContext) => Block | null;
}

/**
 * Adds content to the document head or footer (the `docinfo` slots).
 */
export declare class Docinfo extends Extension {
  /**
   * Adds what {@link content} returns at {@link location}.
   */
  constructor(content: (document: Document) => string | null, options?: { location?: DocinfoLocation });
  readonly content: (document: Document) => string | null;
  readonly location: DocinfoLocation;
}

/**
 * Supplies the content of `include::` directives.
 *
 * {@link resolve} returns the content to include, or `null` to let Ptome
 * read the target as usual. It may return a `Future`; then use the
 * asynchronous methods ({@link Ptome.parseAsync}, {@link Ptome.convertAsync}),
 * which wait for it.
 */
export declare class IncludeResolver extends Extension {
  /**
   * An include resolver running {@link resolve}.
   */
  constructor(resolve: (request: IncludeRequest) => string | null | Promise<string | null>);
  readonly resolve: (request: IncludeRequest) => string | null | Promise<string | null>;
}

/**
 * An inline element: formatted text, a link, an inline image, and so on.
 *
 * Inline elements reach code through the `inlines` of blocks, output
 * overrides and macro extensions. Their {@link text} is already converted.
 */
export declare abstract class Inline extends Node {
  protected constructor();
  /**
   * The converted text of the element, if it has text.
   */
  readonly text: string | null;
  /**
   * The content of the element's text, for an element from `inlines`
   * whose text is part of the text around it (formatted text, a link, a
   * line break); empty otherwise.
   */
  readonly children: InlineContent[];
  readonly plainText: string;
}

/**
 * Handles an inline macro (`name:target{@link attributes}` within text).
 */
export declare class InlineMacro extends Extension {
  /**
   * Handles `name:` macros with {@link process}, which returns the inline element
   * to put in the macro's place (or `null` to drop it).
   */
  constructor(name: string, process: (macro: InlineMacroContext) => Inline | null);
  readonly name: string;
  readonly process: (macro: InlineMacroContext) => Inline | null;
}

/**
 * Edits the converted output of a document.
 */
export declare class Postprocessor extends Extension {
  /**
   * A postprocessor running {@link process}.
   */
  constructor(process: (output: string, document: Document) => string);
  readonly process: (output: string, document: Document) => string;
}

/**
 * Edits the source lines of a document before it is parsed.
 *
 * {@link process} receives the lines (preprocessor directives such as `include::`
 * not yet applied) and returns the lines to parse.
 */
export declare class Preprocessor extends Extension {
  /**
   * A preprocessor running {@link process}.
   */
  constructor(process: (lines: string[], document: Document) => string[]);
  readonly process: (lines: string[], document: Document) => string[];
}

/**
 * Inspects or changes the parsed document before it is converted.
 */
export declare class TreeProcessor extends Extension {
  /**
   * A tree processor running {@link process}.
   */
  constructor(process: (document: Document) => void);
  readonly process: (document: Document) => void;
}

/**
 * An admonition: a `NOTE:` paragraph or a `{@link NOTE}` block.
 */
export declare class Admonition extends Block {
  protected constructor();
  /**
   * The kind of admonition.
   */
  readonly kind: AdmonitionKind;
  /**
   * The converted content: the paragraph text for an admonition paragraph,
   * the converted child blocks for an admonition block.
   */
  readonly content: string;
  /**
   * The paragraph text of an admonition paragraph as inline content (see
   * {@link InlineContent}); empty for an admonition block. Applies the
   * substitutions, as {@link content} does.
   */
  readonly inlines: InlineContent[];
  readonly plainText: string;
}

/**
 * An audio block (`audio::target[]`).
 */
export declare class Audio extends Block {
  protected constructor();
  /**
   * The audio path or URL as written.
   */
  target: string;
}

/**
 * A bibliography anchor (`[[{@link id}]]`).
 */
export declare class BibliographyAnchor extends Inline {
  protected constructor();
  /**
   * The ID of the anchor.
   */
  readonly anchorId: string;
}

/**
 * A UI button (`btn:{@link Save}`).
 */
export declare class Button extends Inline {
  protected constructor();
}

/**
 * A callout in a listing (`<1>`).
 */
export declare class Callout extends Inline {
  protected constructor();
  /**
   * The callout number.
   */
  readonly number: number;
}

/**
 * A callout list (`<1> ...`) explaining the callouts of a listing.
 */
export declare class CalloutList extends Block {
  protected constructor();
  readonly plainText: string;
  /**
   * The items.
   */
  readonly items: ListItem[];
}

/**
 * A cross reference (`<<id>>`, `xref:id[]`).
 */
export declare class CrossReference extends Inline {
  protected constructor();
  /**
   * The ID referred to (including a document path for an inter-document
   * reference, `other.adoc#id`).
   */
  readonly refid: string;
  /**
   * The document path of an inter-document reference, if any.
   */
  readonly path: string | null;
  /**
   * The URL the reference links to.
   */
  readonly target: string;
}

/**
 * A description list (`term:: description`).
 */
export declare class DescriptionList extends Block {
  protected constructor();
  /**
   * The entries: one or more terms with an optional description.
   */
  readonly entries: DescriptionListEntry[];
  readonly plainText: string;
}

/**
 * A discrete heading (`{@link discrete}`): looks like a section title, but
 * starts no section.
 */
export declare class DiscreteHeading extends Block {
  protected constructor();
  /**
   * The heading level, as for a {@link Section}.
   */
  readonly level: number;
  title: string;
  readonly plainText: string;
}

/**
 * A parsed AsciiDoc document.
 */
export declare class Document extends Block {
  protected constructor();
  readonly document: Document;
  /**
   * The document title (the level-0 heading or the `title` attribute),
   * with inline markup converted; `null` when it has none.
   */
  title: string | null;
  /**
   * The document title as written in the header (`= Title`), before
   * substitutions; `null` when the header has no title.
   */
  readonly sourceTitle: string | null;
  /**
   * The document title as inline content (see {@link InlineContent}); empty
   * without a title.
   */
  readonly titleInlines: InlineContent[];
  /**
   * The attributes the document header sets, in source order: name to
   * value, or to `null` for an attribute it unsets (`:name!:`). Unlike
   * {@link attributes}, this leaves out the built-in attributes and those given
   * through the API.
   */
  readonly headerAttributes: Record<string, string | null>;
  /**
   * The source this document was parsed from.
   */
  readonly source: string;
  /**
   * The authors from the document header.
   */
  readonly authors: Author[];
  /**
   * The document type.
   */
  readonly doctype: Doctype;
  /**
   * The document's numbered units (`:units:` in its header; see
   * `doc/units.md`), in document order: books, chapters and verses;
   * sections and their subdivisions. Empty for a document not written in
   * units.
   */
  readonly units: Unit[];
  /**
   * The messages reported while parsing and converting this document.
   */
  readonly diagnostics: Diagnostic[];
  /**
   * The document's index: the terms its index terms (`(((...)))`,
   * `((...))`, `indexterm:[]`, `indexterm2:[]`) name, by letter, each
   * with where it is used, whether or not the document has an `{@link index}`
   * section. Collected by converting the document (its messages are left
   * out of {@link diagnostics}).
   *
   * Throws a {@link StateError} when the document was parsed for a backend
   * other than HTML.
   */
  readonly index: IndexLetter[];
  readonly attributes: Attributes;
  /**
   * This document with the header attribute {@link name} set to {@link value}: its
   * {@link source} rewrites only the attribute entry that sets {@link name} last (or,
   * when the header has none, adds one at the end of the header) and
   * keeps every other byte as written; the result is that source, parsed
   * with the same settings as this document. An unset entry (`:name!:`)
   * becomes a set one.
   *
   * Throws an {@link PtomeException}, and edits nothing, when the source
   * alone can't make the edit: the header sets {@link name} in an include or
   * under a preprocessor conditional, or ends inside an include. Throws an
   * {@link ArgumentError} for a {@link value} of more than one line.
   */
  withAttribute(name: string, value: string): Document;
  /**
   * This document without the header attribute entries for {@link name}: its
   * {@link source} drops only their lines. See {@link withAttribute}.
   */
  withoutAttribute(name: string): Document;
  /**
   * The unit with the ID {@link idOrAddress} (`v-exo-34-6`), or the first unit
   * of the passage at that address, as the document's schemes cite it
   * (`Exod 34:6`, `Exodus 34:6-8`). `null` when there is no such unit or
   * the document is not written in units.
   */
  unit(idOrAddress: string): Unit | null;
  /**
   * The document converted to its output format: the body only, or a
   * complete page when {@link standalone} is `true` (default: as parsed).
   */
  convert(options?: { standalone?: boolean | null }): string;
  /**
   * The document converted to HTML; see {@link convert}.
   *
   * Throws a {@link StateError} when the document was parsed for another
   * backend.
   */
  toHtml(options?: { standalone?: boolean | null }): string;
}

/**
 * An example block (`====`).
 */
export declare class Example extends Block {
  protected constructor();
}

/**
 * A footnote (`footnote:{@link text}`), or a reference to one
 * (`footnote:id[]`).
 */
export declare class Footnote extends Inline {
  protected constructor();
  /**
   * The footnote number.
   */
  readonly number: number | null;
  /**
   * Whether this refers to a footnote defined elsewhere.
   */
  readonly isReference: boolean;
  /**
   * The note stream of a note in units (`tn`), if it is one
   * (`note:tn[…]`).
   */
  readonly stream: string | null;
  /**
   * The note's caller in its stream, if the stream has callers.
   */
  readonly caller: string | null;
}

/**
 * Formatted text.
 */
export declare class Formatted extends Inline {
  protected constructor();
  /**
   * The kind of formatting.
   */
  readonly kind: FormattedKind;
}

/**
 * An icon (`icon:name[]`).
 */
export declare class Icon extends Inline {
  protected constructor();
  /**
   * The icon name.
   */
  readonly name: string;
}

/**
 * An image block (`image::target[]`).
 */
export declare class Image extends Block {
  protected constructor();
  /**
   * The image path or URL as written.
   */
  target: string;
  /**
   * The alternative text.
   */
  readonly alt: string;
  /**
   * The width, if given.
   */
  readonly width: string | null;
  /**
   * The height, if given.
   */
  readonly height: string | null;
  /**
   * The link target, if the image links somewhere.
   */
  readonly link: string | null;
  readonly plainText: string;
}

/**
 * An index term (`indexterm:[...]`, `((term))`).
 */
export declare class IndexTerm extends Inline {
  protected constructor();
  /**
   * The terms: primary, then secondary and tertiary, if any.
   */
  readonly terms: string[];
  /**
   * Whether the term also appears in the text (`((term))`).
   */
  readonly isVisible: boolean;
}

/**
 * An inline anchor (`[{@link id}]`, `anchor:id[]`).
 */
export declare class InlineAnchor extends Inline {
  protected constructor();
  /**
   * The ID of the anchor.
   */
  readonly anchorId: string;
}

/**
 * An inline image (`image:target[]`).
 */
export declare class InlineImage extends Inline {
  protected constructor();
  /**
   * The image path or URL as written.
   */
  readonly target: string;
  /**
   * The alternative text.
   */
  readonly alt: string;
  readonly plainText: string;
}

/**
 * Inline math (`stem:[...]`, `latexmath:[...]`, `asciimath:[...]`).
 */
export declare class InlineStem extends Inline {
  protected constructor();
  /**
   * The notation of the math.
   */
  readonly notation: StemNotation;
}

/**
 * A keyboard shortcut (`kbd:[Ctrl+T]`).
 */
export declare class Keyboard extends Inline {
  protected constructor();
  /**
   * The keys.
   */
  readonly keys: string[];
  readonly plainText: string;
}

/**
 * A forced line break (` +` at the end of a line).
 */
export declare class LineBreak extends Inline {
  protected constructor();
}

/**
 * A link to a URL (`https://...`, `link:target{@link text}`, an email address).
 */
export declare class Link extends Inline {
  protected constructor();
  /**
   * The URL.
   */
  readonly target: string;
}

/**
 * An item of a list, or a term or description of a description list.
 */
export declare class ListItem extends Block {
  protected constructor();
  /**
   * The text of the item as written in the source.
   */
  readonly source: string;
  /**
   * The text of the item with inline markup converted.
   */
  readonly content: string;
  /**
   * The text of the item as inline content (see {@link InlineContent}).
   * Applies the substitutions, as {@link content} does.
   */
  readonly inlines: InlineContent[];
  /**
   * For a checklist item, whether it is checked; otherwise `null`.
   */
  readonly checked: boolean | null;
  readonly plainText: string;
}

/**
 * A listing block (`----`), including source code blocks.
 */
export declare class Listing extends Block {
  protected constructor();
  /**
   * The source language, for a source block.
   */
  readonly language: string | null;
  /**
   * The text of the block as written in the source.
   */
  readonly source: string;
  /**
   * The converted text: inline markup applied for prose, special
   * characters escaped for verbatim text.
   */
  readonly content: string;
  /**
   * The text as inline content (see {@link InlineContent}): text and the inline
   * elements in it, nested. Applies the substitutions, as {@link content} does.
   */
  readonly inlines: InlineContent[];
  readonly plainText: string;
}

/**
 * A literal block (`....` or indented text).
 */
export declare class Literal extends Block {
  protected constructor();
  /**
   * The text of the block as written in the source.
   */
  readonly source: string;
  /**
   * The converted text: inline markup applied for prose, special
   * characters escaped for verbatim text.
   */
  readonly content: string;
  /**
   * The text as inline content (see {@link InlineContent}): text and the inline
   * elements in it, nested. Applies the substitutions, as {@link content} does.
   */
  readonly inlines: InlineContent[];
  readonly plainText: string;
}

/**
 * A menu selection (`menu:File{@link Save}`).
 */
export declare class Menu extends Inline {
  protected constructor();
  /**
   * The top-level menu.
   */
  readonly menu: string;
  /**
   * The submenus leading to the item.
   */
  readonly submenus: string[];
  /**
   * The menu item, if any.
   */
  readonly item: string | null;
  readonly plainText: string;
}

/**
 * A note's caller in the text, for a stream whose notes are gathered in
 * an entry (a reference Bible's lettered cross-references).
 */
export declare class NoteCall extends Inline {
  protected constructor();
  /**
   * The note's stream (`x`).
   */
  readonly stream: string;
  /**
   * The caller (`a`).
   */
  readonly caller: string;
}

/**
 * The entry a unit's notes of a stream are gathered in (a verse's
 * cross-references).
 */
export declare class NoteEntry extends Inline {
  protected constructor();
  /**
   * The stream (`x`).
   */
  readonly stream: string;
}

/**
 * An open block (`--`).
 */
export declare class Open extends Block {
  protected constructor();
}

/**
 * An ordered (`.` or `1.`) list.
 */
export declare class OrderedList extends Block {
  protected constructor();
  readonly plainText: string;
  /**
   * The items.
   */
  readonly items: ListItem[];
  /**
   * The number of the first item.
   */
  readonly start: number;
}

/**
 * A block of a kind Ptome does not define, created by an extension.
 */
export declare class OtherBlock extends Block {
  protected constructor();
  /**
   * The block's context, as the extension named it.
   */
  readonly context: string;
}

/**
 * A page break (`<<<`).
 */
export declare class PageBreak extends Block {
  protected constructor();
}

/**
 * A paragraph.
 */
export declare class Paragraph extends Block {
  protected constructor();
  /**
   * The text of the block as written in the source.
   */
  readonly source: string;
  /**
   * The converted text: inline markup applied for prose, special
   * characters escaped for verbatim text.
   */
  readonly content: string;
  /**
   * The text as inline content (see {@link InlineContent}): text and the inline
   * elements in it, nested. Applies the substitutions, as {@link content} does.
   */
  readonly inlines: InlineContent[];
  readonly plainText: string;
}

/**
 * A passthrough block (`++++`): output as written.
 */
export declare class Passthrough extends Block {
  protected constructor();
  /**
   * The text of the block as written in the source.
   */
  readonly source: string;
  /**
   * The converted text: inline markup applied for prose, special
   * characters escaped for verbatim text.
   */
  readonly content: string;
  /**
   * The text as inline content (see {@link InlineContent}): text and the inline
   * elements in it, nested. Applies the substitutions, as {@link content} does.
   */
  readonly inlines: InlineContent[];
  readonly plainText: string;
}

/**
 * The content of a document before its first section.
 */
export declare class Preamble extends Block {
  protected constructor();
}

/**
 * A quote block (`____`, or `{@link quote}`).
 */
export declare class Quote extends Block {
  protected constructor();
  /**
   * Who the quote is attributed to.
   */
  readonly attribution: string | null;
  /**
   * The work the quote is from.
   */
  readonly citation: string | null;
  readonly plainText: string;
}

/**
 * A section.
 */
export declare class Section extends Block {
  protected constructor();
  /**
   * The section level: 0 for a book part, 1 for `==`, and so on.
   */
  readonly level: number;
  title: string;
  /**
   * The section number (`1.2`), when sections are numbered.
   */
  readonly number: string | null;
  /**
   * The kind of section (`section`, `chapter`, `appendix`, `part`,
   * `preface`, `abstract`, `colophon`, `glossary`, ...).
   */
  readonly sectionName: string;
  /**
   * Whether this is a special section (appendix, glossary, ...).
   */
  readonly isSpecial: boolean;
}

/**
 * A sidebar (`****`).
 */
export declare class Sidebar extends Block {
  protected constructor();
}

/**
 * A math block (`{@link stem}`).
 */
export declare class Stem extends Block {
  protected constructor();
  /**
   * The notation of the math.
   */
  readonly notation: StemNotation;
  /**
   * The text of the block as written in the source.
   */
  readonly source: string;
  /**
   * The converted text: inline markup applied for prose, special
   * characters escaped for verbatim text.
   */
  readonly content: string;
  /**
   * The text as inline content (see {@link InlineContent}): text and the inline
   * elements in it, nested. Applies the substitutions, as {@link content} does.
   */
  readonly inlines: InlineContent[];
  readonly plainText: string;
}

/**
 * A table.
 */
export declare class Table extends Block {
  protected constructor();
  /**
   * The header rows.
   */
  readonly head: TableCell[][];
  /**
   * The body rows.
   */
  readonly body: TableCell[][];
  /**
   * The footer rows.
   */
  readonly foot: TableCell[][];
  /**
   * The columns.
   */
  readonly columns: TableColumn[];
  readonly plainText: string;
}

/**
 * A cell of a {@link Table}.
 */
export declare class TableCell extends Block {
  protected constructor();
  /**
   * The text of the cell as written in the source.
   */
  readonly source: string;
  /**
   * The converted text of the cell (for an AsciiDoc cell, the converted
   * blocks).
   */
  readonly content: string;
  /**
   * How many columns the cell spans.
   */
  readonly colspan: number;
  /**
   * How many rows the cell spans.
   */
  readonly rowspan: number;
  /**
   * The blocks of an AsciiDoc cell (`a|`); empty for other cells.
   */
  readonly blocks: Block[];
  readonly plainText: string;
}

/**
 * A table of contents placed with the `toc::[]` macro.
 */
export declare class TableOfContents extends Block {
  protected constructor();
}

/**
 * A thematic break (`'''`).
 */
export declare class ThematicBreak extends Block {
  protected constructor();
}

/**
 * A unit that is blocks (see `doc/units.md`): a statute's provision, a
 * catechism's question, a stanza, with its blocks as children.
 */
export declare class UnitBlock extends Block {
  protected constructor();
  /**
   * The name of the unit's scheme (`eu`).
   */
  readonly scheme: string;
  /**
   * The name of the unit's level (`point`).
   */
  readonly level: string;
  /**
   * The unit as its scheme cites it (`Article 6(1)(a)`).
   */
  readonly citation: string;
}

/**
 * Where a unit starts in a text (its anchor and label), or what it prints
 * at its end (see `doc/units.md`).
 */
export declare class UnitMark extends Inline {
  protected constructor();
  /**
   * Whether this is the unit's start (else what it prints at its end).
   */
  readonly isStart: boolean;
  /**
   * The name of the unit's scheme (`bible`).
   */
  readonly scheme: string;
  /**
   * The name of the unit's level (`verse`).
   */
  readonly level: string;
  /**
   * The unit as its scheme cites it (`Exod 34:6`).
   */
  readonly citation: string;
  /**
   * The unit's reftext (`Exodus 34:6`).
   */
  readonly reftext: string;
  /**
   * The unit's own label (`6`).
   */
  readonly label: string;
}

/**
 * An unordered (`*`) list, including checklists.
 */
export declare class UnorderedList extends Block {
  protected constructor();
  readonly plainText: string;
  /**
   * The items.
   */
  readonly items: ListItem[];
  /**
   * Whether this is a checklist (`* {@link x} done`).
   */
  readonly isChecklist: boolean;
}

/**
 * A verse block (`{@link verse}`).
 */
export declare class Verse extends Block {
  protected constructor();
  /**
   * Who the verse is attributed to.
   */
  readonly attribution: string | null;
  /**
   * The work the verse is from.
   */
  readonly citation: string | null;
  /**
   * The text of the block as written in the source.
   */
  readonly source: string;
  /**
   * The converted text: inline markup applied for prose, special
   * characters escaped for verbatim text.
   */
  readonly content: string;
  /**
   * The text as inline content (see {@link InlineContent}): text and the inline
   * elements in it, nested. Applies the substitutions, as {@link content} does.
   */
  readonly inlines: InlineContent[];
  readonly plainText: string;
}

/**
 * A video block (`video::target[]`).
 */
export declare class Video extends Block {
  protected constructor();
  /**
   * The video path, URL or ID as written.
   */
  target: string;
  /**
   * The hosting service (`youtube`, `vimeo`), or `null` for a file.
   */
  readonly service: string | null;
}

/**
 * The default configuration: `secure` safe mode, no attributes, no
 * extensions.
 */
export declare const asciidoc: Ptome;
/**
 * The Asciidoctor release Ptome is compatible with.
 */
export declare const asciidoctorVersion: string;
/**
 * The version of Ptome.
 */
export declare const ptomeVersion: string;
