description = "Anchor: a pool document cut down and sanitized."
source = "pool:asciidoctor-pdf/spec/fixtures/bmp.adoc"
formats = ["pdf"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
