description = "Anchor: a pool document cut down and sanitized."
source = "pool:asciidoc-docs/docs/modules/sections/examples/colophon.adoc"
formats = ["epub3"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
