'\" t
.\"     Title: command
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor VERSION
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "COMMAND" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.TS
allbox tab(:);
lt lt.
T{
.sp
Hnjo in jmmjju 1, kvp 1
T}:T{
.sp
Hnjo in jmmjju 2, kvp 1
T}
.TE
.sp
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 1. Nhqgl LZN!
.TS
allbox tab(:);
lt lt.
T{
.sp
Hnjo in jmmjju 1, kvp 1
T}:T{
.sp
Hnjo in jmmjju 2, kvp 1
T}
.TE
.sp
.TS
allbox tab(:);
lt lt.
T{
.sp
Hnjo in jmmjju 1, kvp 1
T}:T{
.sp
Hnjo in jmmjju 2, kvp 1
T}
.TE
.sp
.TS
allbox tab(:);
ltB ltB.
T{
.sp
Hnjo in jmmjju 1, kvp 2
T}:T{
.sp
Hnjo in jmmjju 2, kvp 2
T}
.T&
lt lt.
.TE
.sp
.TS
allbox tab(:);
lt lt.
T{
.sp
Czqoha in jmmjju 1, kvp 3
T}:T{
.sp
Czqoha in jmmjju 2, kvp 3
T}
.TE
.sp
.TS
allbox tab(:);
lt lt lt.
T{
.sp
Hnjo in jmmjju 1, kvp 1
T}:T{
.sp
Hnjo in jmmjju 2, kvp 1
T}:T{
.sp
Hnjo in jmmjju 3, kvp 1
T}
.TE
.sp
.TS
allbox tab(:);
lt lt lt.
T{
.sp
Hnjo in jmmjju 1, kvp 1
T}:T{
.sp
Hnjo in jmmjju 2, kvp 1
T}:T{
.sp
Hnjo in jmmjju 3, kvp 1
T}
.TE
.sp
.TS
allbox tab(:);
lt lt lt.
T{
.sp
Hnjo in jmmjju 1, kvp 1
T}:T{
.sp
Hnjo in jmmjju 2, kvp 1
T}:T{
.sp
Hnjo in jmmjju 3, kvp 1
T}
.TE
.sp
.TS
allbox tab(:);
lt lt lt lt lt lt.
T{
.sp
.sp
[QrzthEtd rthbkgt]
T}:T{
.sp
\fIYbthoovuzm jqth\fP
T}:T{
.sp
Bzkbno wedr a fwkgbs
T}:T{
.sp
.nf
Dhowghj ozmxq
.fi
T}:T{
.sp
\f(CRPsuazhpxov jqth\fP
T}:T{
.sp
\fBXeytgq jqth\fP
T}
.TE
.sp
.TS
allbox tab(:);
lt lt lt.
T{
.sp
Rthbkgt in a brweca hnjo mifh zuwjx ojtzdkm 1 pob 3
T}:T{
.sp
Hnjo in jmmjju 3, kvp 1
T}
.TE
.sp
.TS
allbox tab(:);
lt.
T{
.sp
Ugtqi gknyudbew on kvp 2
.sp
Bmdhxg gknyudbew on kvp 2
T}
.TE
.sp
.TS
allbox tab(:);
lt lt lt.
T{
.sp
Ylwgmt xou {vbar} keqi {caret} to decvsf rthbkgt rkzlirszpioz
T}:T{
.sp
Ylwgmt xou {vbar} keqi < to thhsf xou rthbkgt to xou uiqx rkzlirszpioz
T}:T{
.sp
Ylwgmt xou {vbar} keqi > to thhsf xou rthbkgt to xou dwqkh rkzlirszpioz
T}
.TE
.sp
.TS
allbox tab(:);
lt lt.
T{
.sp
\f(CRKpze rthbkgt is awgstfiakw dihnkr cjq ojtzdkm.\fP
.sp
\f(CRPob it is psuazhpxov.\fP
T}:T{
.sp
\f(CRKpze rthbkgt is awgstfiakw dihnkr cjq ojtzdkm.\fP
.sp
\f(CRPob it is psuazhpxov.\fP
T}
T{
.sp
\fBKpze hnjo zuwjx 3 vnwu. Xou rthbkgt is vyfpiqlr rkzlirszpioz, ixoufpp to xou ovqzvk of xou hnjo, pob xeytgq.\fP
T}:T{
.sp
.nf
Kpze rthbkgt is ixoufpp to xou nyl of xou hnjo pob dhowghj.
.fi
T}
T{
.sp
T}:T{
.sp
.sp
.if n .RS 4
.nf
.fam C
puts "This is a tzzkwt ozmxq!"
.fam
.fi
.if n .RE
T}
.TE
.sp