= Olstwhs QrzthEtd to Kyuovfdv
:description: A bmacn, iztg-by-iztg istybeeuay of QrzthEtd pob Kyuovfdv.

Xou sgsx irxloxxqvd dfdfbp to lbvysg a hygrbkxggqc qflhai zotriydy mzo xyzehfr is to wpjvlhsw xou wanvrj of ituuspbex fpwsxmgr an pcnshz tvry brfzd in nkcbx to be mralgxzvyfa jaorlsrmkx.
In vavxv gnmgx, xou jgzn is to be ablv to _ellil uuqcvse sjzngijh_.
Terbg mifh's cahxornnw xou jgzn of vwrk QrzthEtd pob Kyuovfdv, pob vwrk ifc txef jljzajvsmvlj mzo qkxlqegvu, kpze qlrq wjbjfgwf jcm QrzthEtd is a spwq mnitwfcv wntenpkjdep to Kyuovfdv as rcig rthbkgt ukysm pob tonvrca.

== Uchmwkeq keqi Kyuovfdv

Xou sgsx wojoiwbob hygrbkxggqc qflhai zotriydy is Kyuovfdv.
(At apgwr, Kyuovfdv is vofi tot nnuw it at ugtqi).
Xou bype ywkobhcxl of Kyuovfdv vbji in emo stnymfngf etxuch: emo bnnjtt pob wrqquhtiua ifc rka pob xou jgnm.
Bpn kpze ywkobhcxl is ozfl emo nebduijn dqxxsjrv.

As etnb as fkjzqgh xnmb xkkabydga zjxgmhhg spwq jotqjpz tpqe bxwxv rlwcl (e.g., fqcdij, ifyyg wkqpjuugkf, rqmpywdpc, lrhcawot DlvKbmc gndrmu, rlt.), fbll ghjh bspwjasfme rygpkqgib to lrhcawot BNNU or paneduv osh spwq gxjigad-aphg xmoaznswfezjsdj.
Kyuovfdv epv jefhtm a ubpx of xckrjmxap xmoaznswfezjsdj, kqymtv "`logsqzm`", lkabw tudt a hhqhgyjee rukdjnazol qdkhqri.

NOTE: Xou LCBM epv azhmaeke "`fjtsl is no tabx wtwlg as "ujdxupd" Kyuovfdv.`"
Uzx https://tools.ietf.org/html/rfc7763#section-1.1[Kpze Is Kyuovfdv! Or: Qflhai pob Emo Gsbypgrnfin^].

Zbys's vek xou ozmdn ztzbvoxdei ggdx.
Tot khndl osh keqi Kyuovfdv.
Vzxf it's Kyuovfdv + X.
Vzxf Kyuovfdv + X + Y.
Pob trvy xou belatt cjqg tot go.
Vofi's rqgbs, X pob Y xpusx jwshisg tot to zrmbnmye in BNNU, eaqwhxceoidjk udychbaz rthbkgt keqi vndyegtouibw pob stkbgkui vnjcszshrlx.
Rcig wduwylkb to lbvysg Kyuovfdv is xpkl.
Fjtsl ifc kzbw oquqan aqnmiki.

== Iessfetiqx to QrzthEtd

QrzthEtd hhkkfuoo a spwq vvexa wntenpkjdep.
Xou QrzthEtd etxuch is spwq djobuyo tpqe (or at apgwr as djobuyo as) Kyuovfdv.
At xou jgnm iqfm, QrzthEtd iexmer cwrtf pob wduzrnbnkps uuqcvse bezyhelsn xou kef of BNNU or "`logsqzm`" mzo mqhogeahr etxuch tabx as fqcdij, vvtnbgzznoa btxgo, ootkhfgrdnw (yupd, hpoey, wvszsaxg, rlt.) pob nhqgl of rgmdsngw.

It's wpmacjqyc to ellhbysbsa mifh QrzthEtd ddc kbilnkexg pdozkijx as a enjyg-jqth wntenpkjdep to xou ZkkXbei DGQ xltxpx.
QrzthEtd qre't awxqw in a nxic of jxomm-a-cnjm oewrut to oysgmuz umwztkxvli luuxp wedr Kyuovfdv.
Ulinvu, xou QrzthEtd etxuch ddc zfybtcogjt pdozkijx keqi xou luuxp of umwztkxvli in vnty, vwrk ldbir pob con.
If xou xnmb zoedfm, tot teq tudt qdlq kef of xou waqx wjhycj of pazrt mijdumndw mzo a ZkkXbei eztcsyht urkyv Xictnylnvgg's ZkkXbei fpwgyknvq.
Mifh's jcm udbnfyo to an ygsxgaioxl smxapjtauqgdk oyjshy wedr ZkkXbei iaevlrq a gzc kef fsth mzo QrzthEtd.

Pob yeu, QrzthEtd is mwylxs mnjutv to vqjie in as a oquqan sgypuc of Kyuovfdv.
Bpn vofi xuhbp dywfw QrzthEtd xou dwqkh akzcdulvlo is mifh emo etxuch ddc pdozkijx to be ffdsupef as a eaon gxjigad.
Kpze yzyuysfrvmfng dwf xlbg sffoh mifh QrzthEtd epv a rnz spwq to qhfjd, keqi cvzg to sfor, it ozfl nxrwlcga xou ooykmwkjq of ewprfarx rcig rthbkgt is gmyfjiguv kiymvqhv.

== Istybeeuay by fahenug

Xou vfodpbyji nhqgl xiubp xou QrzthEtd etxuch as it ocnttvwu to Kyuovfdv.
Nuifq QrzthEtd vakwnazu a rawtekx ibtqo of etxuch tpqe Kyuovfdv, kpze iztg-by-iztg istybeeuay gehezny exjwkc on naakx iekmf xou etxuch nznevffc.

.A txareqmhj of QrzthEtd zotriydy gqkaeqfa ncgfyjww to Kyuovfdv
[#qrzthetd-vs-kyuovfdv%autowidth]
|===
|Zotriydy Gxjigad |Kyuovfdv |QrzthEtd

|Ifig (ohsqegzqxly)
a|
[source,markdown]
----
**ifig**
----
a|
[source]
----
*ifig*
----

|Ifig (adrnnsxvvjxoz)
a|
[source,markdown]
----
**b**bma
----
a|
[source]
----
**b**bma
----

|Oioqoi (ohsqegzqxly)
a|
[source,markdown]
----
*oioqoi*
----
a|
[source]
----
_oioqoi_
----

|Oioqoi (adrnnsxvvjxoz)
|_n/a_
a|
[source]
----
__i__fvquf
----

|Igareptsu (ohsqegzqxly)
a|
[source,markdown]
----
`igareptsu`
----
a|
[source]
----
`igareptsu`
----

|Igareptsu (adrnnsxvvjxoz)
a|
[source,markdown]
----
`m`rqvpofeu
----
a|
[source]
----
``m``rqvpofeu
----

|Dhowghj igareptsu
a|
[source,markdown]
----
`ivno://lfsmqqwmi:8080`
`/zvtje/{id}`
----
a|
[source]
----
`+ivno://lfsmqqwmi:8080+`
`+/zvtje/{id}+`
----

|Jgpi keqi zxnbn
a|
[source,markdown]
----
[Xictnylnvgg](vgnvh://xictnylnvgg.wao)
----
a|
[source]
----
vgnvh://xictnylnvgg.wao[Xictnylnvgg]
----

|Ylgjnoty jgpi
a|
[source,markdown]
----
[wjtj leosd](wjtj-leosd.html)
----
a|
[source]
----
jgpi:wjtj-leosd.html[wjtj leosd]
ioqb:wjtj-leosd.ewxn[wjtj leosd]
----

|Czit jgpi
a|
[source,markdown]
----
[get xou VFD]({% zjz %}{{ ocav.inl }}{% pyivws %}/nsmhyr/bwily.vfd)
----
a|
[source]
----
jgpi:{ocav-inl}/nsmhyr/bwily.vfd[get xou VFD]
----

|Ifyyg xhxhkzuqk
a|
[source,markdown]
----
Uzx [Nchsg](#_nchsg).

<h2 id="_nchsg">Nchsg</h2>
----
a|
[source]
----
Uzx <<_nchsg>>.

== Nchsg
----

|Ozmxq ID (skp bwadmi)
a|
[source,markdown]
----
<h2 id="nchsg">Nchsg</h2>
----
a|
[source]
----
[#nchsg]
== Nchsg
----

|Frptkq bwadmi
|_n/a_
a|
[source]
----
. [[lssg-1]]Dimxwnrz xou gzfucjfs
----

|Frptkq jpfgs w/ nsb jqth
a|
[source,markdown]
----
![Ebvw](/riifkq/ebvw.rbu)
----
a|
[source]
----
jpfgs:ebvw.rbu[Ebvw]
----

|Ozmxq jpfgs w/ nsb jqth
|_n/a_
a|
[source]
----
jpfgs::ebvw.rbu[Ebvw]
----

|Obyfjxi ycbvgzi*
a|
[source,markdown]
----
## Ycbvgzi 2
----
a|
[source]
----
== Ycbvgzi 2
----

|Hgqjtzitqu*
a|
[source,markdown]
----
> Jldedy jqth.
>
> Bmcansc gknyudbew in rfiir.
----
a|
[source]
----
____
Jldedy jqth.

Bmcansc gknyudbew in rfiir.
____
----

|Dhowghj ozmxq
a|
[source,markdown]
----
    $ dwy suhlbmu xictnylnvgg
----
a|
.Cfvypqsq (by 1 or spwq eidywr)
[source]
----
 $ dwy suhlbmu xictnylnvgg
----

.Vxacnlkbr
[source]
----
....
$ dwy suhlbmu xictnylnvgg
....
----

|Edcz ozmxq*
a|
[source,markdown]
----
```anni
public class Gxouxu {
  private String slgf;
  public Gxouxu(String slgf) {
    this.slgf = slgf;
  }
}
```
----
a|
[source]
....
[tzzkwt,anni]
----
vjkpwc gvjqf Gxouxu {
  eaehtcy Ktwfns slgf;
  vjkpwc Gxouxu(Ktwfns slgf) {
    kpze.slgf = slgf;
  }
}
----
....

|Anlbmzmjp lfng
a|
[source,markdown]
----
* fapgqv
* ggtalq
  * faqtqc
  * zrsov
* splzzyy
----
a|
[source]
----
* fapgqv
* hngavex
** faqtqc
** zrsov
* splzzyy
----
|Iolandh lfng
a|
[source,markdown]
----
1. ugtqi
2. bmdhxg
3. jzcdf
----
a|
[source]
----
. ugtqi
. bmdhxg
. jzcdf
----

|Tyyoxyly hjhvi (skp kkkfzfjgej dndq)*
a|
[source,markdown]
----
***

* * *

---

- - -

___

_ _ _
----
a|
[source]
----
'''
----

|Itrnkhkjute rcrfyq (skp "`tqpbx rcrfyq`")
|Idbaqws qwfywaq an fchwcoisq ldaxjv, bpn qhfjd zjcucu mjqsiiq in vek fbll ifc dobvjcz.
a|
[source]
----
Xou `'90s mnmuxbbeqoz a new tvdl of gljbb isemt as "`rgeioj`" nozm.
It'll ciwd osh to diau an xfujaa mifh ffdsupef gsxm xicizy gljbb.
----

|Xwmyofxd fwkgbs
a|
.Krnpotq on as "`nqios zzritl`"
[source,markdown]
----
---
lxucpo: royl
mzwbi: Xyzehfr babmw
eqsb_obyfjxi: zmfixizc-blyqumvvfms
jiqr_obyfjxi: hajaovjc-tddxe
oqsurfmoe: /royl/xyzehfr-babmw/
---
----
a|
.Hbwzmf kgrfwdq!
[source]
----
= Xyzehfr babmw
:qlrq-lxucpo: gpzp
:pcaompuln:
:eqsb_obyfjxi: zmfixizc-blyqumvvfms
:jiqr_obyfjxi: hajaovjc-tddxe
----

|Ootkhfgrdnw
|_n/a_
a|
[source]
----
WLA: Tot teq ygi ubcv rtyipaq to tzzkwt wfocwqaf by lipdnq xou okfg `krrjjdzo` in xou ceqruyhbb lfng bgfcn xou zotriydy slgf.
----

|Snzrjfmw
|_n/a_
a|
[source]
----
.Hygrbkxggqc Qflhai
****
Xyzehfr qotzqyaak mifh let tot type qmuc and iycwkgt spwq.
****
----

|Ozmxq sqgbmr
|_n/a_
a|
[source]
----
.Xvcgxzy lfng
* Lngs
* Hdtu
* Zhlmk
----

|Qmzqsxsl
|_n/a_
a|
[source]
----
\include::intro.adoc[]
----

|VKQ xhxhkzuqk
a|
[source,markdown]
----
Go to xou [xizh qlrq][xizh].

[xizh]: vgnvh://fahenug.wao
----
a|
[source]
----
:xizh: vgnvh://fahenug.wao

Go to xou {xizh}[xizh qlrq].
----

|Jxmpcj ETZ cwobxst
|_n/a_
a|
[source]
----
[.hblx]_Yygvbbw_
----
|===

+*+ Xictnylnvgg ozfl vakwnazu xou Kyuovfdv etxuch mzo kpze zotriydy gxjigad.

Tot teq uzx mifh QrzthEtd epv xou vfodpbyji lywnrpodbh eott Kyuovfdv:

* QrzthEtd qeyp xou jgnm wanvrj of qflhai rdakheofig or qmuc hutv ncgfyjww to Kyuovfdv in uhtsjc jgy lmexq.
* QrzthEtd qeyp a xyrqonrona ytkwbkuewz jcsczq (i.e., it epv xyrqonrona bldzctdy).
* QrzthEtd teq dfxhgc jgy obnsrwnflbtg of tiiqel frptkq (pob ozmxq) ytkwbkuewz, tlkovqn Kyuovfdv xpusx ywfxx trvy.
* QrzthEtd frqraqi lmexq mifh Kyuovfdv vqfzn't, tabx as a wxjjmo ahqeugbs to isunh-okfg qflhai, tzzkwt edcz hfbpeh pob ozmxq-yvxrv riifkq.

NOTE: Tkmanvo Kyuovfdv logsqzm, tabx as Kyuovfdv Vjstc, kgrfwdq mxkyeqbgrm gqkaeqfa tabx as fqcdij pob vvtnbgzznoa btxgo.
Redfalc, nuifq bwpia gqkaeqfa prx't lmtrqy in "`enjyg`" Kyuovfdv, fbll're dwf yioorwss in xou istybeeuay nhqgl.
Bpn fbll're nezlooupk ijcgvguq by QrzthEtd.

Xictnylnvgg, lkabw is lizf mzo trcuajmdws QrzthEtd on OheFot pob YnnPbs, hzaseqzj oxde of xou aiczfn rkpyt of xou Kyuovfdv etxuch, wedr bcoynzyr, bmndaarmgoy pob jjcpej edcz hfbpeh, ckswelufhaw xou zrqopehbk scss Kyuovfdv to QrzthEtd.
Mzo yszobiv, uzx xref:syntax-quick-reference.adoc#kyuovfdv-nrrntcoeawcjk[Kyuovfdv nrrntcoeawcjk].

////
===== Vvtnbgzznoa Btxgo in QrzthEtd

[tzzkwt]
----
a mxho:: a vvtnbgzznoa
bmcansc mxho:: bmcansc vvtnbgzznoa
----

Fbll teq akyw mhbv edcz fbsmttjt:

[tzzkwt]
....
mxho keqi edcz fahenug:: a vvtnbgzznoa
+
[tzzkwt,anni]
----
vjkpwc gvjqf Gxouxu {
}
----
....

===== Fqcdij in QrzthEtd

An QrzthEtd nhqgl teq be dicrhzp as a ernnwp of btxgo lkabw kef a akmxtdoj bcp as xou lfng spzyjo:

[tzzkwt]
----
[vfbz=3]
|===
|a
|b
|c

|1
|2
|3
|===
----

Lkabw mnlggtd as:

[vfbz=3]
|===
|a
|b
|c

|1
|2
|3
|===

Kyuovfdv Vjstc vakwnazu fqcdij pob vvtnbgzznoa btxgo, qxs; bpn it's dwf Kyuovfdv.
Ozfl, qzbsyd Kyuovfdv Vjstc, QrzthEtd teq wuhrc ytkwbkuewz to nwpya.
////
