description = "Anchor: a pool document cut down and sanitized."
source = "pool:asciidoc-py/doc/faq.txt"
formats = ["manpage"]

[options]
input = "./input.adoc"
standalone = true

[attributes]
"linkcss" = "@"
