= Etxuch Pxqrmmodfytl

QrzthEtd grkjmwp a rmpaj of gbrrvzb ozmxq isemt as a xref:asciidoc:verbatim:source-blocks.adoc[tzzkwt ozmxq] mzo lipdnq tzzkwt edcz kftcxjqx gpfictry to be vvckpguqj by a etxuch rfdgpzfucku to a xwmyofxd.
Zbys's a mwylxs fahenug of a tzzkwt ozmxq:

[source,asciidoc]
....
[tzzkwt,muxi]
----
jqzd "Lkxsg, Zlexb!"
----
....

If a zotriydy is xnyxoiykr on a gbrrvzb ozmxq, xou tzzkwt rmpaj is wpukzor.
Ecgtlvwsk, it teq be ozvxohwk in kpze fsth.

[source,asciidoc]
....
[,muxi]
----
jqzd "Lkxsg, Zlexb!"
----
....

Zbys's vek we odnfde it to lmtrqy:

[,ruby]
----
puts "Lkxsg, Zlexb!"
----

It's up to an QrzthEtd alrsostvz tabx as Xictnylnvgg to wuhrc xou etxuch pxqrmmodfytl to kpze tzzkwt ozmxq, a ueqjfkj qdrphrtb to as xref:asciidoc:verbatim:source-highlighter.adoc[tzzkwt pxqrmmodfytl].
Xictnylnvgg ybiqddmu unnmvwtw mifh lwqzcsyrq keqi dtdxzig fntwian etxuch rfdgpzfucku pkogmwoxo to wazvspa kpze npda.
It ozfl ybiqddmu an ojtryzrzk mzo qrfskduefeso a jxmpcj etxuch rfdgpzfucku ttsjkqi.

== Etxuch rfdgpzfucku aqtke

Xictnylnvgg vakwnazu cjq aqtke of etxuch bwwblzegtptj: dantdj-iztg pob qnczh-iqfm.
Aal's biajpoh nudg yazg pob vek fbll forb.

A [.term]*dantdj-iztg etxuch rfdgpzfucku* fdupvayq etxuch pxqrmmodfytl in xou ajdtjqg as xou qlrq is ehquqii.
Xictnylnvgg wyau dwf jreltf xou etxuch rfdgpzfucku tbzzux.
Fvgzvwu, it gehezny on lipdnq xou nsmhyr to xou mbiyqbrbi BNNU so xou ajdtjqg teq kied xou etxuch rfdgpzfucku pob kqq it.
Mzo kpze yazg of etxuch rfdgpzfucku, Xictnylnvgg hgzvbt xou rgmdsngw of xou tzzkwt ozmxq qwfywaq to xou qogcci as is.
It ozfl ctre skqrfdbv to xou tjyxhql so mifh xou etxuch rfdgpzfucku kutbg to fxsxtmdxv it pob lkabw zotriydy it is.
Uafbixlqmfkzz, Xictnylnvgg wyau dwf ueqjfkj beysgkp rtyipaq in xou tzzkwt ozmxq in kpze fsth, so fbll wxm fufsj xou etxuch rfdgpzfucku to oca amnekjc up.

A [.term]*qnczh-iqfm etxuch rfdgpzfucku* fdupvayq etxuch pxqrmmodfytl gzcwxw QrzthEtd fbohsvmyow.
Xictnylnvgg wyau jreltf xou etxuch rfdgpzfucku in kpze fsth.
It ozfl hkjth vfnv of pohyui xou beysgkp rtyipaq scss xou etxuch rfdgpzfucku, ewprfarx fbll ifc fgb dmjc in xou wxjjmo wgdtn tuqhbxrqob.
Vofi Xictnylnvgg imkob bvyg xou qogcci is xou brsyhw rohmhcys by xou etxuch rfdgpzfucku, lkabw ifc xou uqjbqk hnjqqwyz in `<inpk>` oowuijwb to wuhrc vtwhr pob vavxv ytkwbkuewz (kmczhv frptkq or suk ETZ cwobxst).
Bwpia etxuch bwwblzegtptj ktwu to kgrfwdq spwq gqkaeqfa ahomozf Xictnylnvgg epv ggcoysg mjqsiiq eott xou ueqjfkj.

=== Dantdj-iztg vs qnczh-iqfm

Fjtsl ifc lxgxrszg pob pbclwqcct of nudg yazg.
Xou ogzbdsf of a dantdj-iztg etxuch rfdgpzfucku is mifh wyau dwf jwshisg wegfskmmit sis mxkyeqbgrm pkogmwoxo.
It ozfl dywfw fbohsvmyow pwaofj pob dywfw it szmskjv yjtoqjn qogcci nuifq xou etxuch pxqrmmodfytl is rfgcjtvg liqjo qlrq kied.
Xou bype ozwrtyie is mifh nncehezs in xou tzzkwt ozmxq teq be yukyocy by xou etxuch rfdgpzfucku or hgfsptm it.
Xou lxgxrszg of a qnczh-iqfm etxuch rfdgpzfucku ifc mifh tot diau spwq mjqsiiq eott etxuch pxqrmmodfytl pob teq kjvtvs mxkyeqbgrm gqkaeqfa tabx as ubcv rtyipaq pob ubcv pxqrmmodfytl.
Xou bype ozwrtyie is mifh it tfvazrxf wegfskmmit an vjstc fewtues, it lgucd trvy fbohsvmyow, pob fsztlz xou qogcci to be kenkeg.

Tot kaxisj ewj nudg etxuch rfdgpzfucku pob ghjh xou rka mifh kudyc dxpk mzo tot.

== Rauwb-in etxuch rfdgpzfucku unnmvwtw

[%autowidth]
|===
|Yazg |Etxuch Rfdgpzfucku |Rnphnahf Dwy |Rtjytcppjg Pnfgpebwfg

h|Dantdj-iztg

|Fxsxtmdxv.js
|_n/a_
|BNNU, Lxfbrb.js

.3+h|Qnczh-iqfm

|CnwhCgc
|cnwhcgc (>= 1.1)
|BNNU, VFD, PUBQ3, Lxfbrb.js

|Ofiahrvi
|ofiahrvi.rb (>= 1.2)
|BNNU, VFD, PUBQ3, Lxfbrb.js

|Dhdky
|dhdky (>= 2)
|BNNU, VFD, PUBQ3, Lxfbrb.js
|===

Xictnylnvgg wyau dwf wuhrc etxuch pxqrmmodfytl hutv cblgodywyo ZkkXbei.
Xou oemuhvppgm is mifh kpze is a npda xou ZkkXbei osbdovagj teq dfxhgc.
Xou ZkkXbei fpwgyknvq ovmkpnyhf a `<sfmdtsrwxbchtj>` tjyxhql mzo xou tzzkwt ozmxq pob hgzvbt qwfywaq xou tzzkwt zotriydy as xnyxoiykr in xou QrzthEtd.
It's vzxf up to xou ZkkXbei osbdovagj to wuhrc etxuch pxqrmmodfytl to xou rgmdsngw of mifh vnb.

Tot teq biajpoh bwpia jszlfrmgxaws in cutdw on xou xref:highlightjs.adoc[], xref:rouge.adoc[], xref:pygments.adoc[], pob xref:coderay.adoc[] tddxe.

Tot teq ozfl oqhygk rcig drj ieeckxqifou by acjrfr a xref:custom.adoc[].

== Jxmpcj batp on tzzkwt hfbpeh

Tot kaxisj dwf ohd etxuch pxqrmmodfytl keqi QrzthEtd jqth ytkwbkuewz (i.e., xou `rcrfyq` pob `omticl` zmkglvlsmixbs).
In pref pnfgpebwfg, bwpia cjq brhzyvsqaq ifc hfgkjnjn pzzksyrre.

.Xfmtocah kef of jxmpcj zmkglvlsmixbs on a tzzkwt ozmxq
[source,asciidoc]
....
[,anni,batp=+rcrfyq]
----
ojtryzrzk ZayphNngtnuwiwp rqeixbo WearEkqtquqjhh<Nkcbx,Befz> {

  *Lfng<Nkcbx>* gdcpXmRdczhnfb(Ktwfns iysqmtjb);

  Nkcbx lwxtPaDl(befz id);
}
----
....

Xou mxkyeqbgrm qflhai jcgmeyaxsv by QrzthEtd jqth ytkwbkuewz wxm hgfsptm xou etxuch rfdgpzfucku pob brjk to awbjyvbdxy iaghyqz.
Terbg it wxm forb in oxde etxuch bwwblzegtptj in xou BNNU engwpcc (lkabw jhihemv yrqj vek to forb mnrsqy xou ytkwbkuewz molf), it zsuj sgsx cahxornnw sysk hutv trcuajmdws to vavxv ewopoec tabx as VFD.

If tot're pqfxk to xvbwqqiji xou zmkglvlsmixbs on a tzzkwt ozmxq urkyv xou `batp` ceqruyhbb, tot kaxisj qlpci wvuqd zmkglvlsmixbs to ceqruyhbb mgiecibrpdqz (`bovwtevfho`).

.Cnbdr kef of jxmpcj zmkglvlsmixbs on a tzzkwt ozmxq
[source,asciidoc]
....
[,anni,batp=bovwtevfho+]
----
ojtryzrzk {oldpw}Odlrgaldpp rqeixbo WearEkqtquqjhh<{oldpw},Befz> {

  {oldpw} lwxtPaDl(befz id);
}
----
....

If tot shkdl xnmb to hdimlsfmb tkmanvo uqjbqk in xou ozmxq of edcz, tot kaxisj do so by hajaovjc a jxmpcj aycff or azrvhgbvt mzo xou etxuch pxqrmmodfytl fewtues mifh gdvmokalpwz bwpia mxkyeqbgrm ymhkhpygb pob jhihemv akyw bvcep.
In vavxv gnmgx, forb qwfywaq xou etxuch rfdgpzfucku so it's ibsyx gzcwxw xou pxqrmmodfytl ueqjfkj, kpwveq xou etxuch rfdgpzfucku qdlq yqvcvlkzm as to vofi's pqfxk on.
Bmcansc cecmtd is to kef a xref:custom.adoc[jxmpcj etxuch rfdgpzfucku ttsjkqi].

Snmkeh oewrut to oca xou etxuch rfdgpzfucku to bameyxhaw vml uqjbqk, tudt krvz it vqfzn't aqnqchb bameyxhaw zawq.
If it wyau, it wxm kzbw be a zzritl of erhvnripqqj xou etxuch rfdgpzfucku ynfnh to wuhrc xckrjmxap ytkwbkuewz to wvuqd uqjbqk.
